### ISSUE TITLE
404 Microsoft Azure marketplace

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/ubuntu.com#10018]
To replicate:
-  Go on https://ubuntu.com/download/cloud
- Search for:
![image](https://user-images.githubusercontent.com/2707508/125412010-6b60ef80-e3b6-11eb-87fc-3060546d9a56.png)
- Click on the Microsoft Azure logo
- 404!
- I added a [comment in the copydoc](https://docs.google.com/document/d/1kp7QQXst1EbCjZjzWZP3YZwfmG0EIXLfQoRUVaMEZng/edit?disco=AAAANciWZ9M) but I am not sure who to contact to figure out which one is the right URL

**Comment by SirSamTumless** [comment]
@lechsandecki I could you please provide the correct link ASAP

**Comment by anthonydillon** [comment]
@lechsandecki This is the best I could find: https://azuremarketplace.microsoft.com/en-gb/marketplace/apps?search=Canonical%20Ubuntu%20Server&page=1.

There is a lot of difference between author names and descriptions.

**Comment by lechsandecki** [comment]
surprising that Pro is not listed there. I will try to find another URL to
use here, I wonder if we shouldn't be pointing to
https://cloud-images.ubuntu.com/locator/
wdyt?
