### ISSUE TITLE
Typos/errors in the article

### ISSUE THREAD

**Issue by sputi85** [canonical-web-and-design/ubuntu.com#10025]
How does kernel livepatching works? -> How does kernel livepatching work? [no S in work]

There are many types of vulnerabilities and many reasons behind them such a logic error, or a missing check in a small piece of code and others.  -> There are many types of vulnerabilities and many reasons behind them, such as a logic error or a missing check in a small piece of code, and others. [comma before "such as",  "as" missing, remove comma before "or" and I would add one before "and others"

"Livepatch" and "livepatch" used inconsistently. 

---
*Reported from: https://ubuntu.com/blog/linux-kernel-livepatching*

**Comment by pmahnke** [comment]
@nmav this feedback is for you.

**Comment by nmav** [comment]
Thank you for pointing these out @sputi85 , really appreciated!
