### ISSUE TITLE
New customers incorrectly naming their accounts

### ISSUE THREAD

**Issue by alysonrose88** [canonical-web-and-design/ubuntu.com#10022]
Hi team,

In the last couple of weeks we have seen a very big increase in the number of new customers purchasing through /advantage who are accidentally naming their new UAI account after themselves rather than the name of their organisation (out of 39 new purchases in the last 7 days, 30 of the accounts were named for the person purchasing).

Could we make some changes to the payment form to try to reduce the number of customers making this mistake?

Things we discussed in the UA sync today included: switching the order of the form so that people are prompted to provide an organisation name before they provide their personal details, having an error show if a new customer does not provide an organisation name.

It would also be good to try to understand why this problem has suddenly occurred, if anyone has any insight there.

---
*Reported from: https://ubuntu.com/advantage*

**Comment by SirSamTumless** [comment]
We are going to resolve this in the new UI.
