### ISSUE TITLE
Advantage Portal: Free User's Page Has Outdated Information

### ISSUE THREAD

**Issue by arossbell** [canonical-web-and-design/ubuntu.com#10041]
## Summary

After logging in to the [Ubuntu Advantage portal](https://ubuntu.com/advantage) as a free user, the `Your free personal subscription` section has some outdated (or lacking) information:
> Initially, this free subscription is available for Ubuntu 14.04 ESM and 16.04 ESM.

## Process

Log in to the Ubuntu Advantage portal as a free user.

## Current and expected result

Mentions of 18.04 and 20.04 (especially as UA tool 27.2 is soon to be released) should be included for the non-ESM parts.

## Screenshot

![image](https://user-images.githubusercontent.com/48603952/125972847-472d8c8b-08b7-4ede-9f36-c6c377c0f085.png)

**Comment by SirSamTumless** [comment]
@lechsandecki Could you please double-check this.

**Comment by lechsandecki** [comment]
thanks @arossbell fair point
I think that we can simply get rid of that sentence entirely: "Initially, this free subscription is available for Ubuntu 14.04 ESM and 16.04 ESM."
