### ISSUE TITLE
Payment form does not allow customers from Bermuda to purchase

### ISSUE THREAD

**Issue by alysonrose88** [canonical-web-and-design/ubuntu.com#10050]
Hi team,

We've just been contacted by a prospective customer from Bermuda who is unable to purchase through the store because his postcode is not accepted by the form (I am unsure if this is a problem with the form or with Stripe).

The customer says: Due to the requirement for the postal code in the credit card section in purchasing support for Ubuntu 20.4, I am unable to have the payment section to complete. I am located in Bermuda and the postal codes are in a two letter and two number format, HM11, the CC section will not allow me to proceed.

If it's a Stripe problem, could you please let me know and I'll raise it with CS. Thanks!

---
*Reported from: https://ubuntu.com/advantage/subscribe*

**Comment by anthonydillon** [comment]
Seems to work for me. @ClementChaumel can you reproduce this issue?

**Comment by albertkol** [comment]
We are talking about our Stripe card input field:
![image.png](https://images.zenhubusercontent.com/5ee7415a47536a7869302593/f6d139bb-4015-4554-a7e1-4a384d343328)

### This the information I found on Strip's website
_The card element automatically determines your customer’s billing address country based on their card number._

_Using this information, the postal code field validation reflects whether that country uses numeric or alphanumeric-formatted postal codes, or if the country uses postal codes at all._

_For instance, if a U.S. card is entered, the postal code field only accepts a five-digit numeric value. If it’s a UK card, an alphanumeric value can be provided instead._

### Results of my testing
US test card asks for ZIP Code:
![image.png](https://images.zenhubusercontent.com/5ee7415a47536a7869302593/a03c0aa1-2dfa-4e61-a509-16e2160ddf12)

Canada test card asks for Postal Code:
![image.png](https://images.zenhubusercontent.com/5ee7415a47536a7869302593/fb328297-4d73-4b75-9d92-c16189a7f7c8)

Brazil and Mexico test cards ask for no ZIP/Postal Code:
![image.png](https://images.zenhubusercontent.com/5ee7415a47536a7869302593/3e38c4a4-4454-4fc0-a696-f9034d482a0f)
![image.png](https://images.zenhubusercontent.com/5ee7415a47536a7869302593/c93d8f16-8a28-4a13-af4c-aceca1d61b0b)

### Back to the customer's problem
Unfortunately I have no Bermuda (test) card to see what they saw. But we know Bermuda is using alphanumeric-formatted postal codes, and if we assume Stripe works correctly, then they should have received a Postal Code input field in the card input field.

But it seems they received a ZIP code field instead, as that one is not allowing users to insert letters.

So I have the following questions:
- Do they really see a Postal Code field that is rejecting their input? If so then Stripe does not work correctly. But I suspect they get a ZIP field.
- Is the card they use a Bermuda card? It might be a US one. Or whatever it is, the billing zip/post code does not match the country of the card.

**Comment by alysonrose88** [comment]
@albertkol I've gone back to the customer to confirm which of the fields would not accept their postcode, whether they saw an error message or the Continue button remained greyed out, and if they had any other problems with the form, I'll let you know what I hear back

**Comment by alysonrose88** [comment]
@albertkol the customer has confirmed:

1. The card payment field rejected their postcode, they were able to provide their postcode in the address fields lower down
2. The error code is “ Your purchase can not be processed” or something like that, they tried twice but did not want to lock out the credit card. I can't see any record of the attempted payments in Stripe, the customer email is itlicensing@aeolus.com and I searched using that email and just the domain.

**Comment by albertkol** [comment]
It's hard to tell what's going on at their end. Would have helped to know exactly what error they got, or a screenshot. 

If they insert a card without a (or with a wrong) post code they should not even be able to press the continue button on the modal to attempt the purchase. So I do not understand how they even got a message like "Your purchase cannot be processed".

There is a way to disable the card Post Code field, but I do not think that's the right approach, as it provides an extra anti-fraud element.

Not sure how to proceed with this one. 

@ClementChaumel @alnvdl any ideas?

**Comment by alysonrose88** [comment]
The customer is purchasing through Sales, so we don't need to fix the problem for them. As long as you're all happy that this was user error rather than a limitation of the payment form I say we can close this!

**Comment by albertkol** [comment]
We will try to capture more errors from our wizard. We will do it as part of: https://github.com/canonical-web-and-design/commercial-squad/issues/10

That might help us troubleshooting this sort of errors.

Closing this for now.
