### ISSUE TITLE
CUBE SSO updates

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#10051]
<td>Project name: 
</p>
<p>
CUBE (Certified Ubuntu Engineer)
</p>
   </td>
   <td>Requested by:
</p>
<p>
Kellen Renshaw
</p>
   </td>
   <td>Due date: 
</p>
   </td>
   <td rowspan="2" >Currently, all CUBE related pages are behind Ubuntu ONE SSO, with an additional access control list to restrict them to people with a "@canonical.com" email address in the SSO.
</p>
<p>
For our Beta (and eventual GA) release, we would like to remove the access control list, and change the pages that are behind the Ubuntu ONE SSO login.
</p>
<p>
The requested changes should be made live once ready.
</p>
   </td>
   <td rowspan="2" colspan="2" >Deliverables:
</p>
<p>
Covered in detail in GitHub issue <a href="https://github.com/canonical-web-and-design/ubuntu.com/issues/9970">#9970</a>.
We are not currently ready to have the requested changes go live, but wanted to have a head start to avoid crunches.

We would like the following:

- [x] ubuntu.com/cube - No SSO, open to the public.
- [x] ubuntu.com/cube/microcerts - SSO, open to anyone with an Ubuntu ONE SSO account.
- [x] ubuntu.com/cube/study - SSO, open to anyone with an Ubuntu ONE SSO account.
- [x] ubuntu.com/cube/* - SSO, open to anyone with an Ubuntu ONE SSO account. Refers to potential future pages.

Additionally, any access control lists should be removed as part of this.

</p>
<p>
High-level overview:
</p>
<ol>

<li>Remove the access control list for all CUBE pages.

<li>Remove the SSO requirement for ubuntu.com/cube

<li>Keep the SSO requirement for ubuntu.com/cube/*
</li>
</ol>
   </td>
   <td>Target audience (if applicable):
</p>
   </td>
   <td rowspan="2" colspan="2" >Any additional information:
</p>
<p>
<em>Don’t forget to think of links to the page you are creating</em>
</p>
   </td>
   <td>Stakeholders:
</p>
<p>
David Britton
</p>
<p>
Bruce Tarro
</p>
<p>
Laurie Matthews
</p>
<p>
Kellen Renshaw
</p>
<p>
Lex Joy
</p>
<p>
Kris Sharma
</p>
<p>
Thibaut Rouffineau
</p>
   </td>
   <td colspan="3" >
   </td>

**Comment by SirSamTumless** [comment]
@KellenRenshaw FYI 👀

**Comment by KellenRenshaw** [comment]
Thanks!

**Comment by bethcollins92** [comment]
@KellenRenshaw I can't tag you in the PR not sure why but your name isn't coming up - maybe you don't have permissions to see it? but FYI this change is going live

**Comment by KellenRenshaw** [comment]
@bethcollins92 Thanks! Saw it come through. Much appreciated!
