### ISSUE TITLE
Links to https://451research.com are erroring

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#10059]
We link to https://451research.com from https://ubuntu.com/openstack/what-is-openstack. This site has an SSLError.

To reproduce:
- Run `curl -I https://451research.com/`
- See SSL certification prolem.

**Comment by SirSamTumless** [comment]
@tytus-kurek Is this something you can raise with them?

**Comment by anthonydillon** [comment]
This is still an issue on https://451research.com/

**Comment by SirSamTumless** [comment]
It is working for me.

**Comment by anthonydillon** [comment]
Did you run `curl -I https://451research.com/`?

**Comment by carkod** [comment]
> Did you run `curl -I https://451research.com/`?
```
curl -I https://451research.com/
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

We seem to be having this same issue in multiple places. I believe [IS is updating DNS](https://chat.canonical.com/canonical/pl/kzq4rr1oxbnb5k7ptemkbexjhr), hopefully they will fix this soon

**Comment by sowasred2012** [comment]
@anthonydillon do you still see the original error?

@carkod and I both ran it and see:
```

**Comment by anthonydillon** [comment]
Looks like they fixed the SSL issue but surprised the links on live action is paying with the 403 status. 🤷‍♂️
