### ISSUE TITLE
16.04 ESM page discusses 'april 2021' in the future tense

### ISSUE THREAD

**Issue by setharnold** [canonical-web-and-design/ubuntu.com#10067]
Hello, the 16.04 ESM page discusses the start of 16.04 ESM support as if it is in the future:

- "Xenial enters the ESM period in April 2021"

- "ESM for Ubuntu 16.04 LTS will be available April 2021" twice

Thanks

---
*Reported from: https://ubuntu.com/16-04*

**Comment by SirSamTumless** [comment]
Thanks for flagging this. @lechsandecki Can you update the copy and flag us to get it changed?

**Comment by lechsandecki** [comment]
thanks for reporting that. I updated the copy doc: https://docs.google.com/document/d/1wclofqY9b3v_M9igpkYn6or5uXx0B_Xb_nVVzGBbOLY/edit#

**Comment by SirSamTumless** [comment]
@ClementChaumel You fine to sort this?

**Comment by SirSamTumless** [comment]
@ClementChaumel 🔔  🔔  ⏰
