### ISSUE TITLE
"LMA" may not be well-known enough to use as an acronym

### ISSUE THREAD

**Issue by setharnold** [canonical-web-and-design/ubuntu.com#10074]
Hello, a user asked for a definition of "LMA" on askubuntu.com: https://askubuntu.com/questions/1353648/what-does-lma-stand-for

> I usually know my IT abbreviations pretty well, but what does LMA stand for?

Is 'LMA' sufficiently well-known in the target audience for this page to use it as-is? (I didn't know what it meant, but I'm not in a position to spend money on support contracts.)

Thanks

---
*Reported from: https://ubuntu.com/support*

**Comment by mmanciop** [comment]
LMA is unfortunately a Canonical terminology that nobody uses outside. We currently do not plan to add content on the website for the LMA used by Bootstack in manager services, so we might need to think up something.
