### ISSUE TITLE
Checkbox highlight on /certified?q= is cut off

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/ubuntu.com#10129]
See comment [here](https://github.com/canonical-web-and-design/ubuntu.com/pull/10125#issuecomment-892584621)
It seems the `overflow: hidden` is causing this (only on Macs?), which we need to produce the ellipses on the filter name to stop one vendor taking up 2 lines and throwing off the number of vendors shown.

**Comment by carkod** [comment]
It's not only happening on Macs, my Chrome 90.0.4430.212 on Ubuntu (Chrome debian)

**Comment by bethcollins92** [comment]
This has been fixed [here](https://github.com/canonical-web-and-design/ubuntu.com/pull/10125)
