### ISSUE TITLE
edX Account lookup needs to URI encode email addresses

### ISSUE THREAD

**Issue by KellenRenshaw** [canonical-web-and-design/ubuntu.com#10131]
The modal that pops up when the user doesn't have an account on edX relies on the edX API /api/user/v1/accounts?email=someemail@example.com query.

This query is currently returning HTTP 404  for emails with the form some+email@example.com even when they have an account.

The issue is that the "+" in the email needs to be URI encoded in the API call.

I have tested and confirmed that the URI encoding of the email works as expected with the API.

---
*Reported from: https://ubuntu.com/cube/microcerts*

**Comment by KellenRenshaw** [comment]
@SirSamTumless @jpmartinspt Hoping this is a quick fix? It is breaking testing of the integrations.

**Comment by jpmartinspt** [comment]
@KellenRenshaw should be a quick fix, I'll try to have a look asap.
