### ISSUE TITLE
UA client instructions specify <sudo apt upgrade> where <sudo apt update> might be better

### ISSUE THREAD

**Issue by alysonrose88** [canonical-web-and-design/ubuntu.com#10147]
Hi team,

A customer has just brought to my attention that our instructions for using the ua client on this page specify that customers should run $ sudo apt upgrade after installing the ua client, but this would let them know all available updates for that machine, rather than whether there's an update specifically for the ua client. He suggested that using sudo apt update might be better, and indeed that is the command used in our ua client instructions on our [ua client discourse page](https://discourse.ubuntu.com/t/ubuntu-advantage-client/21788).

I'm guessing we'd want @lechsandecki to be involved in deciding between the two when he's back, so we can put this suggestion on ice for the next couple of weeks.

Thanks!

---
*Reported from: https://ubuntu.com/advantage*

**Comment by lechsandecki** [comment]
based on the feedback from Rick Harding we could consider promoting the following command
sudo apt install ubuntu-advantage-tools

but I need to do more research to decide if we want to make this update or not.

**Comment by albertkol** [comment]
This is very old. If we still want this please re-open.
