### ISSUE TITLE
Ubuntu Core Build Service fails for Core20 variant

### ISSUE THREAD

**Issue by bugraaydogar** [canonical-web-and-design/ubuntu.com#10189]
## Summary
Ubuntu Core Build service "ubuntu.com/core/build" service allows users to create their custom Ubuntu Core image with simple steps. As a user, if you try to build an image by choosing Core20 as your operating system, it redirects to 500-server error. 

The issue is created after I made some improvements on UI where I also added core20. 
#10152 

## Process

1- Go to ubuntu.com/core/build and Login
2-Select NUC, Core20 and amd64 and click build image.
3- Redirected to 500-Server Error

## Current and expected result

Currently, the application redirects to 500-Server Error, the expectation is to redirect to the success page and start the Launchpad job to build the custom image.

**Comment by SirSamTumless** [comment]
@carkod Will you have time to tackle this in the next two weeks?

**Comment by carkod** [comment]
> @carkod Will you have time to tackle this in the next two weeks?

Yeah I can squeeze it between tasks.

**Comment by carkod** [comment]
There is an [ongoing conversation about this](https://github.com/canonical-web-and-design/meeting-notes/issues/868), so will not be tackled.
