### ISSUE TITLE
Charmed Kubernetes release cycle has skews from the upstream

### ISSUE THREAD

**Issue by nobuto-m** [canonical-web-and-design/ubuntu.com#10205]
The following part doesn't match with [the upstream release EOL](https://kubernetes.io/releases/).

https://github.com/canonical-web-and-design/ubuntu.com/blob/43dc3ec1aab4e6f0d07c2f2de91106ec5413c308/static/js/src/chart-data.js#L1298-L1315

Release | Upstream EOL | Charmed EOL
-- | -- | --
1.21 | 2022-06-28 | 2022-04-08
1.20 | 2022-02-28 | 2021-12-08
1.19 | 2021-10-28 | 2021-08-16

---
*Reported from: https://ubuntu.com/about/release-cycle*

**Comment by SirSamTumless** [comment]
@alxchalkias Is this something you look after?

**Comment by alxchalkias** [comment]
Yes, let me align with the k8s-crew and get back to you. FYI, I've already updated the text on the page to reflect both our K8s distros.

**Comment by alxchalkias** [comment]
@SirSamTumless there should not be any delta between upstream and Charmed, which should also be referred to as "Canonical Kubernetes" or "Canonical K8s" for short, to encapsulate both distros. Can you have this and the text fixed please?

**Comment by SirSamTumless** [comment]
Closing this as it is tracked on another ticket. Thanks for flagging @nobuto-m

**Comment by nobuto-m** [comment]
What's the new ticket ID?

**Comment by SirSamTumless** [comment]
https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#heading=h.5hdbpimhvupa
