### ISSUE TITLE
Change title for https://ubuntu.com/server/docs/cloud-images/google-cloud-engine

### ISSUE THREAD

**Issue by hugohuangtao** [canonical-web-and-design/ubuntu.com#10229]
Can we change the title and url of this page from "google-cloud-engine' to "google-compute-engine"?
![screenshot](https://user-images.githubusercontent.com/56487433/130687736-ad734103-e9f3-4580-a78c-2ef5d3eba8b8.jpg)

**Comment by fitojb** [comment]
I see the new title there; it was probably a caching issue.
