### ISSUE TITLE
FIPS 140-2 & CIS Tool for 20.04 LTS missing from certifications drop down on /advantage

### ISSUE THREAD

**Issue by ariannalozano** [canonical-web-and-design/ubuntu.com#10228]
Hi Web & Design team, 

The certifications drop down on /advantage needs does not have FIPS 140-2 for 20.04 LTS or CIS tools for 20.04 LTS listed although these are now available for customers to access today.

https://ubuntu.com/advantage

**Comment by wgx** [comment]
This is resolved by the new UI, please re-open and @ me if there's still a separate issue.
