### ISSUE TITLE
Wrong certificate for de.releases.ubuntu.com

### ISSUE THREAD

**Issue by hadmut** [canonical-web-and-design/ubuntu.com#10279]
Sorry, didn't find a better place to drop that bug report, since releases.ubuntu.com doesn't mention an admin contact and ubuntu.com asks to drop bug reports about the web site here. 

I can't currently access https://de.releases.ubuntu.com , browsers and tools like wget complain about an invalid certificate without telling the details. 

What I can see is that the host name is de.releases.ubuntu.com, while the certificated is issued on releases.ubuntu.com (without the leading de.), as if it were a precise mirror of releases.ubuntu.com including the certificate.

**Comment by anthonydillon** [comment]
@hadmut thank you very much for taking the time to report this issue to us. I have asked our IS team to renew the cert. Which I would hope would be complete soon.
