### ISSUE TITLE
The word "positive" appears on "Install Ubuntu" tutorial

### ISSUE THREAD

**Issue by wgx** [canonical-web-and-design/ubuntu.com#10303]
## Summary

https://ubuntu.com/tutorials/install-ubuntu-desktop#8-select-your-location has an erroneous "positive" word below the image. 

## Process

View the page https://ubuntu.com/tutorials/install-ubuntu-desktop#8-select-your-location

## Browser details

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0 (Firefox 91) - also present in Chrome.

**Comment by anthonydillon** [comment]
Thanks @wgx, fixed via discourse
