### ISSUE TITLE
Ubuntu Desktop not shown as compatible with Raspberry Pi 4

### ISSUE THREAD

**Issue by diddledani** [canonical-web-and-design/ubuntu.com#10301]
The raspberry pi page has images and text indicating that the Desktop 21.04 edition is only compatible with RPi 400 and RPi CM4. It should be updated to indicate that RPi 4 in 4GB and 8GB with a picture of it (as per the text below the pretty pictures that most people are looking at)

![image](https://user-images.githubusercontent.com/147548/132032306-df662105-8e58-42e1-b118-b76c267c3352.png)

---
*Reported from: https://ubuntu.com/download/raspberry-pi*

**Comment by rhys-the-davies** [comment]
Taken care of @diddledani thanks to the wonderful mr  @pmahnke 😊 

https://github.com/canonical-web-and-design/ubuntu.com/pull/10302
