### ISSUE TITLE
500 when opening invoices

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#10339]
I can't access any of my invoices - gives me a 500 page

<img width="1042" alt="Screenshot 2021-09-10 at 09 48 59" src="https://user-images.githubusercontent.com/36884067/132827395-5f5e8b11-656d-44e2-a161-4f8d9220d5a3.png">

---
*Reported from: https://ubuntu.com/account/invoices?marketplace=*

**Comment by anthonydillon** [comment]
This has been fixed via https://github.com/canonical-web-and-design/ubuntu.com/commit/79306b4f2af76607483c53377c36da5c1ee94dd5
