### ISSUE TITLE
No way to get to account on small screens

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#10344]
The only way to reach the account/invoice view is via the user drop-down which is not enabled on small screens. Therefore, there is no way to get invoices on a small device. 

I propose we add links to these areas from places in which you might purchase something, such as cube or advantage.

**Comment by wgx** [comment]
>I propose we add links to these areas from places in which you might purchase something, such as cube or advantage.

The re-design of the /advantage UI does feature these links as part of the view - including in responsive mode.

It depends how urgent we feel this is - we can wait for the new /adv UI - or we can work on making the user menu appear correctly in responsive mode. 

@anthonydillon WDYT?

**Comment by anthonydillon** [comment]
If something is in the works that is fine. Don't want to side track anything but I was trying to test the invoices on my phone and noticed I couldn't get there.

**Comment by wgx** [comment]
Thanks @anthonydillon - we'll fix this with the release of the new UI.
