### ISSUE TITLE
Subscription list hides selected subscription when the content height changes

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/ubuntu.com#10365]
Small unrelated issue: when you select different contracts, the height of the app jumps around to accommodate the content but sometimes it messes up with the scroll-into-view thing

![scrooll](https://user-images.githubusercontent.com/11927929/133261150-3a3f18ea-9191-44a5-bca0-6bc1b20c8750.gif)

_Originally posted by @ClementChaumel in https://github.com/canonical-web-and-design/ubuntu.com/issues/10357#issuecomment-919122506_

**Comment by huwshimi** [comment]
@wgx do you have any thoughts about this? The issue is that if you click on the very bottom card when it is partially off the bottom of the scrolling list then if the content on the right changes size then the card you clicked on might get completely hidden from view.

**Comment by wgx** [comment]
@huwshimi I think this is an annoyance, but ok for our first version. Can we make an issue to tackle next cycle please?

**Comment by huwshimi** [comment]
> @huwshimi I think this is an annoyance, but ok for our first version. Can we make an issue to tackle next cycle please?

Thanks @wgx I think we can probably just use this issue to keep track of it, I'll remove from the current epic.
