### ISSUE TITLE
Marketo submission should encode HTML comments

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#10394]
## Summary
Marketo submission should encode HTML comments.
Sentry issue: [UBUNTU-COM-1EA](https://sentry.is.canonical.com/canonical/ubuntu-com/issues/20758/?referrer=github_plugin)

## Process
Submit HTML as the comment to https://ubuntu.com/server/contact-us.

## Current and expected result
This is cause a 500. Submitted content to Marketo should be encoded

**Comment by anthonydillon** [comment]
Another one: https://sentry.is.canonical.com/canonical/ubuntu-com/issues/21930/?referrer=alert_email

**Comment by pmahnke** [comment]
Most of these are spam
