### ISSUE TITLE
Change class for not included items

### ISSUE THREAD

**Issue by AnnSoMuller** [canonical-web-and-design/ubuntu.com#10409]
On https://ubuntu.com/kubernetes/what-is-kubernetes

On the section "What kubernetes is not"

Cross list icons should be red, using https://vanillaframework.io/docs/patterns/lists
<img width="824" alt="Screenshot 2021-09-20 at 11 25 42" src="https://user-images.githubusercontent.com/32699582/133981066-15d61cbb-8bb9-436c-be1b-684196c0563a.png">

Expected class:
  < li class="p-list__item is-crossed" >
---
*Reported from: https://ubuntu.com/kubernetes/what-is-kubernetes*

**Comment by petesfrench** [comment]
Closing as this has been fixed
