### ISSUE TITLE
[Rebuild /kubernetes/managed] design page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#10470]

**Comment by spencerbygraves** [comment]
@SirSamTumless @alxchalkias this is ready for a review:

![image](https://user-images.githubusercontent.com/9105999/135483400-7580d47b-cb75-45fd-9f34-dfe7467b11fc.png)

**Comment by alxchalkias** [comment]
@spencerbygraves CTA should read `Read the whitepaper - “Managed IT Services"`

**Comment by spencerbygraves** [comment]
@alxchalkias thanks, I've updated it.

**Comment by alxchalkias** [comment]
+1 from me
