### ISSUE TITLE
[/telco/osm/multi-vendor] UX review

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#10474]
[Copy doc](https://docs.google.com/document/d/1T9Z6UhQUpsb1rkIJGzvR4N3O0S5UxJ-I-3qyNGuq1D4/edit#)

There is a planned link from charmed-osm.com; however, nothing from /telco/osm

**Comment by davegoddard42** [comment]
Added UX feedback. Waiting for PM response

**Comment by davegoddard42** [comment]
Feedback implemented by PMs
