### ISSUE TITLE
incorrect names in grace hopper blog post

### ISSUE THREAD

**Issue by setharnold** [canonical-web-and-design/ubuntu.com#10488]
Hello, I believe there's mistakes in two names on the blog post:

> Hosted by Chlo Smith

Her email address has an 'e' in it, I suspect this is lacking an accented character. (I understand her name breaks our directory, so maybe look for it elsewhere.)

> Hosted by Crisitna Dresch

The directory says "Cristina" (I know, the previous bullet point the lesson would be "don't trust the directory", and in this bullet point the lesson is "trust the directory".)

Thanks

---
*Reported from: https://ubuntu.com/blog/canonical-at-grace-hopper-2021*

**Comment by pmahnke** [comment]
@setharnold thanks for pointing this out.  I have updated the post.
