### ISSUE TITLE
Observability is not represented as a section in the Footer

### ISSUE THREAD

**Issue by mmanciop** [canonical-web-and-design/ubuntu.com#10496]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

![Screenshot from 2021-09-24 13-44-55](https://user-images.githubusercontent.com/14020598/134669769-67c777cb-1c52-49bc-94a2-0a4361a76285.png)

The "Observability" link at the very end of the footer was consciously done this way since, until #10439, the `/observability` section was made of only one page.

But now that the pages are two, "Observability" deserves a "proper" section in the footer :-) 

## Process

Steps to replicate the issue: browse www.ubuntu.com, scoll aaaaall the way to the end, search for the lonely "Observability" link at the very end.

## Current and expected result

An "Observability" section in the footer before the "Appliances" one, with two sublinks: "Overview" and "What is Observability"

![Screenshot from 2021-09-24 13-57-14](https://user-images.githubusercontent.com/14020598/134670446-9a7d5e79-cdbb-4dca-8a52-6308f48b932e.png)

## Screenshot

See above.

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

**Comment by pmahnke** [comment]
'Overview' is not a valid link in the footer as it is the same as the link on Observability

**Comment by mmanciop** [comment]
> 'Overview' is not a valid link in the footer as it is the same as the link on Observability

Oh, yeah you are right. Having just “What is observability” as subitem it fine ofc.
