### ISSUE TITLE
Ubuntu Desktop is not downloading

### ISSUE THREAD

**Issue by thetejasmagade** [canonical-web-and-design/ubuntu.com#10529]
---
*Reported from: https://ubuntu.com/download/desktop*
"Ubuntu desktop" downloading is not working from the website.

**Comment by SirSamTumless** [comment]
Thanks for reporting this!

Could you please give us a little be more information - what link/iso isn't working?

**Comment by thetejasmagade** [comment]
Ya, ISO download link is not working.

**Comment by anthonydillon** [comment]
Would you be able to provide the ISO URL?

**Comment by thetejasmagade** [comment]
https://ubuntu.com/download/desktop/thank-you?version=20.04.3&architecture=amd64

It says, "Not Found
The requested URL /ubuntu-releases/20.04.3/ubuntu-20.04.3-desktop-amd64.iso was not found on this server."

**Comment by thetejasmagade** [comment]
Now, It's working. Yesterday I, was facing this problem. I think the problem is fixed now. 

Thanks

**Comment by pmahnke** [comment]
great
