### ISSUE TITLE
Error if user without admin role accesses ubuntu.com/advtange/users

### ISSUE THREAD

**Issue by TeodorPt** [canonical-web-and-design/ubuntu.com#10576]
## Summary
If a user with no Admin role on the account accesses ubuntu.com/advantage/users, the page loads and after getting a spinning wheel for a while, we get a page that reads:
```
Account Users

Error: An unknown error has occurred
```

## Process

Add a user to an account as Technical or Billing. Log in with that user and navigate to ubuntu.com/advantage/users.

## Current and expected result

Current: unknown error has occurred.
Expected: either 404 or something more explanatory, like "insufficient rights to access this page" or something similar.

**Comment by albertkol** [comment]
Done a while back. Users get Access Forbidden page. Closing.
