### ISSUE TITLE
New /advantage: cost is a bit redundant

### ISSUE THREAD

**Issue by frankban** [canonical-web-and-design/ubuntu.com#10679]
## Summary
In the right panel of /advantage we show the cost of the contract, like `$3,800 USD/yr` which says "dollars" twice.

**Comment by albertkol** [comment]
@wgx thoughts?

**Comment by wgx** [comment]
Sorry just saw this - I don't think it's a problem - as Clem said, there are lots of types of dollars so saying it's USD and then denoting the amount with $ is fine for me.
