### ISSUE TITLE
UA-Shop: Add support for tracking leads created from Campaigns

### ISSUE THREAD

**Issue by brotich** [canonical-web-and-design/ubuntu.com#10696]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary
This is needed to support reporting of effectiveness of marketing campaigns towards the UA-shop
This will allow the integration downstream to attribute a purchase to a specific marketing channel.
## Process
To support this feature, we need to add specific metadata to when making a purchase. Downstream integration shall look for and process the metadata to generate the appropriate leads.

- Currently this looks not to be implemented  on the UA shop purchase process. The metadata shall need to be added in the make purchase function [here](https://github.com/canonical-web-and-design/ubuntu.com/blob/d15bc53e6c9e7ed7152b829a61ff3040eeb51444/webapp/advantage/views.py#L346-L418)

refer to https://github.com/CanonicalLtd/ua-contracts/blob/develop/docs/howtos/track-purchases.md for how to implement the feature.

**Comment by albertkol** [comment]
This was done. Let us know if it's not working. Closed.
