### ISSUE TITLE
CVE URL in USN references still points to old URL

### ISSUE THREAD

**Issue by dodys** [canonical-web-and-design/ubuntu.com#10709]
## Summary

As can be seen [here](https://github.com/canonical-web-and-design/ubuntu.com/blob/7687afcdf34a537c757e060d9b7578eec55fafe2/templates/security/notices/usn.html#L89), the USN pages, in the References section, are still pointing to the old CVE tracker URL. The new CVE tracker URL is "https://ubuntu.com/security/{{ cve.id }}"

## Process

Open a USN page, e.g. https://ubuntu.com/security/notices/USN-5114-1, and check the References page. If you just hover your mouse over the CVE you will see it points to the old CVE tracker location, while in the Details section it is already using the new URL.

## Current and expected result

To use the new CVE tracker URL: "https://ubuntu.com/security/{{ cve.id }}"

**Comment by albertkol** [comment]
I made the change. It's in review.
