### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by carv-cmd** [canonical-web-and-design/ubuntu.com#10766]
In context; "Sometimes the structure of the network-config file that you modified before boot gets messed up when you book."

I think *book* is supposed to be *boot*?

Found on, https://ubuntu.com/tutorials/how-to-install-ubuntu-on-your-raspberry-pi#4-boot-ubuntu-server
Under header, "Still not connected to the internet?"

**Comment by pmahnke** [comment]
@carv-cmd thanks, I have fixed it, might take a bit of time to get through the caches.
