### ISSUE TITLE
CVE search results - filters not retained from one page to the next

### ISSUE THREAD

**Issue by alexmurray** [canonical-web-and-design/ubuntu.com#10799]
Filters are not retained when going from the first page of search results to the next / other pages:

Originally reported at https://bugs.launchpad.net/ubuntu-cve-tracker/+bug/1947320 as follows:

Go to the following page:
https://ubuntu.com/security/cve?q=&package=&priority=medium&version=focal&status=&version=impish&status=

At the bottom of the page, we select another page, and we get this URL:
https://ubuntu.com/security/cve?priority=medium&version=focal&version=impish&offset=20

Added filters disappear.

The website URL should look like this:
https://ubuntu.com/security/cve?q=&package=&priority=medium&version=focal&status=&version=impish&status=&offset=20

---
*Reported from: https://ubuntu.com/security/cve?q=

**Comment by sowasred2012** [comment]
Thanks for reporting this @alexmurray - we'll look into this ASAP.

**Comment by petesfrench** [comment]
Blocked as it is only a partial fix. I am looking into a full fix currently
