### ISSUE TITLE
No message currently on Cypress github action on main

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/ubuntu.com#10790]
There is a cypress test which currently checks the marketo forms on main on merge. Currently we don't have a way to know if this failed (as it's not a check in the actual PR).

A message should be added so we get alerted in mattermost if the test fails. Something like this - 

` - name: Send message on failure
        if: failure()
        run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" ${{ secrets.BOT_URL }}?room=web--design`

**Comment by minkyngkm** [comment]
Closing this issue as it's the same as https://github.com/canonical-web-and-design/web-squad/issues/4440
