### ISSUE TITLE
virtualisation is spelt both in US and UK forms

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#10815]
I think we, at Canonical, use British English unless the guidelines have changed. Either way, it's spelt in 2 different ways on this page.

<img width="849" alt="Screenshot 2021-11-08 at 14 56 37" src="https://user-images.githubusercontent.com/36884067/140764872-69b7fcda-9c08-4803-ac50-dbfe45dd0229.png">

---
*Reported from: https://ubuntu.com/containers/what-are-containers*

**Comment by pmahnke** [comment]
whoever picks this up, please update the copy doc as well.
