### ISSUE TITLE
Component table on server certification pages do not show certified status

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/ubuntu.com#10829]
## Summary

https://ubuntu.com/certified/201802-26096

When viewing that machine, the "Components" table lists several items, all of which have been marked as validated for 18.04. On the back end, each component does show the status indicator that they've been successfully tested and are marked as certified.

On the front end, however, that status is not being displayed, leaving the table empty.

## Process

View this machine entry on ubuntu.com/certified:
https://ubuntu.com/certified/201802-26096

## Current and expected result

Current: Components do not indicate that they have been validated for a given release
Expected: Indicators are present for each validated release.

## Screenshot

![Screenshot from 2021-11-09 11-52-50](https://user-images.githubusercontent.com/4295496/140968792-0fa79054-150d-4835-aaaf-d161c828cabc.png)

**Comment by codersquid** [comment]
I think this is actually a backend bug. I checked the API response and the `lts_releases` field is empty. https://certification.canonical.com/api/v1/componentsummaries/?canonical_id=201802-26096

**Comment by codersquid** [comment]
I've opened a bug for the backend. This can be closed.
