### ISSUE TITLE
UASD - the table of contents is not working properly

### ISSUE THREAD

**Issue by lechsandecki** [canonical-web-and-design/ubuntu.com#10835]
Hi team,

The table of contents (on the right) on the new uasd page is not working correctly. I also have an idea that could help improve it further.

[the page] https://ubuntu.com/legal/ubuntu-advantage-service-description

1. [the bug] Looks like it doesn't scroll properly -I have to scroll all the way down on the left side of the screen (the actual document) to see the last section of the table of content (definitions). Otherwise, it's not visible to me at all.
2. [an improvement idea] (being addressed in https://github.com/canonical-web-and-design/ubuntu.com/issues/10838)

many thanks
Lech

**Comment by sowasred2012** [comment]
Thanks for flagging this - I'm going to split this into two issues, keep this one as the bug we can fix ASAP, and then create the improvement suggestion as a follow up that we can look into later. It's a good suggestion, and possibly a pattern we can use in other places.

**Comment by petesfrench** [comment]
Could we just remove the 'sticky' class and have it appear as a static element for now?

**Comment by pmahnke** [comment]
that makes sense

**Comment by davegoddard42** [comment]
@lechsandecki Looking at the items in the navigation, does each one need a link? For example:

![image](https://user-images.githubusercontent.com/25453620/142880948-f57097f9-09f0-4c40-8113-ddd9b9c47950.png)

Would it be enough to have just "kubernetes" or is it important for both items listed underneath to have their own links? Those sections are very short.
