### ISSUE TITLE
[Page update] /managed

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#10842]
Update /managed and its contact modal: [Brief](https://docs.google.com/document/d/1NMHLQ4pagB1oXPelb9xsZEer3yM-sjdN2h6JoEB5trw/edit)

**Comment by minkyngkm** [comment]
The modal on `/managed` is already updated with this [PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/10862)
