### ISSUE TITLE
Could we include names with the 16.04, 18.04, 20.04 etc?

### ISSUE THREAD

**Issue by briannadstuart** [canonical-web-and-design/ubuntu.com#10850]
Would it be possible to get the names added here for the ones without?  This is confusing to people outside Canonical as well as new hires (like, me!).

Thanks!

---
*Reported from: https://ubuntu.com/about/release-cycle*

**Comment by davegoddard42** [comment]
Remove "ubuntu" from each label and add a a title on the left hand side saying "Ubuntu Release". This will give enough space to include the name

**Comment by cristinadresch** [comment]
@briannadstuart could you review the design from Dave and let us know if this addresses your comment please? Thank you

**Comment by briannadstuart** [comment]
That's great - thank you!
