### ISSUE TITLE
21.10 kernel is 5.13

### ISSUE THREAD

**Issue by mhampl** [canonical-web-and-design/ubuntu.com#10866]
Besides the image in
https://ubuntu.com/about/release-cycle#ubuntu-kernel-release-cycle
"21.10 kernel" should be updated to "5.13 kernel"

https://github.com/canonical-web-and-design/ubuntu.com/blob/main/templates/about/release-cycle.html#L284

---
*Reported from: https://ubuntu.com/about/release-cycle*

**Comment by cristinadresch** [comment]
@nmav let us know your thoughts on this

**Comment by nmav** [comment]
This is correct! We use the 5.13 kernel
