### ISSUE TITLE
Aggregation Issues on cert site

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/ubuntu.com#10888]
## Summary

Looking at the following certification:
https://ubuntu.com/certified/201809-26501

There's an entry for 16.04 and this is incorrectly aggregating the hardware from other certs on this machine.

The 16.04 cert shows that 16.04 w/ the 4.4 kernel is certified using 
Processor	
Intel Corp. Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz
Intel Corp. Intel(R) Xeon(R) Platinum 8276 CPU @ 2.20GHz

Which is incorrect.  Looking on the back end, the 16.04 certificate used the Skylake (8180) CPU:
https://certification.canonical.com/certificates/1810-11031/

while the 18.04 cert was tested using Cascade Lake and Skylake (there are two listed 18.04 certs, correctly, as one is for SKL and one for CLX) BUT boht 18.04 certificates ALSO are aggregating the hardware listings, so there's little reason to display both 18.04 certs if you're going to aggregate the hardware for both into one dump.

## Process

Open the first link and click on the 16.04 entry, you'll see two CPUs when only one 16.04 cert exists for that machine. so one listed CPU is aggregated incorrectly from somewhere else.

## Current and expected result
Current: Certificates are incorrectly aggregating component details from all certificates, leading to incorrect statements of certification.
Expected: Certificates correctly reflect the hardware used for that certificate only and do not aggregate hardware from other certificates, thus accurately reflecting the hardware that was tested for each release.

## Screenshot
![Screenshot from 2021-11-17 15-08-13](https://user-images.githubusercontent.com/4295496/142274653-d8d13c06-6b98-42b0-8a8b-16a3d0ff5c9e.png)
![Screenshot from 2021-11-17 15-08-30](https://user-images.githubusercontent.com/4295496/142274669-584d3223-b5a4-4307-8387-f3dcbad955f4.png)
![Screenshot from 2021-11-17 15-08-47](https://user-images.githubusercontent.com/4295496/142274718-1f854667-0b1d-490c-a325-9d4ea9269c92.png)

**Comment by carkod** [comment]
@codersquid can you take a look at the API? it seems to be returning the Intel processors too https://certification.canonical.com/api/v1/certifiedmodeldetails/?format=json&canonical_id=201809-26501

**Comment by codersquid** [comment]
This is an issue with the data being returned by the api and not an issue for the frontend.

**Comment by codersquid** [comment]
however, I did notice where the wrong api is used when a user clicks through for the hardware details. I can open a separate issue for that.
