### ISSUE TITLE
'OpenStack Y LTS' should be 'OpenStack Yoga LTS'

### ISSUE THREAD

**Issue by pmatulis** [canonical-web-and-design/ubuntu.com#10901]
On the [The Ubuntu lifecycle and release cadence](https://ubuntu.com/about/release-cycle) page, in the **OpenStack release cycle** section, at the top of the image, 'OpenStack Y LTS' should be 'OpenStack Yoga LTS'.

---
*Reported from: https://ubuntu.com/about/release-cycle

**Comment by sowasred2012** [comment]
Closing, this was fixed by [#10391](https://github.com/canonical-web-and-design/ubuntu.com/issues/10898)
