### ISSUE TITLE
[COPY UPDATE] /esm - "ROS Extended Security Maintenance"

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#10941]
Please update /esm - "ROS Extended Security Maintenance" from the [copy doc](https://docs.google.com/document/d/1oiz_006n9U1Ya50wdSkKIyj_jsxSr92FdCpkDU4kpHs/edit?usp=drivesdk)

**Comment by minkyngkm** [comment]
This issue was resolved by this [PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/10950)
