### ISSUE TITLE
Broken URL to App-Armor engagement page

### ISSUE THREAD

**Issue by are-scenic** [canonical-web-and-design/ubuntu.com#10946]
Hi,

Link to https://ubuntu.com/engage/apparmor-intro is not working. However, google and some Canonical documents refer to this URL.
Perhaps some aliasing might help.

Kind regards

**Comment by sowasred2012** [comment]
Hi, thanks for reporting this @are-scenic - earlier today there was an issue causing 500s on pages like this, and the issue has since been resolved; the link you provided now works as expected. I'll close this issue, but please reopen if it persists for you.
