### ISSUE TITLE
[Engage Page] MAAS white paper

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#10955]
From copy doc: https://docs.google.com/document/d/1Q-7KpNu5bB3kWV4uNuyj1yeXhmqqU_tBlOQXpwgz3CI/edit#

We're to create the page in discourse and link to the whitepaper being created here: https://github.com/canonical-web-and-design/brand-squad/issues/593

**Comment by sowasred2012** [comment]
Currently blocked by marketing: https://warthogs.atlassian.net/browse/MKTG-611

**Comment by pmahnke** [comment]
This is live - https://ubuntu.com/engage/bare-metal-kubernetes
