### ISSUE TITLE
Black screen while copying fonts to ~/.fonts 

### ISSUE THREAD

**Issue by forrhead** [canonical-web-and-design/ubuntu.com#10961]
I ran: sudo cp *.ttf *.TTF /usr/share/fonts/truetype/ and sudo cp *.otf *.OTF /usr/share/fonts/opentype

Was running CPU heavy software while the fonts copied.  Everything froze. I forced a restart and now, after logging in my user, I get only black screen with working mouse curser.  

Entering the terminal, either through login screen or my second “test” user, It does not seem “kill”, “killall” or “pkill” are actually killing any of the processes. 

I have also taken every appropriate step here for my old Alienware witha graphics card: https://support.system76.com/articles/login-loop-pop/

Is there anyone out there who can please help me?!? I went full linux just last winter, despite not being a programmer. I am not relying out it for my current deadlines, but I am much more comfortable working inside Linux than Mac or Windows now, except when I break sh1t. Thank you!!!!

**Comment by sowasred2012** [comment]
Thank you for reporting this bug; however, this repo is for the ubuntu.com website, not the OS.  [This might help you find the right place to file it](https://help.ubuntu.com/community/ReportingBugs).
