### ISSUE TITLE
Link on smart-city page is broken

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#10977]
## Summary
There is a 404 link on the /internet-of-things/smart-city page

## Process
- Go to https://ubuntu.com/internet-of-things/smart-city
- Find the "container confinement and kernel livepatch" link click it and see that it 404's

## Current and expected result
- The [copy doc](https://docs.google.com/document/d/1Zh-IkLDnaqmPr4TTeUZ3mtyY2_OGW4iElfntYWZyveY/edit#) for that page suggested the link is in fact two links. 
- For extra bonus points the actioned suggestions in the copy doc should be resolved.

**Comment by petesfrench** [comment]
@anthonydillon I don't have an option to resolve some of the conversations, not sure if it is a permission thing or something
