### ISSUE TITLE
Render community membership on personal token

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#11016]
## Summary
If a user is a community member we should display that information on the personal token.

## Process
The number of machine's a personal token can be applied to is returned by the API. If that is 50 that person has a community membership and that should be viable somewhere on the logged in view of the store.

## Current and expected result
We currently site the number of attached machines but with no reference to the level of membership.

**Comment by wgx** [comment]
@anthonydillon @ClementChaumel @albertkol @jpmartinspt @cristinadresch 

So the way this works is a bit confusing. Personal tokens are for up to 3 machines, BUT we don't actually police that. 

What we're saying is that if you're a community member we *allow* you to use up to 50 machines, but it's not policed - it's a 'soft' limit. 

So;

1. There's no flag per user that designates a community member
2. There's no actual monitoring of your usage of the personal token - it's an honesty system

We can change this, but it would need to wait until the new telemetry work is done and released by the UA client team.

Then, we could look at adding these kinds of things. We would need some sort of GUI and process for designating a user as a community member and giving them access to the 50 licences. 

I suggest this is "won't fix" for now.

**Comment by anthonydillon** [comment]
I understand that it is slightly awkward to display limits when they are soft limits but that is not confusing in and of its self. It is awkward to be a community member (or think you are one) without any confirmation of this in the UI.

To address the points raised:
1. There is a flag returned from the API indicating if someone is a community member. We had the feature in previous version of the dashboard UI. It's actually just a lookup to membership of a lp team.
2. I am not suggesting we display usage as part of this issue (that feature should come later, as you mention). But simply indicate somehow the current person is a community member and what that means.

This is simply a feature that has been lose in migration. Not something entirely new.

**Comment by wgx** [comment]
Sounds like a great outcome for users, let's do it. 👍🏽

**Comment by albertkol** [comment]
This has not moved for a long time. If you think this is still needed, please re-open.
