### ISSUE TITLE
Gif not loading properly from Cloudinary on a WP page

### ISSUE THREAD

**Issue by VergilYotov** [canonical-web-and-design/ubuntu.com#11010]
The [gif in the middle of the page](https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,c_fill,w_928,h_590/https://ubuntu.com/wp-content/uploads/e026/beforesnap.gif) does not load. 

However, the gif previews in Wordpress and load fine [directly](https://ubuntu.com/wp-content/uploads/e026/beforesnap.gif),

---
*Reported from: https://ubuntu.com/blog/how-to-stream-video-with-raspberry-pi-hq-camera-on-ubuntu-core*

**Comment by sowasred2012** [comment]
@VergilYotov do you still see this issue? I've just checked the page and it seems OK for me.

**Comment by carkod** [comment]
Seems to work. Feel free to re-open if the issue persists
