### ISSUE TITLE
[Sphinx] Page title should not be displayed in local ToC

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/ubuntu.com#11029]
The RHS ToC shouldn't include the title of the page you are currently on

See [comment](https://github.com/evildmp/vanilla-sphinx-test/issues/11#issue-1048776374)

**Comment by sowasred2012** [comment]
This is being addressed by: https://github.com/evildmp/vanilla-sphinx-test/pull/40

**Comment by sowasred2012** [comment]
The PR has been merged
