### ISSUE TITLE
Broken favicon.ico redirect for pages.ubuntu.com leading to mixed content

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/ubuntu.com#11051]
## Summary
Pages on pages.ubuntu.com, e.g. https://pages.ubuntu.com/eBook-MAAS.html have 

```
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" >
<link rel="icon" href="/favicon.ico" type="image/x-icon" >
```
alongside other, richer icons for e.g. iOS devices

https://pages.ubuntu.com/favicon.ico however redirects to http://ubuntu.com (not to a favicon, and goes from https:// to http://)

## Process

1. Go to https://pages.ubuntu.com/eBook-MAAS.html
2. Note mixed content message in the browser (seen in Firefox and Chromium)
3. curl https://pages.ubuntu.com/favicon.ico

## Current and expected result

Currently see an issue with mixed content, and the curl shows a redirect to http://ubuntu.com

Expect to not see any mixed content, and for either the page not to link to `/favicon.ico` or for pages.ubuntu.com/favicon.ico to be a reasonable ICO file (redirect, or actual content).

## Browser details

Firefox 95.0 but also Chromium 96.0.4664.93

**Comment by carkod** [comment]
As far as I know, we don't mantain that site. Might need to ask IS who is.

**Comment by pmahnke** [comment]
It is us, it is on Marketo, and I can do it.

**Comment by pmahnke** [comment]
It took ages, but I found the setting in marketo that prevented it from adding extra, not existent favicons.
