### ISSUE TITLE
20.04 FIPS openssl certification

### ISSUE THREAD

**Issue by setharnold** [canonical-web-and-design/ubuntu.com#11068]
Hello, the table on the FIPS page appears to be lacking the 20.04 FIPS OpenSSL certification. I found https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3966 which appears to be the corresponding paperwork.

I'm no expert on the certifications, it's probably worth asking Vineetha or Richard to give this table a review and make sure we're not missing anything.

Thanks

---
*Reported from: https://ubuntu.com/security/fips

**Comment by davegoddard42** [comment]
Peter emailed Richard

**Comment by setharnold** [comment]
@lechsandecki this was updated in https://github.com/canonical-web-and-design/ubuntu.com/commit/af041766b5f03109c2189b4f5365b4ba67e2dfa3  -- I think this was left open to make sure that the website matches what certifications we've actually got, but sadly Richard has moved on since then :( -- so this task should probably be reassigned to someone still with the team.

Thanks

**Comment by pmahnke** [comment]
@setharnold do you have a recommendation of another person to look after this, or can I close it until it is an issue or there is a person?

**Comment by setharnold** [comment]
@arossbell perhaps?

**Comment by arossbell** [comment]
I've opened PR #11257 to add one module that's been omitted. There are no other public modules missing from the table ... perhaps this issue could be closed after that PR is approved/merged?
I'll open another PR when the next modules are approved!

**Comment by setharnold** [comment]
Wonderful, thanks Adam!

**Comment by sowasred2012** [comment]
https://github.com/canonical-web-and-design/ubuntu.com/pull/11257 was merged, so sounds like this issue can be closed too.
