### ISSUE TITLE
[COPY UPDATE] tutorials - "MicroK8s tutorials"

### ISSUE THREAD

**Issue by davegoddard42** [canonical-web-and-design/ubuntu.com#11063]
Please add this tutorial **https://ubuntu.com/tutorials/getting-started-with-microk8s-on-ubuntu-core#1-introduction** to this page **tutorials - "MicroK8s tutorials"**  as per the [copy doc](https://docs.google.com/document/d/1Lpo7Od9VA1aHYmr9UVp02vCGOP5Zxmzx4zZE9YJwlQg/edit?usp=drivesdk)

Thanks

**Comment by davegoddard42** [comment]
Please leave this issue along for now.

**Comment by carkod** [comment]
> **tutorials - "MicroK8s tutorials"**

If this goes in https://microk8s.io/tutorials we should transfer the issue to https://github.com/canonical-web-and-design/microk8s.io
