### ISSUE TITLE
[Wiki] Broken link to GNOME HIG in UbuntuArchitecture

### ISSUE THREAD

**Issue by Polirecyliente** [canonical-web-and-design/ubuntu.com#11077]
Hi there, there is a broken link in the Ubuntu architecture wiki, at https://wiki.ubuntu.com/UbuntuArchitecture, in the 'Design Principles' heading. The anchor element has the content: 'GNOME Human Interface Guidelines (HIG)', and it links to http://library.gnome.org/devel/hig-book/stable, which now redirects to a 404 page in gnome.org.

I'm not 100% sure if I should report this here, because I can't find the wiki files in this repository. I'm only reporting this here as https://wiki.ubuntu.com is a subdomain of https://ubuntu.com. Where are the wiki files in this repo? Or are they generated? If I knew this, maybe I could send a Pull Request with a possible solution (after I investigated the current location of GNOME HIG). Thank you!

**Comment by fitojb** [comment]
I just updated the link on the page.

**Comment by Polirecyliente** [comment]
I have confirmed this, I think we can close this issue now, thank you @fitojb
