### ISSUE TITLE
KeyError: 'email'

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#11143]
Looks like we need some null checking here.

https://sentry.is.canonical.com/canonical/ubuntu-com/issues/22584/?referrer=github_plugin

```
KeyError: 'email'
(2 additional frame(s) were not displayed)
...
  File "flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "flask/_compat.py", line 39, in reraise
    raise value
  File "flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "webapp/views.py", line 683, in marketo_submit
    enrichment_fields = {"email": form_fields["email"]}

KeyError: 'email'
```

**Comment by jpmartinspt** [comment]
It's possible that there is a form somewhere where we are not submitting an e-mail and that leads to this error. @anthonydillon is it safe to say that all marketo forms need an e-mail? If so we could possibly raise a sentry error when there is no e-mail in the payload so we can find out the culprit.

**Comment by anthonydillon** [comment]
Not confident that is safe. We probably want the flexibility to have forms not asking for email.

**Comment by anthonydillon** [comment]
My point is that `form_fields["email"]` is used without checking that field exists in the form_fields.

**Comment by jpmartinspt** [comment]
Yeah I got that @anthonydillon. Just wanted to know if e-mail was a thing we always collect. If it is not I think the solution for this would be to actually put the enrichment section inside a `if 'email' in form_fields:` since if there is no e-mail we don't want to make that enrichment call.
