### ISSUE TITLE
Marketo form API Issue

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#11142]
This looks like someone has manipulated the form id when submitting the form. Should we add validation to the form id field when passing through the submit function?

https://sentry.is.canonical.com/canonical/ubuntu-com/issues/20743/?referrer=github_plugin

```
Marketo form API Issue
```

**Comment by sowasred2012** [comment]
@anthonydillon looking at the Sentry error, where do you see the manipulation? I just checked the ID given in the payload, and it matches the page given in the referrer (/advantage) - maybe I'm missing something in the Sentry report?

**Comment by sowasred2012** [comment]
Sentry itself has closed the issue for inactivity, and we couldn't see anything untoward. Happy to reopen if need be.
