### ISSUE TITLE
Multiple Media Stream Controlling support for Ubuntu 20.04LTS Desktop

### ISSUE THREAD

**Issue by yash10019coder** [canonical-web-and-design/ubuntu.com#11157]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*
## Media is controlled by these above top buttons when the fn lock is on
![20220114_194426_2487891648338495691](https://user-images.githubusercontent.com/76404817/149815457-a30e5357-7a33-441c-afb9-8b305483e62a.jpg)

## Summary

In Ubuntu 20.04LTS Desktop when there are more than one streams of media then Ubuntu only controls the first media stream and does not care about other streams.
The basic idea of this issue is that if someone has played a media and then paused it and started playing media from other source, then Ubuntu should manage the media which is playing currently or is on the top of the media stacks played.

## Process

1. Try playing a YouTube video on the browser.
2. Open another media stream like Spotify.
3. Pause the YouTube video 
4. Play Spotify then try to switch the tracks with the above buttons mentioned in the photo 
5. You won't be able to switch the music.

## Current and expected result

The music in Spotify should switch tracks and also Ubuntu must be able to manage multiple input streams

**Comment by sowasred2012** [comment]
Hi there, thanks for reporting this, but this repo is for the ubuntu.com website specifically - please take a look at: https://help.ubuntu.com/community/ReportingBugs for info on where to file this bug.
