### ISSUE TITLE
Pagination of certified hardware miscalculated

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/ubuntu.com#11188]
![image](https://user-images.githubusercontent.com/246192/150979636-794295a4-64d9-44d9-b0f5-260de0dbc712.png)

Instead of the normal Arabic Numerals for counting pages, it seems that sometimes the certified hardware list decides to jump?

Note that the offset links are also wrong (in the same way as the page number), so it's `0, 20, 40, 60, 80, 120` and not ... `100`

---
*Reported from:https://ubuntu.com/certified?q=&limit=20&category=Desktop&category=Laptop&vendor=Intel+Corp.&vendor=Lenovo&offset=40

**Comment by sparkiegeek** [comment]
https://staging.ubuntu.com/certified?q=&limit=40&category=Desktop&category=Laptop&vendor=Lenovo&vendor=Intel+Corp.&offset=0

still behaves oddly

page 1 shows pages 1-5
page 2 shows pages 1-4 # here's the bug
page 3 shows pages 1-5
page 4 shows pages 1-5

**Comment by petesfrench** [comment]
@sparkiegeek could you take a look at the demo to make sure it is working https://ubuntu-com-11214.demos.haus/certified

**Comment by sparkiegeek** [comment]
> @sparkiegeek could you take a look at the demo to make sure it is working https://ubuntu-com-11214.demos.haus/certified

:shipit:
