### ISSUE TITLE
Raspberry Pi Imaging Tool Won´t work

### ISSUE THREAD

**Issue by doognibor** [canonical-web-and-design/ubuntu.com#11180]
Hi, link won´t work error 404..
https://downloads.raspberrypi.org/imager/imager_amd64.deb

---
*Reported from: https://ubuntu.com/appliance/plex/raspberry-pi2*

**Comment by carkod** [comment]
I left a comment in the [copy doc](https://docs.google.com/document/d/1H_4L-kqKx6HJ0_3krpzdDVZ24pdVm5jb0evLMT6mcuo/edit#) to update this.
