### ISSUE TITLE
Not to show links to a source pkg in a USN when it is made for ESM

### ISSUE THREAD

**Issue by kirotawa** [canonical-web-and-design/ubuntu.com#11228]
## Summary

When a USN is made there is a section where it list the package/source/binary was affected. For ESM packages we can't provide a link to it since it is a private access/either doesn't exists. The way it is being published currently is making a link to the source as example: https://ubuntu.com/security/notices/USN-5252-2

At the source affected list for each releases when it is ESM is showing a link, like to: https://launchpad.net/ubuntu/+source/policykit-1/0.105-14.1ubuntu0.5+esm1, what results in an error, as it doesn't exists. 

## Process

1. Go to a USN ESM page published like:   https://ubuntu.com/security/notices/USN-5252-2
2. try to access the link to the source package in listed Xenial esm ones. 
3. You'll get an error page

## Current and expected result

We expect it just show the name of the package/source without any link when it is about ESM updates.

Thanks in advance!

**Comment by carkod** [comment]
This issue seems duplicated? https://github.com/canonical-web-and-design/ubuntu.com/issues/11198
The link https://launchpad.net/ubuntu/+source/policykit-1/0.105-14.1ubuntu0.5 without the `esm1` works

**Comment by kirotawa** [comment]
It works without the esm1 because it points to an old version of the package when it was in archive. So it is not ESM/current related to the USN.

Thanks it is a dup, sorry.
