### ISSUE TITLE
/kubernetes/docs/X.YY/release-notes bundle links 404

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-web-and-design/ubuntu.com#11242]
The bundle links 404 on all of the release notes pages.

---
*Reported from: https://ubuntu.com/kubernetes/docs/1.22/release-notes*

**Comment by anthonydillon** [comment]
Thanks for reporting this issue @cjohnston1158.

@evilnick could you look into this?

**Comment by sowasred2012** [comment]
@evilnick - this is still valid, could you take a look please?
