### ISSUE TITLE
Handle security API failures gracefully

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/ubuntu.com#11253]
Following on from https://github.com/canonical-web-and-design/ubuntu.com/pull/11249#issuecomment-1042361625, we should ensure that any 504s or other errors from the security API result in a nice official well-styled and descriptive error page on any relevant ubuntu.com pages (e.g. /security/cves). This page should have a descriptive message and an appropriate status code. I can't quite decide whether 502 or 503 is most appropriate. I think maybe 503.

**Comment by mtruj013** [comment]
Fixed in https://github.com/canonical-web-and-design/ubuntu.com/pull/11249
