### ISSUE TITLE
Survey pop up appears misaligned on small screens

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#11263]
I was happier reading a post of our blog and then a survey popup thing popped out from the side. I couldn't read it as it was partly visible. Made me stop reading to be honest.

![Screenshot_20220219-203910.jpg](https://user-images.githubusercontent.com/1413534/154818335-a6ff27df-4630-4308-a700-de71f40e6506.jpg)

**Comment by davegoddard42** [comment]
Switched off the pop up for mobile users - should only appear on desktop going forward.
