### ISSUE TITLE
does some one know how to recover this with out reinstalling os and losing all data?

### ISSUE THREAD

**Issue by wolfgraphicsllc** [canonical-web-and-design/ubuntu.com#11289]
---[ end kernel panic - not syncing: attempted to kill init! exitcode= 0x00000100--- how to fix this on raspberry pi 4

**Comment by pmahnke** [comment]
Sounds horrible, however, this repo is for the ubuntu.com website, not the OS.  [This might help you find the right place to file it](https://help.ubuntu.com/community/ReportingBugs).

You might get more immediate help on [askubuntu.com](https://askubuntu.com/) or [forum.ubuntu.com](https://ubuntuforums.org/).

Good luck.

**Comment by wolfgraphicsllc** [comment]
yes yes it is and so far the only fix found is re install however i did hear some where one could rebuild the kernel! but thank you for responding i will see what else i could find
