### ISSUE TITLE
certified devices should include subsystem information

### ISSUE THREAD

**Issue by codersquid** [canonical-web-and-design/ubuntu.com#11311]
Some devices have subsystem pci.id, not just the main pci.id. This information should be shown on the hardware details page.

For example,

https://ubuntu.com/certified/202108-29379 shows the wifi pci.id as (8086:2725).

https://certification.canonical.com/api/v1/certifiedmodeldetails/?canonical_id=202108-29379 includes the subsystem id, 8086:4020.

The information should be displayed, though I don't know what the display should look like. maybe (<main id> <subsystem id>)?.

**Comment by carkod** [comment]
@codersquid Is this part of the wireless information?

**Comment by codersquid** [comment]
This information can show up in any device that is on the pci or usb bus, not just wireless cards.

**Comment by carkod** [comment]
> This information can show up in any device that is on the pci or usb bus, not just wireless cards.

mm ok. What is it related to? The devices directly?

**Comment by codersquid** [comment]
On Wed, Mar 9, 2022 at 7:15 AM Carlos Wu ***@***.***> wrote:

> This information can show up in any device that is on the pci or usb bus,
> not just wireless cards.
>
> mm ok. What is it related to? The devices directly?
>

Yes, for some devices the main id does not have enough resolution to
distinguish which hardware was installed. That's true in the case of the
wifi card in this example.
