### ISSUE TITLE
Typo in OpenStack blog post

### ISSUE THREAD

**Issue by davegoddard42** [canonical-web-and-design/ubuntu.com#11321]
On this [blog post](https://ubuntu.com/blog/openstack-is-dead), there is a typo - it should say "world" not "word". See image below

![image.png](https://images.zenhubusercontent.com/609106f0180d4707d2eed75a/632dbc4c-4b6d-434c-9063-88ac5fd05b86)

**Comment by carkod** [comment]
Fixed
