### ISSUE TITLE
"Token" is not on the page, but referred to from the CLI

### ISSUE THREAD

**Issue by cpaelzer** [canonical-web-and-design/ubuntu.com#11357]
Hi,
when you use `ua` in the cli it will rightfully tell you:

```
root@b:~# ua attach
Attach requires a token: sudo ua attach <TOKEN>
To obtain a token please visit: https://ubuntu.com/advantage.
```

But then you get to to https://ubuntu.com/advantage and after logging in there is no word "Token" anywhere around the token.
See the image below.
![image](https://user-images.githubusercontent.com/14993822/158853995-26a0b08b-3283-4a4b-8897-ab1bf08d8bbe.png)

The only occurrence of token is in the bottom left at "Free Personal Token" but then when opening above the token that one is meant to copy it still says just **"Subscription"**.

Could you please rename that to **"Subscription token"** or even **"Subscription token (pass this to ua attach)"** or anything like this to help users to quicker find what to use?

---
*Reported from: https://ubuntu.com/advantage*

**Comment by wgx** [comment]
@albertkol @ClementChaumel there is another ticket open elsewhere to change Subscription to Token everywhere.
