### ISSUE TITLE
All Server images lead to dead 404 links

### ISSUE THREAD

**Issue by Makaze** [canonical-web-and-design/ubuntu.com#11400]
The download links for the Raspberry Pi editions of Ubuntu all lead to invalid URLs. This happens both with the rpi-imager app and the direct download from Ubuntu's website. How I get to the 404s: https://ubuntu.com/download/raspberry-pi

The dead URLs: https://cdimage.ubuntu.com/releases/20.04.4/release/ubuntu-20.04.4-preinstalled-server-arm64+raspi.img.xz ; https://cdimage.ubuntu.com/releases/20.04.4/release/ubuntu-20.04.4-preinstalled-server-armhf+raspi.img.xz ; https://cdimage.ubuntu.com/releases/21.10/release/ubuntu-21.10-preinstalled-server-arm64+raspi.img.xz

---
*Reported from: https://ubuntu.com/download/raspberry-pi*

**Comment by adalava** [comment]
The same for me. As workaround I could download the raspberry pi images from here: https://old-releases.ubuntu.com/releases/20.04.1/

**Comment by sowasred2012** [comment]
Thanks for reporting this, we'll look into this immediately

**Comment by sowasred2012** [comment]
Hi there, these links are now working, but please let us know if you have any more problems!
