### ISSUE TITLE
Query parameters on /certified always return the search view

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#11428]
- Visit https://ubuntu.com/certified?_ga=2.21855739.1592984825.1648455425-346899473.1635344581
- You'll be presented with the search results view
- Visit https://ubuntu.com/certified
- You'll be presented with the overview page

The example link given above only includes some google analytics parameters, so I'd expect it to show the overview page.

It seems like the view for this page is assuming _any_ query parameter relates to the search, and is showing that page regardless of whether it actually is or not.

**Comment by sowasred2012** [comment]
@carkod @nottrobin could this be picked up in systems work?

**Comment by nottrobin** [comment]
Files pr. One line fix.
