### ISSUE TITLE
./entyrypoint 127.0.0.1 gives errors

### ISSUE THREAD

**Issue by abhigyanghosh30** [canonical-web-and-design/ubuntu.com#11426]
I was trying to run the website as a simple flask app. So I was following the instructions in HACKING.md.  I have two issues,
1. The website runs fine when I do a simple `export FLASK_APP="webapp/app.py"` but when I run "./entrypoint 127.0.0.1" it throws the following error however nothing seems to be broken when I go to 127.0.0.1:
https://pastebin.com/RXccK4Es
2. How do you run tests? (I was trying to run tests to check if actually everything was working). So I tried running `python test_routes.py` but I get the following error: 
```
Traceback (most recent call last):
  File "/home/masterg/Documents/canonical/ubuntu.com/tests/test_routes.py", line 10, in <module>
    from webapp.app import app 
```

**Comment by abhigyanghosh30** [comment]
[UPDATE]
Forgot to mention the environment. Running on Manjaro
Got the tests running.

**Comment by carkod** [comment]
We usually run the project using `dotrun`. I don't know if Manjaro supports snaps but you would install `dotrun` as a snap. Otherwise, you should try using the `./run` shell script

**Comment by carkod** [comment]
Please reopen if you still have any issues.
