### ISSUE TITLE
images are not displaying on /appliance/lxd

### ISSUE THREAD

**Issue by minkyngkm** [canonical-web-and-design/ubuntu.com#11434]
## Summary

The images are not displaying on https://ubuntu.com/appliance/lxd

![image](https://user-images.githubusercontent.com/57550290/161046426-d8616a75-4ba4-4e8b-940d-483e977f1d1d.png)

and when clicking the links they show empty pages

![image](https://user-images.githubusercontent.com/57550290/161046793-6f6672e1-3386-48a1-b417-7fa44ca7d4b2.png)

**Comment by anthonydillon** [comment]
This screenshot links can be found here: https://github.com/canonical-web-and-design/ubuntu.com/blob/main/templates/appliance/lxd/index.md in the frontmatter of the page.

**Comment by Lukewh** [comment]
Also being tracked here: https://github.com/canonical-web-and-design/snapcraft.io/issues/3943

I've started a conversation with the store team that provides these - looks like intermittent empty responses
