### ISSUE TITLE
Many blog post's resulting in 500 error

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#11441]
Here is a list of blog posts that are 500'ing:
- https://ubuntu.com/blog/meet-canonical-at-cloud-expo-europe-london-2022
- https://ubuntu.com/blog/deep-work-in-interesting-times
- https://ubuntu.com/blog/smart-agile-mlops-on-any-cloud-canonical-releases-charmed-kubeflow-1-4
- https://ubuntu.com/blog/artificial-intelligence-ai-generated-art-created-in-space-as-prelude-to-celestium-global-art-and-stem-project
- https://ubuntu.com/blog/canonical-and-corespace-announce-partnership-to-offer-organizations-one-stop-shopping-for-private-clouds

Author page erroring:
- https://ubuntu.com/blog/author/mcjaeger

**Comment by samubarb** [comment]
Found also this, for what it's worth:

- https://ubuntu.com/blog/universal-snap-packages-launch-on-multiple-linux-distros

**Comment by sowasred2012** [comment]
Closing - we found the source of the issue, it was a broken image in a recent article that was showing up as a related post in other articles and causing them to also 500. We removed the image, updated the author, and have raised an issue on the blog module to think about handling similar errors in a better way: https://github.com/canonical-web-and-design/canonicalwebteam.blog/issues/164

**Comment by sowasred2012** [comment]
I should probably have led with "all of those pages are working again! :tada: :tada: :tada: :tada: :tada:"
