### ISSUE TITLE
ubuntu-drivers list_oem not list-oem

### ISSUE THREAD

**Issue by LeisureLinux** [canonical-web-and-design/ubuntu.com#11469]
a typo on this page. 

---
*Reported from: https://ubuntu.com/kernel/lifecycle*

**Comment by xnox** [comment]
ubuntu-drivers: error: argument <command>: invalid choice: 'list_oem' (choose from 'list', 'list-oem', 'devices', 'install', 'autoinstall', 'debug')

The command has always been list-oem with dash. What language are you browsing the web-page in and what fonts are you using? If you copy and paste the command from the webpage into the terminal, is it with dash?

**Comment by minkyngkm** [comment]
I am closing this issue as it seems it's not a typo. Thanks :)

**Comment by LeisureLinux** [comment]
Here is the view-source code on the html page :
https://ubuntu.com/kernel/lifecycle

` <p>Note that certain desktop machines may be on a separate "OEM" track. To determine if the machine is eligible for this, run the command <code>ubuntu-drivers list-oem</code> from a terminal. `

**Comment by xnox** [comment]
> Here is the view-source code on the html page : https://ubuntu.com/kernel/lifecycle
> 
> `<p>Note that certain desktop machines may be on a separate "OEM" track. To determine if the machine is eligible for this, run the command <code>ubuntu-drivers list-oem</code> from a terminal.`

list-oem is the correct command, list_oem does not exist. When I try list_oem i get an error; when i do list-oem everything works. Can you please explain what problem do you have with list-oem?

**Comment by LeisureLinux** [comment]
sorry my bad. terrible bad for raising this issue. 
I realize my brain must be something short-circuted that time. 
:-(
