### ISSUE TITLE
Your subscriptions - didn't save or cancel the actions and didn't get a warning

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#11464]
On the features tab, when we change what's included (ESM Apps, Infra, Livepatch) we get a [ cancel ] and [ save ] buttons at the bottom. I think those 2 buttons are easy to dismiss as, depending on the size of the screen, we might need to scroll down to be able to see them. In that case, the user will probably leave the page or click on another subscription thinking those changes were automatically saved and it was not. That said, I suggest having a modal or a notification (?) asking the user if they want to save the changes or discard them. I am currently working on the UX spec for the Vanilla modal and I am thinking about proposing a modal for these use cases, as a confirmation/saving or cancel actions - @wgx happy to discuss this further with you :)

https://user-images.githubusercontent.com/36884067/162201741-de20d54c-0224-403f-a3f6-d1dbd7d219bd.mov

---
*Reported from: https://ubuntu.com/advantage*

**Comment by wgx** [comment]
@anasereijo I think a "You have unsaved changes" modal would be a great idea, let's do it!

**Comment by wgx** [comment]
@abhigyanghosh30 

so in this case, a modal (which blocks the user from progressing) would be the best implementation:

if anything is changed on the view and save not clicked:
show a modal "you have unsaved changes, really navigate away?"
"Yes, leave" -> leaves view, discards changes
"No, stay here" -> closes modal, user stays here

**Comment by bartaz** [comment]
I may be mistaken, but I recall a discussion that switch component should be used for changes that take effect immediately after it is switched (so it's "saved" automatically).

<img width="162" alt="image" src="https://user-images.githubusercontent.com/83575/174538795-b60ab816-04f9-4be8-b66d-064b9677de32.png">

If this is a form that needs to be saved they probably should be standard checkboxes.

**Comment by wgx** [comment]
@bartaz This is a good point! If you're right, then its saving all the time so no need. Is there a way I can check from the component what it's doing?

**Comment by wgx** [comment]
@abhigyanghosh30  the behaviour I think would be safest is

1. Switches (toggles) as the users is turning something on or off
2. A Save button as some of the changes here can be destructive / dangerous

In this case, we'd still need a modal for unsaved warning.
