### ISSUE TITLE
Please update the Ceph versioning graphic

### ISSUE THREAD

**Issue by pmatulis** [canonical-web-and-design/ubuntu.com#11462]
The Ceph versioning graphic on https://ubuntu.com/ceph should be updated according to: 

![image](https://user-images.githubusercontent.com/6303808/162062976-0395c26d-8cb3-437b-a4bd-5e2d42a33f48.png)

This should be done at the very latest by April 21st as that's when the charms that support Ceph Quincy will be released.

p.s. Is it possible to make the delineation between Ubuntu releases clearer on the eventual web page? It's not currently the case:

![image](https://user-images.githubusercontent.com/6303808/162063531-335f53e2-557b-4308-b41e-38ebfdb62a4b.png)

Thank you.

---
*Reported from: https://ubuntu.com/ceph*

**Comment by lyubomir-popov** [comment]
I've made a version where all text is 14px, as lower than that can be an accessibility problem. Let me know what you think.

 ![Ceph table](https://user-images.githubusercontent.com/2741678/163352313-8ebc90ff-f1a8-4d65-bce2-3511a691bc0c.png)

**Comment by pmatulis** [comment]
Looks good. You just need to correct:

* **18.04 LTS Focal** to **20.04 LTS Focal**
* **18.04 LTS Jammy** to **22.04 LTS Jammy**

**Comment by lyubomir-popov** [comment]
@pmatulis thanks, updated.
