### ISSUE TITLE
Images broken on Nextcloud page

### ISSUE THREAD

**Issue by davegoddard42** [canonical-web-and-design/ubuntu.com#11472]
There are two images that appear broken on this page: https://ubuntu.com/appliance/nextcloud

**Comment by minkyngkm** [comment]
We had the same issues before(#11434, [#3943](https://github.com/canonical-web-and-design/snapcraft.io/issues/3943)) and @Lukewh is going to fix this page/issue.

**Comment by Lukewh** [comment]
This has been done. The store team also ran a script to tidy others up and have started a deeper investigation.
