### ISSUE TITLE
Is mongo db open source?

### ISSUE THREAD

**Issue by aragilar** [canonical-web-and-design/ubuntu.com#11513]
---*Reported from: https://ubuntu.com//blog/what-is-mongodb*

https://ubuntu.com//blog/what-is-mongodb states that mongo db is open source, as far as I know it's licensed under the SSPL, which isn't [open source](https://opensource.org/node/1099), should that be corrected?

**Comment by carkod** [comment]
@pmahnke do you have any thoughts about this?

**Comment by nottrobin** [comment]
I reached out to Michelle. She's said they'll update the article.
