### ISSUE TITLE
Charmed kubernetes copy update

### ISSUE THREAD

**Issue by petesfrench** [canonical-web-and-design/ubuntu.com#11510]
https://docs.google.com/document/d/1mEOBW4pfsWJqTLm9Pn9myKtaslD-QB2RvUKcNQ52bXU/edit#heading=h.gcvta4pbyzz

https://docs.google.com/document/d/1b018GoKMF3abEFJlUkfAEK2JEhXWICKF4V0dGdTvgJs/edit

**Comment by mtruj013** [comment]
Copy updates for [/kubernetes](https://docs.google.com/document/d/1b018GoKMF3abEFJlUkfAEK2JEhXWICKF4V0dGdTvgJs/edit) were addressed in this [pr](https://github.com/canonical-web-and-design/ubuntu.com/pull/11554)
