### ISSUE TITLE
[22.04 post release] Update Lenovo laptop image

### ISSUE THREAD

**Issue by petesfrench** [canonical-web-and-design/ubuntu.com#11524]
The Lenovo laptop image on /organisations & /developers has a windows toolbar at the bottom so needs replacing

![image.png](https://images.zenhubusercontent.com/609109f935b2ad43af7db68e/8cf6a87a-a6de-4e06-ab19-022ad32eb410)

**Comment by spencerbygraves** [comment]
@petesfrench here you go...

https://assets.ubuntu.com/v1/8c02c97a-Laptop-X1-Carbon.png
