### ISSUE TITLE
contact us card on my advantage page doesn't let me to contact us

### ISSUE THREAD

**Issue by xnox** [canonical-web-and-design/ubuntu.com#11538]
I am logged in, and on this page https://ubuntu.com/advantage i see "Your subscriptions" summary.

Under my subscriptions there are three columns / cards "Got questions?" "Legal info" and "Further reading"

The "Got questions?" card has the wording "Let our experts help you in the right direction with Ubuntu Advantage. [Contact us](https://ubuntu.com/support/contact-us?product=contextual-footer-ua)" however clicking that contact-us button doesn't let me contact canonical. Instead an unrelated webform opens offering me to "Register your interest for the Ubuntu Pro on-prem beta"

---
*Reported from: https://ubuntu.com/advantage*

**Comment by anthonydillon** [comment]
Thanks, @xnox, you are right. I will update that link.
