### ISSUE TITLE
Broken image links on the Ubuntu installation guide

### ISSUE THREAD

**Issue by DCrawley94** [canonical-web-and-design/ubuntu.com#11551]
The guide found [here](https://ubuntu.com/tutorials/install-ubuntu-desktop#1-overview) has some missing images that look like broken links

Issues start on step 5 as seen in this screenshot:

![Screenshot 2022-04-27 at 11 12 36](https://user-images.githubusercontent.com/76622730/165496044-47c6e156-06b7-4d03-aae9-81f3a91b348b.png)

**Comment by anthonydillon** [comment]
It looks like the images are back now. Is this issue resolved?

**Comment by carkod** [comment]
Issues seems to be resolved, closing.
