### ISSUE TITLE
Images in blog thumbnails don't scale on small screens

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/ubuntu.com#11589]
## Summary

Images on Ubuntu blog seem to have fixed size and don't scale well on smaller screens.
When screen is resized to below 1024px (or so) the cards start to take whole screen width, but images are smaller (while occupying large amount of whitespace around):

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/83575/167430919-740ea2c8-3e11-4b2a-bc9f-905b90297261.png">

## Browser details

Chrome, FIrefox in macOS

**Comment by sowasred2012** [comment]
This was fixed by https://github.com/canonical-web-and-design/ubuntu.com/pull/11709
