### ISSUE TITLE
Expired certificate on download page

### ISSUE THREAD

**Issue by AlexandrTyshchenko** [canonical-web-and-design/ubuntu.com#11587]
Try to download Ubuntu Server 22.04 LTS and you can see that the certificate is expired.

![Screenshot_409](https://user-images.githubusercontent.com/46418015/167310198-17e9c39e-a145-4c2f-8081-05f492d021ad.jpg)
---
*Reported from: https://ubuntu.com/download/server*

**Comment by pmahnke** [comment]
@AlexandrTyshchenko this is a bad cert on a mirror that we use, not directly Canonical.  I have asked our IS team to get in touch with the people running ubuntu-releases.ip-connect.vn.ua to ask them to update their cert.

Thank you.
