### ISSUE TITLE
Possible copy error: Desktop page still mentions 20.04

### ISSUE THREAD

**Issue by vitalkanev** [canonical-web-and-design/ubuntu.com#11592]
The "Visually stunning, wherever it’s used" section of the [/desktop](https://ubuntu.com/desktop) page still mentions 20.04 with "a new default theme, Yaru".

22.04 includes additional changes to the theme, including colour themes (as seen in the image by the left of the text)

![Screen capture with a bug](https://user-images.githubusercontent.com/18398761/167595081-2a029588-4bd3-4a8d-8cb2-eaaab23a62cb.png)

---
*Reported from: https://ubuntu.com/desktop*

**Comment by sowasred2012** [comment]
Thanks for reporting this @vitalkanev, we'll update ASAP
