### ISSUE TITLE
[web tribe specs] Indico events website

### ISSUE THREAD

**Issue by davegoddard42** [canonical-web-and-design/ubuntu.com#11624]
https://docs.google.com/document/d/178Eg1n9VEBQwUMDLdUjHDtwc-t1-HQSs74LRIiyRutM/edit

**Comment by anthonydillon** [comment]
The status of the spec is still draft but I left a few suggestions.

**Comment by anthonydillon** [comment]
Pete to meet with someone to get the Charm working.

**Comment by petesfrench** [comment]
I had a meeting with Britt last night where went through the doc and he gave it a +1. Can you take another look @nottrobin?

**Comment by sowasred2012** [comment]
@nottrobin to take another look

**Comment by nottrobin** [comment]
Approved
