### ISSUE TITLE
[Bubble nav updates] Server Download UX

### ISSUE THREAD

**Issue by davegoddard42** [canonical-web-and-design/ubuntu.com#11635]
Explore way to highlight the alternative architectures (ARM, POWER, s390x) and MAAS (Provisioning) once the menu has been removed.

**Comment by anthonydillon** [comment]
@davegoddard42 are you actively working on this?

**Comment by davegoddard42** [comment]
@anthonydillon - yes, it's quite complex stakeholder wise, there's a lot of discussion involved, hence why it's taking a while
