### ISSUE TITLE
Left over of 72TB for storage support

### ISSUE THREAD

**Issue by nobuto-m** [canonical-web-and-design/ubuntu.com#11654]
It looks like the storage free tier has been bumped from 72TB to 192TB in:
https://github.com/canonical-web-and-design/ubuntu.com/pull/11516

However, there is one left over of mentioning 72TB in the service description.
https://github.com/canonical-web-and-design/ubuntu.com/blob/a005e722e5639cdaf01978794a5cd6d1de350b37/templates/legal/ubuntu-advantage-service-description/index.md?plain=1#L123-L126

---
*Reported from: https://ubuntu.com/legal/ubuntu-advantage-service-description*

**Comment by davegoddard42** [comment]
@nobuto-m thanks for raising this. We currently have an issue open to solve this.

**Comment by nobuto-m** [comment]
> @nobuto-m thanks for raising this. We currently have an issue open to solve this.

Hi, would you mind posting the link so that I can track the progress (if it's public)?

**Comment by davegoddard42** [comment]
@nobuto-m this should now be fixed, so I'm closing this issue. Please re-open if you have any further comments.
