### ISSUE TITLE
usb boot failed error: can't find command 'grub platform'

### ISSUE THREAD

**Issue by 73-eml** [canonical-web-and-design/ubuntu.com#11661]
---
*Reported from: https://ubuntu.com/contact-us*

**Comment by carkod** [comment]
Sorry, where are you reporting this error from?

**Comment by pmahnke** [comment]
@carkod I assume the person is having an issue with Ubuntu itself, not the website.


@73-eml 

Thank you for filing this bug; unfortunately, it is not the right place to report this particular issue. 

This repo is for the development of the ubuntu.com website, not the OS. 

You may want to [file a bug report in launchpad](https://bugs.launchpad.net/ubuntu).  

Here is information on [how to report a bug](https://help.ubuntu.com/community/ReportingBugs).

**Comment by davegoddard42** [comment]
@73-eml We're closing this issue for now, please leave a message if you need more help. Thanks.
