### ISSUE TITLE
fix: Broken Image Links

### ISSUE THREAD

**Issue by shikharvashistha** [canonical-web-and-design/ubuntu.com#11673]
## Preview
![image](https://user-images.githubusercontent.com/51105234/171843731-e039412b-a76f-4752-92e8-ef8ddc9a811d.png)
![image](https://user-images.githubusercontent.com/51105234/171843737-1d0dc4bc-63dd-499d-8a39-e7e7928fa7b4.png)

Link : https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-11-with-gui-support#3-download-ubuntu

**Comment by davegoddard42** [comment]
Hi @shikharvashistha, thanks for raising this. It's been previously reported and we're working on a fix here #11669

**Comment by shikharvashistha** [comment]
> Hi @shikharvashistha, thanks for raising this. It's been previously reported and we're working on a fix here #11669

I think the image issue mentioned in #11669 is with reference to the ubuntu installation tutorial, this issue is regarding broken image links on wsl2 installation page, are both the same?

**Comment by minkyngkm** [comment]
@shikharvashistha - The images have been updated. It should all look good now. Thanks.
