### ISSUE TITLE
/blogs layout breaks on smaller screens

### ISSUE THREAD

**Issue by petesfrench** [canonical-web-and-design/ubuntu.com#11690]
## Summary

- /blogs layout breaks on medium and small screens

## Process

Go to ubuntu.com/blogs and change the screen size

## Current and expected result

The blog cards are not responsive

## Screenshot

![image](https://user-images.githubusercontent.com/58276363/172465026-c3367649-3e4e-4828-a7b2-7b40f59aa75b.png)

**Comment by anthonydillon** [comment]
Could we please switch to using the Vanilla card pattern? https://vanillaframework.io/docs/patterns/card#content-bleed
