### ISSUE TITLE
typo on lxd virtual machines blog post

### ISSUE THREAD

**Issue by setharnold** [canonical-web-and-design/ubuntu.com#11711]
Hello, there's a small typo on the lxd virtual machines blog post:

> instance, s this 

Thanks

---
*Reported from: https://ubuntu.com//blog/lxd-virtual-machines-an-overview*

**Comment by petesfrench** [comment]
This typo has now been fixed here: https://admin.insights.ubuntu.com/wp-admin/post.php?post=108736&action=edit
