### ISSUE TITLE
Missing Discourse API key should produce a more informative error

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/ubuntu.com#11712]
This is what I get when trying to view tutorials without a Discourse API key:

![image](https://user-images.githubusercontent.com/519935/173530423-53b8f8f6-805a-4bb5-9ae9-5896bff37f8c.png)

**Comment by carkod** [comment]
I think this should be raised maybe in the discourse module, we use so many things these days that require API key

**Comment by nottrobin** [comment]
Good shout. @carkod would you be able to move the issue? Or is that not possible until this repo moves to Canonical org?

**Comment by carkod** [comment]
> Good shout. @carkod would you be able to move the issue? Or is that not possible until this repo moves to Canonical org?

I've tried to "Move issue" but I can't find the repo in the dropdown, so I guess it's not possible. I can do it manually
