### ISSUE TITLE
Blog cards with descriptions dont have correct padding

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#11734]
- visit ubuntu.com/blog
- the cards left of the newsletter form have descriptions, but padding hasn't been applied correctly:

![image](https://user-images.githubusercontent.com/2376968/174097491-bd891f7c-30e7-4a6f-855c-62e5640f8ba9.png)

**Comment by lyubomir-popov** [comment]
@sowasred2012 @anthonydillon flagged this, why not use the [content bleed card](https://vanillaframework.io/docs/examples/patterns/card/content-bleed) rather than this custom implementation? The only part that we don't have in vanilla is the top bar, which we can maybe add as a variant?

**Comment by lyubomir-popov** [comment]
@sowasred2012 just tried it in the browser, the only addition needed is indeed the top bar. @bartaz maybe we can introducex these in vanilla with a few common colours.
```
<div class="p-card u-no-padding">
      <header class="p-card__header u-no-margin--bottom" style="border-top: 3px solid #666;">
    <div class="p-card__inner u-no-padding--bottom">
      <h5 class="p-muted-heading">Charms</h5>
    </div>
  </header>
      <div class="p-card__inner">
        <img class="p-card__image" src="https://assets.ubuntu.com/v1/0f33d832-The-State-of-Robotics.jpg"><h3>The State of Robotics - August 2021</h3>
        <p>From robots learning to encourage social participation to detect serious environmental problems, it was a learning month.</p>
      </div>
      <hr class="u-no-margin--bottom">
      <div class="p-card__inner">
        by <a href="#">Bartek Szopka</a> on 21st August 2021
      </div>
    </div>
    ```

**Comment by sowasred2012** [comment]
@lyubomir-popov This issue is actually [a duplicate](https://github.com/canonical-web-and-design/ubuntu.com/pull/11730), it was fixed but it seems like u.c hadn't been deployed afterwards.

That aside, I would love to go with one of the Vanilla patterns, but I think it would need a little more than just the top bar - particularly the footer section, which looks odd at large, equal heights given it isn't fixed to the bottom - using your code it looks like this:

![image](https://user-images.githubusercontent.com/2376968/174504086-b47650e0-5195-4706-bbab-54c5587bcdd5.png)

I also took a look at the comments around using the content bleed pattern, aside from yours above, there is:
- this comment from @anthonydillon: https://github.com/canonical-web-and-design/ubuntu.com/issues/11690#issuecomment-1149152018
- which is on an issue that is a duplicate of https://github.com/canonical-web-and-design/ubuntu.com/issues/11589

I like the content bleed pattern, so I'm inclined to update this issue to request it be changed to that (while also preserving this conversation), but the category above the image looks odd to me - what do you think?

![image](https://user-images.githubusercontent.com/2376968/174504601-88113f62-4e7b-4a7a-8554-6ae311017dc4.png)

**Comment by lyubomir-popov** [comment]
@sowasred2012 Thanks for the additional context. The implementation I proposed will need some polish to address the valid points you've raised, but definitely doable. I'l play around some more and make a pr.

**Comment by sowasred2012** [comment]
@lyubomir-popov awesome - I'll close this one then, and we'll implement the new cards when your PR is ready.
