### ISSUE TITLE
typo in link href

### ISSUE THREAD

**Issue by picchietti** [canonical-web-and-design/ubuntu.com#11741]
Page: https://ubuntu.com/core
Link text: Full disk encryption
Link href: https://ubuntu.com/core/featrues/full-disk-encryption

Notice that "featrues" in the url above should be "features".

---
*Reported from: https://ubuntu.com/core*

**Comment by minkyngkm** [comment]
@picchietti Thanks for reporting this issue. It will be fixed soon. Thanks :)
