### ISSUE TITLE
Desactivar panel táctil al escribir no se puede desactivar 

### ISSUE THREAD

**Issue by Leviathan617** [canonical-web-and-design/ubuntu.com#11752]
Los archivos para modificar estás opciones están encriptado inclusive entrando desde el usuario root es imposible modificar los archivos tampoco funciona el gsettings set ni el chmod para autorizar el permiso de escritura tampoco el chown y esto Jode por qué cuando juego sin ratón el panel táctil se desactiva por lo que es injugable deberían añadir esta opción en configuración/panel táctil-Desactivar el panel táctil al escribir si/no saludos 

---
*Reported from: https://ubuntu.com/support*

**Comment by sowasred2012** [comment]
Title: 
"Disable touchpad when typing cannot be disabled"

Content: 
"The files to modify these options are encrypted even when entering from the root user it is impossible to modify the files neither does the gsettings set nor the chmod work to authorize the write permission nor does the chown work and this sucks why when I play without a mouse the touch panel is deactivated so it is unplayable they should add this option in settings/touchpad-Disable touchpad when typing yes/no greetings

**Comment by fitojb** [comment]
@Leviathan617 Estás en el lugar incorrecto. Este repositorio es el código fuente del sitio web de Ubuntu; cualquier problema con el sistema operativo va a Launchpad.net, no aquí.

**Comment by carkod** [comment]
@Leviathan617 Por favor, consulta la [guia](https://help.ubuntu.com/community/ReportingBugs) y si es necesario puedes abrir una  incidencia en Launchpad.
