### ISSUE TITLE
Broken link on /core

### ISSUE THREAD

**Issue by Hollzz** [canonical-web-and-design/ubuntu.com#11765]
## Summary

The "IoT app store" link on ubuntu.com/core, under "Key Features" is broken. It redirects to https://ubuntu.com/core/featrues/full-disk-encryption (gives a 404) but should redirect to https://ubuntu.com/internet-of-things/appstore. It is correct in the  copy doc but not on the  live page.

## Screenshot

<img width="1143" alt="Screenshot 2022-06-23 at 15 12 41" src="https://user-images.githubusercontent.com/15069682/175296496-970e8654-cb0c-468c-af0e-faf3a26681fe.png">

**Comment by minkyngkm** [comment]
Thanks for opening this issue @Hollzz. This should be fixed now :)

**Comment by Hollzz** [comment]
Thank you! :)
