### ISSUE TITLE
[visual update] juju.is/operator-day

### ISSUE THREAD

**Issue by petesfrench** [canonical-web-and-design/ubuntu.com#11797]
I spoke with Teodora Mihoc about the juju.is/operator-day page where we host videos and she has requested it has a small visual overhaul. As currently the page is quite dry.
https://docs.google.com/document/d/1ZFRGkZ4vvvMVOgq4MIsBuebHsA7Y0rTyiZ76qjQpOAg/edit#

**Comment by minkyngkm** [comment]
@spencerbygraves Could you please take a look at this?

**Comment by petesfrench** [comment]
Thank you @spencerbygraves, it looks great! We can get the video descriptions manually or I believe we can use the youtube api and some JS to fetch them dynamically. This will probably require some permission changes on the youtube account if it hasn't been done already.
