### ISSUE TITLE
Need update google-authenticator document.

### ISSUE THREAD

**Issue by sanketg86** [canonical-web-and-design/ubuntu.com#11792]
I observed missing pam config in below document while use for configure google-authenticator  on Ubuntu 20.04 LTS.

https://ubuntu.com/tutorials/configure-ssh-2fa#2-installing-and-configuring-required-packages

Need to add below line at the end of /etc/pam.d/sshd after `auth required pam_google_authenticator.so nullok`

`auth required pam_permit.so`

**Comment by sowasred2012** [comment]
Hi @sanketg86 - thanks for reporting this, the best place to report these issues is directly on the discourse post: https://discourse.ubuntu.com/t/configure-ssh-to-use-two-factor-authentication/13956
