### ISSUE TITLE
Broken page footer CSS on 'Certified' pages?

### ISSUE THREAD

**Issue by tomreyn** [canonical-web-and-design/ubuntu.com#11794]
On Firefox 101.0.1 and Chromium 101.0.4951.64, both running on Ubuntu 18.04 LTS, the page footer of a 'Certified' (hardware) page looks like this:
![image](https://user-images.githubusercontent.com/1328851/176863614-18e54254-7c5c-4eff-871d-53661daf5ffc.png)

I would assume that the dots on the very bottom are supposed to be positioned in front of the options given in the line above them (one dot for "Legal information" and so on).

---
*Reported from: https://ubuntu.com/certified/202006-28000*

**Comment by sowasred2012** [comment]
Hi, thanks for reporting this - this has [been addressed](https://github.com/canonical-web-and-design/vanilla-framework/issues/4429) in an upstream project, and will be rolled out to this site in the next couple of days.

**Comment by sowasred2012** [comment]
Closed by https://github.com/canonical-web-and-design/ubuntu.com/pull/11795
