### ISSUE TITLE
"A technical intro to Ubuntu Core 22" takeover "register webinar" CTA is linking to homepage

### ISSUE THREAD

**Issue by carkod** [canonical-web-and-design/ubuntu.com#11815]
## Summary

"A technical intro to Ubuntu Core 22" takeover "register webinar" CTA is linking to homepage. It should be linking to the respective webinar link or engage page.
Try to find similar/same name of engage page in the discourse engage page index list or if there is not, ask David Beamonte probably he knows.

**Comment by sowasred2012** [comment]
@carkod seems the link to the engage page was missing from the discourse entry, I've just updated. Also - get some rest! :wink:
