### ISSUE TITLE
microk8s install file on MacOS

### ISSUE THREAD

**Issue by JohnSedgmen** [canonical-web-and-design/ubuntu.com#11844]
macOS Monterey Version 12.4.

I was following the tutorial:
https://ubuntu.com/tutorials/install-microk8s-on-mac-os?&_ga=2.75028437.67766953.1657855306-438911294.1657855306#1-overview

Error returned during microk8s install step:

multipass was successfully installed!
Waiting for multipass...
Launched: microk8s-vm                                                           
ping: snapcraft.io: Temporary failure in name resolution                        
An error occurred when trying to execute 'sudo ping -c 1 snapcraft.io' with 'multipass': returned exit code 2.

microk8s does not run:
microk8s status
sudo: microk8s.status: command not found
An error occurred when trying to execute 'sudo microk8s.status' with 'multipass': returned exit code 1.

**Comment by sowasred2012** [comment]
Hi there, this is the repo for the website, you can leave a comment on the original Discourse post for issues like this, and the author may be able to help: https://discourse.ubuntu.com/t/install-microk8s-on-macos/13978?_ga=2.244694469.195228169.1658130881-1911518134.1654680560
