### ISSUE TITLE
Searching for CVEs in a package results in "Invalid payload" error

### ISSUE THREAD

**Issue by ist199099** [canonical-web-and-design/ubuntu.com#11857]
When searching for CVEs in a package for any current release (https://ubuntu.com/security/cves?q=&package=vlc&priority=&version=current&status=), I get an "Invalid payload" error.

**Comment by petesfrench** [comment]
@mtruj013 Can you take a look at this please?

**Comment by mtruj013** [comment]
@wapsi @ist199099 The invalid payload should be fixed now (ref: https://github.com/canonical-web-and-design/ubuntu-com-security-api/pull/104). @mhampl we are currently in the process of fixing the frequent timeouts, this is being tracked in a [separate issue](https://github.com/canonical-web-and-design/ubuntu-com-security-api/issues/101). Closing this as the original problem has been fixed, thank you all for taking the time to report these to us!
