### ISSUE TITLE
The style of the card header is not applied on /tutorials

### ISSUE THREAD

**Issue by minkyngkm** [canonical-web-and-design/ubuntu.com#11856]
<img width="622" alt="image" src="https://user-images.githubusercontent.com/57550290/179765292-b8409c3f-e061-47e1-93a0-1ffd61a670d6.png">

**Comment by sowasred2012** [comment]
Closing, this is a duplicate of https://github.com/canonical-web-and-design/ubuntu.com/issues/11855
