### ISSUE TITLE
Styling of topic labels on tutorials appears broken

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#11855]
Visit any tutorials page e.g. https://ubuntu.com/tutorials

The category labels in the header of each card look broken:

![image](https://user-images.githubusercontent.com/2376968/179765281-33866275-ed86-46f4-9df3-7e6ce1399f7c.png)

**Comment by carkod** [comment]
This is probably related to some Renovate update. We can either remove the `--desktop` styles or find the piece of CSS that has been removed.
