### ISSUE TITLE
Broken cards in the engage page

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#11865]
![image](https://user-images.githubusercontent.com/1413534/180256250-0a62975e-bd6c-488d-a188-625f20cd69d2.png)

---
*Reported from: https://ubuntu.com/engage*

**Comment by sowasred2012** [comment]
Closing - this is a duplicate of https://github.com/canonical-web-and-design/ubuntu.com/issues/11855
