### ISSUE TITLE
Ubuntu 21.10 shown on CVE tables

### ISSUE THREAD

**Issue by ist199099** [canonical-web-and-design/ubuntu.com#11876]
When searching for CVEs in a package (https://ubuntu.com/security/cves?q=&package=node-moment), Ubuntu 21.10 appears in the tables, but reached end-of-life on July 14.

---
*Reported from: https://ubuntu.com/security/cves?q=

**Comment by alexmurray** [comment]
I wonder if this release just needs to be deleted via https://ubuntu.com/security/api/docs#/default/delete_security_releases__release_codename__json

**Comment by alexmurray** [comment]
Ah I see - [impish](https://ubuntu.com/security/releases/impish.json) currently has it's support expiry date set as 2022-07-31T00:00:00 - as such I expect it will automatically disappear from results after that time.

**Comment by mtruj013** [comment]
Thanks @alexmurray, that's exactly correct.  Closing this issue.
