### ISSUE TITLE
CVE tracker: Footer middots wrap to the next line before their item does

### ISSUE THREAD

**Issue by tomreyn** [canonical-web-and-design/ubuntu.com#11872]
The issue discussed in https://github.com/canonical-web-and-design/vanilla-framework/issues/4429 still applies to the page footer on https://ubuntu.com/security/cves and all (or those I have seen) CVE pages. See also #11794.

---
*Reported from: https://ubuntu.com/security/cves*

**Comment by anthonydillon** [comment]
Hi @tomreyn we have deployed a fix for this. Thanks.
