### ISSUE TITLE
Missing USNs in search

### ISSUE THREAD

**Issue by eslerm** [canonical-web-and-design/ubuntu.com#11899]
Most USNs are missing when searching for `intel-microcode`.

e.g., [USN-5486-1](https://ubuntu.com/security/notices/USN-5486-1) is not listed when searching `intel-microcode`.

---
*Reported from: https://ubuntu.com/security/notices?order=newest

**Comment by eslerm** [comment]
It looks like the search applies to text, but not to package names.

**Comment by mtruj013** [comment]
Hi @eslerm, thanks for flagging. So it's not that usns are missing, it's that the functionality for searching a notice by package name does not currently exist. Right now you can only search by id, related cve id, or details. I agree though that it would be quite useful. There's already a [separate issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/9271) requesting this functionality, so I will close this one and see when we can schedule this work in. Thanks!
