### ISSUE TITLE
Use new pagination style on /resources

### ISSUE THREAD

**Issue by frankiegranato** [canonical-web-and-design/ubuntu.com#3133]
Please implement pagination style as seen on insights (blog.canonical.com)

---
*Reported from: https://www.ubuntu.com/resources*

**Comment by anasereijo** [comment]
@pmahnke @anthonydillon can we update this or are we killing resources?

**Comment by pmahnke** [comment]
@anasereijo how? just above related posts?

**Comment by anasereijo** [comment]
@pmahnke I think it should use the same pagination pattern as seen on the blog.

<img width="1439" alt="Screenshot 2019-05-08 at 11 55 57" src="https://user-images.githubusercontent.com/36884067/57370585-607ff400-7188-11e9-8a02-e24c9b0d1ee3.png">

**Comment by pmahnke** [comment]
look at how hard this is vs. getting max to update this page with the blog module

**Comment by pmahnke** [comment]
@b-m-f did you get the ubuntu.com/resources page to work with your new blog module? or is that still to do?

**Comment by b-m-f** [comment]
@tbille, did you add something for this?

**Comment by b-m-f** [comment]
@pmahnke, so this is not yet on **blog.u.c**, so we do not have the functionality in the blog module.
We can plan this into a future iteration though. I am not exactly sure what data should be on here. Maybe @solazio @sowasred2012 can tell whether or not we need a new endpoint here, or can actually just use the blog module as is.

**Comment by anasereijo** [comment]
Closing this for now as we may be ditching the resources page altogether.

**Comment by anthonydillon** [comment]
@anasereijo oh are we? that would save me a lot of time converting the section for the Flask migration?

**Comment by anasereijo** [comment]
I thought so as it says on https://github.com/canonical-web-and-design/ubuntu.com/pull/5366
