### ISSUE TITLE
Size of USB Drive For Installation Only Hinted At

### ISSUE THREAD

**Issue by loslosbaby** [canonical-web-and-design/ubuntu.com#4029]
I believe the size of the install media should be mentioned explicitly.  On the page below, the size of a necessary USB drive is only hinted at (larger than a CD-ROM):

> Either a DVD drive or a USB port for the installer media

I figure that since the install requirements are impressively modest, they would tempt people with modest resources in general, and there's still plenty of 1,2,4 etc Gb thumb drives floating around.

---
*Reported from: https://www.ubuntu.com/download/desktop*

**Comment by pmahnke** [comment]
@8none1 can you help?

**Comment by 8none1** [comment]
The problem I see with explicitly stating the size of the USB stick is that the ISO grows over time and could require maintaining.  We could either state "minimum 4GB" which would buy us a lot of time - or just leave it as is.  I don't think it's really a big problem.

**Comment by tbille** [comment]
It is at the moment mentioned in the tutorial https://ubuntu.com/tutorials/tutorial-create-a-usb-stick-on-ubuntu#2-requirements

Closing the issue.
