### ISSUE TITLE
/resources cache is empty too often

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#4418]
can we update the caching logic to always have something to show like on blog?

---
*Reported from: https://www.ubuntu.com/resources?*

**Comment by anasereijo** [comment]
@pmahnke still relevant or are we killing /resources?

**Comment by nottrobin** [comment]
I think @jpmartinspt could possibly apply his magic API calls fix here...

**Comment by tbille** [comment]
Resources doesn't exist anymore.
