### ISSUE TITLE
Consider providing the option to only use secure mirrors for downloads

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/ubuntu.com#4431]
Some of the mirrors which we use for serving downloads support HTTPS. We could check which ones support HTTPS at the point that we parse the mirrors list, and then provide an option to the user on the download page to only use HTTPS mirrors. Could this work?

**Comment by pmahnke** [comment]
@nottrobin can you flesh out a plan here?  should we check each mirror for https?  then work to make the selector offer two options?

I think we heavily rely on releases.u.c?

**Comment by nottrobin** [comment]
So, when this goes to k8s we will be pulling down the mirrors from Launchpad when we build the docker image for release. My suggestion is that we overload this script so that it tests each of the endpoints in [the mirrors list](https://launchpad.net/ubuntu/+archivemirrors), checks if HTTPS is supported, and if it is we included it in a "secure mirrors" list.

We could then provide something optional in the UI to only download from one of these HTTPS mirrors.

Under this new model, people asking for HTTPS would currently *always* be sent to a mirror (until releases.ubuntu.com starts supporting HTTPS) - although if we keep this setting optional, I imagine only a small percentage of people will use it. This would be problematic if, as things stand, we were relying heavily on releases.ubuntu.com, so let's interrogate that a bit:

At the moment, if we don't know where your IP is based - we can't find a location for you - then you will always the served the download from releases.ubuntu.com. Conversely, if we *do* know where you're based, you will *not* be sent to releases.ubuntu.com, unless your `country=GB`. Delving into Google Analytics for the URL `www.ubuntu.com/download/desktop/thank-you`, we can see that people either from the UK or with no country make up only about 3-4% of all downloaders.

This means that I don't think going with my suggested idea here would have a significant impact. We would be leaning slightly more heavily on the 50% or so of mirrors who do support HTTPS, but as long as we keep the HTTPS setting off by default, I think far less than 10% of downloaders will turn it on. And since the vast majority of downloads at present are downloading from mirrors, the change to releases.ubuntu.com will be minimal.

**Comment by tbille** [comment]
The work is done. See referenced PRs.
