### ISSUE TITLE
Modal forms should impose a minimum characters limit in the message field

### ISSUE THREAD

**Issue by caldav** [canonical-web-and-design/ubuntu.com#4722]
To prevent spam and unhelpful contact messages, new contact modal forms should impose a minimum characters limit in the message field. Looking at recent messages, we should only let forms through when they match at least: "[^\s]+\s[^\s]+\s[^\s]+" ("foo bar baz")

**Comment by nottrobin** [comment]
If spam is a problem - is there any kind of robot-busting on that form? Maybe we should add Google's invisible recaptcha? https://developers.google.com/recaptcha/docs/invisible

**Comment by pmahnke** [comment]
@nottrobin 	I have been trying to get this to work on the marketo side, would love to pair on that solution

**Comment by nottrobin** [comment]
@pmahnke have you seen "How can I prevent spam entries to my form?" over at https://nation.marketo.com/community/champion/blog/2017/10/30/common-form-faqs#comment-33628 ? It claims to explicitly provide instructions for Google's invisible recaptcha with Marketo.

**Comment by nottrobin** [comment]
@pmahnke did we actually fix this?
