### ISSUE TITLE
Links on Kubernetes installation landing page

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/ubuntu.com#4783]
## Summary

ISSUE forwarded from kubernetes-docs site:

@ktsakalozos says:

Searching for "ubuntu kubernetes install" gives me this page as the second hit: https://www.ubuntu.com/kubernetes/install . There we point people to https://conjure-up.io/. Should we instead point to https://www.ubuntu.com/kubernetes/docs/quickstart ?

**Comment by pmahnke** [comment]
@evilnick I have asked Carmine has he is currently reworking this page.

**Comment by carmine** [comment]
I've updated the page .. removing conjure-up.io .. and referring to kubernetes/docs.  I've used "manual" rather than quickstart (due to de-emphasis of conjure-up).

**Comment by pmahnke** [comment]
this looks completes/updated... closing
