### ISSUE TITLE
[iot] update the /download/iot/installation-media page to use etcher

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#4956]
[copy doc](https://docs.google.com/document/d/1GEJ-raGZDkcFeedEk_Ja_4DJYzqjeUa-GIHVDV7r7Vo/edit)

**Comment by solazio** [comment]
@pmahnke the copy doc is using Win32DiskImager. Can I update the copy doc as well to use etcher?
