### ISSUE TITLE
Managed services description duplicate

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-web-and-design/ubuntu.com#5095]
The [UASD](https://www.ubuntu.com/legal/ubuntu-advantage-service-description#uasd-managed-services) now includes managed services, however, the legal page still links to the old managed services description. 

---
*Reported from: https://www.ubuntu.com/legal/managed-services-description*

**Comment by sowasred2012** [comment]
Closing, as it looks like this was addressed by @pmahnke a little while ago, [that URL](https://www.ubuntu.com/legal/managed-services-description) now redirects to the UASD: https://github.com/canonical-web-and-design/ubuntu.com/commit/a46b8efa6a8650926667374ed89174db3855da21
