### ISSUE TITLE
Update Kubernetes Datasheet

### ISSUE THREAD

**Issue by Khutch25** [canonical-web-and-design/ubuntu.com#5108]
Opening an issue to have the [Kubernetes datasheet](https://github.com/canonical-web-and-design/www.ubuntu.com/files/3265649/DS_Kubernetes-for-the-Enterprise_screen-AW_31.05.19.pdf) updated on these pages once brand updates:

- /kubernetes page (linked in 'Upstream K8s options...' + 'AI/ML add-on...' sections)
- /kubernetes/managed (linked in hero + resources sections)

[Copy Doc](https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit#heading=h.xnpkx4ypduk)

Also want to make note of a small copy change that needs to be made - please remove "Canal" from the Discoverer table. (This has been noted in the copy doc)

---
*Reported from: https://www.ubuntu.com/kubernetes*

**Comment by SirSamTumless** [comment]
Waiting for the datasheet to be completed by Brand. Once shared I will add it here.

**Comment by Khutch25** [comment]
Update on these pages: 

https://www.ubuntu.com/kubernetes 
> 1) Section header: Upstream K8s options supported by Canonical > Anchor text: Charmed Kubernetes datasheet
> 2) Section header: AI/ML add-on for Discoverer and Discoverer Plus > Anchor text: Download the Enterprise Kubernetes datasheet

https://www.ubuntu.com/kubernetes/managed
> 1) Section header (hero): Fully managed private Kubernetes clusters. Cost effective. Pure upstream > Button text: Read the datasheet
> 2) Section header: Resources > Anchor text: Kubernetes for the enterprise

**Comment by SirSamTumless** [comment]
@Khutch25 Can you confirm this is done?

**Comment by SirSamTumless** [comment]
The new datasheet.
[DS_Kubernetes-for-the-Enterprise_screen-AW_31.05.19.pdf](https://github.com/canonical-web-and-design/www.ubuntu.com/files/3265649/DS_Kubernetes-for-the-Enterprise_screen-AW_31.05.19.pdf)

**Comment by SirSamTumless** [comment]
@Khutch25 has let me know that there are more changes to be made for the sheet.

**Comment by pmahnke** [comment]
@SirSamTumless did you see there is a PR that pushes it live? #5289

**Comment by SirSamTumless** [comment]
@pmahnke Ahhhhh ok. That's not an issue, just means we'll have to review it once we get the changes from @Khutch25
