### ISSUE TITLE
navigation.yaml hidden param hides entire secondary nav

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-web-and-design/ubuntu.com#5165]
According to [HACKING.md](https://github.com/canonical-web-and-design/www.ubuntu.com/blob/master/HACKING.md#navigation):
> If a child is "hidden", then it won't be displayed in the navigation menus, either in the top nav, the footer nav, or in the breadcrumb nav on other pages.

Adding "hidden" to a child/grandchild correctly removes the item from the footer nav, but it also hides the entire secondary nav. It should only hide that item, not the whole secondary nav.

**Comment by pmahnke** [comment]
@Caleb-Ellis where are you seeing this?

**Comment by anasereijo** [comment]
@Caleb-Ellis is this still relevant?

**Comment by Caleb-Ellis** [comment]
@pmahnke @anasereijo This issue came about when @sowasred2012 was building a new section on ubuntu.com (I think `/blog`?). Anyway, I believe he just wanted to hide a single secondary link, for example just `/blog/upcoming`, but adding "hidden" to the yaml hides the entire secondary nav. @sowasred2012 has this been a problem since?

**Comment by sowasred2012** [comment]
@Caleb-Ellis I worked around it by not setting the hidden attribute, and then manually checking in the template for a particular path and not showing it in the navigation if there's a match. Since then we've added a similar check for another path, so feels like this is worth looking at. I could pick it up?

**Comment by Caleb-Ellis** [comment]
The issue is valid at least but I'd put it at a pretty low priority. Just glancing at [context_processors.py](https://github.com/canonical-web-and-design/www.ubuntu.com/blob/master/webapp/context_processors.py) it seems like the behaviour might be intentional (hidden = appear alone) so maybe check with @nottrobin about changing that.

**Comment by sowasred2012** [comment]
closing - the mega nav work happening now will resolve this.
