### ISSUE TITLE
Recaptcha libs should only be loaded on pages where required

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/ubuntu.com#5229]
## Summary

Recaptcha JS library (97K) is currently being loaded on pages which will never use them, increasing page weight and page load times.

<img width="1028" alt="Screenshot 2019-05-30 at 16 39 45" src="https://user-images.githubusercontent.com/505570/58644646-97fe3e00-82f9-11e9-8f14-f87d0faa957c.png">

## Current and expected result

These libs should be loaded only if needed. On page load, JS could search for the existence of a `g-recaptcha` class and load the lib accordingly.

**Comment by pmahnke** [comment]
my understanding it that anypage you could just add #get-in-touch to the url and a modal contact form should magically appear

**Comment by barrymcgee** [comment]
Yep, I spoke with @anthonydillon about this and imo there's no reason these requirements should be mutually exclusive - we can load the contact form and then fire off the requests for Recaptcha. From a UX point of view however, it may make sense to add a loading icon to delay displaying the form until the Recaptcha has loaded?

**Comment by anthonydillon** [comment]
After some investigation we need to investigate or replace the recapture tool as its adding 2.83MBs to each page load. Which makes it the size of the site on average.

**Comment by barrymcgee** [comment]
Wowsers 😬

**Comment by pmahnke** [comment]
I think that @solazio has a PR that will have it load only when requested already.. perhaps that will fix it.
