### ISSUE TITLE
 500 server error page returns on site search 

### ISSUE THREAD

**Issue by WendyS1000** [canonical-web-and-design/ubuntu.com#5248]
I have only noticed this error page a few minutes ago. Search was working fine yesterday.  

---
*Reported from: https://www-ubuntu-com-canonical-web-and-design-pr-5214.run.demo.haus/*

**Comment by anthonydillon** [comment]
@WendyS1000 thanks for reporting this issue. What is the term you searched for?

**Comment by anthonydillon** [comment]
This is due to search not working on demos. Tested live and it's working.
