### ISSUE TITLE
Copy doc not correct on /download/server

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#5259]
should be https://docs.google.com/document/d/1FFQQUtzFGH88hA30qnZm-3pwVqcVl9UYyrNT4qQWrSM/edit

---
*Reported from: https://www.ubuntu.com/download/server*

**Comment by SirSamTumless** [comment]
@bartaz Is this something that you'd have to look into or something we can sort?

**Comment by bartaz** [comment]
@SirSamTumless Seems to be fine on staging. I believe it was fixed by #5335, probably not deployed to production yet.

**Comment by pmahnke** [comment]
it appears fixed (thanks @bartaz) so closing
