### ISSUE TITLE
/engage pages need to use the new metadata format

### ISSUE THREAD

**Issue by caldav** [canonical-web-and-design/ubuntu.com#5261]
Existing engage pages should be changed to use the new metadata format and have meta_images added.

The recommended image size is at least 1200x630, format: jpg or png.

Example:

```
{% extends "engage/base_engage.html" %}

{% block title %} North America&lsquo;s first autonomous runway snowplough{% endblock %}

{% block meta_description %}Northstar Robotics, a Canadian tech start-up founded in 2016, wants to address these challenges by developing autonomous vehicles and wanted to find out if an entire network of vehicles can be powered by a single intelligent control system.{% endblock %}
```
Becomes:

```
{% extends_with_args "engage/base_engage.html" with title="North America's first autonomous runway snowplough" meta_image="<image URL>" meta_description="Northstar Robotics, a Canadian tech start-up founded in 2016, wants to address these challenges by developing autonomous vehicles and wanted to find out if an entire network of vehicles can be powered by a single intelligent control system." %}
```

**Comment by WendyS1000** [comment]
Adding @SirSamTumless, so he can add this to the new brief process.

**Comment by anasereijo** [comment]
Creating these images should be part of the brief for takeovers from now on.
Do we need to create images for any of the ones already live?

**Comment by caldav** [comment]
@anasereijo we should probably look at the 5 to 10 most recent ones. (Your new GitHub avatar is confusing as hell :D)

**Comment by anasereijo** [comment]
@caldav I'm going to add that to our next iteration
(my avatar was very confusing indeed. I've been Totoed 🗡 )

**Comment by anasereijo** [comment]
@caldav can we close this?

**Comment by anthonydillon** [comment]
As the previous engage campaign have already run I think there will be less impact in improving them as sharing old content is less common then ones that are fresh. Therefore we should put the effort into adding social information on all future engage pages.

**Comment by WendyS1000** [comment]
I think it;s a good idea to create meta data images for the last 5 - 10 engage pages. This should be included all future engage pages (and also on product pages). It;s my experience that older content has as much sharing potential as new content. How much time will it take to create meta data images for the last 5 - 10 engage pages.

The happy flowchart looks like this: 
> User A shares content on Twitter (regardless of age . Hey, we're all young)
> User B, C, D, E and..XYZ click on the links to view our content
> They are all wow-impressed
> They contact us and buy product subscriptions
> We make money
> Happiness all around (..especially from munching on biltong and koeksisters. What is this? You'll find out in tomorrow's pow-wow).
