### ISSUE TITLE
Review entire /blog to make sure it matches blog.u.c

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#5262]

**Comment by sowasred2012** [comment]
# Blog QA checklist

_(this is a WIP, feel free to add items)_

- [ ] Index
  - [ ] Featured posts block
  - [ ] Newsletter signup
  - [ ] Filters
  - [ ] Excerpt on card to left of newsletter block (desktop only)
  - [ ] Pagination
  - [ ] Upcoming events block
  - [ ] Ensure nav is present, Overview is highlighted
- [ ] Topics
  - [ ] Ensure headers match
  - [ ] Ensure nav is present and that the hover dropdown works
  - [ ] On mobile, ensure topic links are visible in the navigation, and that the current topic is highlighted
- [ ] Article
  - [ ] Any article tagged with "snapcraft.io" should have a `rel="canonical"` link tag beginning with "snapcraft.io", and not "www.ubuntu.com" 
  - [ ] Product card above newsletter can differ, but should be consistent for each post on old blog and new
  - [ ] Sticky newsletter signup
  - [ ] og description and title should be present, along with image if the article has a featured image
- [ ] Tags
- [ ] Author
  - [ ] shouldn’t include a google plus link
- [ ] Archives
  - [ ] Ensure nav is present (nothing highlighted)
- [ ] Upcoming
  - [ ] Should look completely different, more like a blog index than an archive page
- [ ] Press centre
