### ISSUE TITLE
Missing external link icon on "Read the case study" button for ITstrategen's case study

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/ubuntu.com#5267]
Missing external link icon on "Read the case study" button for ITstrategen's case study on staging.ubuntu.com  

https://www.ubuntu.com/security

(Found by @lilyvidenova)

**Comment by pmahnke** [comment]
Closing as this is now linked to a local file - https://ubuntu.com/engage/ITstrategen-case-study
