### ISSUE TITLE
Should there be a "download" link icon?

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/ubuntu.com#5269]
> @lilyvidenova:
>
> I have a general comment (that does affect this page) - we use the same external link icon to mean both a link and a downloadable file, maybe we should introduce an icon that helps the user distinguish between the two?

**Comment by nottrobin** [comment]
Related to this. Gustavo commented that he didn't think the "external" icon was that helpful anyway, and that it interrupted the smooth reading the text.

**Comment by lilyvidenova** [comment]
I don't have a strong opinion about the external link icon, however do believe we need a "this link will start a download" icon.

**Comment by anasereijo** [comment]
@lilyvidenova do you remember on which page was that?

**Comment by lilyvidenova** [comment]
@anasereijo the specific example I was referring to is here https://ubuntu.com/security/certifications the STIG section the link suggests I'll go to a different page but instead, the download begins. However this isn't the only place this happens and I think it's a good thing to have in general.

**Comment by anasereijo** [comment]
That's a very good point. Thanks @lilyvidenova

@kwm14 I quickly checked Vanilla, but couldn't find a pattern for these type of links (download). Is there anything you're aware of we can use? If not we can think about creating a pattern for this.

thanks

**Comment by kwm14** [comment]
@anasereijo Unfortunately, we don't have a pattern for a download link, surely updating the content to include 'Download' would be the first step?

In @lilyvidenova referenced example the call-to-action is 'Read the STIG' with an external link, on the click it downloads the file...strange.

### Suggested solutions
- Update CTA and remove the external link
<img width="1439" alt="Screenshot 2019-06-14 at 10 14 40" src="https://user-images.githubusercontent.com/17748020/59498760-f3016a80-8e8d-11e9-9abb-18d3fda63d10.png">

- Update CTA and link to use button styling
<img width="1440" alt="Screenshot 2019-06-14 at 10 15 45" src="https://user-images.githubusercontent.com/17748020/59498761-f3016a80-8e8d-11e9-8c9e-cf25e067226d.png">

- Update CTA and use new button-with-icon in Vanilla 2.0 
<img width="1440" alt="Screenshot 2019-06-14 at 10 19 40" src="https://user-images.githubusercontent.com/17748020/59498762-f3016a80-8e8d-11e9-946a-97f4ba031c06.png">

**Comment by matthewpaulthomas** [comment]
I hadn’t seen this issue until today, but in code reviews I’ve been asking for the external-link icon to be removed from links that are direct downloads and therefore don’t take you to a different site.

> Unfortunately, we don't have a pattern for a download link, surely updating the content to include 'Download' would be the first step?

I’ve just done that while fixing the STIG link. For the long term, I think the question “should we use a download icon, or the word ‘Download’?” is equivalent to the question “can we produce a download icon that practically everyone understands?”

**Comment by nottrobin** [comment]
So @matthewpaulthomas is your suggestion that we don't have a "download" icon and instead make sure we say the word "download" in the link text?

In which case we should write that down somewhere. Practices I guess?

**Comment by matthewpaulthomas** [comment]
I’m suggesting that we could A/B-test a download icon (or two, or three) versus the word “Download”.

**Comment by pmahnke** [comment]
I prefere the word 'Download' as it is more accessible and SEO friendly anyway
