### ISSUE TITLE
Console error on /download/iot/kvm

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/ubuntu.com#5271]
![image](https://user-images.githubusercontent.com/519935/59042989-56c6da80-8873-11e9-9c24-cf43cfc8e840.png)

---
*Reported from: https://www.ubuntu.com/download/iot/kvm*

**Comment by nottrobin** [comment]
Also on https://www.ubuntu.com/download/iot/samsung-artik-5-10-server, probably others

**Comment by pmahnke** [comment]
Perhaps it is missing jquery.  we should check if any forms even ask for country anymore before fixeing

**Comment by pmahnke** [comment]
I think this is becuase there is no jquery and the marketo supplied state/provice script requires it

templates/whitepapers/shared/form.html
88:<script  src="//assets.ubuntu.com/v1/f97fa297-stateCountry.js"></script>

templates/whitepapers/beta/shared/form.html
88:<script  src="//assets.ubuntu.com/v1/f97fa297-stateCountry.js"></script>

templates/engage/shared/_en_engage_form.html
72:<script src="//assets.ubuntu.com/v1/f97fa297-stateCountry.js"></script>

templates/engage/shared/_fr_engage_form.html
59:<script src="{{ ASSET_SERVER_URL }}f97fa297-stateCountry.js"></script>

templates/engage/shared/_de_engage_form.html
64:<script src="{{ ASSET_SERVER_URL }}f97fa297-stateCountry.js"></script>

templates/engage/fr/openstack-made-easy.html
113:      <script src="{{ ASSET_SERVER_URL }}f97fa297-stateCountry.js"></script>

templates/rfp/index.html
115:    <script  src="//assets.ubuntu.com/v1/f97fa297-stateCountry.js"></script>

templates/download/shared/_get-ebook-security.html
78:  <script src="{{ ASSET_SERVER_URL }}f97fa297-stateCountry.js" defer async></script>

**Comment by pmahnke** [comment]
Fixed in #5275
