### ISSUE TITLE
WSL and MAAS aren’t clearly presented as server installation methods

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#5272]
The current structure of [the server download page](https://www.ubuntu.com/download/server) is:
1. LTS release [Download]
2. latest release [Download]
3. MAAS [link]
4. OpenStack [nothing]
5. Alternative architectures [links]
6. Help and documentation [links]

It’s weird that:
- Multipass isn’t mentioned
- WSL isn’t mentioned
- MAAS comes between the amd64 downloads and the other-architecture downloads.

In working on where to add Multipass, I experimented with a new page structure. This won’t be done for Multipass, but could be considered for the future.

![server-page-layout](https://user-images.githubusercontent.com/19801137/59042997-59c1cb00-8873-11e9-98ad-2859bf66e0f4.png)

The text and other elements shown in this structure are not meant to be exact. For example, the latest release (e.g. “Ubuntu Server 19.04”) could be a non-default button rather than a link to a secondary page.

[Reported by request of @pmahnke.]

---
*Reported from: https://www.ubuntu.com/download/server*

**Comment by anthonydillon** [comment]
Ana and Peter can you review and triage once agreed.

**Comment by matthewpaulthomas** [comment]
FWIW I don’t think this should be in Review/QA, because there’s no code to review, and it’s not even a final design.
