### ISSUE TITLE
/openstack/training contact CTA doesn't trigger modal

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#5276]
On https://www.ubuntu.com/openstack/training, the "Contact us to book yours" link on Ubuntu Server Administration > Basic on-site Ubuntu Server training section takes the user to a contact page, whereas every other "Contact us" link triggers a modal.

On inspection, it seems the anchor tag just needs a class of `js-invoke-modal` adding to it.

**Comment by pmahnke** [comment]
currently is shouldn't open modals as that page has a form for every course and the modals don't support that, in fact I htink the js-invoke-modal should be removed from some buttons!

**Comment by anasereijo** [comment]
@pmahnke does that mean we should close this issue?

**Comment by anthonydillon** [comment]
I believe the model now supports this. Let's plan it in as a small task soon.
