### ISSUE TITLE
/download/server doesn’t offer Multipass

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#5277]
[/download/server](https://www.ubuntu.com/download/server) does not suggest Multipass as an alternative to downloading server images yourself.

My design work for this explored restructuring the page, but that is now reported separately as #5272.

For now, the top of the page should follow the vertical card structure shown in [the copydoc](https://docs.google.com/document/d/1FFQQUtzFGH88hA30qnZm-3pwVqcVl9UYyrNT4qQWrSM/edit):
- LTS card, with checksum and verification link
- latest-release card, with checksum and verification link
- Multipass card, with large logo, and “Download for X” and “Learn more about Multipass” buttons — where X = your current platform, “Linux”, “macOS”, or “Windows”.

If any visual design is required, that should be done as part of this issue.

(Assigned at request of @pmahnke. The design was tracked in [multipass-design#43](https://github.com/CanonicalLtd/multipass-design/issues/43).)

---
*Reported from: https://www.ubuntu.com/download/server*

**Comment by anthonydillon** [comment]
This has been done, just awaiting v1 release: https://github.com/canonical-web-and-design/www.ubuntu.com/pull/5077

**Comment by matthewpaulthomas** [comment]
The text is changed to more closely match the language used on multipass.run.

**Comment by matthewpaulthomas** [comment]
This is still awaiting Multipass 1.0.

**Comment by xxl007** [comment]
The MP team and product management are now considering enabling this with the 0.9 release rather than with 1.0. To be confirmed shortly.

**Comment by spencerbygraves** [comment]
I've added the Multipass section. As an alternative, in the second version I've removed the cards in favour of separating lines.

**A**

![image](https://user-images.githubusercontent.com/9105999/70926740-88d8a680-2025-11ea-8c50-235bf867f5d3.png)

**B**

![image](https://user-images.githubusercontent.com/9105999/70926788-9d1ca380-2025-11ea-9800-712e85f6c7c6.png)

**Comment by matthewpaulthomas** [comment]
Thanks @spencerbygraves. I prefer option A, merely because it requires less scrolling to get to Multipass.

I think only the 18.04.3 LTS button should be green, the others should be neutral.

**Comment by anasereijo** [comment]
@spencerbygraves I prefer option B as it looks much cleaner. Maybe we can use the default Vanilla [`hr`](https://docs.vanillaframework.io/examples/base/hr/) which appears to have much less padding top and bottom saving some space.

**Comment by spencerbygraves** [comment]
We'll go for A, less scrolling as @matthewpaulthomas says. Thanks.

**Comment by SirSamTumless** [comment]
The only thing I can see is there is a missing closed bracket on the button )
