### ISSUE TITLE
/server/hyperscale - Form issue

### ISSUE THREAD

**Issue by waynecrosby** [canonical-web-and-design/ubuntu.com#5281]
There needs to be space added above the h3 title 'Here’s why Ubuntu is the best answer to the scale-out challenge:'

The contact form in the section 'Your roadmap for hyperscale success' which states 'Contact us about hyperscale ›' - when you go through and complete the form, it says "Thanks for enquiring about Ubuntu Advantage" not Hyperscale.
<img width="1122" alt="Screenshot 2019-06-07 at 11 39 50" src="https://user-images.githubusercontent.com/42238722/59098875-7fa1ab00-8919-11e9-9207-04dc6aadc4ad.png">

---
*Reported from: https://www.ubuntu.com/server/hyperscale*

**Comment by anasereijo** [comment]
Hi @waynecrosby, thanks for filling this issue. 
You described 2 issues here so I created a [separated one for the spacing issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/5309).

 @anthonydillon @solazio @sowasred2012 Regarding the form issue, can this be fixed?

**Comment by anthonydillon** [comment]
Yes it looks like we should use look to see if there is a more appropriate form. If not, we could make the thank you message customizable from the button.

**Comment by sowasred2012** [comment]
I believe this may be resolved, deliberately or not, as part of [this commit](https://github.com/canonical-web-and-design/ubuntu.com/commit/7c25d0c9573835d2e9de92b18a1f9655e9db702b#diff-a35be0c897297e9e8f6dd2b84836c878) - when I submit the form now, I'm taken to `/server/thank-you` (as opposed to a thank you screen within the modal) which has a more general "Thank you for contacting us about Ubuntu Server" message:

![Screenshot 2019-06-25 at 12 18 27](https://user-images.githubusercontent.com/2376968/60094227-5e2b2680-9743-11e9-89e7-416eb0f29946.png)

Would we prefer it to specifically mention hyperscale in the message?
