### ISSUE TITLE
"Support" does NOT mean "Sales"

### ISSUE THREAD

**Issue by boinkitsbroken** [canonical-web-and-design/ubuntu.com#5291]
Seriously, the last thing any user wants when they head to Ubuntu's web site in search of answers is a sales pitch.  So please, make sure the "chat with the Ubuntu Team" box is relocated elsewhere and re-labelled more appropriately.  That confusing, misleading chat scroller is going to frustrate everyone involved until you webmasters correct the mistake.  The thing needs to be under a site heading that means "Sales", not "Help".  You can also make it better by changing "Chat with Ubuntu Team" to something like "Chat with Ubuntu Sales" instead.  At least then the English-speaking world would know that the chat box contacts the Sales Team.

---
*Reported from: https://www.ubuntu.com/*

**Comment by anthonydillon** [comment]
Thank you for reporting this issue. We will discuss this with the marketing team and see if we can release some improvements here.

**Comment by pmahnke** [comment]
@boinkitsbroken we have spoken to the sales and marketing team and passed along your comments.  Closing this issue.
