### ISSUE TITLE
/server/hyperscale - add padding between 2 sections

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#5309]
'Here’s why Ubuntu is the best answer to the scale-out challenge:' looks too close to the text above it. Would look nicer (and more pleasant to read) with space added between both sections.

maybe using a`class="p-strip is-shallow"` will work?

---
*Reported from: https://ubuntu.com/server/hyperscale*

**Comment by lyubomir-popov** [comment]
@anasereijo @anthonydillon first let's identify the desired spacing. The easiest way to do that is to move the paragraph to be direct sibling of one of the p's. We get this:

![image](https://user-images.githubusercontent.com/2741678/59495274-e9283900-8e86-11e9-9a8f-21edff0a9b43.png)

which is 1.5rem added to the nudge value of .4rem, for a total padding of 2.1rem in addition to the default p margin bottom:
![image](https://user-images.githubusercontent.com/2741678/59495368-0bba5200-8e87-11e9-82ee-d7897ca0b9c9.png)

3 different ways to achieve this, my preference is the shallow strip:
![image](https://user-images.githubusercontent.com/2741678/59496465-648aea00-8e89-11e9-853c-adfd75580e3d.png)

**Comment by lyubomir-popov** [comment]
Thinking about it, maybe the empty p is the most straightforward thing to do. This triggers the exact rule the other two solutions are trying to emulate. In vanilla 2.0 the spacing between p+h3 is slightly less I think, so the shallow strip would be a bit off too. an empty element of the same kind would always result in the exact spacing.

Not semantic, but then we used to wrap buttons in p's :)
