### ISSUE TITLE
Create a meta meta_image (1200px x 675px) for Active Directory

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#5313]

**Comment by anasereijo** [comment]
@WendyS1000 here you go

![Integrate-How to integrate Ubuntu Desktop with Active Directory](https://user-images.githubusercontent.com/36884067/59517334-450cb500-8ebb-11e9-8489-b004be9b1acd.jpg)

**Comment by WendyS1000** [comment]
This looks great! Thank you. Approved
