### ISSUE TITLE
Add blog navigation in the footer 

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/ubuntu.com#5322]
Currently the user cannot access blog from the footer navigation.

![image.png](https://images.zenhubusercontent.com/5cb4608f97df763a9090bdec/b89bcf67-8844-496b-b6d9-13260f74e5b0)

**Comment by anasereijo** [comment]
how it should look like

<img width="1187" alt="Screenshot 2019-06-18 at 16 21 20" src="https://user-images.githubusercontent.com/36884067/59697806-6a186500-91e6-11e9-98eb-15acd3ea8687.png">

**Comment by anasereijo** [comment]
@solazio @sowasred2012 this is ready to be built

**Comment by solazio** [comment]
> @solazio @sowasred2012 this is ready to be built

On it
