### ISSUE TITLE
Update author page with paginated list of author's articles

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#5325]
Currently shows a list of the author's five most recent articles as text links, should show all of the author's articles as a list of paginated blog cards e.g. https://blog.ubuntu.com/author/canonical

**Comment by anasereijo** [comment]
Isn't this what @anthonydillon created yesterday?

**Comment by sowasred2012** [comment]
@anasereijo yes it is - the blog module needed an update for it so just wanted to make sure we were tracking this somewhere.
