### ISSUE TITLE
Mobile connectivity takeover + landing page misuse “in favour of”

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#5332]
1\. Go to [ubuntu.com](https://ubuntu.com/).
2\. If necessary, reload the page until you see “The future of mobile connectivity”.
3\. Follow the link to [the whitepaper page](https://ubuntu.com/engage/ubuntu-lime-telco?utm_source=Takeover&utm_medium=Takeover&utm_campaign=FY19_IOT_UbuntuCore_Whitepaper_LimeSDR).

What happens:
2, 3. Both pages have a subhed: “Are mobile operators ready to adopt open source in favour of proprietary technology?”

What’s wrong with this: It says the opposite of what’s intended.

The whitepaper page says: “Rather than rely on costly proprietary hardware and operating models, the use of open source technologies offers the ability to commoditise and democratise the wireless network infrastructure.” So, more open-source stuff, _less_ proprietary stuff.

But “in favour of” means “approving”, “to the benefit of”, or “to show preference for”. (References: [Collins](https://www.collinsdictionary.com/dictionary/english/in-favour-of), [Merriam-Webster](https://www.merriam-webster.com/dictionary/favor).) So “in favour of proprietary technology” would mean adopting _more_ proprietary technology.

What should happen: A simple fix would be to change “in favour of” to “rather than” or “instead of”.

---
*Reported from: https://ubuntu.com/*

**Comment by anasereijo** [comment]
thanks, @matthewpaulthomas for spotting this. 
@WendyS1000 can you please have a look into this? Thanks

**Comment by matthewpaulthomas** [comment]
This mistake has now been [copied by the Ubuntu Twitter account](https://twitter.com/ubuntu/status/1163864036397764609). So it should be fixed there too, especially if that tweet is scheduled for repetition like most others from that account.
