### ISSUE TITLE
Step 7 for Mac illegal numeric value

### ISSUE THREAD

**Issue by dbytyci** [canonical-web-and-design/ubuntu.com#5334]
sudo sh -c 'xzcat ~/Downloads/< image file > | sudo dd of=< drive address > bs=32M'
Didnt work with "32M" had to use "32m"

macOS High Sierra
10.13.6

---
*Reported from: https://ubuntu.com/download/iot/installation-media

**Comment by anthonydillon** [comment]
Please investigate and test.
