### ISSUE TITLE
Multipass not mentioned on server download “Thank you” page

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#5348]
Mark has requested that Multipass be mentioned on the Ubuntu Server download thankyou page.

The layout (designed in [multipass-design#41](https://github.com/CanonicalLtd/multipass-design/issues/41)) is a ribbon between the verification section and the e-book section:

![-download-server-thank-you](https://user-images.githubusercontent.com/19801137/59434037-aa40a780-8de2-11e9-8590-51de51d1db9a.png)

The text should vary depending on the browser’s reported OS: “**Downloading for a virtual machine?** Next time try [Multipass for {OS name}](https://multipass.run/), for a mini-cloud of automatically-updated Ubuntu VMs.” (If you’re not apparently browsing on Linux, Windows, or macOS, the link text can be simply “Multipass”.)

This also requires tweaking the e-book heading, to avoid the possibility that people will think the e-book is about Multipass rather than about Ubuntu Server: “**Starting with Ubuntu Server? You’ll want this eBook**”

This change could be made at the same time as more extensive changes to the page (#5316), or it could be done beforehand.

**Comment by anthonydillon** [comment]
This seems like a duo of #5353

**Comment by matthewpaulthomas** [comment]
They are both waiting for the 1.0 release.
