### ISSUE TITLE
[COPY UPDATE] index.html - "Ubuntu Advantage"

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#5364]
Please update index.html - "Ubuntu Advantage" from the [copy doc](https://docs.google.com/document/d/10tSvsCUMOcAXP6_QvdB3pr3iBV9G6GyVdM9eHqe032Q/edit?usp=drivesdk)

**Comment by pmahnke** [comment]
this was for buy.ubuntu.com and it was completed already...
