### ISSUE TITLE
On the new blog page it seems impossible to sign up for robotics news, when it is on the old one.blog.ubuntu.com

### ISSUE THREAD

**Issue by campbieil** [canonical-web-and-design/ubuntu.com#5367]
On the new blog page it seems impossible to sign up for robotics news, when it is on the old one.blog.ubuntu.com

---
*Reported from: https://ubuntu.com/blog*

**Comment by campbieil** [comment]
![image](https://user-images.githubusercontent.com/230348/59941459-24ad9f00-9455-11e9-96b5-1c4f193b9381.png)
vs 
![image](https://user-images.githubusercontent.com/230348/59941488-368f4200-9455-11e9-9e26-6ab19e91e1d1.png)

**Comment by anthonydillon** [comment]
Thanks for taking the time to file this issue. This will be scheduled in the coming iterations.

**Comment by pmahnke** [comment]
this was fixed in #5369 closing
