### ISSUE TITLE
Grammatical error on 500 error page

### ISSUE THREAD

**Issue by jdgregson** [canonical-web-and-design/ubuntu.com#5379]
The error page shown when a 500 internal server error is encountered says:

> Try reloading the page. If the error persists, please it may be a known issue. If not, please file a new issue.

I'm not sure what was meant to be here, but it seems that the first "please" should either be removed or replaced with "please note that".

**Comment by anthonydillon** [comment]
Thank you very much for taking the time to report this issue. You are right and we update the copy shortly. How did you see this page?

**Comment by jdgregson** [comment]
I encountered this when accessing a blog page as reported in issue #3578, but I see you've already triaged that one as well.
