### ISSUE TITLE
The top link to download Ubuntu Core for Rpi should link to the Core page

### ISSUE THREAD

**Issue by campbieil** [canonical-web-and-design/ubuntu.com#5403]
The link to download Ubuntu Core for Rapi should link to https://ubuntu.com/download/iot/raspberry-pi-2-3-core

---
*Reported from: https://ubuntu.com/core*

**Comment by pmahnke** [comment]
add an anchor to the ubuntu core strip on /download/iot and send people from /core (in the banner) to that anchor - 
![image](https://user-images.githubusercontent.com/441217/60577725-cd260200-9d77-11e9-8088-edc02ae9e620.png)
