### ISSUE TITLE
Design for training strip

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#5424]
![image](https://user-images.githubusercontent.com/441217/60652139-83a0ea00-9e3f-11e9-94db-6b4701982297.png)

Provide design suggestions for the training strip on /openstack and /kubernetes

**Comment by anasereijo** [comment]
@pmahnke we are waiting for new illustrations to go on Kubernetes bubble pages so I think we can leave this for now and pick it when we have the new assets. Is that ok to you?

**Comment by pmahnke** [comment]
yes, that's fine
