### ISSUE TITLE
Mysterious “Minimal Edition” reference on release cycle page

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#5452]
[The page “The Ubuntu lifecycle and release cadence”](https://ubuntu.com/about/release-cycle) says:
> Each release of Ubuntu will include a Minimal Edition which has the fewest possible packages installed, a Server Edition which has a standard set of out-of-the-box usability conveniences, and a Desktop Edition which has the default GUI experience pre-installed.

However, while [the Download page](https://ubuntu.com/download) mentions Ubuntu Server and Desktop (and Cloud, IoT, and flavours), it doesn’t mention Minimal Edition. Furthermore, [ubuntu.com’s search returns nothing for “Minimal Edition”](https://ubuntu.com/search?q=%22minimal+edition%22) besides the lifecycle page itself, one apparently-deleted Discourse post, and some years-old IRC logs.

I’m reporting this as a bug, rather than on the copydoc, because whatever this is referring to, probably other pages need changing too:

- If it refers to “[Minimal Ubuntu](https://wiki.ubuntu.com/Minimal)”, “a set of Ubuntu images designed for automated deployment at scale and made available across a range of cloud substrates”, then they should use a consistent name, and the release cycle page and Download page should link to that wiki page (or else that wiki page should move to ubuntu.com).

- If it refers to [the network installer](https://ubuntu.com/download/alternative-downloads#network-installer), which “includes the minimal set of packages needed to start”, then they should use a consistent name, and the release cycle page should link to that download page.

- If it refers to a future unreleased project, then either the reference should be removed (for better surprise or less disappointment), or it should be clarified as an announcement of a future release rather than something that already exists.

- If it refers to a project that used to exist but no longer does, the reference should be removed.

---
*Reported from: https://ubuntu.com/about/release-cycle*

**Comment by matthewpaulthomas** [comment]
I’ve mailed Steve Langasek to ask what this is referring to.

**Comment by nottrobin** [comment]
I'm sure this refers to what you call "Minimal Ubuntu" (option 1 of the 3 you present above), although it is also referred to as "Ubuntu Minimal" in other places - e.g. http://cloud-images.ubuntu.com/minimal/releases/bionic/release/ (linked from the very wiki page you link to).

I personally find the name "Ubuntu Minimal" quite familiar and know exactly what it's referring to, and prefer it as the standard name from "Minimal Ubuntu" which sounds clunky to me. It's the version of Ubuntu that's used in the default Ubuntu LXD and Docker images, and is therefore the basis for almost all application images and containers that are based off Ubuntu. It's very common.

I'm not sure the wording here necessarily needs changing at all - although I'm never against adding links. Maybe the wiki page needs changing instead?

**Comment by matthewpaulthomas** [comment]
Steve Langasek replied:
> Given the context, I believe this is referring to the minimal cloud images.
>
> I have not previously seen this called "Minimal Edition".

He CCed Stephan Fabel, who replied:
> Steve is correct in stating that there isn't an Ubuntu Minimal Edition. I
think taking a look at the /about section on our website is important but
we need to stay coordinated with Product Management on this one.
>
> This overlaps with another concern I have w.r.t the /kernel pages. I
brought this issue up with Peter.

Meanwhile:
> I personally find the name "Ubuntu Minimal" quite familiar and know exactly what it's referring to, and prefer it as the standard name from "Minimal Ubuntu" which sounds clunky to me … Maybe the wiki page needs changing instead?

I agree. However, now I notice that the wiki page used the terms “Ubuntu Minimal” and “Ubuntu Minimal Cloud” until July last year, when they were changed to “Minimal Ubuntu” … [by Mark](https://wiki.ubuntu.com/Minimal?action=diff&rev2=42&rev1=41).

**Comment by nottrobin** [comment]
> I agree. However, now I notice that the wiki page used the terms “Ubuntu Minimal” and “Ubuntu Minimal Cloud” until July last year, when they were changed to “Minimal Ubuntu” … by Mark.

I guess I can see the logic to that - if we refer to "Ubuntu {release-codename}" then "Ubuntu minimal" could be expected to be another release name. Whereas "Minimal Ubuntu" can then naturally become e.g. "Minimal Ubuntu Bionic" if needed.

But it still seems like we need official alignment on the proper name for it.

**Comment by matthewpaulthomas** [comment]
I think if “Minimal” goes before “Ubuntu”, while “Core”, “Desktop”, and “Server” go after, we’ll need something written down to help people remember which is which.

**Comment by pmahnke** [comment]
We have re-written the section, I am closing this.
