### ISSUE TITLE
404 - page not found

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#5458]
If you search for _broadsign_ on ubuntu.com and click the first search result it will open a 404 page.

<img width="776" alt="Screenshot 2019-07-15 at 15 10 22" src="https://user-images.githubusercontent.com/36884067/61222576-e5503680-a712-11e9-9517-37a0d91af051.png">

<img width="1075" alt="Screenshot 2019-07-15 at 15 10 29" src="https://user-images.githubusercontent.com/36884067/61222585-e7b29080-a712-11e9-8ec6-2795dcb13d76.png">

---
*Reported from: https://ubuntu.com/blog/tag/broadsign*

**Comment by pmahnke** [comment]
@MeltySnow 	recently removed this tag, perhaps it is just a short-term caching issue

![image](https://user-images.githubusercontent.com/441217/61223471-9c997d00-a714-11e9-94e0-66d08342aa44.png)

**Comment by anasereijo** [comment]
@pmahnke I still see the link when searching for Broadsign

**Comment by nottrobin** [comment]
Yeah, it can take Google a very long time to notice pages have gone. We can help it along by submitting URLs at https://www.google.com/webmasters/tools/url-removal?hl=en&siteUrl=https://ubuntu.com/. I've submitted this URL now, it usually takes a day or so to be processed. I'll close this now as I think this is the best we can do.
