### ISSUE TITLE
[Data sheet] Update the UA data sheet

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#5483]
Please update the UA Datasheet CTA link with the web version of the Ubuntu Advantage Infrastructure datasheet on https://ubuntu.com/support.

[Copy doc](https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit)

[DS_UA Datasheet-web_16.07.19.pdf](https://github.com/canonical-web-and-design/ubuntu.com/files/3407011/DS_UA.Datasheet-web_16.07.19.pdf)

**Comment by anasereijo** [comment]
@SirSamTumless should we move this to next iteration?
