### ISSUE TITLE
[Takeover] Create meta images and add them to the Yahoo JP and SBI JP pages

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#5570]
We need meta images created for Yahoo JP and SBI JP, then added to the pages.

**Yahoo**
Yahoo! JAPAN、Canonicalとプライベートクラウドの構築で協業

**SBI**
SBIグループがセキュアなオンプレミス型のOpenStackクラウドによりインフラ自動化を推進

**Comment by anasereijo** [comment]
@SirSamTumless is this the build card too?

**Comment by anasereijo** [comment]
yahoo: https://assets.ubuntu.com/v1/db188a00-Embedded+social+media+banner+yahoo.jpg

SBI: https://assets.ubuntu.com/v1/85d92436-Embedded+social+media+banner+-SBI.jpg

**Comment by anasereijo** [comment]
@solazio couldn't find a build card for this, so please use the images I saved here
