### ISSUE TITLE
Ubuntu Advantage contact form lists 13 things but not Ubuntu Advantage

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#5640]
1. Go to [the Ubuntu Advantage page](https://ubuntu.com/support).
2. Choose “contact us online”.
3. Click “Next”.
4. Click “Next”.

What happens:

2. A contact form appears asking “Where would you like to go faster?” (…What?) It has 13 checkboxes, none of which have any obvious connection with Ubuntu Advantage.
3. The form now asks “Should we bring a particular expert to the discussion?” There is still no mention of Ubuntu Advantage. (And Canonical’s experts all have bizarre names, such as “DevSecOps” and “NumPy”.)
4. The final step asks “I agree to receive information about Canonical’s products and services”, which, despite appearances, is an optional newsletter subscription form.

What should happen:

2. The form should be specific to Ubuntu Advantage.
3. The signup form in general should not refer to subject areas as if they are experts.
4. Regardless of the misleadingness of the newsletter signup in general, contacting Canonical sales should not invite you to subscribe to a newsletter, because if you happen to receive one before a salesperson gets back to you, you’ll be confused/annoyed that it’s not about your enquiry.

ubuntu.com does have a contact form that is specifically about Ubuntu Advantage, it just isn’t linked from this page: [ubuntu.com/support/contact-us?product=caramel-flavoured-unicorns](https://ubuntu.com/support/contact-us?product=caramel-flavoured-unicorns).

![contact-ua](https://user-images.githubusercontent.com/19801137/62422564-70867180-b6ac-11e9-9e9a-980757705275.png)

---
*Reported from: https://ubuntu.com/support*

**Comment by pmahnke** [comment]
This is currently working as requested. Closing
