### ISSUE TITLE
/kubernetes contact links all display the wrong form

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#5641]
1. Go to [ubuntu.com/kubernetes](https://ubuntu.com/kubernetes).
2. For each of the contact links:
   a. Click the link.
   b. Dismiss the form.
   c. Right-click the link and choose “Open in New Tab”/ “Open in New Window”.

What happens:

**Contact link**|**On click**|**On “Open in New…”**
-|-|-
“Get support for kubeadm ›”| ❌ “Get your kubernetes clusters running” | ✅ “Contact us about kubeadm”
“Get started with Kubernetes consulting packages” > “Get in touch” | ❌ “Get your kubernetes clusters running” | ❌ “Contact Canonical about Ubuntu Advantage”
“AI/ML add-on for Discoverer and Discoverer Plus” > “Get in touch” | ❌ “Get your kubernetes clusters running” | ❌ “Contact Canonical about Ubuntu Advantage”

What should happen:

**Contact link** | **On click** | **On “Open in New…”**
-|-|-
“Get support for kubeadm ›”| “Contact us about kubeadm” | “Contact us about kubeadm”
“Get started with Kubernetes consulting packages” > “Get in touch” | “Contact us about Kubernetes consulting” | “Contact us about Kubernetes consulting”
“AI/ML add-on for Discoverer and Discoverer Plus” > “Get in touch” | “Contact us about Kubernetes AI/ML” | “Contact us about Kubernetes AI/ML”

---
*Reported from: https://ubuntu.com/kubernetes*

**Comment by pmahnke** [comment]
The non-javascript fall back has slightly more contextual headers, that's all.  if marketing wants to add this to the modal forms, we will consider how to do it.  I don't see how this is an issue, closing.

**Comment by matthewpaulthomas** [comment]
I understand that it’s not trivial to make the modal and non-modal forms match because they’re currently separate chunks of code. And if it really was just non-Javascript fallback, rather than what you get when choosing “Open in New…”, it would be less important.

However there are several ways to tell that this is an issue, most important first:
- The Kubernetes consulting packages and the AI/ML add-on are [consulting packages](https://ubuntu.com/pricing/consulting), not Ubuntu Advantage packages, so “Contact Canonical about Ubuntu Advantage” is simply incorrect.
- The heading is (unfortunately) the only way in which the other `contact-us?product=` pages differ in contents, suggesting that their failure to do so here isn’t deliberate, just an oversight.
- Sure enough, [kubernetes/contact-us.html](https://github.com/canonical-web-and-design/ubuntu.com/blob/master/templates/kubernetes/contact-us.html) and [kubernetes/thank-you.html](https://github.com/canonical-web-and-design/ubuntu.com/blob/master/templates/kubernetes/thank-you.html) contain heading text that would make sense for these forms and nowhere else, it just isn’t being used.

So I just submitted a fix for part of this, #5659.
