### ISSUE TITLE
Update stacked forms to use grid

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#5650]
Per point 7 of https://ubuntu.com/blog/vanilla-framework-2-0-upgrade-guide

**Comment by kwm14** [comment]
@sowasred2012 thought I'd make you aware of a recent issue raised by @anasereijo regarding signup forms on [ubuntu.com](https://ubuntu.com/blog) 👍 

**Padding between checkboxes**
https://github.com/canonical-web-and-design/vanilla-framework/issues/2392

**Fix recommended by @lyubomir-popov** 
https://github.com/canonical-web-and-design/vanilla-framework/issues/2392#issuecomment-518601399
