### ISSUE TITLE
[Kernel] Build ubuntu.com/kernel

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#5683]
Build the five pages that were sketched in [Ubuntu-design#120](https://github.com/CanonicalLtd/Ubuntu-design/issues/120) and [Ubuntu-design#121](https://github.com/CanonicalLtd/Ubuntu-design/issues/121):

URL|Title + copydoc
-|-
ubuntu.com/kernel|[Ubuntu kernels from Canonical](https://docs.google.com/document/d/1XLdk2Slh4vi4AjGnatcK1BmJGmMNKIjN27KwbTwG5iI/edit)

I’ve proposed fixes for the worst, but not all, of the language issues in the source documents. Ideally each copydoc would be reviewed by someone doing pair-editing with a kernel engineer for accuracy.

This issue might need converting to an epic for building each page separately. If so, take care that the “Kernel” navigation ribbon is coherent at each step.

**Comment by steverydz** [comment]
@anasereijo demo link for /kernel https://ubuntu-com-canonical-web-and-design-pr-6534.run.demo.haus/kernel
