### ISSUE TITLE
[Kernel] Build ubuntu.com/kernel/variants

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#5685]
Build the five pages that were sketched in [Ubuntu-design#120](https://github.com/CanonicalLtd/Ubuntu-design/issues/120) and [Ubuntu-design#121](https://github.com/CanonicalLtd/Ubuntu-design/issues/121):

URL|Title + copydoc
-|-
ubuntu.com/kernel/variants|[Ubuntu kernel variants from Canonical](https://docs.google.com/document/d/1UVxrF8raNb5Pggj05P0ar_OzV_uwhrTRHv9XRiuM4zs/edit)

I’ve proposed fixes for the worst, but not all, of the language issues in the source documents. Ideally each copydoc would be reviewed by someone doing pair-editing with a kernel engineer for accuracy.

This issue might need converting to an epic for building each page separately. If so, take care that the “Kernel” navigation ribbon is coherent at each step.

**Comment by SirSamTumless** [comment]
The copy doc for this is now final, so this is good to go.
