### ISSUE TITLE
[Kernel] Create whtiepaper PDF from ubuntu.com/kernel/custom

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#5686]
Build the five pages that were sketched in [Ubuntu-design#120](https://github.com/CanonicalLtd/Ubuntu-design/issues/120) and [Ubuntu-design#121](https://github.com/CanonicalLtd/Ubuntu-design/issues/121):

URL|Title + copydoc
-|-
ubuntu.com/kernel/custom|[Custom Ubuntu kernels from Canonical](https://docs.google.com/document/d/1eO2fDbSYBOzvxmDabwoiO8Y2UPL-VIlQAkAXMN34tec/edit)

I’ve proposed fixes for the worst, but not all, of the language issues in the source documents. Ideally each copydoc would be reviewed by someone doing pair-editing with a kernel engineer for accuracy.

This issue might need converting to an epic for building each page separately. If so, take care that the “Kernel” navigation ribbon is coherent at each step.

**Comment by anasereijo** [comment]
@SirSamTumless why is this blocked?

**Comment by SirSamTumless** [comment]
The content hasn't be finalised by marketing.

**Comment by anasereijo** [comment]
@SirSamTumless do you want to move this to next iteration? not sure which Epic to put this in
