### ISSUE TITLE
rm <big file> not free memory in ubuntu 16.04

### ISSUE THREAD

**Issue by Beginerok** [canonical-web-and-design/ubuntu.com#5695]
---
*Reported from: https://ubuntu.com/*

**Comment by matthewpaulthomas** [comment]
Hi @Beginerok, this tracker is for issues with the ubuntu.com site.

To report issues with Ubuntu itself, go to [bugs.launchpad.net/ubuntu](https://bugs.launchpad.net/ubuntu) — but you will need to provide much more detail than you have here.

**Comment by Beginerok** [comment]
I'm sorry, but problem with gui delete big file from nautilus, and empty trash. Then file have path /.Trash-0/file . Why him delete incomplete? It's problem spend my time when I'm working. Do this problem "well done"!

**Comment by matthewpaulthomas** [comment]
Nautilus is not part of the ubuntu.com site. It is part of the Ubuntu operating system. To report issues with Ubuntu, go to [bugs.launchpad.net/ubuntu](https://bugs.launchpad.net/ubuntu).
