### ISSUE TITLE
Low-contrast text in press centre hero section

### ISSUE THREAD

**Issue by fitojb** [canonical-web-and-design/ubuntu.com#5714]
The text in the Press Centre’s hero section lacks any contrast to be readable.

![image](https://user-images.githubusercontent.com/554953/63817421-e4114c80-c901-11e9-8ffa-a8021a0df184.png)

A possible solution would be to make the text dark and set it inside a box, like in https://ubuntu.com/desktop/organisations: 

![image](https://user-images.githubusercontent.com/554953/63817469-1622ae80-c902-11e9-80f7-1995545f9c72.png)

**Comment by pmahnke** [comment]
@fitojb thanks for filing this, it is actually missing the card as you suggest.  We should get a fix out today.
