### ISSUE TITLE
Spelling mistake on the IoT gateways page. Under Container Friendly and Docker there is no letter 'D' at the beginning of Docker.

### ISSUE THREAD

**Issue by BenRichmond** [canonical-web-and-design/ubuntu.com#5721]
---
*Reported from: https://ubuntu.com/internet-of-things/gateways*

**Comment by pmahnke** [comment]
@BenRichmond thanks! we will get this fixed asap

![image](https://user-images.githubusercontent.com/441217/63944026-b2ff5c00-ca68-11e9-999b-69a58d109ca8.png)
