### ISSUE TITLE
'Include'  statement instead of a content

### ISSUE THREAD

**Issue by idobos71** [canonical-web-and-design/ubuntu.com#5743]
Hi,
on the top part of the page there is a "{% include "shared/pricing/_ua-for-infrastructure.html" %}" string instead of the content itself.
---
*Reported from: https://ubuntu.com/legal/ubuntu-advantage-service-description*

**Comment by pmahnke** [comment]
@idobos71 thanks for filing this, we just moved to flask and we will fix it soon.
