### ISSUE TITLE
placeholder is shown as {{ pricing_table | safe }}, but no table

### ISSUE THREAD

**Issue by nobuto-m** [canonical-web-and-design/ubuntu.com#5751]
Please refer to the screenshot below.

![Screenshot from 2019-09-04 11-59-03](https://user-images.githubusercontent.com/4356209/64222557-7bcaf800-cf0b-11e9-80e7-1546c4eb9a8d.png)
---
*Reported from: https://ubuntu.com/legal/ubuntu-advantage-service-description*

**Comment by nottrobin** [comment]
Thanks for filing this.

This was first reported in https://github.com/canonical-web-and-design/ubuntu.com/issues/5743, and has now been fixed in https://github.com/canonical-web-and-design/ubuntu.com/pull/5750.
