### ISSUE TITLE
Suggestion: Reduce visual noise for blog post dates

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#5753]
This is a minor issue, but…

The second major section on [the ubuntu.com front page](https://ubuntu.com/) is “Latest news from our blog”.

![image](https://user-images.githubusercontent.com/19801137/64238531-7dd68c00-cef6-11e9-850c-a6598212df4e.png)

The dates are visually noisy, because (a) they aren’t lined up with each other, (b) they’re `<em>`phasised when really they deserve _less_ emphasis than normal text, and (c) they needlessly repeat the year.

![news-dates](https://user-images.githubusercontent.com/19801137/64239180-ae6af580-cef7-11e9-851f-0a438fdee9ff.png)

Instead, the dates could be (a) above the headlines, (b) in small print, (c) without the year.

![image](https://user-images.githubusercontent.com/19801137/64240126-53d29900-cef9-11e9-9e5b-3b460bfa855b.png)

---
*Reported from: https://ubuntu.com/*

**Comment by anasereijo** [comment]
@matthewpaulthomas thanks for your suggestion! I totally agree, looks much cleaner and easier to read. We've been planning to update/improve this section for a long time, I will make sure this happens after Paris. 👍

**Comment by sowasred2012** [comment]
Closing, this has been addressed:
![Screenshot from 2021-11-03 16-13-17.png](https://images.zenhubusercontent.com/5cd93aaf2406d87914830598/5529f161-cda9-41e3-b930-75c17d18df34)
