### ISSUE TITLE
Reference to mobile - still relevant?

### ISSUE THREAD

**Issue by Ads20000** [canonical-web-and-design/ubuntu.com#5776]
Under 'An open source operating system' at the bottom of the page:

> so as a developer, carrier or manufacturer, you can work with us to start building Ubuntu mobile experiences now.

Is this still relevant?

---
*Reported from: https://ubuntu.com/desktop/features*

**Comment by pmahnke** [comment]
@Ads20000 thanks for this, turns out I updated that block forever ago in our copy docs, but it never got pushed up live.
