### ISSUE TITLE
MacOS gunzip command should exract to stdout

### ISSUE THREAD

**Issue by stephendotcarter** [canonical-web-and-design/ubuntu.com#5803]
Current command shows:
```
sudo sh -c 'gunzip ~/Downloads/< image file > | sudo dd of=< drive address > bs=32m'
```
But gunzip needs a `-c` to that the unzipped data gets piped to `dd`:
```
sudo sh -c 'gunzip -c ~/Downloads/< image file > | sudo dd of=< drive address > bs=32m'
```

---
*Reported from: https://ubuntu.com/download/iot/installation-media*

**Comment by anasereijo** [comment]
@pmahnke please estimate this

**Comment by pmahnke** [comment]
@stephendotcarter thanks for filing this... the fix is on it's way
