### ISSUE TITLE
“Featured articles” are irrelevant on /blog?category=anything

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#5828]
1\. In the global nav, choose “Products”.
2\. In the “Resources” section, choose “[Webinars](https://ubuntu.com/blog?category=webinars#posts-list)”, “[Videos](https://ubuntu.com/blog?category=videos#posts-list)”, “[Case studies](https://ubuntu.com/blog?category=case-studies#posts-list)”, or “[White papers](https://ubuntu.com/blog?category=white-papers#posts-list)”.

What you see: The resulting page does list articles _about_ webinars, videos, case studies, or white papers. Unfortunately this is almost unnoticeable, because the page is dominated by three “Featured articles” that do not fall into any of those categories.

![image](https://user-images.githubusercontent.com/19801137/65431478-7594b100-de11-11e9-89ea-14cb6a6fb1f4.png)

This block is appropriate on `/blog`, but not on `/blog?category=`anything.

What should happen:
- `/blog?category=`anything pages do not contain the “Featured articles” section (most likely), or
- the “Featured articles” section is _much_ less prominent (for example, it’s at the bottom of the page), to clarify that it’s not the main purpose of the page, or
- the “Products” menu does not contain any of these links (unlikely), or
- the “Products” menu does not exist at all (least likely).

---
*Reported from: https://ubuntu.com/blog?category=videos

**Comment by cristinadresch** [comment]
needs UX decision and design
