### ISSUE TITLE
PDFs sent through to UpWork

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#5834]
- Yahoo! Japan case study in English 
- Domotz case study
- SBI Japan case study in English
- Acuris (TIM) case study
- [Dell OpenStack Reference Architecture](https://docs.google.com/document/d/1h1cbM0MH4hQw_aHPcwrSbzixMBr5e8BVy4qqexA3bAs/edit#heading=h.u08tmofanpk1)

**Comment by pmahnke** [comment]
should we add these to the takeover template? https://docs.google.com/spreadsheets/d/1qPAMkl4idCvo9HHX-jECq_xh3ZHg2RbLV4MW8MvIL7U/edit#gid=0
