### ISSUE TITLE
[19.10 release] Create the homepage takeover and social images

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#5852]

**Comment by anasereijo** [comment]
### Takeover

- text is 7col
- [mascot](https://assets.ubuntu.com/v1/1869b4c2-Eoan+Ermine-orange-outline.svg) is 320px wide

![19 10 webinar takeover](https://user-images.githubusercontent.com/36884067/66746284-481fae00-ee79-11e9-85ab-e9d73bfa40b8.jpg)

### Landing page

![19 10 takeover- Landing page](https://user-images.githubusercontent.com/36884067/66746297-4d7cf880-ee79-11e9-9766-4aca372e402f.png)

### Social media

![Embedded social media banner](https://user-images.githubusercontent.com/36884067/66746308-55d53380-ee79-11e9-8f15-549f289cb8a5.jpg)
