### ISSUE TITLE
iot/digital-signage - suru heading looks blurred 

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#5855]
don't know what happened but I am sure this was looking good a few days ago.

the same thing is happening on https://ubuntu.com/desktop/statistics but not as bad

<img width="1440" alt="Screenshot 2019-09-26 at 17 02 17" src="https://user-images.githubusercontent.com/36884067/65705003-7fbbe700-e07f-11e9-8f69-8e9853421e62.png">

---
*Reported from: https://ubuntu.com/internet-of-things/digital-signage*

**Comment by pmahnke** [comment]
@anasereijo I assume this is the opposite of what I mentioned... Ant fixed/changed this strip that you couldn't see in my PR, but once live, it might have broke it.
