### ISSUE TITLE
Please consider responding on https://bugs.launchpad.net/snappy/+bug/1622342

### ISSUE THREAD

**Issue by zyga** [canonical-web-and-design/ubuntu.com#5858]
There's a bug reported on the snappy launchpad project that relates to the "use snappy in kvm" website. Please consider responding to https://bugs.launchpad.net/snappy/+bug/1622342

---
*Reported from: https://ubuntu.com/download/iot/kvm*

**Comment by pmahnke** [comment]
@zyga I responded, the command on launchpad isn't the same on ubuntu.com, so not sure what to do, I commented on LP.

**Comment by pmahnke** [comment]
closing as no response from @zyga
