### ISSUE TITLE
[New page] devices - "Ubuntu IoT and Devices - plans and pricing"

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#5865]
This is a new page request from Galem. It outlines the prices for the IOT and devices. There are some unresolved comments, but we have been told; _"Most of the open comments are requests for clarifications, or require information that we don't have yet. It is Mark who requested me to publish it."_

- [Copy doc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit?usp=drivesdk)
- [Trello Card](https://trello.com/c/nMOPV0GZ/419-devices-plan-and-pricing)

**Comment by anasereijo** [comment]
@SirSamTumless this was estimated as a 3 but I changed it to 5 as this ended up having design/ux time too. As this is not an Epic I can't create a separate issue for it.

**Comment by SirSamTumless** [comment]
Didn't @pmahnke say that this didn't need design time?

**Comment by anasereijo** [comment]
@SirSamTumless the copydoc wasn't prep for build. I had to go through it and amend headings and making suggestions

**Comment by SirSamTumless** [comment]
Aight, makes sense.
