### ISSUE TITLE
Kubernetes chart needs updated

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-web-and-design/ubuntu.com#5866]
The Kubernetes chart doesn't have 1.16. Also, I think CDK should be changed out for Charmed Kubernetes.

---
*Reported from: https://ubuntu.com/about/release-cycle*

**Comment by solazio** [comment]
@evilnick can you please help me with dates for Kubernetes 1.16 to add to the release chart.

**Comment by anasereijo** [comment]
@solazio is this still blocked?

**Comment by solazio** [comment]
@anasereijo yes, still blocked. Awaiting information from @evilnick
