### ISSUE TITLE
[Accelerating Deep Tech Webinar] - Build takeover and engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#5868]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1z7Dojp0ZXFgLFz9oPwNopvNPdMifTPRUoI-WtckGE84/edit?usp=sharing) and [design](1693):
 
- [x] build takeover
- [x] build engage page
- [x] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [x] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by SirSamTumless** [comment]
Alex is amended the copy of the engage page as it isn't correct at the moment.

**Comment by anasereijo** [comment]
design is ready https://github.com/canonical-web-and-design/web-squad/issues/1751
