### ISSUE TITLE
weird text on blog section HP

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#5872]
<img width="1146" alt="Screenshot 2019-10-01 at 14 05 35" src="https://user-images.githubusercontent.com/36884067/65964466-fdec0500-e454-11e9-87f6-24f66a076852.png">

---
*Reported from: https://ubuntu.com/*

**Comment by pmahnke** [comment]
@anasereijo do yo know what the characters are?  also, do you know you can fix these yourself?

**Comment by pmahnke** [comment]
@anasereijo let me show you tomorrow.

**Comment by anasereijo** [comment]
Ah I didn't know I could fix that. I thought you'd need to have access to
blog. Yes, please show me tomorrow! Thanks

**Comment by anthonydillon** [comment]
@pmahnke we should also escape special characters to solve this in the future.

**Comment by anasereijo** [comment]
I guess Ant fixed it so no learning tomorrow 😭

**Comment by pmahnke** [comment]
@anthonydillon will the slug be messed up? or does WP convert that to ascii?

**Comment by anthonydillon** [comment]
I only render the title text itself as HTML so not effecting the URL in the link.
