### ISSUE TITLE
Broken URLs

### ISSUE THREAD

**Issue by apg036** [canonical-web-and-design/ubuntu.com#5877]
When you hover the mouse cursor over the first row of the cloud providers (GCP, AWS, Azure) all three URLs are pointing to GCP

Expected: three different URLs as with the rest of the Cloud providers on the page.

Version 77.0.3865.90 (Official Build) (64-bit)
Windows 8.1

---
*Reported from: https://ubuntu.com/download/cloud*

**Comment by matthewpaulthomas** [comment]
Thanks for the report, @apg036. I’ve just submitted a fix for these cloud links.
