### ISSUE TITLE
Replace images containing base64

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#5892]
The assets that need to be replace:
**support**
- https://assets.ubuntu.com/v1/15e9c496-logo-bestbuy.svg

**download/server/thank-you**
- https://assets.ubuntu.com/v1/5e6b2dce-MAAS-ebook-web.svg

**openstack/managed**
- https://assets.ubuntu.com/v1/2e38f398-uct.svg

This one is used from a few pages and it is large:
https://assets.ubuntu.com/v1/4ba0e3a6-Joint+Lime-illustration-white.svg

**Comment by lyubomir-popov** [comment]
@anthonydillon the best-buy logo has changed in 2018, good news is the new version is 5kb
https://manager.assets.ubuntu.com/?q=performance-improvements

**Comment by anthonydillon** [comment]
@lyubomir-popov did you manage to find the other images? Let's close this once the images are updated.

**Comment by lyubomir-popov** [comment]
@anthonydillon The link above is a tag search containing all 4 images.
