### ISSUE TITLE
Search button wraps under input

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/ubuntu.com#5898]
**Describe the bug**
When searching on ubuntu blog the search button is wrapping under the search input on the results page.

**To Reproduce**
1. Go to https://ubuntu.com/blog
2. Click on Search
3. Enter your search 'Vanilla' for example
4. See that the search button wraps under the input

**Expected behavior**

**Screenshots**
<img width="1439" alt="Screenshot 2019-10-04 at 16 03 24" src="https://user-images.githubusercontent.com/17748020/66218287-c97c8100-e6c0-11e9-863f-beb436dfb0a6.png">

**Desktop:**
 - OS: iOS
 - Browser: Chrome 
 - Version: 77.0.3865.9

---
*Reported on https://ubuntu.com/search?q=vanilla*

**Comment by anthonydillon** [comment]
Thanks for reporting this issue. 👍
