### ISSUE TITLE
Broken markup with blog articles

### ISSUE THREAD

**Issue by nobuto-m** [canonical-web-and-design/ubuntu.com#5899]
Click an arbitrary blog articles in ubuntu.com/blog, then you see broken <head> markup and a plain text of a URL to a image.

For example, open https://ubuntu.com/blog/kubernetes-1-16-available-from-canonical, then refer to the screenshots below:

### HTML source
![Screenshot from 2019-10-06 23-55-34](https://user-images.githubusercontent.com/4356209/66271073-db168200-e894-11e9-8334-57e8036c5a99.png)

### Rendering
![Screenshot from 2019-10-06 23-52-53](https://user-images.githubusercontent.com/4356209/66271050-98ed4080-e894-11e9-940b-3e6b583f8b74.png)

---
*Reported from: https://ubuntu.com/blog/kubernetes-1-16-available-from-canonical*

**Comment by anthonydillon** [comment]
Thank you for reporting this issue @nobuto-m. Confirmed this is a high priority issue.

**Comment by nobuto-m** [comment]
Dup of #5904
