### ISSUE TITLE
Update design of /pricing index

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#5903]

**Comment by pmahnke** [comment]
@anasereijo I know we couldn't do it last iteration, but do you have time this iteration? or next?  I don't want to lose it to the icebox

**Comment by anasereijo** [comment]
> @anasereijo I know we couldn't do it last iteration, but do you have time this iteration? or next? I don't want to lose it to the icebox

Unfortunately, I don't think I have to finish that this iteration. I was hoping to get that done the next iteration. I will add this to the spreadsheet

**Comment by anasereijo** [comment]
### Proposed Design

![pricing](https://user-images.githubusercontent.com/36884067/69165390-6ff1d980-0ae9-11ea-9c92-480c86c7e555.jpg)

#### Grid for reference

<img width="732" alt="Screenshot 2019-11-19 at 16 31 23" src="https://user-images.githubusercontent.com/36884067/69165792-0c1be080-0aea-11ea-8be8-71fe4e25e966.png">

**Comment by anasereijo** [comment]
@pmahnke @solazio @anthonydillon this is ready to be built. There is no build card we can use this one as we estimated quite high on purpose.

**Comment by anasereijo** [comment]
@solazio if you have any questions while you're building this let me know
