### ISSUE TITLE
[Acuris case study] - Build engage page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#5927]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/17SMISc4VP9sCkED9cjK-La-ww8pW74teAFwT3CKQk1k/edit#gid=738287198) and [design](1815):
 
- [x] build engage page
- [x] add engage page to `/engage/index.html`
- [x] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by anasereijo** [comment]
@sowasred2012 this is ready https://github.com/canonical-web-and-design/web-squad/issues/1815
