### ISSUE TITLE
/esm promotes Ubuntu 12.04 ESM, but offer expired in April 2019

### ISSUE THREAD

**Issue by tomreyn** [canonical-web-and-design/ubuntu.com#5936]
https://ubuntu.com/esm still promotes Ubuntu 12.04 ESM, but 12.04 ESM [expired in April 2019](https://wiki.ubuntu.com/Releases#Extended_Security_Maintenance).

---
*Reported from: https://ubuntu.com/esm*

**Comment by Khutch25** [comment]
@cristinadresch We are still providing ESM for 12.04 to a few customers through April 2020, but agree that this should be removed from the /esm page, as we don't want to promote it (unless @matthewpaulthomas disagrees).

**Comment by tomreyn** [comment]
This appears to have been done between [Oct 18](http://web.archive.org/web/20191018193149/https://ubuntu.com/esm) and [Oct 25](http://web.archive.org/web/20191025194025/https://ubuntu.com/esm).

**Comment by matthewpaulthomas** [comment]
Yes, it was fixed in 3326a803b8e2140bd09b3871713abb3696be2ca2. Thanks @tomreyn.
