### ISSUE TITLE
[COPY UPDATE] canonical-openstack-consulting.pdf

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#5940]
Please update canonical-openstack-consulting.pdf from the [copy doc](https://docs.google.com/document/d/1J-oS4hqfh1EEV_odzMZQ_2MhsRZiEngDQ8kLpIZ6r1c/edit?usp=drivesdk)

**Comment by anasereijo** [comment]
@waynecrosby @marcushas

**Comment by SirSamTumless** [comment]
@waynecrosby @marcushas This needs to be done by Friday if at all possible.

**Comment by marcushas** [comment]
@SirSamTumless @waynecrosby @anasereijo  Hi can you confirm what this is, as 
we are not sure whether it's a WP or something else

**Comment by SirSamTumless** [comment]
@waynecrosby Could you add the file in this issue?

**Comment by waynecrosby** [comment]
[https://app.zenhub.com/files/23468646/ac209faa-7ce0-4fb9-806b-f1a637e9db84/download](https://app.zenhub.com/files/23468646/ac209faa-7ce0-4fb9-806b-f1a637e9db84/download)

**Comment by Khutch25** [comment]
@SirSamTumless Should this issue be used to update the datasheet on the website: https://ubuntu.com/openstack/consulting
