### ISSUE TITLE
[COPY UPDATE] training - "Training"

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#5942]
Please update training - "Training" from the [copy doc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit?usp=drivesdk)

**Comment by pmahnke** [comment]
@SirSamTumless are we waiting on the pdf?

**Comment by Khutch25** [comment]
@SirSamTumless @pmahnke What is the blocker here with the PDF? It doesn't need to be fully branded, just save the current file as a PDF.

**Comment by Khutch25** [comment]
Went ahead and made the OpenStack Operations Training and MAAS Deployment training course outlines PDFs in this folder https://drive.google.com/drive/folders/1HT_6RTfAa4cqxryCyJVqzIaQWYqiIgQg?usp=sharing

**Comment by pmahnke** [comment]
@SirSamTumless I am happy with @Khutch25's pdfs... is there anything else I don't know about?

**Comment by Khutch25** [comment]
IS THERE SOMETHING THEY'RE NOT TELLING US?! @SirSamTumless 

:P
