### ISSUE TITLE
Small regression in meganav p-p--small line-height

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/ubuntu.com#5947]
The line-height of `p-p--small` used to be 1.25rem, it is currently 1rem. 

Before:
![image](https://user-images.githubusercontent.com/2741678/66905809-75e22f80-effe-11e9-952c-f3e497212c69.png)

After:
![image](https://user-images.githubusercontent.com/2741678/66905784-6c58c780-effe-11e9-9f02-c2539cfecfa4.png)

**Comment by anasereijo** [comment]
@solazio @sowasred2012 maybe this is something you can quickly fix?

**Comment by sowasred2012** [comment]
@anasereijo I will take a look
