### ISSUE TITLE
[advantage dashboard] Simplify row expansion and add FIPS + EAL warnings

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#5953]
Implement the design from [Ubuntu-design#171](https://github.com/CanonicalLtd/Ubuntu-design/issues/171):

![fips-warning](https://user-images.githubusercontent.com/19801137/66715573-c702e100-edbc-11e9-88da-ab736b0a867f.png)

That is, in the `/advantage` subscription table:
- [x] Remove the shadow from the cell expansion (simplifying the overall appearance, and allowing a shadowed Vanilla caution inside it).
- [x] Make the expanded cell white, rather than dark grey, so that it is seamless with the expansion. (Unexpanded cells can still be dark grey on hover.)
- [x] In a FIPS cell expansion, start with a Vanilla caution: “Older versions of software are used for FIPS-certified packages. Use them only if your organisation requires it.”
- [x] Similarly in a CC-EAL cell expansion, start with a Vanilla caution: “Older versions of software are used for CC-EAL-certified packages. Use them only if your organisation requires it.”

**Comment by BryanQuigley** [comment]
For 14.04 launch, I think FIPS/CC should just say Coming Soon!  See https://docs.ubuntu.com/security-certs/en/ for current instructions.

**Comment by matthewpaulthomas** [comment]
@BryanQuigley If you think we should convey that FIPS and CC-EAL are not available for 14.04 LTS, perhaps report it as a separate issue? In yesterday’s meeting I offered to do that, but David didn’t think it was necessary for now. (FWIW I think making a subscription available initially for 14.04 LTS users, then saying “Coming soon!” for particular _features_, would imply that those features will ever be available for 14.04 LTS when they almost certainly won’t be.)

_This_ issue is that no matter which Ubuntu releases FIPS or CC-EAL are available for at any moment, if you use them you will have older software than if you didn’t use them. You’re gaining certification at the expense of features/performance/reliability. So they shouldn’t be turned on just from FOMO.

**Comment by BryanQuigley** [comment]
I agree it's more complicated based on what you said.. but was taking a different approach..  The command it shows today won't work on 16.04 until we launch the new ua client there. 

We have the *current* UA client on 16.04 and it requires you to use the instructions at https://docs.ubuntu.com/security-certs/en/

We could change the text to:
Not available using the new UA tool yet, please see https://docs.ubuntu.com/security-certs/en/ for supported systems and installation instructions.
