### ISSUE TITLE
/advantage wrongly implies need to enable ESM and Livepatch

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#5967]
From user feedback on `/advantage`:

> the only confusion point is that ESM/Livepatch come enabled by default, but the webpage gives you
instructions for activating each of those services. Their suggestion was that we note that these services are already enabled.

This could be fixed by adding an [information notification](https://docs.vanillaframework.io/patterns/notification/#information) in the expansion, above the instructions, and changing “activate” as the first instruction to “reactivate” as the second instruction:

> ESM is active by default on any newly-attached Ubuntu 14.04 LTS system.
>
> ----
> To deactivate: `sudo ua disable esm`
> To reactivate:  `sudo ua enable esm`

~~Similarly for Livepatch:~~ _Apparently Livepatch is not on by default._

> ~~Livepatch is active by default on any newly-attached system.~~
>
> ---
> ~~To deactivate: `sudo ua disable livepatch`~~
> ~~To reactivate:  `sudo ua enable livepatch`~~

**Comment by powersj** [comment]
I like the ESM change. It creates less confusion.

On Trusty, livepatch is not enabled by default. Would we keep that message as is then?

**Comment by matthewpaulthomas** [comment]
@powersj Thanks, fixed. I was going by the user feedback — any idea why they might have thought Livepatch was on by default?

We’d be less likely to err here if there was an API that reported, for each service, which releases it is (a) available for and (b) on by default for. That way the Web UI would update automatically when, for example:
- the new `ua` client was made available for another release
- Livepatch became available for another release
- a new LTS was released.

**Comment by anasereijo** [comment]
@solazio please estimate this once you're ready to work on it

**Comment by anasereijo** [comment]
@solazio @matthewpaulthomas is this happening?

**Comment by solazio** [comment]
@anasereijo I don't know what exactly we are supposed to do. Perhasp @anthonydillon and @matthewpaulthomas can help?

**Comment by anthonydillon** [comment]
I don't think there was an outcome. There are main difference situations which makes it a complex UX issue.

**Comment by powersj** [comment]
The original page had steps to enable ESM and livepatch called out. These have both been removed and now it shows how to attach and run status. For the purpose of the Trusty client this is sufficient and I do not think there is any remaining action.

**Comment by matthewpaulthomas** [comment]
Unfortunately I can’t see the current state because of #6081. But I guess @powersj is referring specifically to the free subscription section. My design above is specifically for the paid-subscriptions table.
