### ISSUE TITLE
Download button doesn't work

### ISSUE THREAD

**Issue by RSlava** [canonical-web-and-design/ubuntu.com#5984]
Hi!

After filling all fields and checking that I agree with terms, Download button won't start to download white paper.  Tried it on latest firefox and IE Edge.

---
*Reported from: https://ubuntu.com/blog/the-future-of-mobile-connectivity*

**Comment by pmahnke** [comment]
@RSlava thanks for filing this.

team, looks like recaptcha isn't working on this page?
