### ISSUE TITLE
Update/rebuild /internet-of-things/app-store page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#5994]
Per the [copy doc](https://docs.google.com/document/d/1Wj-aq6qPnNMjgMY3yyBeJRjbBVVCRBq6s00JkR6-d_A/edit#)

* we should ask @anasereijo if she wants to advise before we update or after
* we need to move this copy doc over the old one, perhaps just copy and paste the new over the old to keep the history
* ignor the form in the doc, use the existing modal

**Comment by SirSamTumless** [comment]
@anasereijo

**Comment by anasereijo** [comment]
@sowasred2012 @solazio please do not start this before having a design. I will start working on this today.

**Comment by anasereijo** [comment]
@sowasred2012 here goes the design

(fyi @pmahnke )

![appstore - half and half](https://user-images.githubusercontent.com/36884067/67565452-5f825500-f71d-11e9-871c-91c9dec3d3fb.jpg)

**Comment by anasereijo** [comment]
@sowasred2012 contact us image https://assets.ubuntu.com/v1/c4b290c8-Contact+us.svg
