### ISSUE TITLE
[Case study] Welcome Sanger - Build engage page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#6005]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1I6mV4Zj9JIeE38bAOKDthJnsBg336wFQF7NonNldG9E/edit#gid=0) and [design](https://github.com/canonical-web-and-design/web-squad/issues/1873):
 
- [x] add engage page to `/engage/index.html`
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by anasereijo** [comment]
@SirSamTumless why is this closed???

**Comment by SirSamTumless** [comment]
I thought it was a dupe. My bad.

**Comment by anasereijo** [comment]
Although the pdf is still in progress we can start building based on my designs

design https://github.com/canonical-web-and-design/web-squad/issues/1873

**Comment by SirSamTumless** [comment]
This PDF is good to go as per; https://docs.google.com/spreadsheets/d/1I6mV4Zj9JIeE38bAOKDthJnsBg336wFQF7NonNldG9E/edit#gid=877682240
