### ISSUE TITLE
19.10 download doesnt work

### ISSUE THREAD

**Issue by huzargarden** [canonical-web-and-design/ubuntu.com#6021]
The link in downloads doenst work for 19.10 

http://ftp.heanet.ie/pub/ubuntu-releases/19.10/ubuntu-19.10-desktop-amd64.iso
---
*Reported from: https://ubuntu.com/download*

**Comment by anthonydillon** [comment]
This has been reported and is with IS: https://rt.admin.canonical.com/Ticket/Display.html?id=122213

**Comment by anthonydillon** [comment]
Hi @huzargarden we have taken a look and could not find http://ftp.heanet.ie in the mirror list. Please reopren if you can replicate this issue.

**Comment by huzargarden** [comment]
Hi,

I have downloaded it already through the torrent file.

Cheers!
