### ISSUE TITLE
[Webinar] Kata containers] - Build takeover and engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#6041]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1UTIqPG9KSnnBr_r403jzCLD4JhcAmya_axqA2H60kds/edit#gid=1271849439) and [design](1873):
 
- [x] build takeover
- [x] build engage page
- [x] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [x] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by anasereijo** [comment]
@SirSamTumless can we push this live now? or do we need to wait for a specific date? fyi @sowasred2012

**Comment by SirSamTumless** [comment]
I think we're fine to push it live.
