### ISSUE TITLE
'CONTENTS' list on the UASD page is broken

### ISSUE THREAD

**Issue by MikeeC** [canonical-web-and-design/ubuntu.com#6048]
It seems the 'contents' list on the UASD page are broken - is it related to the work done here? - [bug 5993](https://github.com/canonical-web-and-design/ubuntu.com/issues/5993
)

None of the previous page sections are in the list and none of the links in the current list go anywhere.

---
*Reported from: https://ubuntu.com/legal/ubuntu-advantage-service-description

**Comment by pmahnke** [comment]
@MikeeC thanks ... you are correct, pulling in the wrong include.
