### ISSUE TITLE
typo/grammatical error

### ISSUE THREAD

**Issue by OMGdaDPS** [canonical-web-and-design/ubuntu.com#6060]
on the "data privacy" page, under "webinars"

"...third party provider may collects information...", 
should be: "...third party provider may collect information..."
---
*Reported from: https://ubuntu.com/legal/data-privacy*

**Comment by matthewpaulthomas** [comment]
Thanks @OMGdaDPS, I’ve submitted a fix for this paragraph.

**Comment by OMGdaDPS** [comment]
You're most welcome!

**Comment by OMGdaDPS** [comment]
I didn't want to be pushy, and perform a "pull request" (honestly don't know how really). Would that be something that I should do the next time I find something, or should I just do what I did? There are a few more things that I know about, but this was just a test to see what I was supposed to do, really.

**Comment by matthewpaulthomas** [comment]
@OMGdaDPS Yes, you’re very welcome to submit pull requests to fix typos! You can do it entirely on GitHub:

1. Find the [template](https://github.com/canonical-web-and-design/ubuntu.com/tree/master/templates) for the page/chunk that you want to change. (For example, [ubuntu.com/desktop/developers](https://ubuntu.com/desktop/developers) is in [templates/desktop/developers.html](https://github.com/canonical-web-and-design/ubuntu.com/blob/master/templates/desktop/developers.html).)

2. Click the “Edit this file” pencil icon.
  ![edit](https://user-images.githubusercontent.com/19801137/68213667-e5cb5080-ffd3-11e9-813c-885af8ae8535.png)

3. Make your corrections, and fill in the “Commit changes” form underneath explaining what you’ve done.

4. Fill in the pull request form on the next page.

The ubuntu.com developers will review any change before merging it into the site.
