### ISSUE TITLE
[advantage] definition of "free personal subscription" will disappear once logged in

### ISSUE THREAD

**Issue by nobuto-m** [canonical-web-and-design/ubuntu.com#6068]
Before logging into the page, https://ubuntu.com/advantage, the definition of "free personal subscription" is clear as follows:
```
Free for personal use

Anyone can use UA Infrastructure Essential for free on up to 3 machines 
(limitations apply). All you need is an Ubuntu One account. And if
you’re a recognised Ubuntu community member, it’s free on up to 50
machines.
```

However, the text block disappears once an user logged in. It would be nice to keep it even after logging in so the definition can be clear to everyone.

[Before logging in]
![Screenshot from 2019-11-05 23-05-04](https://user-images.githubusercontent.com/4356209/68214819-7f6d1f00-0021-11ea-98be-fb570e6d9c1e.png)

[After logging in]
![Screenshot from 2019-11-05 23-05-34](https://user-images.githubusercontent.com/4356209/68214830-85630000-0021-11ea-9f52-4b13434a115c.png)

---
*Reported from: https://ubuntu.com/advantage*

**Comment by anthonydillon** [comment]
@nobuto-m thank you for reporting this issue. I will assign this to UX.
