### ISSUE TITLE
500 for robotics tag

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6069]
Clicked on the robotics tag at the top of the blog post and got a 500 page

![Screenshot 2019-11-05 at 14 45 51](https://user-images.githubusercontent.com/36884067/68217764-15ca2200-ffdb-11e9-8f4d-a6f6ab0635d8.png)

---
*Reported from: https://ubuntu.com/blog/the-state-of-robotics-october-2019*

**Comment by anthonydillon** [comment]
That was a temp outage. It's working now.
