### ISSUE TITLE
Switch "Get Ubuntu" with "Register for webinar" on 19.10 takeover

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#6073]
![Screenshot 2019-11-06 at 11.59.58.png](https://images.zenhubusercontent.com/5cb4608c97df763a9090bdeb/182b371f-2644-4374-a8ec-48ec28da9b7e)

Alex has requested that the "Get Ubuntu" is switched with "Register for webinar".

**Comment by anasereijo** [comment]
@SirSamTumless by switching you mean the order or getting rid of "get ubuntu" and have a green button for the webinar?

**Comment by SirSamTumless** [comment]
Sorry for the confusion. Alex wants them reordered, so the "Register for webinar" appears first in a green box, then "Get Ubuntu" follows as a link.
