### ISSUE TITLE
[Private Cloud Build WBN] - Build takeover and engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#6092]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1dV2RFXNnpLnZBo_Gx_iuyv3qwhppGSyXE3_3dweLbQY/edit#gid=0) and [design](1955):
 
- [x] build takeover
- [x] build engage page
- [x] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [x] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by anasereijo** [comment]
ready for you https://github.com/canonical-web-and-design/web-squad/issues/1976
