### ISSUE TITLE
Download page redirects to non-existing mirror URL

### ISSUE THREAD

**Issue by DiogoConstantino** [canonical-web-and-design/ubuntu.com#6100]
When using the download page for Ubuntu, I'm being systematically redirected to non-existing mirror URL and getting HTTP 404. Which will likely block a lot of people from downloading Ubuntu.

---
*Reported from: https://ubuntu.com/*

**Comment by anthonydillon** [comment]
@DiogoConstantino thank you for taking the time to report this issue. Could you please let me know which mirror URL is 404ing and I will remove it from the list.

**Comment by pmahnke** [comment]
@DiogoConstantino we think this now fixed.  Thank for filing.
