### ISSUE TITLE
typo in ubuntu CoC v2

### ISSUE THREAD

**Issue by anonymouse64** [canonical-web-and-design/ubuntu.com#6115]
The section `Courage and considerateness` has this sentence:

```
Nevertheless, boldness demands considerateness; take bold decisions, but do so mindful of the challenges they present for others, and work to soften the impact of thos decisions on them
```

This has a typo `thos` -> `those`.

---
*Reported from: https://ubuntu.com/community/code-of-conduct*

**Comment by sowasred2012** [comment]
@anonymouse64 thanks for spotting and reporting this, it's now been fixed.

**Comment by anonymouse64** [comment]
Thanks folks
