### ISSUE TITLE
500: Server error when loading Ubuntu blog feed

### ISSUE THREAD

**Issue by MikkCZ** [canonical-web-and-design/ubuntu.com#6125]
STR:
1. Open Ubuntu blog feed https://ubuntu.com/blog/feed.
1. Get 500.
![obrazek](https://user-images.githubusercontent.com/3941344/68835541-97474180-06b8-11ea-95b4-636854dc04ee.png)

At this moment it block building of https://github.com/UbuntuCZ/ubuntu-cz/, as we fetch the RSS feed there to display on the main page. It started between 21:20 and 23:20 UTC yesterday (Nov 13).

**Comment by anasereijo** [comment]
@nottrobin please estimate this.

**Comment by MikkCZ** [comment]
Seems to work now again.

**Comment by nottrobin** [comment]
Thanks @MikkCZ, and thanks for closing it too. For the record, it was fixed in https://github.com/canonical-web-and-design/ubuntu.com/pull/6126.
