### ISSUE TITLE
Change "microstack.launch test" to "microstack.launch cirros" on website

### ISSUE THREAD

**Issue by matthewalanpenning** [canonical-web-and-design/ubuntu.com#6137]
Under step 5 (Launch an instance) of the section "How to install Kubernetes on Ubuntu Single node cluster" there is a command that reads "microstack.launch test". It should read "microstack.launch cirros".  This was the name of the only instance to launch when I installed the opentstack via the snap on the latest Ubuntu 18.04LTS server.

---
*Reported from: https://ubuntu.com/openstack/install*

**Comment by pmahnke** [comment]
@matthewalanpenning thanks for letting us know, I have asked an engineer on microstack to confirm what to update.

**Comment by pmahnke** [comment]
@matthewalanpenning I have a PR in to fix this, thanks for reporting it.
