### ISSUE TITLE
Update /telecommunications to reflect charmed-osm.com

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#6138]
[ubuntu.com/telecommunications](https://ubuntu.com/telecommunications) describes Charmed OpenStack, Charmed Kubernetes, and OSM, and links to [“the latest OSM bundle”](https://jaas.ai/osm).

Now that [Charmed OSM](https://charmed-osm.com/) exists and has its own site, the Telecommunications page probably should link to that. I don’t know enough about it to tell whether a description of Charmed OSM should replace just the “OSM” section, or all three sections.

[Originally raised while reviewing [web-squad#1951](https://github.com/canonical-web-and-design/web-squad/issues/1951).]

---
*Reported from: https://ubuntu.com/telecommunications*

**Comment by solazio** [comment]
@pmahnke do you know who would be best to advise on how we should deal with this?

**Comment by matthewpaulthomas** [comment]
Tytus Kurek is the product manager, he’d know.
