### ISSUE TITLE
/livepatch incorrectly points to https://ubuntu.com/advantage

### ISSUE THREAD

**Issue by tomreyn** [canonical-web-and-design/ubuntu.com#6145]
https://ubuntu.com/livepatch currently, amongst other, states this:

> Free for personal use
> 
> All you need is an Ubuntu One account. Free for 3 machines.
> 
> [Get Livepatch](https://ubuntu.com/advantage)

After reading this text and clicking the button, a random user will expect to find information on how to enable live kernel patching on any currently supported Ubuntu release.
Instead, what they currently find at /advantage is a statement that
> Initially, free subscription is available for Ubuntu 14.04 LTS only.

![ubuntu_advantage_1404only](https://user-images.githubusercontent.com/1328851/69074279-4ffddf80-0a2f-11ea-9387-164a2686814d.jpg)

The location where, today, someone wants who wants to enable live kernel patching, should be pointed to, seems to rather be https://auth.livepatch.canonical.com/ though.

---
*Reported from: https://ubuntu.com/livepatch*

**Comment by anthonydillon** [comment]
@tomreyn thank you for taking the time to report this issue to us.

@matthewpaulthomas could you colate the UA issues into a update to the page please.

**Comment by anthonydillon** [comment]
@tomreyn thank you for taking the time to report this issue to us.

@matthewpaulthomas could you colate the UA issues into a update to the page please.
