### ISSUE TITLE
/advantage invites people to use non-functional FIPS/CC-EAL

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#6154]
From @BryanQuigley in #5953:
> For 14.04 launch, I think FIPS/CC should just say Coming Soon! See https://docs.ubuntu.com/security-certs/en/ for current instructions.

And in #6136:
> FIPS and CC-EAL don't do anything today, we should not encourage anyone to run those commands

**Comment by anthonydillon** [comment]
![image.png](https://images.zenhubusercontent.com/55f93fbc4f7a08fbb7f4ee18/662a36e4-3268-49e0-891a-b3bbd49ff5f0)

**Comment by matthewpaulthomas** [comment]
@BryanQuigley As shown in Ant’s screenshot above, FIPS and CC-EAL say “N/A” and they aren’t clickable. So I don’t see how we’re encouraging anyone to run those commands.

**Comment by BryanQuigley** [comment]
That's not what I see with  my test account.  Screenshot taken today.

![UA-I-showingfips](https://user-images.githubusercontent.com/702754/69443527-6c399f00-0d03-11ea-991c-7099ae545bd5.png)

**Comment by matthewpaulthomas** [comment]
Oh, that’s weird … Even if we did intend it to be expandable at all, it shouldn’t be expandable for an Essential subscription. I wonder if @anthonydillon hasn’t seen this because his subscription isn’t an Essential one. (Lack of testability strikes again.)

**Comment by anthonydillon** [comment]
This can only be due to the API returning `resourceEntitlements` for FIPs and CC-EAL. @urosj @franban

**Comment by anthonydillon** [comment]
@BryanQuigley having a hard time replicating this with the subscriptions I have access too. Could it be you have a test subscription which entitles you to both FIPs and CC-EAL?

**Comment by BryanQuigley** [comment]
@anthonydillon To my knowledge, we have pretty much no "modern" subscriptions that do not include access to FIPS (CC-EAL was generally considered included in that too).  See https://buy.ubuntu.com.   This specific test account has 1 UA Server Essential.

Please let me know what subscriptions you have access to, it's possible all of them are not really representative.

**Comment by BryanQuigley** [comment]
This is still an  issue  with my Essential test account

**Comment by matthewpaulthomas** [comment]
I was confused above. Both [the UA page](https://ubuntu.com/advantage) and [the infra pricing page](https://ubuntu.com/pricing/infra) show that FIPS and CC-EAL2 _are_ available for all UA plans, including Essential.

The actual problem here was that they are _not_ available for Ubuntu 14.04 LTS, which — at the time — was the only version `ua` ran on.

However, `ua` is now shipped on 20.04 LTS as well, so we now need to distinguish the two.

Separately from that, adding columns for tech support (#7137), Landscape (#7718), and CIS benchmark (#6710) will cramp this table. So what I think I may do is combine FIPS, EAL2, and CIS into a “Certifications” column, with cells that expand to show version info and instructions for all three.

**Comment by matthewpaulthomas** [comment]
Proposed design:

![certifications](https://user-images.githubusercontent.com/19801137/85724978-9bc2e680-b6ec-11ea-8dc5-5516c10df254.png)

Links:
- “[FIPS setup instructions](https://docs.ubuntu.com/security-certs/en/fips)”
- “[EAL2 setup instructions](https://docs.ubuntu.com/security-certs/en/cc-16)”
- “[CIS setup instructions](https://docs.ubuntu.com/security-certs/en/cis-18-16.html)”

Once the `ua` client is available on 16.04 LTS or 18.04 LTS, but not both, we’d show both these links and the `ua` command.

Once the `ua` client is available on both 16.04 LTS _and_ 18.04 LTS, we’d return to showing just the `ua` command.

**Comment by matthewpaulthomas** [comment]
Reviewed and approved by @cassiocassio, with the proviso that this grouping suggests a more extensive restructuring is needed later).

**Comment by matthewpaulthomas** [comment]
[Specification updated](https://docs.google.com/document/d/1K65n3NpZCh7EWDXKLhG31seGJ2jKbW6lqw3BwV2mlnU/edit#heading=h.rvsupctzkbga).
