### ISSUE TITLE
/advantage doesn’t help distinguish multiple paid subscriptions

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#6155]
From @BryanQuigley in #6136:
> Needs some sort of thought flow when customer has more than one subscription, there is not remotely enough info there for them to decide which on they should attach.

**Comment by matthewpaulthomas** [comment]
@BryanQuigley As far as I know, we display all the info we have that distinguishes between multiple paid subscriptions:
- subscription name
- UA level (Essential/Standard/Advanced)
- number of machines attached.

Other things I can think of, that could help distinguish subscriptions, which we don’t have the ability to show at the moment:
- number of machines entitled (exists in the back end, but there’s no API for it)
- date that the subscription was created (since you’re more likely to want to work with a recent one)
- date that a machine was most recently attached/detached from that subscription (ditto).

Can you think of anything else that would be helpful? Thanks.

**Comment by matthewpaulthomas** [comment]
I guess most effective, but also most difficult, would be allowing custom names for subscriptions. (And prompting for a name whenever you bought any subscription other than your first.)

**Comment by BryanQuigley** [comment]
I think you've got most of them covered.  Others:
Who is the Technical Contact on the customer side (is in SF), would also make it a bit clearer.
Name of contract - if customized.

**Comment by matthewpaulthomas** [comment]
> As far as I know, we display all the info we have that distinguishes between multiple paid subscriptions

I’m glad to have been wrong about this. Turns out there’s plenty more we can show to help distinguish subscriptions. So here’s the plan:

- [ ] If someone has multiple UA accounts, we should show a separate table of subscriptions for each. In each table (even if there’s only one), the leftmost header cell (which currently says “NAME”) should instead display the UA account name.

- [ ] In every row, the subscription name cell should be expandable (like most of the other cells) to show a key-value table of extra info about that subscription:
  - [ ] “Created:” (just the date, not the time)
  - [ ] “Effective from:” (ditto)
  - [ ] “Technical contact:”

**Comment by anthonydillon** [comment]
@matthewpaulthomas I couldn't find the technical contact information. I have added the other areas.

**Comment by BryanQuigley** [comment]
date that subscription expires would be incredibly useful for customers as well.

It's not clear to be what "Effective date" is to me.  Was that the last time it was used?
