### ISSUE TITLE
[Automotive page] Build page + contact-us update

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#6174]
Build the new /automotive page from the [copy doc](https://docs.google.com/document/d/1PVliB92h4ZqexaZV9F5MIcX7aRG6yBAGH1hG7x8UZTw/edit)

- [x] Build the new [/automotive](https://docs.google.com/document/d/1PVliB92h4ZqexaZV9F5MIcX7aRG6yBAGH1hG7x8UZTw/edit#heading=h.c6wjbvvp8mcm) page
- [x] Add to the IoT navigation
- [x] Add to the [Enterprise dropdown](https://docs.google.com/document/d/1YBdQvLuqEpEQr_QqyycxMhZr4OaLapMlNJyYKCmPJsQ/edit) in IoT and Sectors

**Comment by anasereijo** [comment]
@steverydz the page is ready to be built https://github.com/canonical-web-and-design/web-squad/issues/2004
