### ISSUE TITLE
[SBI (English)] - Build engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#6175]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/u/1/d/158eh4AHxfgssQLu8pfCp0pKFZduwE4BpJ8y0-rfAs6k/edit?usp=sharing) and [design](1955):
 
- [x] build engage page
- [x] add engage page to `/engage/index.html`
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by anasereijo** [comment]
@steverydz @sowasred2012 this is ready to go. re-use the previous design

**Comment by steverydz** [comment]
This still needs the following provided to be completed:
[ ] meta description
[ ] meta image
[ ] form ID
[ ] form return URL i.e. the whitepaper

**Comment by anasereijo** [comment]
@SirSamTumless please see @steverydz's comment above.

**Comment by steverydz** [comment]
@SirSamTumless I've found the marketo form ID but the brief doesn't provide the following:
- [ ] meta description
- [ ] meta/social media image
- [ ] return URL once the form has been submitted

**Comment by SirSamTumless** [comment]
Return URL: https://pages.ubuntu.com/CStudy_SBI-TY.html

**Comment by SirSamTumless** [comment]
@anasereijo Are there meta images for this?

@steverydz For the meta description use: "SBI Group unlocks infrastructure automation with secure, on-premises OpenStack cloud"

**Comment by anasereijo** [comment]
@steverydz data image here https://assets.ubuntu.com/v1/41c9663c-Embedded+social+media+banner+.jpg
