### ISSUE TITLE
/wsl: Visual design

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#6184]
Visual design for [the ubuntu.com/wsl page](https://docs.google.com/document/d/18jhBViEdsAjabJdTdakN7JPi-taeHVOYyS_N1wCkwZQ/edit).

[Original design tracked in [Ubuntu-design#205](https://github.com/CanonicalLtd/Ubuntu-design/issues/205).]

**Comment by anasereijo** [comment]
there is no visual design from me - I've made a few comments on the [copydoc](https://docs.google.com/document/d/1M7e2B08GgPA7K6Wx0ThE6s9_xQINM0MSkarfdKUTEYI/edit)
