### ISSUE TITLE
/wsl: Build

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#6185]
Build ubuntu.com/wsl, as written in [Ubuntu-design#205](https://github.com/CanonicalLtd/Ubuntu-design/issues/205) and visually designed in #6184.

**Comment by anasereijo** [comment]
Dev: there is no jpg with my design. I've left comments in the [copydoc](https://docs.google.com/document/d/1M7e2B08GgPA7K6Wx0ThE6s9_xQINM0MSkarfdKUTEYI/edit#). Please make sure you resolve all my comments after it's done.

**Comment by sowasred2012** [comment]
@waynecrosby could I get a fancy version of the WSL hero strip image pls? [copy doc](https://docs.google.com/document/d/1M7e2B08GgPA7K6Wx0ThE6s9_xQINM0MSkarfdKUTEYI/edit#)

![Screenshot 2020-03-10 at 11 45 49](https://user-images.githubusercontent.com/2376968/76309465-b9e31300-62c4-11ea-94a8-db1496466054.png)

**Comment by waynecrosby** [comment]
@sowasred2012 Not sure how fancy but here is an image for you to use:

https://assets.ubuntu.com/v1/f06b3499-ubuntu+windows.svg
