### ISSUE TITLE
[Tutorials] Apply homepage design

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#6206]

**Comment by anasereijo** [comment]
@steverydz this is ready for you designs here https://zpl.io/anQJdBr

**Comment by steverydz** [comment]
Done in https://github.com/canonical-web-and-design/ubuntu.com/pull/6284

**Comment by steverydz** [comment]
@anasereijo can you give this a design review? https://ubuntu-com-canonical-web-and-design-pr-6284.run.demo.haus/tutorials

**Comment by steverydz** [comment]
@anasereijo can you give this a design review? https://ubuntu-com-canonical-web-and-design-pr-6284.run.demo.haus/tutorials/tutorial-install-ubuntu-desktop#overview
