### ISSUE TITLE
/download/server/provisioning unlinked and redundant with maas.io/install

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#6229]
[“Get Metal as a Service”](https://ubuntu.com/download/server/provisioning) (which was reviewed in #2995) describes MAAS and how to “Install MAAS in 7 easy steps”. It then links to the manual for MAAS 2.3 (the current version is 2.6).

Meanwhile, [maas.io](https://maas.io/) has an “Install MAAS” button, which takes you to instructions to “Install MAAS in 7 easy steps” — the same instructions, just with different screenshots — and links to the manual for MAAS 2.6.

On [the “Download Ubuntu Server” page](https://ubuntu.com/download/server), the ribbon navigation links only to “Get Metal as a Service”, but the page body “Server provisioning with MAAS” section links only to maas.io.

All this suggests that the “Get Metal as a Service” page has been forgotten. (Perhaps it predates maas.io?)

If the page is still appropriate, the “Server provisioning with MAAS” section should link to it. If it is not still appropriate, it the `/download/server/provisioning` URL should instead redirect to maas.io, and the navigation ribbon link should be marked as an external link.

---
*Reported from: https://ubuntu.com/download/server*

**Comment by lilyvidenova** [comment]
@edu-ap FYI

**Comment by tbille** [comment]
@lilyvidenova @amylily1011 could we get an update about this page.

**Comment by amylily1011** [comment]
@tbille the external link on https://ubuntu.com/download/server/provisioning routes to maas.io/install atm. So I think it is fixed....?

**Comment by lilyvidenova** [comment]
Yes, this is done, thanks @tbille
