### ISSUE TITLE
[[Case study] Cyberdyne] - Build engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#6238]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1NFagqfLZ0WSc5GrTrdD2zakLhOuQzwGtlZwBIInRlqc/edit#gid=0) and [design](1955):
 
- [ ] build engage page
- [ ] add engage page to `/engage/index.html`
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by anasereijo** [comment]
@sowasred2012 this is ready https://github.com/canonical-web-and-design/web-squad/issues/2159
