### ISSUE TITLE
[[Whitepaper] Linux Enterprise] - Build takeover and engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#6239]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1NLbSg_HAaLEknFNk30CJ2kwqxjaL7iUuw-fZQW3YGfM/edit) and [design](1955):
 
- [x] build takeover
- [x] build engage page
- [x] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [x] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by anasereijo** [comment]
@sowasred2012 this is ready for you https://app.zenhub.com/workspaces/web-ubuntu--brand-squad-5931746dba512f05402b61f6/issues/canonical-web-and-design/web-squad/2162
