### ISSUE TITLE
[/networking] Design the new page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#6253]
https://docs.google.com/document/d/1EWlkTkGvul-ek4P1cR9pyNvyJsh5WtpOkChvk0igzVQ/edit#

**Comment by anasereijo** [comment]
![Networking](https://user-images.githubusercontent.com/36884067/70808993-d1d7f300-1db8-11ea-914f-f96a6dcaa5d5.jpg)
