### ISSUE TITLE
rasfibo

### ISSUE THREAD

**Issue by rasfibo** [canonical-web-and-design/ubuntu.com#6267]
This is a serious problem. Try again later. If this problem appears again, please report an error to the developers.
E:The package unifi needs to be reinstalled, but I can't find an archive for it.
i get above errors when i tried to install unifi controller by adding the repository and run update on Ubuntu Desktop 18.04LTS

---
*Reported from: https://ubuntu.com/*

**Comment by steverydz** [comment]
Hi @rasfibo. This repo is only for the ubuntu.com website. If you have a bug with Ubuntu itself you can [file a bug report here](https://bugs.launchpad.net/ubuntu/).
