### ISSUE TITLE
Title typo

### ISSUE THREAD

**Issue by m-svo** [canonical-web-and-design/ubuntu.com#6273]
After downloading LXD whitepaper, title says:
`<title>LXD Wbitepaper</title>`

---
*Reported from: https://pages.ubuntu.com/LXD_Whitepaper_TY.html*

**Comment by matthewpaulthomas** [comment]
Thanks for spotting this, @m-svo. Apparently this typo is not in the ubuntu.com code, it is in a database, so I am tracking down someone who has access to fix it in the database.

**Comment by matthewpaulthomas** [comment]
This is fixed now.
