### ISSUE TITLE
Install guides for ubuntu desktop difficult to find

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/ubuntu.com#6274]
There doesn't appear to be links to any instal guides easily accessible when downloading the Ubuntu Desktop image. 

"How to install" links should be more prominent at the top of the thank-you page.

**Comment by tbille** [comment]
![image.png](https://images.zenhubusercontent.com/583afafbb9dc3c6220228d0c/1e3c5387-6b39-4110-b05d-960f482f19fb)

We now link: Help on installing it.
