### ISSUE TITLE
Developer desktop survey: Visual design

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#6277]
Visual design for [the developer desktop survey results page](https://docs.google.com/document/d/1iiNRqvpzhv2XrFayKfXVgEtIcIFbWjSCzDqRaM6IRK0/edit#heading=h.alljj5b20yp4).

One point, which Martin has asked for the visual design to consider, is whether the section menu would look better on the right rather than the left.

**Comment by anasereijo** [comment]
@SirSamTumless we should have an epic for this I think

**Comment by anasereijo** [comment]
@SirSamTumless is this planned for any time soon? If not we should put it in our backlog ?

**Comment by SirSamTumless** [comment]
I moved it to next next iteration, so should be fine.
