### ISSUE TITLE
/blog - fix middot on the pagination

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6286]
I think this will be solved if we update to the latest Vanilla.

<img width="453" alt="Screenshot 2019-12-17 at 10 54 31" src="https://user-images.githubusercontent.com/36884067/70989655-e3bcdd00-20bb-11ea-8f96-9a54c66affcd.png">

---
*Reported from: https://ubuntu.com/blog*

**Comment by fitojb** [comment]
This should use the Pagination component of Vanilla.
