### ISSUE TITLE
Use HTTPS on releases.ubuntu.com and cdimage.ubuntu.com

### ISSUE THREAD

**Issue by Sanyy** [canonical-web-and-design/ubuntu.com#6309]
Let's encrypt supports wildcard certificates already.
Why do we have to download something over plain http?

---
*Reported from: http://cdimage.ubuntu.com*
*Reported from: http://releases.ubuntu.com*

**Comment by nottrobin** [comment]
This question has a very long history. I'll try to find the last place I responded to it to give you more context.

In any case, though, this repository is just for ubuntu.com itself. You're likely to have more luck asking the question over on [the cdimage repo](https://code.launchpad.net/ubuntu-cdimage).

**Comment by nottrobin** [comment]
@Sanyy the most thorough exploration of this topic is probably [in this issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/4394#issuecomment-441317879). That prompted us to [improve the way we offer checksums](https://github.com/canonical-web-and-design/ubuntu.com/issues/4723) on the download thank-you pages.
