### ISSUE TITLE
[[Whitepaper] 451 MicroK8s] - Build takeover and engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#6316]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1UFVnl9Cr2FwlyMJeqfu2VGWCediSNqOHKbL9WjNcCmo/edit#gid=0) and [design](1955):
 
- [ ] build takeover
- [ ] build engage page
- [ ] add takeover to `/takeovers/index.html`
- [ ] add takeover to `/index.html`
- [ ] add engage page to `/engage/index.html`
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by anasereijo** [comment]
@sowasred2012 ready https://github.com/canonical-web-and-design/web-squad/issues/2189
