### ISSUE TITLE
[Security notices] build search results view

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#6323]
[UX document](https://docs.google.com/document/d/183fLUXOLL17_baS617aX7Sj133n4lLfS6-rLhXXv9I0/edit#)

build search results variant of main page (/security/notices?release=foo&package=bar&details=hum)

**Comment by anasereijo** [comment]
@sowasred2012 this is ready https://github.com/canonical-web-and-design/web-squad/issues/2217
