### ISSUE TITLE
[Security notices] build individual notice page

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#6324]
[UX document](https://docs.google.com/document/d/183fLUXOLL17_baS617aX7Sj133n4lLfS6-rLhXXv9I0/edit#)

build /security/notices/{id}

**Comment by anasereijo** [comment]
@sowasred2012 this is ready to be built. let me know if you want to catch up

https://github.com/canonical-web-and-design/web-squad/issues/2192
