### ISSUE TITLE
Page outdated

### ISSUE THREAD

**Issue by camille-rodriguez** [canonical-web-and-design/ubuntu.com#6327]
Hi, 

This page is outdated and is misleading our customers. The proper way to install kubeflow no longer uses kfctl. The k8s team either suggests to use the bundle-kubeflow from their github repo or the microk8s.enable kubeflow command for microk8s. It would be useful to sync with the k8s team to update this page. Thank you.

---
*Reported from: https://ubuntu.com/kubeflow/install*

**Comment by anthonydillon** [comment]
@evilnick could you take a look an recommend a change please

**Comment by evilnick** [comment]
@anthonydillon I will make a PR for this after conferring with Ken
