### ISSUE TITLE
Add tutorial back link

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/ubuntu.com#6361]
From https://github.com/canonical-web-and-design/ubuntu.com/pull/6284#issuecomment-573069777

> small screens: there is now link to go back to tutorials homepage in the nav. Can you try to add Tutorials in the secondary nav just before the tutorials tile?

https://user-images.githubusercontent.com/36884067/72162383-ce388b80-33b9-11ea-9c7a-c770f51cb573.png

**Comment by steverydz** [comment]
@anasereijo can you do a quick mockup of this? I'm not sure what you mean.

**Comment by anasereijo** [comment]
As discussed this is an issue we have across all ubuntu.com, therefore, let's leave it as it is for now until we find a better solution for u.c navigation
