### ISSUE TITLE
[Whitepaper] Anbox Cloud with Intel] - Build takeover and engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#6375]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1tlACaoregRa06_55lnQ-OPcMbCktK2n0YABQLT0RBRk/edit#gid=1149709150) and [design](1955):
 
- [x] build takeover
- [x] build engage page
- [x] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [ ] add engage page to `/engage/index.html`
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by SirSamTumless** [comment]
Note; Waiting for brief to be finalised by Alex.

**Comment by anasereijo** [comment]
@deadlight @steverydz this is ready for one of you :) https://github.com/canonical-web-and-design/web-squad/issues/2216

**Comment by SirSamTumless** [comment]
Please make sure to use "www.ubuntu.com/engage/anbox-cloud-gaming-whitepaper" as the final URL.
