### ISSUE TITLE
Merchandise link doesn't work

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-web-and-design/ubuntu.com#6379]
On ubuntu.com clicking the 'Products' dropdown and then 'Merchandise' results in a "This site can’t be reached"

---
*Reported from: https://ubuntu.com/*

**Comment by pmahnke** [comment]
Issue moved to [canonical-web-and-design/global-nav #137](https://github.com/canonical-web-and-design/global-nav/issues/137) via [**ZenHub**](https://www.zenhub.com/)
