### ISSUE TITLE
search field is missing

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6399]
how it should look like

![Screenshot 2020-01-15 at 16.56.31.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/638bd0c3-89b3-4cbd-bf8b-2b92001c24d5)

how it looks like

![Screenshot 2020-01-15 at 16.57.25.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/b7491edb-90de-436c-b26a-bd2ec96930e3)

**Comment by steverydz** [comment]
@anasereijo currently we don't have a search. I think that will come in a later iteration @tbille?

**Comment by anthonydillon** [comment]
In checking the search on the main site. The results are actually very accurate. For example, https://ubuntu.com/search?q=Burn+dvd. So happy to consider this complete for now.
