### ISSUE TITLE
fixes on "sorted by" dropdown

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6400]
Let's follow what @matthewpaulthomas [proposed](https://docs.google.com/document/d/1KwkyPUASE3EyYQlHM6iPN_AWBIAkKkNuz53QAr1TDxo/edit#). Instead of filtering by the difficulty we should filter by oldest or newest.

- [ ] replace "Most difficult" and "Least difficult" with "Newest" and "Oldest"

- [ ] delete "choose" and have "Newest" as default

**how it looks like:**
![Screenshot 2020-01-15 at 16.59.10.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/224f0578-e205-4cf0-8b83-62b5dc51a569)

**how it should look like:**
![Screenshot 2020-01-15 at 17.03.47.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/95139389-e938-4ff6-997e-975e8ff7ea9b)

**Comment by steverydz** [comment]
We don't have the dates to sort by "newest/oldest", and is that really a useful filter? I can't imagine ever going to a tutorials site and looking for the newest or oldest. I'd be far more interested in the topic.

For what it's worth I don't really see the point in filtering by difficulty either.

What do people thing? @anasereijo @matthewpaulthomas @tbille @anthonydillon

**Comment by anthonydillon** [comment]
Yeah difficulty and topic are the only useful things to sort and filter on.
