### ISSUE TITLE
fix spacing on search filters strip

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6401]
can we delete the extra spacing below the filters (as per image) so it has the same top and bottom padding?

![Screenshot 2020-01-15 at 17.10.21.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/56b30126-8627-4f10-bd33-400c5ca7262a)

**Comment by steverydz** [comment]
Pull request: https://github.com/canonical-web-and-design/ubuntu.com/pull/6411
