### ISSUE TITLE
cards strip shouldn't be shallow

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6402]
### how it looks like:
![Screenshot 2020-01-15 at 17.13.53.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/321ee5ea-a594-416a-9e9a-f72a11e6c997)

### how it should look like (I removed `shallow`)
![Screenshot 2020-01-15 at 17.13.44.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/b2f84213-2b46-4268-90c9-083ea033eea3)

**Comment by steverydz** [comment]
Pull request: https://github.com/canonical-web-and-design/ubuntu.com/pull/6411
