### ISSUE TITLE
date is missing from tutorial cards

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6404]
### how it looks like:
![Screenshot 2020-01-15 at 17.20.31.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/b158f048-853d-4c10-8a49-6f1f1d4eee40)

### How it should look like:
![Screenshot 2020-01-15 at 17.20.25.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/864cf6cb-ff56-4dfc-abde-d1f79b2efbca)

**Comment by anthonydillon** [comment]
I don't think date is useful for tutorials. They should not age as articles do.

**Comment by anthonydillon** [comment]
That is useful and that data is available to the template.

**Comment by steverydz** [comment]
That data isn't given in the metadata. I don't know if that's something we can add? @tbille
