### ISSUE TITLE
fix card without topic and description

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6405]
![Screenshot 2020-01-15 at 17.23.11.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/18c3caf6-c02d-405d-b9d1-752d40bdcea9)

on the current tutorials page looks like this:

![Screenshot 2020-01-15 at 17.23.00.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/2a3768b5-0900-4638-8394-7b643acea427)

**Comment by steverydz** [comment]
I've made a card for this already (#6392) so will close this one.
