### ISSUE TITLE
fix notifications (apply vanilla pattern)

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6408]
### how it looks like

![Screenshot 2020-01-15 at 17.39.44.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/77d964b0-470b-45ff-a747-96b4532b3189)

### how it should look like
![Screenshot 2020-01-15 at 17.42.00.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/5297d3e8-6934-4b3e-8431-fc681a61d5ba)

**Comment by tbille** [comment]
This is done now.
The content has been updated.
