### ISSUE TITLE
"finding help" section missing from tutorials

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6415]
when we finish a tutorial we should have a "Finding help" section as per design.

### How it should look like

![Screenshot 2020-01-16 at 09.30.51.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/f6d5dcf3-39f9-4838-a0a5-04f35d77ffef)

**Comment by tbille** [comment]
This comes from the content writer. Not every tutorials has this part.

Closing this issue.
