### ISSUE TITLE
Step 6 is not highlighted 

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6419]
Seems like it's an issue just in [this tutorial](https://ubuntu-com-canonical-web-and-design-pr-6385.run.demo.haus/tutorials/microstack-get-started#that%E2%80%99s-all-folks!) but we should check if it's happening anywhere else

 ![Screenshot 2020-01-16 at 11.01.17.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/2e9eaf73-a2fb-4745-ba6c-0fb2873c4ab5)

**Comment by steverydz** [comment]
@tbille this is because there is punctuation in the slug e.g. `that’s-all-folks!`

**Comment by steverydz** [comment]
> @tbille this is because there is punctuation in the slug e.g. `that’s-all-folks!`

@tbille I think this one will need you to take a look

**Comment by tbille** [comment]
yep, it's seems I need to change something in the backend. I moved to to medium since the app is not breaking.
