### ISSUE TITLE
[ILLUSTRATIONS UPDATE] index u.com

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6446]
Please update index - "The leading operating system for PCs, IoT devices, servers and the cloud" from the [copy doc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit?usp=drivesdk)

**Comment by steverydz** [comment]
PR: https://github.com/canonical-web-and-design/ubuntu.com/pull/6464
