### ISSUE TITLE
[ILLUSTRATIONS UPDATE] /kubernetes/managed 

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6456]
Please update managed - "Kubernetes - on Ubuntu, managed by Canonical" from the [copy doc](https://docs.google.com/document/d/1Qv379nYnod9e4jMrsdDND8D7mbPyqELi2lowjkfD-gU/edit?usp=drivesdk)

**Comment by steverydz** [comment]
@anasereijo I can't see any new illustrations in the copy doc. Has this one not been done yet or are there no changes to be made?

**Comment by anasereijo** [comment]
> @anasereijo I can't see any new illustrations in the copy doc. Has this one not been done yet or are there no changes to be made?

Hey Steve, sorry I don't understand your question. I just had a look and I updated all illustrations in the copydoc and you resolved all comments? So maybe you already did this?

**Comment by anasereijo** [comment]
@steverydz I think @pmahnke created [another issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6474) for this, but this is getting confusing so I think we should stick with the ones I created in the right [Epic](https://github.com/canonical-web-and-design/web-squad/issues/2220)

**Comment by steverydz** [comment]
I'm going to close this as a duplicate as it's been dealt with in https://github.com/canonical-web-and-design/ubuntu.com/pull/6476
