### ISSUE TITLE
[COPY UPDATE] what-is-openstack - "What is OpenStack"

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6463]
Move the diagram from the hero section to its own section

[copy doc](https://docs.google.com/document/d/15xrgIq_KUwHaCyFoI7-yS_JmBbsoyXJ4GpRMFAa7_is/edit?usp=drivesdk)

**Comment by pmahnke** [comment]
@anasereijo you didn't like the idea of an OpenStack logo as well?... I am approving either way.

**Comment by anasereijo** [comment]
> @anasereijo you didn't like the idea of an OpenStack logo as well?... I am approving either way.

I like the idea, I just didn't brief that because I would like to see how it looks when we put suru on it - I will then brief it or not depending of how it looks.
