### ISSUE TITLE
[ILLUSTRATIONS UPDATE] /kubeflow

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6465]
Please update index.html - "AI and Machine Learning on Ubuntu" from the [copy doc](https://docs.google.com/document/d/1mJq8PxH8FVRVF9i1Xzh0f6M73eyjqZE4NaKYHRcRAKM/edit?usp=drivesdk)

**Comment by anasereijo** [comment]
@steverydz don't do this one for now

**Comment by anasereijo** [comment]
@steverydz this one is ready to go now.

**Comment by steverydz** [comment]
I'll do this once https://github.com/canonical-web-and-design/ubuntu.com/pull/6464 has merged
