### ISSUE TITLE
Reduce h4 and h5 font size by one heading level in a tutorial section

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/ubuntu.com#6480]
In a tutorial section reduce the heading size of h4 to h5 and h5 to h6.

**Comment by steverydz** [comment]
@anasereijo do you have any thoughts on this? This is related to #6409.

**Comment by anasereijo** [comment]
> @anasereijo do you have any thoughts on this? This is related to #6409.

Where can I see it?

**Comment by steverydz** [comment]
After speaking with @anasereijo we decided to make the section heading a h3 then drop each heading below that one font size except h6 - so h5 and h6 will be the same.
