### ISSUE TITLE
/telecommunications - copydoc not linked to this page

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6489]
copy doc link is missing from this page. https://docs.google.com/document/d/15FY_IaT39V81FQcoSoEJpmRRjBX80PJ7uxjgzHnDDws/edit#heading=h.cc10rmxh86i7
---
*Reported from: https://ubuntu.com/telecommunications*

**Comment by pmahnke** [comment]
@anasereijo I am seeing this on the page... strange.
