### ISSUE TITLE
/security - copydoc not linked to this page

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6491]
copy doc link is missing from this page
https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit
---
*Reported from: https://ubuntu.com/security*

**Comment by pmahnke** [comment]
@anasereijo this works fine for me and it is in the page... strange.
