### ISSUE TITLE
fix illustration size on ubuntu.com homepage

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#6505]
As discussed, see below the sizes for each illustration in order to be proportional.

Any questions let me know

<img width="941" alt="Screenshot 2020-01-29 at 10 42 56" src="https://user-images.githubusercontent.com/36884067/73350515-13e3c800-4285-11ea-9aa3-814a1c799af2.png">

---
*Reported from: https://ubuntu.com/*

**Comment by anasereijo** [comment]
@steverydz please estimate this

we also should fix the other page using these illustrations. I'm trying to find which page it is

**Comment by steverydz** [comment]
@anasereijo the other page is /kubeflow
