### ISSUE TITLE
Issues on Win10

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/ubuntu.com#6541]
As mentioned here:

https://twitter.com/Gerry69381272/status/1223004735264915456

"Please fix the errors on your website first. No main menu, bug with header background in Edge (Win 10). How should people be convinced to migrate?"

![EPj8UmEWkAEoll_](https://user-images.githubusercontent.com/479384/73642642-f7230800-4669-11ea-8b80-4a2a4a9f291c.jpeg)

**Comment by pmahnke** [comment]
@anthonydillon who is the best person to look at this?
