### ISSUE TITLE
tutorial-create-a-usb-stick-on-windows: broken

### ISSUE THREAD

**Issue by svins** [canonical-web-and-design/ubuntu.com#6545]
https://ubuntu.com/tutorials/tutorial-create-a-usb-stick-on-windows#2-requirements

1. Screenshots are missing.
2. Tutorial is outdated: Rufus 3.8 has a different UI options.

Tested with
Chrome Version 79.0.3945.130 (Official Build) (64-bit)
Windows 10

**Comment by pmahnke** [comment]
@svins thanks for filing the issue.

I have uploaded the missing screenshots.

We will be updating the tutorial for 20.04 for your second point, so I am going to close this for now.
