### ISSUE TITLE
The colored disc next to a long-worded tutorial step is misshapen

### ISSUE THREAD

**Issue by fitojb** [canonical-web-and-design/ubuntu.com#6547]
In e.g. https://ubuntu.com/tutorials/tutorial-burn-a-dvd-on-windows#3-windows-95--98--me--2000--xp--server-2003--vista-instructions…
![image](https://user-images.githubusercontent.com/554953/73726697-9e00b600-46f5-11ea-84bb-8ef0ad8248a4.png)

… the step’s number disc is compressed by the long text next to it.

**Comment by pmahnke** [comment]
Thanks @fitojb I see it too.  We will get on it soon.
