### ISSUE TITLE
[Webinar] AI] - Build takeover and engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#6555]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/11RDq5vNUpgdy3UU_51d-QtGiptq5Fgz_tdOFbgx3zec/edit#gid=2113339190) and [design](https://github.com/canonical-web-and-design/web-squad/issues/2292):
 
- [x] build takeover
- [x] build engage page
- [x] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by steverydz** [comment]
@SirSamTumless That design link goes to a PR from 2017. Do you have the right link?

**Comment by SirSamTumless** [comment]
@steverydz That's now sorted!

**Comment by anasereijo** [comment]
@steverydz this is ready https://github.com/canonical-web-and-design/web-squad/issues/2292
