### ISSUE TITLE
Thinger maker snap is private?

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#6564]
@SirSamTumless can you ask Galem about this on the gateways page? The link is broken and we should probably remove the strip or at least the link.

---
*Reported from: https://ubuntu.com/internet-of-things/gateways*

**Comment by SirSamTumless** [comment]
I have chased Galem about this and am awaiting his answer.

**Comment by SirSamTumless** [comment]
He needs to update the copy doc as it is very out of sych from the webpage. Once this is done I can get to work removing it.
