### ISSUE TITLE
[Webinar] Dell Kubernetes] - Build takeover and engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#6571]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1T9BEfgdYrkMuxMbJm_KZWwYoMH7eZYPq8eotk6MrUag/edit#gid=0) and [design](https://github.com/canonical-web-and-design/web-squad/issues/2302):
 
- [x] build takeover
- [x] build engage page
- [x] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by anasereijo** [comment]
@sowasred2012 ready for you https://github.com/canonical-web-and-design/web-squad/issues/2302
