### ISSUE TITLE
Link to Raspberry Pi 4 Ubuntu server image is incorrect

### ISSUE THREAD

**Issue by roelofjan-elsinga** [canonical-web-and-design/ubuntu.com#6583]
This currently links to:
https://ubuntu.com/download/raspberry-pi/thank-you?version=18.04.3&architecture=arm63+raspi3

While this should be:
https://ubuntu.com/download/raspberry-pi/thank-you?version=18.04.3&architecture=arm64+raspi3

(arm63 vs arm64)

**Comment by pmahnke** [comment]
@roelofjan-elsinga wow, thanks!  That page has only been live for like 6 minutes.

I will get a fix out asap.

**Comment by roelofjan-elsinga** [comment]
Awesome, thank you for the quick response!
