### ISSUE TITLE
AI Takeover has wrong link

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#6604]
Hi folks, I've just noticed that the green button for this takeover points to the wrong webinar. 

- can you please fix this?

![image](https://user-images.githubusercontent.com/441217/74148257-f1df3380-4bfc-11ea-80b1-be361fd06c5f.png)

**Comment by sowasred2012** [comment]
What URL were you taken to? Having looked at this, the page linked to from that CTA is https://ubuntu.com/engage/ai-edge-webinar?utm_source=Takeover&utm_medium=Takeover&utm_campaign=CY20_IOT_Edge_AI_WBN - which seems correct?

![Screenshot 2020-02-10 at 12 11 12](https://user-images.githubusercontent.com/2376968/74148950-81d1ad00-4bfe-11ea-93f7-4419f21e621b.png)

**Comment by edu-ap** [comment]
I was taken to the VMware webinar

**Comment by edu-ap** [comment]
https://ubuntu.com/engage/vmware-to-charmed-openstack?utm_source=Takeover&utm_medium=Takeover&utm_campaign=CY19_DC_Openstack_WBN_VMwaretoOpenstack

**Comment by pmahnke** [comment]
Apparently this was because of Google Optomize and an unrelated AB test... so closing.
