### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by brydchem** [canonical-web-and-design/ubuntu.com#6635]
The download links for Ubuntu 18.04.3 for raspberry pi are broken. The links should point to 18.04.4 now.

broken - cdimage.ubuntu.com/releases/18.04.3/release/ubuntu-18.04.3-preinstalled-server-arm64+raspi3.img.xz
correct - cdimage.ubuntu.com/releases/18.04.4/release/ubuntu-18.04.4-preinstalled-server-arm64+raspi3.img.xz

---
*Reported from: https://ubuntu.com/download/raspberry-pi/thank-you?version=18.04.3

**Comment by pmahnke** [comment]
@brydchem thanks for filing an issue.  I think you hit the site in the gap between the iso going live and the web page.  It is all working now.
