### ISSUE TITLE
[Whitepaper] Securing ROS on Ubuntu - Build engage page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#6646]
## Requirements

Please build an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1GUWaUHcqg6cYUxq--IjZSYTdt7iDwcROF5uRVOSmU9M/edit#gid=0) and [design](2325):

- [x] build engage page
- [x] add engage page to `/engage/index.html`
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by anasereijo** [comment]
@sowasred2012 this is ready from my side https://github.com/canonical-web-and-design/web-squad/issues/2325 (not sure what's the status of the pdf, please check with Brand)
