### ISSUE TITLE
Tutorial card leads to 410 error

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#6649]
This tutorial is causing problems - there's a URL in place of the title, and following [the link](https://ubuntu.com/tutorials/build-a-nodejs-service) leads to a 410 error.

![Screenshot 2020-02-13 at 13 53 00](https://user-images.githubusercontent.com/2376968/74441835-64a01700-4e68-11ea-8150-2079ef4bdbfd.png)

*Reported from: https://ubuntu.com/tutorials?page=3*

**Comment by pmahnke** [comment]
@sowasred2012 it seems that @tbille removed it entirely and redirected it to some docs; however, it was still in the meta data, so I have removed it.

build-a-nodejs-service-snap

| https://discourse.ubuntu.com/t/build-a-nodejs-service-snap/14003 | We are going to use the nodejs snapcraft plugin to build a simple service. We’ll guide you through the good practice for debugging and iterating over your web server, and basic confinement notions. | packaging | 2 | Didier Roche <didier.roche@canonical.com> |

| https://discourse.ubuntu.com/t/build-a-nodejs-service-snap/14003 | /tutorials/build-a-nodejs-service |


- [old tutorials version](https://github.com/canonical-web-and-design/tutorials.ubuntu.com/blob/0502e61303819aef7b7ef257fdb918f084a43c00/tutorials/packaging/snap-a-nodejs-app.md)
- [closed new version](https://discourse.ubuntu.com/t/build-a-nodejs-service-snap/14003)
