### ISSUE TITLE
Tidy up and organise JavaScript

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/ubuntu.com#6660]
There is a lot of inline JS on ubuntu.com that is not going through the build pipeline which prevents us writing modern JavaScript.

I've done an audit of the amount of JS we have on the site: https://docs.google.com/spreadsheets/d/126cYfYKuhu1jipueBDPYsR_JobzBHHgwAI6IDPQydO8/edit#gid=769828130

**Comment by anasereijo** [comment]
@steverydz @SirSamTumless should this Epic be in our [spreadsheet](https://docs.google.com/spreadsheets/d/17StzFTEjYiokPjfyD1p3JRZFVRJtgmSIqsi-I-9kMcQ/edit#gid=0) for the current iteration? It should be always updated so we can track what was done each iteration

**Comment by anasereijo** [comment]
@steverydz @SirSamTumless I added to the spreadsheet but if for some reasons it shouldn't be there please delete
