### ISSUE TITLE
[Interana Case Study] Design banner and social media image

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#6671]
## Marketing requirements

Please design the elements below according to this [brief](https://docs.google.com/spreadsheets/d/1-oHnA7FYoSErL2Ad_NWzvouAxysgj-SZ_h4nI-VioX8/edit#gid=0):
 
- [x] landing page
- [x] meta image
- [x] social media banner (1200px x 630px)
- [x] save assets

**Comment by anasereijo** [comment]
Landing page:

[logo](https://assets.ubuntu.com/v1/0026bea9-logo-interana.svg) width: 290px

![Case Study  Interana - Landing page](https://user-images.githubusercontent.com/36884067/74647961-9240d500-5174-11ea-8d47-ea1545cab51e.png)

[Meta data img](https://assets.ubuntu.com/v1/863b2860-Meta+data+img.jpg)

![Meta data img](https://user-images.githubusercontent.com/36884067/74647974-98cf4c80-5174-11ea-8fec-bbba6ac37539.jpg)


[Social media banner
](https://assets.ubuntu.com/v1/ca45d154-Social+media+banner.jpg)![Social media banner](https://user-images.githubusercontent.com/36884067/74647987-a1c01e00-5174-11ea-9698-9e3f621a64a2.jpg)
