### ISSUE TITLE
[Interana Case Study] Build engage page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#6672]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1-oHnA7FYoSErL2Ad_NWzvouAxysgj-SZ_h4nI-VioX8/edit#gid=0) and [design](6671):
 
- [x] build engage page
- [ ] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [x] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by anasereijo** [comment]
@sowasred2012 @deadlight @steverydz this is ready from my side https://github.com/canonical-web-and-design/ubuntu.com/issues/6671

**Comment by sowasred2012** [comment]
@anasereijo baggsy!

**Comment by SirSamTumless** [comment]
@sowasred2012 The thank-you page and MKTO page are in the brief now.
