### ISSUE TITLE
Broken Hyperlink in Install Tutorial

### ISSUE THREAD

**Issue by nickfish03** [canonical-web-and-design/ubuntu.com#6674]
Hello, on page 2 (requirements) of the Install Ubuntu Desktop tutorial: 
https://ubuntu.com/tutorials/tutorial-install-ubuntu-desktop?backURL=https://ubuntu.com/download/desktop/thank-you#2-requirements
the hyperlink "several tutorials" in the last sentence, has no link associated with it.
"We also have **_several tutorials_** that explain how to create an Ubuntu DVD or USB flash drive."

**Comment by pmahnke** [comment]
@nickfish03 thanks for filing this.  I will get it fixed up soon.

**Comment by pmahnke** [comment]
@nickfish03 I have linked to https://ubuntu.com/tutorials?topic=desktop, which I think is the best for now... I will look if there is a better link we can use in the future.

Thanks for filing this.
