### ISSUE TITLE
Ubuntu Advantage for Infrastructure Datasheet

### ISSUE THREAD

**Issue by marcushas** [canonical-web-and-design/ubuntu.com#6686]

**Comment by SirSamTumless** [comment]
@Khutch25 any progress on this?

**Comment by SirSamTumless** [comment]
@marcushas Can you link the sheet that needs +1 from marketing here please?

**Comment by Khutch25** [comment]
If this is the French version, please send to @Clotilde Moullec
<clotilde.moullec@canonical.com> to review. Thank you!
