### ISSUE TITLE
[Webinar] Smart Start - Build takeover and engage page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#6765]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1BHbx3SYPCJrGij5wc7kzH5Y-KN4QqACEdd8iJzb_KAs/edit) and [design](2389):
 
- [ ] build takeover
- [x] remove `takeovers/_dell-kubernetes-webinar.html`
- [x] build engage page
- [x] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by pmahnke** [comment]
@anasereijo, no pressure, but do you or perhaps @spencerbygraves have capacity to do this takeover/engage page this cycle?  Alex forgot it.

**Comment by anasereijo** [comment]
@deadlight this is ready for you https://github.com/canonical-web-and-design/web-squad/issues/2389
