### ISSUE TITLE
broken iot gateway links

### ISSUE THREAD

**Issue by davidahoward** [canonical-web-and-design/ubuntu.com#6836]
under
'COMPANIES, WHO HAVE BUILT THEIR GATEWAYS ON UBUNTU."

Dell link is broken
IBM link doesn't take you to a iot gateway page, rather it lands on a generic training page
Intel link also doesn't land on a gateway page -
even if i do a search for 'ubuntu core' from the page that is referenced, theres no information.

---
*Reported from: https://ubuntu.com/internet-of-things/gateways*

**Comment by pmahnke** [comment]
@davidahoward thanks for filing this issue.

I have tried to fix it up a bit.  It is complicated as the logos come from our partners.ubuntu.com website and only allow a single URL per company.  If we do many things with a single company, you can only point to one.

I have moved these to more generic urls for now.

And made a note to look at how we might fix this in the future.
