### ISSUE TITLE
[Webinar] [Cloud Cost Analysis] - Build takeover and engage page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#6872]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1Yg_sHVjaGh4snje5TltN6SFH0PDyhTEWllnaaEkKmnw/edit#gid=0) and [design](https://github.com/canonical-web-and-design/web-squad/issues/2405):
 
- [x] build takeover
- [x] build engage page
- [x] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [x] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by anasereijo** [comment]
@steverydz @sowasred2012 guys this is ready https://github.com/canonical-web-and-design/web-squad/issues/2405
