### ISSUE TITLE
[Feature Request] Add "Sign in with Google" account option in  launchpad.net website

### ISSUE THREAD

**Issue by Donboscow** [canonical-web-and-design/ubuntu.com#6901]
Please  add "Sign in with Google" account option in  launchpad.net website for easy bug reporting

**Comment by anthonydillon** [comment]
@Donboscow thank you for taking the time to suggest this feature. It would be a good addition :ok_hand: could you please report this to the launchpad project itself please: https://bugs.launchpad.net/launchpad.

This is the repo for the ubuntu.com website.
