### ISSUE TITLE
[BootStack] update the BootStack Datasheet

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#6915]
- [BootStack Datasheet](https://docs.google.com/document/d/1H65-gxCQuwSyMbAnNEDULuOjGXb2KoJEZp17amEF6IE/edit#)

**Comment by SirSamTumless** [comment]
Copying in @waynecrosby so he has clarity on it.

**Comment by SirSamTumless** [comment]
@waynecrosby I can't find the artwork for these, any idea where it could be?

**Comment by waynecrosby** [comment]
@SirSamTumless Do you know who did them, or how old they are?

**Comment by SirSamTumless** [comment]
I have no idea sorry.
