### ISSUE TITLE
[BootStack] update the Whitepaper - Busting the myth of private cloud economics

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#6916]
- [Whitepaper - Busting the myth of private cloud economics](https://docs.google.com/document/d/1NtRmAB4Pkphc8WTU8n4-b10knVqqFhMDc_FtGAwQ7nw/edit)

**Comment by SirSamTumless** [comment]
@waynecrosby I can't find the artwork for these, any idea where it could be?

**Comment by waynecrosby** [comment]
@SirSamTumless - I haven't got the artwork, unless it's specifically sent to me from Upwork I don't always get them.
Here is the folder on Drive where old ones are kept:
https://drive.google.com/open?id=1K5WozxTkNe0_qWbFnQv-x5GRa8PmOCQK&authuser=wayne.crosby@canonical.com&usp=drive_fs
