### ISSUE TITLE
Security broken link

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#6945]
There is an unusable download link
on the Ubuntu Security page here: https://ubuntu.com/security/certifications

In the section titled "STIG" there is a link labeled "Download the STIG".
The link URL is:
https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_Canonical_Ubuntu_16-04_LTS_V1R2_STIG.zip

When I try to access it, I get a 403 Forbidden response.
Happens using Brave, Chrome, and wget (command line).

**Comment by deadlight** [comment]
I fixed this in #7243
