### ISSUE TITLE
[Image builder] Reloading pre-fills search field but doesn’t search

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#6965]
1\. Load the image builder page
2\. Choose a board and OS
3\. In the snap search field, enter some text
4\. Reload the page

What happens:
- the search field contents persist, but
- the results pane is emptied.

What should happen: either
- the search field contents do not persist, or
- the results pane reloads results for that text.

[Discovered while reviewing #6851.]

**Comment by anthonydillon** [comment]
No longer required as Image builder is being removed.
