### ISSUE TITLE
Update the chart for 'Ubuntu OpenStack release cycle' for Ussuri

### ISSUE THREAD

**Issue by pmatulis** [canonical-web-and-design/ubuntu.com#6975]
The graphic under section **Ubuntu OpenStack release cycle** needs to be updated to reflect reality. Two rows need changing:

* OpenStack Ussuri LTS: bar moved up the equivalent of one month (the release of OpenStack Charms 20.05 is currently scheduled for May 20)

* OpenStack Ussuri: bar moved up to be essentially the same as the corrected OpenStack Ussuri LTS bar (the release of OpenStack Ussuri is currently scheduled for May 11-15) 

---
*Reported from: https://ubuntu.com/about/release-cycle

**Comment by coreycb** [comment]
Just a little to add to what Peter said. Typically the upstream release schedule for OpenStack aligns with Ubuntu but not for Ussuri. Upstream schedule: https://releases.openstack.org/ussuri/schedule.html

**Comment by pmahnke** [comment]
@pmatulis and @coreycb this chart is only accurate if someone from the product team tells us how to fix it.  The webteam cannot possibly keep up to date with all the product changes in the company.  Can you update the date in the A-D columns in this [spreadsheet](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=1483484944)?

Thanks,

Peter

**Comment by coreycb** [comment]
@pmahnke Spreadsheet looks good to me for Ussuri. Thanks!
