### ISSUE TITLE
19.10 doesn't want to be fully downloaded, it would seem

### ISSUE THREAD

**Issue by Ianto66** [canonical-web-and-design/ubuntu.com#6981]
as above. Have tried more than six times in 3 different browsers without luck. Gets to 2.03 Gb before carking it.

**Comment by pmahnke** [comment]
@Ianto66 I am sorry to hear you are having issues.

I assume this was the desktop image?

I just tested and it was fine for me.

Perhaps try the bittorrent instead? https://ubuntu.com/download/alternative-downloads - many people have had better sucess with this.

I hope this helps.

Peter
