### ISSUE TITLE
Missing Download Link

### ISSUE THREAD

**Issue by JonasEinig** [canonical-web-and-design/ubuntu.com#7011]
Clicking on the download link for 18.04.4 LTS Desktop yields a 404 not found error.

Browser adress: https://ubuntu.com/download/desktop/thank-you?version=18.04.4&architecture=amd64
---
*Reported from: https://ubuntu.com/download/desktop*

**Comment by tomreyn** [comment]
91.189.91.44 seems to be missing the file in question. To clarify, the problem is not with the release (ISO) mirrors but immediately with the Ubuntu website hosting.

**Comment by anthonydillon** [comment]
The cache has been refreshed which seems to have resolved the issue.
