### ISSUE TITLE
[CVEs] Outline db schema

### ISSUE THREAD

**Issue by carkod** [canonical-web-and-design/ubuntu.com#7016]
## Summary 
- [x] Look at the existing data, compare with UX designs to ensure we know we have the data we need
- [x] Consider what types of data we will be requiring security to submit through the API and check they have the capability to provide each
[Reported here](https://docs.google.com/document/d/1gZs7zBuQF7f9q60hMgwBgYgHFpLSfOf__NyDV7-Xt8s/edit#heading=h.p528aj5gg7n)
- [x] Understand how usn works and see which parts are exactly reusable and which parts are not
- [ ] Analyze how we would create the tables, given that we have 3 categories.

**Comment by nottrobin** [comment]
@carkod you created the table already? Where / how did you do that? Are you sure you know all the fields you need?

From the [tasks in the spec doc](https://docs.google.com/document/d/1gZs7zBuQF7f9q60hMgwBgYgHFpLSfOf__NyDV7-Xt8s/edit#bookmark=id.109rzo9uc19t) I thought any actual creation of tables and data would happen in the "Migrations to create CVE data tables", and this task would just be about writing down what we thought the shape looked like.

I'm concerned that if we create stuff too early we'll have to change it which will require writing many migrations on top of migrations, which seems like a waste of time.

**Comment by carkod** [comment]
@nottrobin so I ran ubuntu.com on local and an error popped up saying "CVE table already exists" so I suppose that it's already created. I haven't checked it though

**Comment by nottrobin** [comment]
Okay, dunno what that's about. But either way I don't think "create table" is part of this task

**Comment by carkod** [comment]
Initial DB schema
https://docs.google.com/drawings/d/1dsU5KT0iC3QSIFcE4xlf1q8SsgeAuyypkKpU7qVB0Ww/edit

**Comment by anthonydillon** [comment]
Are References likely to be a shared piece of data? Why not store the URI directly in the CVE object instead of the FK?

The description might need to be more than a String, maybe a Blob? 

Will bugs just be a comma-separated string of bug ids?

**Comment by carkod** [comment]
@anthonydillon 
1. Not sure about references, but I assume it is, because USN is doing it this way.
2. I haven't checked all CVEs, but most of them are just a piece of text, I don't see the need of using a blob
3. I added a table for bugs, if that's what you mean? So the CVEs table will store it as a string of

**Comment by carkod** [comment]
Final schema:
<img width="840" alt="Screenshot 2020-03-25 at 15 18 04" src="https://user-images.githubusercontent.com/14939793/77552858-f8272780-6eab-11ea-8ac1-66216fe325d0.png">

**Comment by nottrobin** [comment]
@carkod what @anthonydillon means I think is that String fields in databases usually have relatively small max sizes. but it doesn't matter for this schema. When it comes to writing the database schema we might want to make it a blob.
