### ISSUE TITLE
IP page fails to mention all of Ubuntu's trademarks

### ISSUE THREAD

**Issue by wxl** [canonical-web-and-design/ubuntu.com#7029]
According to [EUIPO](https://euipo.europa.eu/eSearch/#advanced/trademarks/1/100/n1=ApplicantName&v1=canonical&o1=AND&c1=CONTAINS&sf=ApplicationNumber&so=asc) it seems the sum total of wordmarks registered are not represented on the IP page. Here's the full list with checks for those that are listed:

 - [X] Juju
 -  [X] Ubuntu
 - [ ] Canonical
 -  [X] Kubuntu
 -  [X] Edubuntu
 -  [X] Landscape
 - [ ] Bazaar
 - [ ] Launchpad
 - [ ] Ubiquity
 - [ ] Upstart
 - [ ] Lightware
 - [ ] Carrierstack
 - [ ] Ubuntu Edge
 - [ ] Bootstack
 - [ ] Maas
 - [ ] LXD
 - [ ] Snappy
 - [ ] Jaas
 - [ ] Snapcraft
 - [ ] Lubuntu

While it may not be necessary to list all of them, it would seem to me that it would be essential to include all of the flavors (so Lubuntu needs to be added) and Canonical itself.

Also, Xubuntu is listed but that does not seem to be a registered trademark. It doesn't seem like it ever was, either.

(Note the list does not include "Charm" or "Snap," both of which are found in the EUIPO results. The former's application was withdrawn and the latter is currently in opposition)

---
*Reported from: https://ubuntu.com/legal/intellectual-property-policy*

**Comment by SirSamTumless** [comment]
We have run this past our legal team, who are reviewing it. Thank for you for flagging this.
