### ISSUE TITLE
Visiting author page does not display the latest posts

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#7048]
Visit https://ubuntu.com/blog/canonical-managed-services-ubuntu-support-covid-19
Click on the author
The author page does not display latest posts
The second page crashes the site.

---
*Reported from: https://ubuntu.com/blog/canonical-managed-services-ubuntu-support-covid-19*

**Comment by sowasred2012** [comment]
@anthonydillon I've tried to reproduce this, but can see both latest posts and a second page - is it still happening for you?

**Comment by anthonydillon** [comment]
@sowasred2012 I am referring to the fact the covid post is not available on marks profile: https://ubuntu.com/blog/author/mark-shuttleworth

**Comment by SirSamTumless** [comment]
This issue is due to the fact that Mark has many accounts on WordPress, closing due to staleness.
