### ISSUE TITLE
/advantage: “Add another subscription” point disconnected from button+panel

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7065]
1\. With a paid Ubuntu Advantage subscription, go to [/advantage](https://ubuntu.com/advantage) and sign in. (Or while #7042 is open, use [that PR’s demo](https://ubuntu-com-canonical-web-and-design-pr-7042.run.demo.haus/advantage).)
2\. Choose “Add another subscription”.

What you see:

![image](https://user-images.githubusercontent.com/19801137/77415952-22e58300-6dbb-11ea-8b6c-6e964a229066.png)

What you should see:
- Horizontally, the panel’s point should align with the chevron.
- Vertically, the point should touch or overlap the button.
- Most importantly, the point should be connected with the rest of the panel.

**Comment by lyubomir-popov** [comment]
This is not a vanilla pattern, and we recently removed a similar triangle from the contextual menu. Why not use a wide contextual menu here? It can be as wide as the fixed-width of the website.

**Comment by matthewpaulthomas** [comment]
> we recently removed a similar triangle from the contextual menu.

That would have been great, if it helped convey that those menus behave differently from popovers — that, as with menus in other toolkits, you can select an item with a single drag (so the lack of arrowhead reduces the distance you need to drag), or you can use Space to open the menu then arrow keys to select an item. Unfortunately neither of those works.

> Why not use a wide contextual menu here?

The simplest answer is that this isn’t a menu. I hope those issues with the menu get fixed, but they wouldn’t apply to this panel, since it doesn’t contain menu items.

An extra, minor reason is that without an arrowhead, the top of the panel would be flush with the bottom of the button, and that would make the panel collide unattractively with the baseline of the “Your paid subscriptions” heading alongside.

**Comment by anthonydillon** [comment]
Fixed as part of #7040
