### ISSUE TITLE
Impossible to create an account

### ISSUE THREAD

**Issue by SamuelP1111** [canonical-web-and-design/ubuntu.com#7081]
Hi,

I use Windows 10 and ubuntu from more than 20 years for Windows.

I was an ubuntu forum user some years ago.

I can't create a new account, all the username i use, are impossible to use with ubuntu.

SamuelP, SamuelP1111, Samuel P, SamuelP111, SamuelPzero, SamuelP11110, etc...

No username is ok with my mail.

So it will be very nice if i can create a ubuntu account.

Thanks

regards

**Comment by SirSamTumless** [comment]
Hello,

Thanks for reaching out. Unfortunately, you've found the board for the site ubuntu.com, not https://login.ubuntu.com/. You can find our FAQ section for https://login.ubuntu.com/ [here](https://help.ubuntu.com/community/SSO/FAQs?_ga=2.92296020.859801676.1585557100-125046274.1557910907).

Thanks for being part of the Ubuntu community for so long! 

Cheers,
Sam
