### ISSUE TITLE
captcha is unsolvable

### ISSUE THREAD

**Issue by setharnold** [canonical-web-and-design/ubuntu.com#7120]
Hello, the captcha images on https://ubuntu.com/legal/contributors/agreement are impossible to solve. I'll be able to provide reasonable screenshots soon, but in the meantime, you can probably see for yourself that they are unintelligible. Or I'm a robot and this is a rough way to find out.

Thanks

---
*Reported from: https://ubuntu.com/legal/contributors/agreement*

**Comment by pmahnke** [comment]
@setharnold we tried to make it a bit harder, just for you.

#joke, I have contacted the person who manages that form to get it fixed.

Thanks for letting us know,

Peter
