### ISSUE TITLE
www.ubuntu.com redirection to release notes does not work

### ISSUE THREAD

**Issue by murraybd** [canonical-web-and-design/ubuntu.com#7129]
## Summary

All Ubuntu ISOs include a file (/media/cdrom/.disk/release_notes_url) which as a link to the release notes. Its contents look like this:

http://www.ubuntu.com/getubuntu/releasenotes?os=ubuntu&ver=18.04.4&lang=${LANG}

This now redirects to https://wiki.ubuntu.com/Releases?os=ubuntu&ver=18.04.4&lang=en which is not the release notes for that release.

## Process

Load this hyperlink http://www.ubuntu.com/getubuntu/releasenotes?os=ubuntu&ver=18.04.4&lang=en

Additionally, it doesn't matter which release I use for ver.

## Current and expected result

I expect the redirect to the release notes to work.

**Comment by murraybd** [comment]
I think looking back at only releases that are supported for flavours would be fine and keep in mind that not every flavour is supported as long as Ubuntu.

**Comment by oSoMoN** [comment]
Not sure why this was closed, but redirection of the release notes hyperlink in the Ubuntu installer (ubiquity) [still doesn't work](https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1910871).

Should this be re-opened, or a new bug filed?

**Comment by nottrobin** [comment]
I suspect that the PR that closed this issue fixed the issue at the time, and it's now got broken again.

I think maybe a new issue is best.

**Comment by oSoMoN** [comment]
> I think maybe a new issue is best.

Ack, I filed https://github.com/canonical-web-and-design/ubuntu.com/issues/9523.
