### ISSUE TITLE
Update image on What is Ros page

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/ubuntu.com#7131]
@pmahnke 

Something like this?

![image.png](https://images.zenhubusercontent.com/593a90fb51aa2c305781077c/c5ccf61d-e988-4f97-ab59-88cbfdc42cb4)

**Comment by pmahnke** [comment]
perfect!

**Comment by spencerbygraves** [comment]
@pmahnke @steverydz great, you can find the image [here](https://assets.ubuntu.com/v1/f042f4da-what-is-ros.svg).

To avoid duplication, could we move [this image](https://assets.ubuntu.com/v1/a17329f6-ROS.svg) down to the second "What is ROS" section?
