### ISSUE TITLE
/advantage: Tech support isn’t indicated/offered anywhere

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7137]
When you have an Ubuntu Advantage subscription, nothing on [ubuntu.com/advantage](https://ubuntu.com/advantage) indicates whether that subscription includes tech support.

And if it does include tech support, there is no indication of how to access it.

[Reported by Maryan Dahir.]

**Comment by carkod** [comment]
The new advantage page has a support portal.
