### ISSUE TITLE
[COPY UPDATE] index.html - Ceph

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#7139]
Please update index.html - Ceph from the [copy doc](https://docs.google.com/document/d/17VnBygL00hXjLSECXMo3bF7KOCT5oZGFBLo6Qd6rF3A/edit?usp=drivesdk)

- [x] Update ctas
- [x] Update diagram
- [x] Add video

**Comment by deadlight** [comment]
Waiting for the new diagram asset

**Comment by deadlight** [comment]
@SirSamTumless let me know when we have the diagram
