### ISSUE TITLE
[CVEs] Design search options

### ISSUE THREAD

**Issue by carkod** [canonical-web-and-design/ubuntu.com#7143]
## Summary
Design the different search options and its limits based on Matthew's [wireframes](https://docs.google.com/document/d/1VuAElUpFay7MBFNmE3NhSyY9TkXiqHcA1ZHQ11AYO-Q/edit#heading=h.aoek8nxke7k9).

**Comment by spencerbygraves** [comment]
@carkod I'm not sure what you mean by "limits" or what's required here.

**Comment by carkod** [comment]
maybe @steverydz  can shed more light to this, but I was thinking that we may need a design for this

<img width="687" alt="Screenshot 2020-04-08 at 10 38 23" src="https://user-images.githubusercontent.com/14939793/78769488-57de0200-7985-11ea-85a3-17d81c67d91c.png">
