### ISSUE TITLE
Update the /desktop/partners page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#7163]
Update [For partners | Ubuntu](https://ubuntu.com/desktop/partners) page baed on the [copy doc](https://docs.google.com/document/d/1b4pwQYVHm8-R5_Wqx5zj09Qn8QsrKt3JblteauspmKI/edit)

**Comment by deadlight** [comment]
Missing assets and copy flagged for update not updated.
