### ISSUE TITLE
When Install the latest CUDA version, Did not need nvidia-cuda-toolkit, Only need Install the cuda.

### ISSUE THREAD

**Issue by ytooyama** [canonical-web-and-design/ubuntu.com#7174]
There is a mistake on this page.
* https://ubuntu.com/tutorials/gpu-data-processing-inside-lxd#4-install-the-cuda-toolkit

```
sudo apt install cuda nvidia-cuda-toolkit
↓
sudo apt install cuda
```

* latest CUDA = 10.2
* Ubuntu 18.04 's nvidia-cuda-toolkit = 9.1.85-3ubuntu1
* Ubuntu 16.04's  nvidia-cuda-toolkit = 7.5.18-0ubuntu1

**Comment by SirSamTumless** [comment]
Hi, thanks for flagging this. Please could you suggest the changes here; https://discourse.ubuntu.com/t/gpu-data-processing-inside-lxd/13968.
