### ISSUE TITLE
Update the /public-cloud page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#7191]
Update [Ubuntu on Public Clouds](https://ubuntu.com/public-cloud) page baed on the [copy doc](https://docs.google.com/document/d/1ZzUIh9Tfz5SvkrHyo4-izzmUjRka1Tn0UQisKcXGEPA/edit)

- [x] needs new laptop image
~~needs 20.04 mention from Lech~~

**Comment by deadlight** [comment]
No new content present as of today

**Comment by deadlight** [comment]
@spencerbygraves @SirSamTumless do we have a laptop image to replace this one?
![image.png](https://images.zenhubusercontent.com/5931737051aa2c3057804027/4c3741a9-489c-4ebe-9a3e-cecb68ca1642)

@SirSamTumless can you chase Lech to see if we need to add any 20.04-specific content?

**Comment by spencerbygraves** [comment]
@deadlight we used this one on desktop/developers:

https://assets.ubuntu.com/v1/b3061ad7-laptop-dev.png

**Comment by SirSamTumless** [comment]
@lechsandecki told me "I don't know if they will even be able to deliver links before Thursday. Links are pointing to our partners websites: aws and azure. I will meet them at 6pm today to discuss the action plan". 

With this in mind, I would just make the changes without Lech's input.

**Comment by pmahnke** [comment]
@deadlight can we push up anything without the links?

**Comment by deadlight** [comment]
@pmahnke I will update the image to the one that Spencer suggested and that's about all we need to do. I don't think that it's release-critical to have the 20.04 links if they're not ready yet, we can add them when we have them. I updated this page last week, so we already have the /aws and /azure links in place and some other copy/styling changes.
