### ISSUE TITLE
Update the /server overview page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#7193]
Update [Ubuntu Server - for scale out workloads](https://ubuntu.com/server) page baed on the [copy doc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit)

**Comment by pmahnke** [comment]
@deadlight where is this, it should be simple.

**Comment by deadlight** [comment]
Yeah, it is. Nothing blocking it, I was delayed by other stuff. Will PR it
soon after I get to my desk.
