### ISSUE TITLE
Misprint

### ISSUE THREAD

**Issue by Goshiq** [canonical-web-and-design/ubuntu.com#7199]
Hello,
There is a misprint on the page:
https://ubuntu.com/tutorials/command-line-for-beginners#5-moving-and-manipulating-files

The phrase "In the same way that two dots ("…")" has one extra point.

Thank you for the great tutorial :)

--
George

**Comment by anthonydillon** [comment]
Thank you very much for taking the time to report this issue. I have fixed the markup. This will take a few mins at appear.

Glad you enjoyed it.
