### ISSUE TITLE
Update the /desktop page with new images

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#7254]
Update [Ubuntu PC operating system](https://ubuntu.com/desktop) page baed on the [copy doc](https://docs.google.com/document/d/1ZhMkLlkXcimHTIe1taXy24vbbR9pBkZd49H2sJqeQH0/edit)

- [x] top banner - replace screen with focal fossa background
- [x] complete - logo cloud from snapstore
- [x] visually stunning - netflix screenshot
- [x] availble - dell laptop

**Comment by spencerbygraves** [comment]
@pmahnke here is 3 of the 4 images. I'm waiting for a PSD of the Dell laptop to save a better image.

[Hero banner](https://assets.ubuntu.com/v1/2a202263-hero-banner.jpg)
[Netflix screen](https://assets.ubuntu.com/v1/1ebe9dec-netflix-x2.jpg)
[Logos](https://assets.ubuntu.com/v1/48a26da6-logos.png)

**Comment by spencerbygraves** [comment]
@pmahnke [laptop image](https://assets.ubuntu.com/v1/3e3f7d1f-hero-laptop.png)
