### ISSUE TITLE
Update the /desktop/developers page with new images

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#7255]
Update [Desktop for developers](https://ubuntu.com/desktop/developers) page baed on the [copy doc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit)

- [x] new screenshot - VS code peter
- [x] by dev, for dev - VS code (same one)

**Comment by spencerbygraves** [comment]
@pmahnke here is the [vscode image](https://assets.ubuntu.com/v1/d998d55f-vscode.jpg)

**Comment by spencerbygraves** [comment]
@pmahnke here's the updated [vscode image on a laptop](https://assets.ubuntu.com/v1/b3061ad7-laptop-dev.png)
