### ISSUE TITLE
Update the /desktop/features page with new images

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#7256]
Update [Desktop features](https://ubuntu.com/desktop/features) page baed on the [copy doc](https://docs.google.com/document/d/1nLHJlZ3igDwAAOUDP03wp4iKLxZts8110EA2ZOF5uaU/edit)

- [x] banner - update Ubuntu Software screenshot
- [x] office software - new libre office
- [x] web browsing - frankie and grace screenshot Peter to create
- [x] photo - new screenshot , icons for krita, gimp, blender
- [x] videos - use the youtube image
- [ ] gaming - sam to fix text

**Comment by spencerbygraves** [comment]
@pmahnke here are the images. I don't have a screenshot for the photo software, could you take one please?

[Hero banner](https://assets.ubuntu.com/v1/3e3f7d1f-hero-laptop.png)
[Libre office](https://assets.ubuntu.com/v1/14e97c61-libre-office.jpg)
[Web browsing Frankie and Grace](https://assets.ubuntu.com/v1/b1d0dc55-frankie-grace.jpg)
[Web browsing feature wide](https://assets.ubuntu.com/v1/4baae677-features-wide.jpg)
[Videos Youtube](https://assets.ubuntu.com/v1/c404705c-video-youtube.jpg)

**Comment by spencerbygraves** [comment]
@pmahnke here is the [shotwell image](https://assets.ubuntu.com/v1/af19d2f8-shotwell.png)
