### ISSUE TITLE
Update the /desktop/organisations page with new images

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#7257]
Update [Ubuntu in organisations](https://ubuntu.com/desktop/organisations) page baed on the [copy doc](https://docs.google.com/document/d/1q3_fQB3PUGbREsbCC4FnmHrpgn9nIWtMwyhDC6CXhNE/edit)

- [x] banner new screen of map? Peter
- [x] pre-installed - use dell laptop

**Comment by spencerbygraves** [comment]
@pmahnke 

[Hero banner](https://assets.ubuntu.com/v1/32d95e39-hero-laptop-org.jpg)
[Laptop](https://assets.ubuntu.com/v1/3e3f7d1f-hero-laptop.png)
