### ISSUE TITLE
Update the /desktop/partners page with new images

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#7258]
Update [For partners | Ubuntu](https://ubuntu.com/desktop/partners) page baed on the [copy doc](https://docs.google.com/document/d/1b4pwQYVHm8-R5_Wqx5zj09Qn8QsrKt3JblteauspmKI/edit)

- [x] Ubuntu certified - use dell image

**Comment by spencerbygraves** [comment]
Just waiting for the correct PSD to supply the image to @deadlight

**Comment by SirSamTumless** [comment]
@spencerbygraves Katie can't find a PSD. Can we do it with the JPEG?

**Comment by spencerbygraves** [comment]
@SirSamTumless ok, will do.

**Comment by spencerbygraves** [comment]
@deadlight try [this image](https://assets.ubuntu.com/v1/3e3f7d1f-hero-laptop.png)
