### ISSUE TITLE
Support universe CVEs in load_cve script

### ISSUE THREAD

**Issue by carkod** [canonical-web-and-design/ubuntu.com#7260]
## Summary

Update script to upload universe CVEs and develop component in the search.

**Comment by nottrobin** [comment]
The updating of the script should now be Security's responsibility - they now own that script and they will do any updates to it. All that we should concern ourselves with is making sure the API endpoints are there for them to submit the data.

The other half of this - updating search - is captured here https://github.com/canonical-web-and-design/ubuntu.com/issues/7926.

So I think this issue contains no extra work and should be closed.
