### ISSUE TITLE
buy.ubuntu.com says “All rights reserved Ubuntu Advantage”

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7287]
1\. Go to [buy.ubuntu.com](https://buy.ubuntu.com/)
2\. Add anything to your cart
3\. Check the checkbox and choose “Check out”
4\. Scroll to the bottom of the checkout page

What you see: “All rights reserved Ubuntu Advantage”

What’s wrong with this: Ubuntu Advantage is not a legal entity

What you should see: either
- nothing, or
- “All rights reserved Canonical”

**Comment by sowasred2012** [comment]
@matthewpaulthomas I've hidden this, the name is taken from the store name, so changing to "Canonical" wouldn't work. Closing.
