### ISSUE TITLE
CVE launch: Uncomment links to CVE page

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/ubuntu.com#7301]
For the soft launch the links on ubuntu.com to /security/cve have been commented out. Once we have fully launched we need to uncomment them in the following places:
- navigation.yaml
- templates/templates/_navigation-developer-h.html

**Comment by anthonydillon** [comment]
What is the motivation for a soft launch? Is it uncomplete in some way?

**Comment by steverydz** [comment]
@anthonydillon the work will be done on our part but the security team will need to be comfortable using the api before we can officially launch it

@carkod or @nottrobin may have more to add

**Comment by carkod** [comment]
Yes, we agreed with Lech that there are some features we are missing like advanced search, which need to come after we have successfully uploaded a batch of hundreds of CVEs. Also the ability to upload hundreds of CVEs is also something ongoing now. Plus the current tracker is not taking into account different "components" like universe and partners.

**Comment by steverydz** [comment]
This is not ready to be closed yet

**Comment by nottrobin** [comment]
Settle down Stalebot
