### ISSUE TITLE
Write and link to Etcher tutorial

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/ubuntu.com#7311]
I will write a OS-agnostic tutorial for creating a boot usb using Etcher and link to it from the relevant ubuntu.com pages.

**Comment by deadlight** [comment]
I've written the steps and have edited the screenshots. I'm just finalising the formatting for the tutorials flow.

**Comment by fitojb** [comment]
balenaEtcher phones home even when instructed not to, and is a bloated application generally, can we stop promoting it?

**Comment by deadlight** [comment]
@fitojb do you have a suggestion for an alternative to suggest to our users? Key points to hit are cross-platform, trivially easy to use for non-technical users and open source. Anything that hit those requirements is a candidate for consideration.

**Comment by fitojb** [comment]
In https://discourse.ubuntu.com/t/create-a-bootable-usb-stick-on-macos/14016/6, usbimager was suggested.
