### ISSUE TITLE
Directry listing

### ISSUE THREAD

**Issue by Noneofyou01** [canonical-web-and-design/ubuntu.com#7312]
Hello Ubuntu I found a directory listing in one of sub domain.
click the link below.

**http://people.ubuntu.com/~rachidbm/vertaalteam/tour/**

Regards 
Akash basnet

---
*Reported from: https://ubuntu.com/*

**Comment by SirSamTumless** [comment]
Hello,

Thanks for flagging this! This is working as expected.

Cheers,
Sam
