### ISSUE TITLE
Impossible to find POWER previous release download (18.04 one, on the 20.04 website)

### ISSUE THREAD

**Issue by xnox** [canonical-web-and-design/ubuntu.com#7319]
I went to home page, then to download, then to server, then scrolldown to the POWER card, and clicked on POWER downloads.

It opened a new POWER specific images.

Under Ubuntu Server card the download link pointed at POWER image. However the "Alternative and previous releases ›" took me to a page with Bittorrent links for amd64 images only.

Not sure if this was intentional. That POWER specific download page guides one into "amd64 specific alternative & previous releases" page.

Where can I find the 18.04 ppc64el download link?

---
*Reported from: https://ubuntu-com-canonical-web-and-design-pr-7269.run.demo.haus/download/server/power*

**Comment by pmahnke** [comment]
I will add more to the alternative download page.
