### ISSUE TITLE
Still shows 'Windows 8' on the Download Page

### ISSUE THREAD

**Issue by RudraSwat** [canonical-web-and-design/ubuntu.com#7329]
There is an error on https://ubuntu.com/download/desktop. It still shows Windows 8.

![image](https://user-images.githubusercontent.com/26926757/80126296-83313580-85b0-11ea-99b1-382e56439f83.png)

Please look into that one.

---------------------------------------
Reported by @rs2009 on Launchpad & Ubuntu Discourse

**Comment by pmahnke** [comment]
wow thank you @RudraSwat!
