### ISSUE TITLE
[Case study] Cyberdyne - JP] - Build takeover and engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#7337]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1yi7AYGRl_G-WeOIS-rp00n4ZOwwhGCY7n98voTsJOy0/edit#gid) and [design](https://github.com/canonical-web-and-design/web-squad/issues/2662):
 
- [x] build takeover
- [x] build engage page
~~add takeover to `/takeovers/index.html`~~
~~add takeover to `/index.html`~~
~~add engage page to `/engage/index.html`~~
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by deadlight** [comment]
@SirSamTumless I don't have the form info
