### ISSUE TITLE
[Whitepaper] Core and snaps - embedded updates ] - Build takeover and engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#7340]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1UYzDr_lRCTESFY9TodAZw_CLqR48ADfdwXmEH9nCZ-w/edit#gid=2113339190) and [design](2453):
 
- [ ] build takeover
- [ ] build engage page
- [ ] add takeover to `/takeovers/index.html`
- [ ] add takeover to `/index.html`
- [ ] add engage page to `/engage/index.html`
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by SirSamTumless** [comment]
PDF link can be found here; https://pages.ubuntu.com/rs/066-EOV-335/images/Over-the-air software_12.05.20.pdf

**Comment by steverydz** [comment]
Waiting on utm for engage page
