### ISSUE TITLE
No 20.04 network installer 

### ISSUE THREAD

**Issue by philipzae** [canonical-web-and-design/ubuntu.com#7341]
The 18.04 network installer is on this page rather than 20.04.

---
*Reported from: https://ubuntu.com/download/alternative-downloads

**Comment by anthonydillon** [comment]
Thanks @philipzae there is a new Ubuntu Live installed for 20.04 LTS.

> For 20.04 LTS, users can use the new Ubuntu Live installer to setup and configure a network install.
