### ISSUE TITLE
/build: “No matching snaps” and “None yet” misaligned

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7359]
1\. Sign in on /build (once #6695 is merged)
2\. Choose a board and Ubuntu version
3\. In the “Available snaps:” search field, search for something with zero results

What you see: “No matching snaps” and “None yet” aren’t lined up with each other.

![image](https://user-images.githubusercontent.com/19801137/80488376-2047f180-8956-11ea-838f-56eeda80991d.png)

What you should see: They are lined up with each other.

![image](https://user-images.githubusercontent.com/19801137/80488610-86347900-8956-11ea-9615-97a00b04c749.png)

One way to achieve this would be positioning them relative to the bottom of their respective lists.

**Comment by carkod** [comment]
https://ubuntu.com/core/build has been deleted
