### ISSUE TITLE
The Firefox and Skype icons are not current in /desktop

### ISSUE THREAD

**Issue by fitojb** [canonical-web-and-design/ubuntu.com#7368]
The Firefox and Skype icons under the hero section are out of date. The Firefox icon is [now more purple](https://3u26hb1g25wn1xwo8g186fnd-wpengine.netdna-ssl.com/files/2019/10/Firefox-Browser-Logo-Assets.zip), and the “S” in the Skype icon is now a rounded version of Segoe instead of Helvetica Rounded ([the snapcraft page displays the correct logo](https://snapcraft.io/skype)).

---
*Reported from: https://ubuntu.com/desktop*

**Comment by pmahnke** [comment]
@fitojb thanks!

@spencerbygraves could you update this image
![image](https://user-images.githubusercontent.com/441217/80567919-e75b5b80-89ed-11ea-9e81-444742d83c1c.png)

- [new skype logo](https://assets.ubuntu.com/v1/db08229d-Skype-202004-logo.png)
- [new firefox logo](https://assets.ubuntu.com/v1/69f10288-Fx-Browser-icon-fullColor.svg)

**Comment by spencerbygraves** [comment]
@pmahnke updated [here](https://assets.ubuntu.com/v1/741b30ec-desktop-logos.png).
