### ISSUE TITLE
/build should scroll on click on mobile

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/ubuntu.com#7372]
> This is probably a “nice to have” follow up and not a blocker, but on mobile would be nice if the page scrolled automatically to the next step once a choice is made. Otherwise the UI is hidden.

https://github.com/canonical-web-and-design/ubuntu.com/pull/6695#issuecomment-620707400

**Comment by pmahnke** [comment]
@anthonydillon might be fixed?

**Comment by anthonydillon** [comment]
@pmahnke not yet
