### ISSUE TITLE
[COPY UPDATE] index - "Plans and pricing for Ubuntu. Support, consulting, training and operations"

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#7397]
Please update index - "Plans and pricing for Ubuntu. Support, consulting, training and operations" from the [copy doc](https://docs.google.com/document/d/1iOM6oBqsTkptsst3yG-U3sGaYLQqs27go_8yJQdhMBE/edit?usp=drivesdk)

**Comment by deadlight** [comment]
Most of the copy changes are around managed apps, which is not ready and none of the linked pages exist yet

**Comment by pmahnke** [comment]
closing for now
