### ISSUE TITLE
Global nav login links followed by empty `<ul>`'s

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/ubuntu.com#7398]
## Summary

Spacing in the global nav is uneven due to empty uls ![image](https://user-images.githubusercontent.com/2741678/80794143-10682180-8b91-11ea-8689-e05e41c91957.png)

## Process

Open the global nav, inspect the Login > links, look for empty uls after them

## Current and expected result
Current:
![image](https://user-images.githubusercontent.com/2741678/80794267-676df680-8b91-11ea-9a99-516f5fd1b81c.png)

Taking the uls out and (optionally) adding a .u-no-padding--bottom on .global-nav__inline-list  element (the parent .global-nav__matrix-item already provides enough padding):

![image](https://user-images.githubusercontent.com/2741678/80794240-57eead80-8b91-11ea-9730-21be103d4ca2.png)

**Comment by davegoddard42** [comment]
Issue moved to [canonical-web-and-design/global-nav #199](https://github.com/canonical-web-and-design/global-nav/issues/199) via [**ZenHub**](https://www.zenhub.com/)
