### ISSUE TITLE
Update engage page image

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/ubuntu.com#7404]
On https://ubuntu.com/engage/moving-to-opensource-whitepaper
- [x] Update the hero to match the design of [this page](https://ubuntu.com/engage/microk8s-451research)
- [x] Update the meta image

**Comment by SirSamTumless** [comment]
@spencerbygraves Could you provide a new meta image as per the older takeover that includes the 451 logo.

https://assets.ubuntu.com/v1/4da9888c-Embedded+social+media+banner.jpg for ref.

**Comment by deadlight** [comment]
@spencerbygraves The headline has changed to "Embracing the open source mandate", if you could change that too

**Comment by spencerbygraves** [comment]
@deadlight here you go

![image](https://user-images.githubusercontent.com/9105999/80807588-87afac80-8bb5-11ea-8bc5-a036ce73bd35.png)
