### ISSUE TITLE
Include favicon.ico

### ISSUE THREAD

**Issue by hloeung** [canonical-web-and-design/ubuntu.com#7408]
Hi,

Seeing quite a lot of requests for favicon.ico. Any chance we could get this included with the ubuntu.com site rather than a 302 **temporary** redirect?

```
$ curl -I https://ubuntu.com/favicon.ico
HTTP/2 302
server: nginx/1.14.0 (Ubuntu)
date: Fri, 01 May 2020 21:43:43 GMT
content-type: text/html; charset=utf-8
content-length: 305
strict-transport-security: max-age=15724800
location: https://assets.ubuntu.com/v1/088fd1bf-favicon.ico
```

Thanks.

**Comment by hloeung** [comment]
The idea is to reduce the load on the backends by increasing the cache HIT ratio (see grafana graphs).

**Comment by nottrobin** [comment]
Yep, this sounds like a good idea. We'll update https://github.com/canonical-web-and-design/canonicalwebteam.flask-base/ to serve `/favicon.ico` from `/static/favicon.ico` if it exists, and then create that file in this ubuntu.com codebase.

**Comment by hloeung** [comment]
Looks like this is WIP, thanks guys.

https://github.com/canonical-web-and-design/ubuntu.com/pull/7539
