### ISSUE TITLE
[Core appliances pages] Design homepage

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#7410]
Deliver the design for the appliance landing page which will live at ubuntu.com/appliance from the [copy doc](https://drive.google.com/open?id=1Fcr5b5Rn06AB89D6DGPmoIgXLxLalijMhwnu_IyUxV4).

**Comment by danielmutis** [comment]
[Here](https://zpl.io/VYEjvOw) is the design for the homepage.
