### ISSUE TITLE
[Core appliances pages] Build About

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#7412]
Build the about at /appliance/about from the design and with the [copy doc](https://drive.google.com/open?id=1UM4K9n9SFNiWdmKIBnPGCsjLQrPSOnqZHMNIMwQ2CZI).

**Comment by waynecrosby** [comment]
@deadlight Here are a couple of designs based on the updated copy doc. Not sure if you want to wait until the copy has been signed off before choosing?
![Alliance Copy 2](https://user-images.githubusercontent.com/42238722/81505449-1d021d80-92e7-11ea-97f2-c7eccabb4bab.jpg)
![Alliance Copy 3](https://user-images.githubusercontent.com/42238722/81505453-225f6800-92e7-11ea-865b-95ac5e8bb881.jpg)
![Alliance](https://user-images.githubusercontent.com/42238722/81505454-22f7fe80-92e7-11ea-8cf1-8de3153f3f90.jpg)
