### ISSUE TITLE
[Core appliances pages] Build page: /appliance/plex/

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#7425]

**Comment by deadlight** [comment]
[copy](https://drive.google.com/drive/folders/1Ta2YUPgx17I4J1pjmih4UNwm_33I3k4L)

**Comment by deadlight** [comment]
[DESIGN](https://app.zeplin.io/project/5eb3d16a91c4117789940141/screen/5eb3fd0a59a84577c29a34ff)

**Comment by deadlight** [comment]
[Plex assets](http://brand.plex.tv/d/qxmJ3odkK0fj/style-guide) Logos, etc.
