### ISSUE TITLE
/advantage: Subscription ends “in 0 day” + “in 0 days”

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7438]
When a subscription is due to end today:

- The cell says “Ends in 0 day”
  ![image](https://user-images.githubusercontent.com/19801137/81047378-31db4d00-8eb2-11ea-8c90-c55409d53957.png)

- The expanded cell says “Ends … — in 0 days”
  ![image](https://user-images.githubusercontent.com/19801137/81047474-5fc09180-8eb2-11ea-9935-838bc5193387.png)

What should happen:
- The cell says “Ends today”
- The expanded cell says “Ends … — today”

[Spec updated](https://docs.google.com/document/d/1K65n3NpZCh7EWDXKLhG31seGJ2jKbW6lqw3BwV2mlnU/edit#heading=h.rg3wp4hc1rio).

[From review of #7310.]

**Comment by sowasred2012** [comment]
Closing, fixed in https://github.com/canonical-web-and-design/ubuntu.com/pull/7310
