### ISSUE TITLE
ubuntu raspberry pi instructions say they're for Windows 

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/ubuntu.com#7459]
I started here: https://ubuntu.com/download/raspberry-pi/thank-you?version=20.04&architecture=arm64+raspi

after downloading the 64bit ARM image for RPi4.

Then I clicked on the link for "Ubuntu Machines" in #2 in the "Installation Instructions" which says this:
Flash Ubuntu onto your microSD card
The first thing you need to do is take a minute to copy the Ubuntu image on to a microSD card by following our tutorials, we have one for Ubuntu machines, Windows machines and Macs.

Clicking on "Ubuntu image" led me here: https://ubuntu.com/tutorials/create-an-ubuntu-image-for-a-raspberry-pi-on-ubuntu#1-overview

which says at the bottom of page 1:
Please note
The following instructions are for Windows users. We also have tutorials for Ubuntu and MacOS users.

The instructions ARE the Ubuntu instructions, so they should not warn users that they are for Windows users.  If I click on either the "Ubuntu" or "MacOS" links in that note, the Ubuntu link just redirects to the same Ubuntu instructions that warns that the instructions are for Windows.  The MacOS link does work pointing to MacOS relevant instructions.

If I look at the MacOS instructions, the note on THAT page DOES redirect to the Windows instructions if you click on the Windows link in the note.

**Comment by pmahnke** [comment]
Thanks jeff.

I fixed the text on discourse.
