### ISSUE TITLE
CVEs: Add priority icons

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7474]
Thanks to @waynecrosby for producing icons for CVE priority. Here they are on the asset server:
- [Unknown](https://assets.ubuntu.com/v1/e85d00c8-CVE-Priority-icon-Unknown.svg)
- [Negligible](https://assets.ubuntu.com/v1/f6820eae-CVE-Priority-icon-Negligible.svg)
- [Low](https://assets.ubuntu.com/v1/2c18ab71-CVE-Priority-icon-Low.svg)
- [Medium](https://assets.ubuntu.com/v1/6d25e065-CVE-Priority-icon-Medium.svg)
- [High](https://assets.ubuntu.com/v1/a9a5dc21-CVE-Priority-icon-High.svg)
- [Critical](https://assets.ubuntu.com/v1/428a85f3-CVE-Priority-icon-Critical.svg)

These icons should be used in two places:
- in search results table cells, to the left of the CVE status text
  ![image](https://user-images.githubusercontent.com/19801137/81720848-df33ff00-9476-11ea-9317-36b15e211fbf.png)
- at larger size, in the “Priority” box on the page for an individual CVE.
  ![image](https://user-images.githubusercontent.com/19801137/81721130-4ce02b00-9477-11ea-995f-752394f3ea56.png)

**Comment by steverydz** [comment]
@matthewpaulthomas @spencerbygraves Here are some screenshots of the current status box with the icons added. In some cases the icons aren't legible on the grey background. Do you have any suggestions for this?

![cve_critical_priority](https://user-images.githubusercontent.com/501889/81798596-23231480-9508-11ea-9c49-5d701fe60a98.png)

![cve_high_priority](https://user-images.githubusercontent.com/501889/81798605-24ecd800-9508-11ea-98de-29f5701ab8f7.png)

![cve_low_priority](https://user-images.githubusercontent.com/501889/81798613-26b69b80-9508-11ea-9e62-7b529ec6ff36.png)

![cve_medium_priority](https://user-images.githubusercontent.com/501889/81798620-28805f00-9508-11ea-9392-663e989fce22.png)

![cve_negligible_priority](https://user-images.githubusercontent.com/501889/81798627-2a4a2280-9508-11ea-8233-37ede22a6d45.png)

![cve_unknown_priority](https://user-images.githubusercontent.com/501889/81798634-2c13e600-9508-11ea-8f28-7eeca27e6060.png)

**Comment by steverydz** [comment]
@matthewpaulthomas Do you know which icons relate to which status in the results table as the statuses in the data are:

- DNE
- needs-triage
- not-affected
- needed
- ignored

**Comment by spencerbygraves** [comment]
@steverydz I suggest we make the background white, and change the text to be more in keeping with @matthewpaulthomas' wireframes. I've used the muted heading and h4:

![image](https://user-images.githubusercontent.com/9105999/81813744-c03d7780-951f-11ea-9f2e-7aa0a9d16c44.png)

**Comment by matthewpaulthomas** [comment]
> In some cases the icons aren't legible on the grey background. 

In the wireframe I implied (but didn’t spell out, since I’m not a visual designer!) that the background of the box could be a pastel version of the colour used in the icon. Spencer’s suggestion of white would also work.

In the wireframe, and above, I also suggested making the icon much larger in this box than it is in results tables.

> Do you know which icons relate to which status in the results table

None of them relate to status. These icons are for priority, not status.

**Comment by steverydz** [comment]
@spencerbygraves Thanks. How does this look?

![cve_priority_critical](https://user-images.githubusercontent.com/501889/81816385-2aa3e700-9523-11ea-9906-d7e46a5ca466.png)

![cve_priority_high](https://user-images.githubusercontent.com/501889/81816389-2bd51400-9523-11ea-9b51-1650af000959.png)

![cve_priority_low](https://user-images.githubusercontent.com/501889/81816390-2bd51400-9523-11ea-85cf-a139b5925377.png)

![cve_priority_medium](https://user-images.githubusercontent.com/501889/81816393-2d064100-9523-11ea-9f84-52ca40c2f2e0.png)

![cve_priority_negligible](https://user-images.githubusercontent.com/501889/81816396-2d9ed780-9523-11ea-80bd-1d439568e703.png)

![cve_priority_unknown](https://user-images.githubusercontent.com/501889/81816397-2d9ed780-9523-11ea-92ff-eeee38e1ccb9.png)

**Comment by steverydz** [comment]
> None of them relate to status. These icons are for priority, not status.

@matthewpaulthomas OK understood, but as the table doesn't display priority I'm confused as to what I should display. There is the priority of the CVE for each row so does that mean we put that icon on each cell?

> in search results table cells, to the left of the CVE status text
   ![image](https://user-images.githubusercontent.com/19801137/81720848-df33ff00-9476-11ea-9317-36b15e211fbf.png)

**Comment by matthewpaulthomas** [comment]
Sorry @steverydz, I misunderstood your question. I hadn’t thought through there being only one priority for an entire CVE row group. (This was because the current tracker obscures this fact, and because I neglected to mock up a whole table with real data.)

Let’s try using the priority icon in cells of every status except for “Does not exist” (a.k.a. DNE) and “Not vulnerable” (a.k.a. not-affected). That will be quite busy for the two shown in your screenshot, but I think it will be much less busy for real data where most CVEs affect only one package and fewer releases.

**Comment by spencerbygraves** [comment]
Thanks @steverydz, that looks good.
