### ISSUE TITLE
Pagination missing page 6 when on page 3

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/ubuntu.com#7490]
When using the pagination, for example on the blog, if you go to the third page and there are more than 6 pages you will see that the 6th page is missing in the pagination. This appears to be an issue with the pagination template.

See: https://ubuntu.com/blog?page=3

![pagination](https://usercontent.irccloud-cdn.com/file/r1unTbEG/Screenshot%20from%202020-05-14%2014-44-13.png)

**Comment by anthonydillon** [comment]
No one ever goes to page 6 ... don't go there man!
