### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by kvv20** [canonical-web-and-design/ubuntu.com#7533]
https://ubuntu.com/tutorials/how-to-install-ubuntu-on-your-raspberry-pi

**Comment by pmahnke** [comment]
@kvv20 must be something temporary, I am getting the page

![image](https://user-images.githubusercontent.com/441217/82345562-51fc2780-99ed-11ea-820b-8998fff174dc.png)

Perhaps it is our cache, can you try again?

Thanks for reporting it.

Peter

**Comment by pmahnke** [comment]
@kvv20 actually Canonical is having some issues right now with websites, perhaps it is that.

**Comment by anthonydillon** [comment]
@kvv20 works ok for me

**Comment by RCMainak** [comment]
I can access the page as well if that helps :sweat_smile:

**Comment by tomponline** [comment]
Seems to be the topic picker affected, e.g. https://ubuntu.com/tutorials?topic=containers gives 500 for me

**Comment by pmahnke** [comment]
@tomponline I think it is all working again.

Sorry, some network issues yesterday.

**Comment by tomponline** [comment]
@pmahnke yep all good here now thanks
