### ISSUE TITLE
USN package links differ on old vs. new pages

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7542]
On the new USN pages, the packages listed are different from those on usn.ubuntu.com.

For example, for USN-4363-1:
- [the old page](https://usn.ubuntu.com/4363-1/) lists 22 packages in Ubuntu 18.04 LTS, and 15 in 16.04 LTS.
- [the new page](https://staging.ubuntu.com/security/notices/4363-1) lists only 6 packages in 18.04 LTS and 4 in 16.04 LTS.

[Originally reported by Mark Morlino.]

**Comment by jpmartinspt** [comment]
Fixed by https://github.com/canonical-web-and-design/ubuntu.com/pull/7665
