### ISSUE TITLE
Contact us modals not working

### ISSUE THREAD

**Issue by Khutch25** [canonical-web-and-design/ubuntu.com#7544]
Hello - It looks like the contact us modals are not appearing when contact us buttons are clicked. I have found it on are https://ubuntu.com/security/certifications & https://ubuntu.com/security/ so far, but also had @caldav check on his end and it looks like all are broken across u.c

---
*Reported from: https://ubuntu.com/security/certifications

**Comment by anthonydillon** [comment]
Thanks for reporting this, found the issue and its on its way to live now.

**Comment by Khutch25** [comment]
Awesome, thank you, Ant!
