### ISSUE TITLE
[new page] /what-is-k8s - design page and create assets

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#7551]
See the epic for details

**Comment by meralonso** [comment]
@SirSamTumless @pmahnke @spencerbygraves 

First draft attached. I wanted to get some feedback on how this is looking
I was also wondering if I need to recreate the visuals on the [copy doc](https://docs.google.com/document/d/19ZAsyujRHjOBIKP15F-4Z9L24KpfoYrx0YpL-0gO6sE/edit#) or someone else is providing those.

![K8s - what is K8s](https://user-images.githubusercontent.com/65166314/83511780-1b331080-a4c7-11ea-87de-9cb22a97ef33.jpg)

**Comment by pmahnke** [comment]
@meralonso a few comments:

- Looks pretty good overall, I think you must like Vanilla!
- You should draw the charts in the page, they are either old or done by the product manager
- I updated the copy doc to make the logo cloud more standard in the 'Kubernetes history and ecosystem' section.

**Comment by spencerbygraves** [comment]
Thanks @meralonso. The second section might benefit from some titles or icons if something could be suggested, like the second section [here](https://vanillaframework.io/).

I think the graphs will help to bring it to life a bit.

**Comment by meralonso** [comment]
@pmahnke @spencerbygraves thanks for the feedback. I'm attaching an updated version and still working on one diagram.
Missing logo in 'Kubernetes history and ecosystem' section - I googled FathomDB and got a message, apparently they're now part of another company? 
http://www.fathomdb.com/

![K8s - what is K8s_v2](https://user-images.githubusercontent.com/65166314/83645641-9d483580-a5aa-11ea-8ffc-3ad78cae4556.png)

**Comment by spencerbygraves** [comment]
Thanks @meralonso I think the icons in the second section look good. Perhaps we should use the Meteor logo instead of FathomDB, @pmahnke?

**Comment by meralonso** [comment]
@pmahnke @spencerbygraves design updated - let me know if you are happy with it.
Links will follow.

![K8s - what is K8s_v3](https://user-images.githubusercontent.com/65166314/83750609-7139bc80-a65d-11ea-8a9b-e8d100edbf51.png)

**Comment by pmahnke** [comment]
@meralonso looks nice.  @SirSamTumless do you want to see if Alex is ok with the diagrams?

**Comment by spencerbygraves** [comment]
Looks good @meralonso, thanks.

**Comment by meralonso** [comment]
**Assets below -**

[Kuberneters Logo](https://assets.ubuntu.com/v1/767f38a4-kubernetes-stacked-color.svg)

Icons
[Design and build](https://assets.ubuntu.com/v1/9fa25e69-Design+and+build.svg)
[Developer](https://assets.ubuntu.com/v1/061edebb-developer.svg) 
[Public cloud ](https://assets.ubuntu.com/v1/a33638f0-public-cloud.svg)

Other icons
[Orange tick](https://assets.ubuntu.com/v1/2ccda8d7-tick-orange.svg)
[Dark aubergine cross](https://assets.ubuntu.com/v1/9cdb5b1e-cross-darkaubergine.svg)

Diagrams
[Machine virtualization vs Containers](https://assets.ubuntu.com/v1/0a04f36f-diagram-machine-virtualization-vs-containers.svg)
[Enterprise Kubernetes ](https://assets.ubuntu.com/v1/26a8de44-diagram-enterprise-kubernetes.svg)

Logo cloud
[Canonical](https://assets.ubuntu.com/v1/5d6da5c4-logo-canonical-aubergine.svg)
[Huawei](https://assets.ubuntu.com/v1/80fe0ebe-Huawei-logo.svg)
[Fujitsu](https://assets.ubuntu.com/v1/5bd692e3-partner-logo-fujitsu.svg)
[ZTE](https://assets.ubuntu.com/v1/3abbe38f-zte_logo_en.png)
[Red Hat](https://assets.ubuntu.com/v1/82c62241-red-hat-2019-primary.svg)
[Mirantis](https://assets.ubuntu.com/v1/9c276e79-mirantis-logo-horizontal.svg)
[Core OS ](https://assets.ubuntu.com/v1/bc96d94b-CoreOS-logo.png)
FathomDB - As I mention before this is now part from another company.
