### ISSUE TITLE
ESM information on "Ubuntu release cycle" page does not match the (linked) Releases wiki page

### ISSUE THREAD

**Issue by OddBloke** [canonical-web-and-design/ubuntu.com#7566]
The current copy and second table in the "Maintenance and security updates" section strongly suggests that every LTS will have an additional 5 years of ESM. This is incorrect; per https://wiki.ubuntu.com/Releases, trusty and xenial will have only 3 years of ESM.

("**is** available for LTS releases since Ubuntu 12.04 LTS", emphasis mine, also suggests it's available for precise still, which hasn't been true for over a year now.)

---
*Reported from: https://ubuntu.com/about/release-cycle*

**Comment by pmahnke** [comment]
Thanks @OddBloke I have emailed Lech (the PM) about updating the text.

Hope you are well!

Peter
