### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Ynshndr** [canonical-web-and-design/ubuntu.com#7568]
Hi I'm installed ubuntu 20.04 my pc but I'm restart the pc nd not opening ubuntu it gets loading screen please help quick
---
*Reported from: https://ubuntu.com/desktop*

**Comment by SirSamTumless** [comment]
Hi, thanks for reaching out. This is the repo for ubuntu.com not the distro. 

If you could report a bug on Ubuntu at https://bugs.launchpad.net/ubuntu or ask your question on https://discourse.ubuntu.com you should receive a quick response.
