### ISSUE TITLE
Usabilla survey using default Usabilla styling

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/ubuntu.com#7582]
## Summary

The Usabilla survey currently live on https://ubuntu.com/advantage is using the default Usabilla styling which is not in any way coherent with the styling on the ubuntu.com website. 

As we are a paying Usabilla customer we can customise the "theme" displayed (e.g. MAAS uses the MAAS logo and colours, snapcraft - theirs). I believe the same should be done for this survey. 

In order to request a new theme, email support@usabilla.com and one of their team will assist - they tend to be quite quick.

Unrelated to the theme, I don't think the position of this survey on the page is good as it clashes with the much bigger LiveChat pop-up and the two are fighting for basically the same information from the user - do they have questions about the content. Maybe instead of a survey a better solution would be collaborate with the team handling the LiveChat requests and subtly rewording the message currently displayed there to capture richer information about the content? 

## Screenshot

![image](https://user-images.githubusercontent.com/17980375/83006362-0576a480-a00a-11ea-9d91-4b190c03cc3b.png)

**Comment by matthewpaulthomas** [comment]
Thanks for reporting this @lilyvidenova. When we realised on Friday that a custom theme would require liaising with Usabilla, the choice became (A) waiting until next week for @sowasred2012 to return or (B) collecting 10+ days more data with the default theme, so we chose (B). Now we can certainly make it more Vanilla. There’s a small risk that changing the goofy emoticons will alter the distribution of people’s choices, but eh.

It’s also a problem that the Usabilla and Livechat popups clash, though they serve quite different purposes. In my testing, the Usabilla popup did not — and still does not — appear until I have minimised the Livechat popup. In your screenshot both are open at once. Did you reopen the Livechat manually, or do you have steps to reproduce them opening simultaneously? We might be able to fix that short-term, while working on whether it makes sense to combine them.

**Comment by lilyvidenova** [comment]
Both open on their own @matthewpaulthomas.

**Comment by sowasred2012** [comment]
@lilyvidenova @matthewpaulthomas Just a quick note - I did fill out the theme creation form with a view to getting a conversation started with them about custom styling. I haven't seen an email from them, so I'll follow up on that when I'm back on Monday.

**Comment by anthonydillon** [comment]
If Usabilla sets a cookie we should add that to the cookie information on ubuntu.com.

**Comment by sowasred2012** [comment]
@matthewpaulthomas @lilyvidenova finally had a reply from Usabilla on Tuesday (an 11 day turnaround), they've requested I send the font file we want to use, but I wanted to check whether you had other customisations you wanted to make before I reply. This is how the theme - which isn't live yet - currently looks:

![Screenshot from 2020-06-04 11-11-33](https://user-images.githubusercontent.com/2376968/83744928-ba394300-a654-11ea-8f4e-787b6602832d.png)

**Comment by sowasred2012** [comment]
@matthewpaulthomas @lilyvidenova bumping to get feedback - if there isn't any, I'll respond to the Usabilla contact with the font file and close this issue out.

**Comment by lilyvidenova** [comment]
Can we include the Ubuntu logo as well, please?

**Comment by matthewpaulthomas** [comment]
Sorry I missed this last week. I’d like:
- faces — more professional, less goofy
- font — Ubuntu
- button colour — Vanilla white with dark-grey border
- link colour — Vanilla blue

To me, the first one is the most important, but it will also take the longest, if we have to provide our own icons. Do we? If so, I’ll write a brief for Wayne.

> Can we include the Ubuntu logo as well, please?

That could make it look more official, at the expense of adding noise. One way to think about it: If we replaced LiveChat with a home-grown chat function, would that UI contain an Ubuntu logo as well?

Searately, if it is (or will be) used on snapcraft.io with the same theme, it shouldn’t be Ubuntu-branded.

**Comment by sowasred2012** [comment]
I could ask them to create a second theme that doesn't have the ubuntu logo, but has everything else - I'll get back to them with this feedback now. We would have to provide our own faces (gotta be a better way of wording that), I'll ask them for any requirements before you brief Wayne.

**Comment by sowasred2012** [comment]
@matthewpaulthomas just had the requirements for icons back from my Usabilla contact:
> We'll need a PNG image of 300x60 pixels (each smiley being 60x60 pixels), containing all 5 smilies aligned right next to each other like so:
> ![unnamed](https://user-images.githubusercontent.com/2376968/84259769-de8f9680-ab10-11ea-8274-9e07b992def5.png)

**Comment by matthewpaulthomas** [comment]
“Privacy Policy” is not in the Ubuntu font, and I don’t understand the use case for including the Ubuntu wordmark. Apart from that and the faces, it looks okay.

I’ve submitted [a brief](https://docs.google.com/document/d/1an3SE2xcq9le8FaeI5uL25A3ZD9JO5fc5gIotA8FVkM/edit) to @waynecrosby for classier faces.

**Comment by sowasred2012** [comment]
@matthewpaulthomas I beg your pardon - I had updated the link font, but something clearly got lost. Updated versions:
![Screenshot from 2020-06-11 17-06-40](https://user-images.githubusercontent.com/2376968/84410838-03b20100-ac06-11ea-9596-8f01fdacbffe.png)
![Screenshot from 2020-06-11 17-07-02](https://user-images.githubusercontent.com/2376968/84410847-044a9780-ac06-11ea-9cad-cdd9cdcc1864.png)

**Comment by sowasred2012** [comment]
Closing, whenever we choose to implement that mood input, they will have custom smilies.
