### ISSUE TITLE
Investigate performance of FB pixel 

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/ubuntu.com#7583]
The FB pixel causes significant perf issues when compared to all other assets loaded on the site - is there any way to make this more performant?

**Comment by pmahnke** [comment]
Based on https://developers.facebook.com/docs/facebook-pixel/advanced#installing-the-pixel-using-an-img-tag, I have removed the javascript portion of the facebook pixel to see if it improves page performance.
