### ISSUE TITLE
TemplateNotFound: templates/_navigation-enterprise-h.html

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/ubuntu.com#7592]
https://sentry.is.canonical.com/canonical/ubuntu-com/issues/8009/?referrer=github_plugin

```
TemplateNotFound: templates/_navigation-enterprise-h.html
(9 additional frame(s) were not displayed)
...
  File "webapp/app.py", line 216, in <lambda>
    flask.render_template(f"templates/{filename}.html"),

TemplateNotFound: templates/_navigation-enterprise-h.html
```

**Comment by tbille** [comment]
This issues came from discourse pulling templates that were renamed recently.
This implied that the discourse navigation wasn't working anymore.

Updated navigation code to pull the right files (no _ anymore).

**Comment by anthonydillon** [comment]
We need to resolve templates with 400's.
