### ISSUE TITLE
UA renewals: 3DS “incomplete_expired” after 24 hours

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7604]
From Allan Vidal:
> One more thing to test: if 3DS authentication is needed, and the user does not confirm in 24h, the subscription status will become "`incomplete_expired`", in which case you should not reattempt to pay the existing invoice (it will be voided), but instead, you should call the accept endpoint again to trigger the creation of a new subscription. Yes, testing this will require leaving it be overnight :)

**Comment by alnvdl** [comment]
These are two issues. The other one is required for proper invoicing. I opened it at #7609 .
