### ISSUE TITLE
UA renewals: We send people to /advantage for subscriptions not renewable there

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7605]
From Francesco:
> Marketing will send an email for all expiring contracts (tech touch) pointing to the web page. In there, [n]ot all renewals will be actionable. Non-actionable renewals require manually contacting sales. Right now, non-actionable renewals are completely hidden. We should instead suggest how to renew.

**Comment by matthewpaulthomas** [comment]
I replied:
> We should certainly explain, on /advantage, if there is any subscription shown there that you can’t renew there. What would be our explanation?
>
> But we should not mail customers telling them to renew by going to a page where, in fact, they can’t. That would just annoy them for no reason. Instead we could give them the sales contact info directly in the mail message.

**Comment by matthewpaulthomas** [comment]
From discussion with Uros:
- The number of non-renewable subscriptions is very small
- It would be much more difficult to fix this in the e-mail than on the Web page.

So we can address this just on the Web page, but we can apologise for not providing renewal there (regardless of whether we promised it in the e-mail or not), and provide the phone numbers.

@meralonso Could you have a go at how to present this info in the expanded cell? Scott can give you a screenshot of how the cell looks now. We’d need to add:

- Text something like “Sorry, this subscription can’t be renewed online. Please call us:”

- The phone numbers (@wgx suggested that we make them `tel:` links):
  - United States +1 737 2040291
  - United Kingdom +44 203 656 5291
  - Germany +49 61512746816
  - Spain +34 932201131
  - France +33 184889319
  - Japan: +81-3 6205 3075

**Comment by sowasred2012** [comment]
@meralonso @matthewpaulthomas here's the requested screenshot:

![Screenshot from 2020-06-01 15-29-48](https://user-images.githubusercontent.com/2376968/83419479-09952e80-a41d-11ea-84a1-8f83f08f63f1.png)

**Comment by matthewpaulthomas** [comment]
Thanks! @meralonso So in this situation, we’d have the text and phone numbers instead of the “Renew…” button. The tricky thing is how to lay it out in alignment with the date info.

**Comment by meralonso** [comment]
Thanks @sowasred2012 

@matthewpaulthomas I had some initial idea, please let me know your thoughts or if you want to have a chat.

I was wondering if we should add a column including 'Hours of operation' of each country, or maybe is not relevant in this case.

![Group 9](https://user-images.githubusercontent.com/65166314/83426003-6f39e880-a426-11ea-97fd-a864317fd883.png)

**Comment by matthewpaulthomas** [comment]
@meralonso The expanded cell should still look visually connected to the original cell, and it should still contain the “Created on:” and “Ends:” info shown in Scott’s screenshot. The apology and phone numbers are a replacement for the “Renew…” button, not a replacement for anything else.

I can see why you wouldn’t want to use an error notification — too alarming — but I’m not sure it’s appropriate to use a caution notification either. From our POV it’s an error state, but from the customer’s POV it’s just an instruction for how to achieve the renewal.

**Comment by meralonso** [comment]
@matthewpaulthomas I created a couple of versions for you to review. I have used the blue info icon so it's not as alarming for the users - what do you think?

right aligned
![UA renewals-2](https://user-images.githubusercontent.com/65166314/83507135-099a3a80-a4c0-11ea-9636-eb36e38828d9.png)

full width including office times. I have put 24hrs as a placeholder, I'm waiting for Thibaut's answer.
![UA renewals-3](https://user-images.githubusercontent.com/65166314/83507138-0b63fe00-a4c0-11ea-9143-e7a547511365.png)

**Comment by sowasred2012** [comment]
Adding my two cents -  I like the full width version, although Vanilla has [an "information" notification](https://vanillaframework.io/docs/patterns/notification#information) we could use out of the box, it's just a darker blue. We wouldn't necessarily need to have an icon in the notification, and could leave the warning triangle next to "Ends"?

Also - I know Martin mentioned changing the background of the expanded row, I'd be happy to include that as part of the PR for this if there's consensus.

**Comment by meralonso** [comment]
@sowasred2012 @matthewpaulthomas check these new versions.
I asked Thibaut about the opening hours - he said "they'll vary especially right now where we're not office based. Wondering if this is not setting the wrong expectation?
We have voicemail if no one picks up the phone." 

![UA renewals-4](https://user-images.githubusercontent.com/65166314/83539188-a7a4f980-a4ee-11ea-8897-cc087197e4fb.png)

![UA renewals-5](https://user-images.githubusercontent.com/65166314/83539255-b68bac00-a4ee-11ea-9509-ada319f7f24c.png)

**Comment by matthewpaulthomas** [comment]
Thanks @meralonso. If there are no office hours, there’ll be only two columns in the table. That would mean:
- a full-width table would look stretched
- a left-aligned or right-aligned table (as shown above) would make the overall cell lopsided
- on the positive side, it would be simple enough that we don’t need column headers.

So, maybe we could just align the numbers with the existing data? What do you think?

![phone-numbers](https://user-images.githubusercontent.com/19801137/83541020-ffdcfb00-a4f0-11ea-8ec1-c25239950455.png)

With that alignment, we wouldn’t need row borders either, because each country is very close to its number.

I have no opinion on changing the colour of the expanded row — but I don’t think it should happen in this PR, because this is urgent, whereas that would require checking for grey text in every state of every expanded column.

**Comment by sowasred2012** [comment]
@meralonso @matthewpaulthomas how's this?
![Screenshot from 2020-06-02 17-32-56](https://user-images.githubusercontent.com/2376968/83545438-20a84f00-a4f7-11ea-9285-4cbe9c1ce95b.png)

**Comment by wgx** [comment]
![lefty](https://user-images.githubusercontent.com/65166314/83539188-a7a4f980-a4ee-11ea-8897-cc087197e4fb.png)

This one, left aligned makes sense to me. Left-aligned is easier to scan and read than centered so I'd reccommend this one.

**Comment by sowasred2012** [comment]
@wgx @meralonso I'm happy to go with that one if we're all in agreement?

**Comment by spencerbygraves** [comment]
I think it would be best to go with the left aligned table version for now. There is an outstanding [Vanilla issue for key value pairs](https://github.com/canonical-web-and-design/vanilla-framework/issues/2848), so that design hasn't been properly resolved yet. Thanks.

**Comment by anthonydillon** [comment]
You can mostly achieve that style via a table: https://codepen.io/anthonydillon/pen/jGXyqo

**Comment by clagom** [comment]
On top of this particular issue, we are adding a table within a table here... it looks like an expanding table is then hard to scale. I would also encourage some parallel explorations for another interaction, instead of accordion expanding cells?

**Comment by cassiocassio** [comment]
- I can go with the left aligned table today, but it's a little unlovely...

- the hours would indeed be useful (and make the design more balanced)  - so +1 go with that today, add the hours when we get them?

- The Right aligned key / left aligned value pair pattern **#2848** has been super useful when used carefully in the maas machine details page, where the user recognises the data from it's format, eg. hostname, IP number - they look like what they are... and the label should receed

- here, the challenge is to 1st find the country, and then read the number, so that key value pattern is solving a different need

- to zoom out a bit, the whole page is challenging in terms of layout: we're asking the user's eye to do this dance:

1. start at the logo
2. see the big headline, 3. subhead
4. be caught by the warning icon
5. jump to the bold created on date
6. then see the bar on the info box
7. then jump to the blue link phone numbers

Mixing Left alignment and Center alignment always stores up trouble. I say Ship this, given the date,  but plan to revisit as part of the broader UA work. 

<img width="1361" alt="Screenshot 2020-06-03 at 12 13 12" src="https://user-images.githubusercontent.com/4593556/83630629-0cfef600-a594-11ea-86a5-a1f0df2b92e2.png">
