### ISSUE TITLE
UA renewals: 500 after trying new payment method

### ISSUE THREAD

**Issue by alnvdl** [canonical-web-and-design/ubuntu.com#7610]
If you try to pay with a 3DS-required card (`4000000000003220` or `4000002760003184`), and you do not authorize, and then change the payment method to something else in the same dialog, the renewal is eventually completed, but the first attempt at checking the invoice status fails with a 500 error (`json.decoder.JSONDecodeError`). This error does not seem to surface to the user, and it doesn't seem to have any practical effect.

**Comment by anthonydillon** [comment]
@alnvdl I followed your steps and it worked for me? Can you still replicate this error?

**Comment by steverydz** [comment]
I can't replicate this either.

**Comment by matthewpaulthomas** [comment]
@alnvdl Please reopen if you have updated steps to reproduce the problem.
