### ISSUE TITLE
UA renewals: inconsistent behavior involving payment retries

### ISSUE THREAD

**Issue by alnvdl** [canonical-web-and-design/ubuntu.com#7617]
An attempt is being made to pay for invoices even when the first attempt just failed. This should not be done, as Stripe will attempt to collect payment automatically when you accept a renewal.

You should only reattempt payment if the renewal is `processing` and has a payment issue (e.g., subscription is `incomplete` and invoice `requires_payment_method`) and the user explicitly tells you to retry payment (meaning they changed something). Right now, this seems to be done automatically whenever the first condition is met (`processing` + `incomplete`).

Related to this, if the customer had input an invalid payment method (e.g., 4000000000000341) and then changes this to a valid one (4242424242424242), Stripe will NOT automatically retry the payment (which is fine). But then you call the `process-payment` method again, which first accepts the renewal again (it shouldn't, it causes a 400 error, as renewal can only be accepted once; this is harmless however), and then reattempts to pay for the invoice twice. The first attempt succeeds, but the second one fails. I'm not sure why these two attempts happen, but it seems to be happening every time.

**Comment by SirSamTumless** [comment]
@sowasred2012 Does this still need a fix?

**Comment by sowasred2012** [comment]
This will be fixed with the shop PR, so I'll close this.
