### ISSUE TITLE
UA renewals: started renewals presentation could be improved

### ISSUE THREAD

**Issue by alnvdl** [canonical-web-and-design/ubuntu.com#7618]
Due to a mistake on my side, I ended up creating a renewal that failed to be accepted (due to a missing tax rate ID). However, I noticed `started` renewals are not being presented, and I believe there's room for improvement.

Ideally, they should be shown with the same label as renewals in `processing`, and if it's `started` and the `lastModified` field is older than, say, 1 hour, it should suggest that the user seeks help from support, as it's probably a problem on our side.

**Comment by sowasred2012** [comment]
Fixed by https://github.com/canonical-web-and-design/ubuntu.com/pull/7651
