### ISSUE TITLE
UA Renewals: VAT handling

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#7619]
Allan recently introduced VAT to transactions in ua-contracts, and he's explained a problem that we need to decide how to handle:

> After implementing taxes as Carla instructed us, there's now an inconsistency between what's shown in the web interface (the total renewal value) and the value that the customer ends up being charged, which depends on their country's VAT rate.
> 
> For example, this customer was told that they would be charged 1500 USD, but ended up being charged 1845 USD:
> https://pay.stripe.com/invoice/acct_1GH9uHCzjFajHovd/invst_HO9IfVUrvLR1jejvRFLeXHK8KFZrDix/pdf
> 
> This issue affects:
> 1. Customers in the EU who do not provide a VAT (e.g., non-company customers)
> 2. All customers in the UK.
> 
> There are several ways we could solve this:
> 1. The easiest and most straightforward for now: add a notice to the web interface that says "VAT may apply and may be automatically charged depending on your country rates. See [link to the EU VAT rate page].".
> 
> 2. Have us implement an endpoint that calculates the total value of a renewal in ua-contracts, or at least one that tells the web interface what rate will be charged and let them do the math.

Uros suggests going with option 1 in the immediate short term, and option 2 soon after.

**Comment by sowasred2012** [comment]
My gut feeling is it doesn't inspire confidence to suggest to a user that the figure we're presenting them could be incorrect and, if it is, that we'll be charging them an unspecified (larger!) amount, even if it's only a short term solution. @matthewpaulthomas what do you think?

**Comment by matthewpaulthomas** [comment]
If this needs releasing tomorrow, I think it’s reasonable to just add “Excluding VAT” below the total:

![image](https://user-images.githubusercontent.com/19801137/83509140-e3c26500-a4c2-11ea-93f1-501edbd4c726.png)

Later we can replace it with a separate row, above the total, giving the precise VAT amount.
