### ISSUE TITLE
UA purchase: Implement VAT validation and total

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7647]
Currently when you renew a UA subscription, in a country that has VAT, the dialog just says “Excluding VAT”.

Now that we have more time, we should make this more informative by showing:
- the VAT rate in your country
- the resulting VAT amount
- the total to pay including VAT.

[This is the sequel to #7619.]

**Comment by matthewpaulthomas** [comment]
Before | After
-|-
![image](https://user-images.githubusercontent.com/19801137/85228376-074e4080-b3db-11ea-86b8-2711a569a9db.png) | ![renewal-dialog-normal](https://user-images.githubusercontent.com/19801137/85228490-8ba0c380-b3db-11ea-895a-202485825e5e.png)

**Comment by wgx** [comment]
👍  looks good to me

**Comment by SirSamTumless** [comment]
Blocked by Urosh.

**Comment by sowasred2012** [comment]
Moving this to the shop epic. In 23/06/20 UA dashboard meeting, Uros said that his aim was to get this implemented by the end of July, ready for the shop launch.
