### ISSUE TITLE
Bad downloading speed.

### ISSUE THREAD

**Issue by Ummamali** [canonical-web-and-design/ubuntu.com#7658]
Location: Islamabad, Pakistan.
Hello, I am trying to download ubuntu desktop from 'isra' repository, but average download speed is 10 KB/sec.
Servers are also not responding.
But its doing great with your servers : releases.ubuntu.com
Hope you solve the problem.
 

---
*Reported from: https://ubuntu.com/*

**Comment by anthonydillon** [comment]
Thank you for taking the time to report this issue to us @Ummamali. We will review the mirror and see what the next steps will be: http://repo.isra.edu.pk/ubuntu/.

**Comment by anthonydillon** [comment]
RT has been raised: https://portal.admin.canonical.com/126244
