### ISSUE TITLE
[Whitepaper] Redhat comparision] - Build takeover and engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#7666]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1DMozJ7XFMOFppwEOADCq52uSryWAVYqS4sdGyq9Mpkc/edit#gid=0") and [design](2734):
 
- [x] build takeover
- [x] build engage page
- [x] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [x] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by steverydz** [comment]
Waiting on PDF

**Comment by SirSamTumless** [comment]
https://pages.ubuntu.com/rs/066-EOV-335/images/Comparing%20OpenStack_24.07.20.pdf

Link to the PDF above
