### ISSUE TITLE
a small mistake

### ISSUE THREAD

**Issue by Aexis-Tenax** [canonical-web-and-design/ubuntu.com#7669]
webpage
https://ubuntu.com/tutorials/tutorial-upgrading-ubuntu-desktop#3-check-for-updates
it says "update-manger -d", instead of "update-manAger -d"
IT woeks great though
Thanks

**Comment by fitojb** [comment]
It seems to be fixed already; I couldn’t find the typo.

**Comment by pmahnke** [comment]
Yes, this must have been fixed on discourse.

Thanks for reporting and looking.

**Comment by Aexis-Tenax** [comment]
No problem, glad I could help with the litle I know of Linux (more or less zero :-) ).
A question: is it possible to make a donation to Ubuntu from Switzerland? And if the answer is "yes", which would be the IBAN number, or the account to not make a mistake and send the money to other "person", be it moral or physicsal?
Thanks in advance for your time.
I've passed to Ubuntu exactly because of it's amazing community. One of my best choices, I think.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
