### ISSUE TITLE
UA purchase: A/B test ubuntu.com vs. buy.ubuntu.com

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7673]
Before the UA shop on ubuntu.com is built:
- Start measuring the average revenue per visitor for buy.ubuntu.com.

Once the UA shop on ubuntu.com is built:
- Start measuring the average revenue per visitor for buy.ubuntu.com.
- Redirect a percentage of people visiting buy.ubuntu.com/ to ubuntu.com/advantage instead.

Once we have results:
- If ubuntu.com does better, increase the percentage, eventually to 100%.
- If buy.ubuntu.com does better, back off until we can implement more granular funnel measurement.

**Comment by sowasred2012** [comment]
@matthewpaulthomas re: sales per customer on buy.ubuntu.com - this is already being tracked by Shopify's built in analytics, and that's what the sales team uses for reporting (as opposed to GA, where there can be discrepancies).

The data can be filtered by date, and exported whenever we want - so I don't think there's any further action to be taken on this issue before we start building the new shop.

**Comment by matthewpaulthomas** [comment]
@sowasred2012 Thanks for researching that. Meanwhile, I realised what will probably be a big disparity: buy.ubuntu.com lets you go through the whole purchase process without an Ubuntu One account! If we require you to create an account during the purchase process, our dropoff could be much bigger than buy.ubuntu.com, for that reason alone. How to tackle this is part of [web-squad#2788](https://github.com/canonical-web-and-design/web-squad/issues/2788).
