### ISSUE TITLE
UA purchase: Build /advantage changes to handle all Ubuntu versions

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7674]

**Comment by lechsandecki** [comment]
I started working on it here:
https://docs.google.com/spreadsheets/d/1krXNNq1BkZCDSJeTARteLxZpylCep6jG6KmUBMA8RwA/edit#gid=0

**Comment by matthewpaulthomas** [comment]
Ubuntu 16.04 LTS or 18.04 LTS users shouldn’t be given instructions that won’t work. So we recognised implementing this was a blocker for (A) promoting /advantage as a way to purchase UA, and (B) adding /advantage to the ubuntu.com navigation. Unfortunately we didn’t recognise that it should also have been a blocker for (C) people visiting /advantage to renew an existing subscription.

At least one customer has now been confused by this. So I think this is now High priority and no longer shop-specific.
