### ISSUE TITLE
Miro/Canonical logo final artwork

### ISSUE THREAD

**Issue by marcushas** [canonical-web-and-design/ubuntu.com#7679]

**Comment by SirSamTumless** [comment]
@cassiocassio Could you please provide feedback ASAP

**Comment by anthonydillon** [comment]
If there was a link to review you might get quick feedback.

**Comment by SirSamTumless** [comment]
@anthonydillon We're waiting on a review form Martin who we've emailed, assigned here and chased on Telegram.

**Comment by anthonydillon** [comment]
@SirSamTumless completely understand the state just starting it would be better if someone dropped a link here and then asked for a link. Chasing via email and telegram should be last resort.

**Comment by waynecrosby** [comment]
@Anthony Dillon <anthony.dillon@canonical.com> Good shout, I'll drop a link
in here

**Comment by waynecrosby** [comment]
@cassiocassio You can access Miro designs here: https://miro.com/welcomeonboard/ihiQkyiKOKWn98VpaUj9RhRUmLqT9WPgaSjzwLh9uehgNXVpSJkGY3ecNF0ak3QU
