### ISSUE TITLE
Raspberry Pi 4 image for 18.04

### ISSUE THREAD

**Issue by Lacan82** [canonical-web-and-design/ubuntu.com#7699]
https://ubuntu.com/download/raspberry-pi

list image for Rpi4 64 bit not compatible.
downloading an flashing the image provided for 18.04 is not compatible with the RPi4 for it complains about the start4.elf

**Comment by pmahnke** [comment]
@Lacan82 this repo is for the website, not the images; however, I have emailed the release team so see if they know anything.

**Comment by Lacan82** [comment]
Yes it is for the website. If you look at the link on the site it is also referring Rpi3. On the Pi 4 link.

**Comment by Lacan82** [comment]
@pmahnke Yes it is for the website. If you look at the link on the site it is also referring Rpi3. On the Pi 4 link.

**Comment by pmahnke** [comment]
@Lacan82 I got this back from the team:

> We're testing all device combinations on release day, so I'd say this is some user error/confusion. I'll poke Dave to take a look just-in-case, but the Pi4's are a main target for our images.

Also, on over the last two weeks all images have been updated.  And we have sym links so the iso has the numbers in the names or no numbers.

**Comment by Lacan82** [comment]
There is zero user error or confusion 18.04 has the wrong boot loader. 20.04 works. Literally download image burn it using raspberry pi image tool to a new sd card. It the says start.elf is not correct and will not boot into os. Stating I need to download the newest firmware to use the image. Be glad to record a video of the whole process.

**Comment by pmahnke** [comment]
@Lacan82 so someone tested again and it worked, but they asked:

> So I'm wondering which image they used, and also which device, so that we can try to recreate this more accurately.

**Comment by Lacan82** [comment]
Since the link has been updated the correct image is now downloading. Which has the correct boot loader. I was downloading the Rp4 64 bit, but as I stated the link was pointing to rp3 originally.
