### ISSUE TITLE
Update seconary navigation under /appliances

### ISSUE THREAD

**Issue by rhys-the-davies** [canonical-web-and-design/ubuntu.com#7702]
Hello o/ 

The menu in this demo is now outdated while the rest is getting updated. The correct words and order is here: https://github.com/canonical-web-and-design/ubuntu.com/issues/new?body=%0a%0a%0a---%0a*Reported%20from:%20https://ubuntu-com-canonical-web-and-design-pr-7454.run.demo.haus/appliance* 

and also in any of the other copy docs with the same banner. 

---
*Reported from: https://ubuntu-com-canonical-web-and-design-pr-7454.run.demo.haus/appliance*

**Comment by anthonydillon** [comment]
This has been done
