### ISSUE TITLE
/advantage: List of UA services doesn’t include Landscape

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7718]
All Ubuntu Advantage subscribers get access to Landscape. When they subscribe, they receive a message saying “If you are a new customer, you will receive emails from noreply@canonical.com with an invitation to become an administrator of your Landscape account…”

This makes sense only if you know what Landscape is. Currently buy.ubuntu.com mentions Landscape, but /advantage does not. If this is not changed, once buy.ubuntu.com is retired, it will be possible for someone to buy UA and then be confused by the mention of Landscape.

---
*Reported from: https://ubuntu.com/advantage*

**Comment by pmahnke** [comment]
@matthewpaulthomas is this a reminder for you to do this work?

**Comment by SirSamTumless** [comment]
@lechsandecki Can you check to see if you agree with this and if you do, update the copy doc.

**Comment by matthewpaulthomas** [comment]
@pmahnke I’ve expanded the report to explain the problem further.

**Comment by lechsandecki** [comment]
yes, I agree.  thanks for pointing that out
Looking at the copy doc - it seems that this job would be more complex than
just a doc update:
https://docs.google.com/document/d/1AW8wQu1Uvq0xFtd_c2JwNdic075MPOTx7k2KHqFPPeo/edit#heading=h.2p4jyl34ww3l

**Comment by wgx** [comment]
Easy part: adding Landscape to the logged-out comparison table: https://docs.google.com/document/d/1AW8wQu1Uvq0xFtd_c2JwNdic075MPOTx7k2KHqFPPeo/edit?disco=AAAAGqmgBe8

**Comment by wgx** [comment]
Less easy part: add Landscape to the table of subscriptions, and, if not installed, show this help panel:

![image](https://user-images.githubusercontent.com/930099/85699740-af158800-b6d3-11ea-8373-6ad511cccfd2.png)

**Comment by matthewpaulthomas** [comment]
This is a good start. A small issue is that it’s quite different from the layout of the other expanded cells. Probably it could be more similar.

A much bigger issue is that currently, from /advantage, we have no way of telling whether you have Landscape installed. (I imagine it would be pretty hard to implement, given that the contracts service doesn’t manage Landscape.) And even if we did know, you might have it installed on some machines and not others. So we probably shouldn’t provide an imperative instruction as if you don’t have it installed.

I think there are three things we should help you do here:
1. Get your Landscape account in the first place. According to [the message we looked at yesterday](https://miro.com/app/board/o9J_kr5Ty8s=/?moveToWidget=3074457348350641839&cot=3), that involves reading a message you received from noreply@canonical.com. So maybe let’s provide a button for resending it.
2. Register a computer (the Landscape equivalent of `ua enable`), including installing Landscape on that computer.
3. Actually use Landscape, once your computers are registered.

Unfortunately, (2) has a complication. Once you are signed in on landscape.canonical.com, there’s a prominent link for registering:

![image](https://user-images.githubusercontent.com/19801137/85832382-e2b1ea00-b787-11ea-85d1-71a43eb9b9c5.png)

But the URL of that link includes your account name, which we don’t know here, so we can’t link to it! The best we can do is invite you to sign in to Landscape. As seen in the Landscape navigation bar, the URL for that is https://landscape.canonical.com/login/authenticate.

That URL also takes you to the Landscape UI if you are already signed in, so you might be able to combine (2) and (3) into a single instruction: “To register a computer and access Landscape:” or something like that. Or it might be clearer to keep them separate, even though they go to the same place.

**Comment by lechsandecki** [comment]
FYI here are emails that are sent to new UA customers, incl. email on how
to activate landscape.
https://docs.google.com/document/d/17FhJSQg0yQqOHF1FkJx8uNPwXW2zlw2azwRoLs0Veng/edit?ts=5ef4bbb5#heading=h.a838nekhhr2e

**Comment by wgx** [comment]
![image](https://user-images.githubusercontent.com/930099/85860977-7fd84700-b7b7-11ea-8ae0-177bd11f4217.png)

Might need @meralonso to make it look prettier, but here is a wireframe.

**Comment by matthewpaulthomas** [comment]
Thanks @wgx. [Spec updated](https://docs.google.com/document/d/1K65n3NpZCh7EWDXKLhG31seGJ2jKbW6lqw3BwV2mlnU/edit#heading=h.o9au2lkx2w4j).

I made a couple of tweaks:
- split the first line in two, so that we can help you find the message by displaying the address that we’re about to send it to
- specified what should happen when you choose resend (show “✔ Sent” alongside).

Now ready for implementation.

**Comment by meralonso** [comment]
@matthewpaulthomas @wgx Do you guys need me to make it look pretty?

**Comment by wgx** [comment]
@matthewpaulthomas  👍  from me

**Comment by anasereijo** [comment]
@wgx I think we can close this, right?
