### ISSUE TITLE
Cant download  ISOS

### ISSUE THREAD

**Issue by Moratorro** [canonical-web-and-design/ubuntu.com#7726]
Hi

Im trying to download the server iso but i get this
![image](https://user-images.githubusercontent.com/35039632/84408146-05a99f00-abc9-11ea-9eec-292c53aadff6.png)

thanks!

**Comment by fonseca-leonardo** [comment]
Same problem here!

**Comment by anthonydillon** [comment]
Thank you for reporting this issue to us. We are working on fixing this now.

**Comment by shiblee86** [comment]
Same problem here.

**Comment by anthonydillon** [comment]
Fix has been merged and it going live now.
