### ISSUE TITLE
Ubuntu desktop download not available now

### ISSUE THREAD

**Issue by SaidBenaissa** [canonical-web-and-design/ubuntu.com#7727]
https://ubuntu.com/download/desktop/thank-you?version=20.04&architecture=amd64

500: Server error
Something’s gone wrong.

Try reloading the page. If the error persists, please note that it may be a known issue. If not, please file a new issue.

**Comment by sowasred2012** [comment]
Thanks for reporting - this has now been fixed as part of https://github.com/canonical-web-and-design/ubuntu.com/issues/7726
