### ISSUE TITLE
can't download ubuntu

### ISSUE THREAD

**Issue by anishghimire603** [canonical-web-and-design/ubuntu.com#7728]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

500: Server error
Something’s gone wrong.

## Browser details

https://ubuntu.com/download/desktop/thank-you?version=20.04&architecture=amd64

**Comment by sowasred2012** [comment]
Thanks for reporting - this has now been fixed as part of https://github.com/canonical-web-and-design/ubuntu.com/issues/7726
