### ISSUE TITLE
[COPY UPDATE] desktops - "Ubuntu Advantage for Desktop"

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#7747]
Please update desktops - "Ubuntu Advantage for Desktop" from the [copy doc](https://docs.google.com/document/d/1Ypf66YyJfsch-jJgVkRpYLv2XnDdvumvFLqSUAhZyMY/edit?usp=drivesdk)

**Comment by sowasred2012** [comment]
Closing - it's CMS content, so no PR necessary.
