### ISSUE TITLE
CVEs: 404 error on usn.ubuntu.com links because of ?_ga=…

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7766]
1\. Go to [staging.ubuntu.com/security/cve](https://staging.ubuntu.com/security/cve).
2\. Follow any CVE link.
3\. Scroll to the bottom and click the usn.ubuntu.com link.

What happens: You get [a 404 error](https://usn.ubuntu.com/usn-4315-1?_ga=2.110046213.1484319780.1592118763-172698722.1590142628).

What should happen: You’re taken to a USN page.

This seems to happen because Google Analytics attaches a `?_ga=` parameter to the link URL, and usn.ubuntu.com doesn’t strip or ignore that parameter.

**Comment by steverydz** [comment]
@matthewpaulthomas this doesn't seem to be a problem with the query string as it still 404s if you remove it.

@nottrobin @jpmartinspt do you know why these pages aren't working?

**Comment by pmahnke** [comment]
it links to /usn-4318-1, but the link on usns is /4318-1

**Comment by jpmartinspt** [comment]
@pmahnke is right, we were asked to include the `USN-` prefix as part of the ID since there can be different prefixes.

**Comment by nottrobin** [comment]
@jpmartinspt but the live links 404. If we're gonna link to usn.ubuntu.com we have to use actual links that don't 404. The solution to them wanting a "usn-" prefix in the URL is presumably not to simply create a 404ing link...

**Comment by nottrobin** [comment]
I'll look into this when I get a sec.

**Comment by nottrobin** [comment]
This is a bug in the way usn.ubuntu.com is redirecting URLs, because of the `?ga` query string as @matthewpaulthomas suggested.

The fix is here: https://code.launchpad.net/~usn-website-team/usn.ubuntu.com/+git/usn.ubuntu.com-1/+merge/385965

**Comment by nottrobin** [comment]
Fix merged and released, this is now fixed.
