### ISSUE TITLE
Bad Link

### ISSUE THREAD

**Issue by rhys-the-davies** [canonical-web-and-design/ubuntu.com#7770]
The first CTA on this page, 'Join the Ubuntu Appliance Discourse' fails to reach the appliance discourse. It links to /appliance. For consistency, we should change the Ubuntu discourse URL to be /appliance rather than changing this link. 

When this is done please let me know so I can update the links elsewhere. 

---
*Reported from: https://ubuntu.com/appliance/community*

**Comment by anthonydillon** [comment]
@rhys-the-davies thanks, I've updated the discourse link which has resolved this issue.

**Comment by pmahnke** [comment]
@anthonydillon are you aware of #7771 did we fix then break this?
