### ISSUE TITLE
Text error in the side menu

### ISSUE THREAD

**Issue by rhys-the-davies** [canonical-web-and-design/ubuntu.com#7774]
The page reads:

Base:
Core 20

But should be Core 18

---
*Reported from: https://ubuntu.com/appliance/nextcloud*

**Comment by pmahnke** [comment]
@rhys-the-davies did yo update all the copy docs?

**Comment by pmahnke** [comment]
@rhys-the-davies is also reads 'core20'... should it read 'core18' or 'Core 18' like you suggest here?

**Comment by rhys-the-davies** [comment]
None of the copy docs for the individual appliances match their page so I've been updating the template page in the template folder and the yaml in those pages? 

Let's use 'Core 18' - I'll update with this now

**Comment by pmahnke** [comment]
@rhys-the-davies I think it should be 'core18' as that is the snap name. See https://snapcraft.io/core18, at this point, I don't care.

Also, what do you mean none of the pages match, I have been doing nothing but hundreds of copy updates.  Have there been updates that haven't been flaged?  What are the issues specifically?  Let's get them fixed.

The live data is all here on github:

- https://raw.githubusercontent.com/canonical-web-and-design/ubuntu.com/master/templates/appliance/adguard/index.md
- https://raw.githubusercontent.com/canonical-web-and-design/ubuntu.com/master/templates/appliance/plex/index.md
- https://raw.githubusercontent.com/canonical-web-and-design/ubuntu.com/master/templates/appliance/openhab/index.md
- https://raw.githubusercontent.com/canonical-web-and-design/ubuntu.com/master/templates/appliance/nextcloud/index.md
- https://raw.githubusercontent.com/canonical-web-and-design/ubuntu.com/master/templates/appliance/mosquitto/index.md
