### ISSUE TITLE
appliances: old Multipass linked

### ISSUE THREAD

**Issue by Saviq** [canonical-web-and-design/ubuntu.com#7777]
## Summary

https://ubuntu.com/appliance/vm links to old Multipass that doesn't actually have the `appliance:` remote. It needs to be 1.3.0 at least.

https://multipass.run/#install will always link to the latest release, but maybe we need a stable URL for the latest release?

## Process

Go to the URL above, click on either Windows or macOS installer.

## Current and expected result

It's v1.2.1 now, should be v1.3.0.

CC @rhys-the-davies

**Comment by pmahnke** [comment]
@Saviq a stable URL would be helpful
