### ISSUE TITLE
appliance: VM pages unnecessarily download the images

### ISSUE THREAD

**Issue by Saviq** [canonical-web-and-design/ubuntu.com#7778]
## Summary

On https://ubuntu.com/appliance/<appliance>/vm, there's a "Your download should start automatically." section, and the image is downloaded. That's wasteful and unnecessary, as Multipass is downloading the images.

## Process

Go to any of the <appliance>/vm page:

https://ubuntu.com/appliance/openhab/vm

## Current and expected result

There's a VM image being downloaded.

## Screenshot

![image](https://user-images.githubusercontent.com/231077/84881299-f4abd280-b08d-11ea-815c-5a43c6a71559.png)

CC @rhys-the-davies

**Comment by pmahnke** [comment]
@Saviq so is it downloaded via the `multipass launch appliance:openhab` command?

**Comment by Saviq** [comment]
@pmahnke correct.
