### ISSUE TITLE
/managed shows /kubernetes navigation

### ISSUE THREAD

**Issue by caldav** [canonical-web-and-design/ubuntu.com#7784]
## Summary

The /managed navigation shows the /kubernetes navigation. It should show:

Caused by https://github.com/canonical-web-and-design/ubuntu.com/pull/7754
Tentative fix at https://github.com/canonical-web-and-design/ubuntu.com/pull/7783

**Comment by pmahnke** [comment]
Personally I think even if you did get a fix, it is a broken experience.  It would be better to add a strip in the pages you want people to find the managed experience.  People learn your site's IA and if you just fart around with it, people will get lost.  Not that we haven't farted around before (see TCO calc) but I never like it.
