### ISSUE TITLE
Proposed new appliance link issue

### ISSUE THREAD

**Issue by rhys-the-davies** [canonical-web-and-design/ubuntu.com#7787]
'The propose new appliance' button links to 'https://discourse.ubuntu.com/c/appliances' when it should now be 'https://discourse.ubuntu.com/c/appliance' - without the s
---
*Reported from: https://ubuntu.com/appliance/portfolio*

**Comment by anthonydillon** [comment]
Dup of https://github.com/canonical-web-and-design/ubuntu.com/issues/7788
