### ISSUE TITLE
Proposed New Appliance Link

### ISSUE THREAD

**Issue by rhys-the-davies** [canonical-web-and-design/ubuntu.com#7788]
The 'Proposed New Appliance' link on this page still has an 's'. It should be: https://discourse.ubuntu.com/c/appliance/proposed-new-appliances

---
*Reported from: https://ubuntu.com/appliance/community*

**Comment by anthonydillon** [comment]
@Albert-Arthur to fix this issue. Find all occurrences of "https://discourse.ubuntu.com/c/appliances" and replace it with "https://discourse.ubuntu.com/c/appliance" (Notice the missing 's' on appliance).
