### ISSUE TITLE
The new government page does not seem to be index by Google 

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#7810]
This could be due to Google not crawling out the site since the launch on this new page but it would help if we had the word government in the heading of the page.

## Replicate
- Search for "Ubuntu government" and the blog and other pages come up first.

## Proposal
Maybe be adding the title content as the first heading of the page it would help. For example:
![image](https://user-images.githubusercontent.com/1413534/85279143-de32bc00-b47d-11ea-9520-a449ff9c260f.png)

---
*Reported from: https://ubuntu.com/gov*

**Comment by SirSamTumless** [comment]
@Khutch25 Can you change the copy doc so that it includes the word "Government" in H1 for Googlee.

**Comment by Khutch25** [comment]
@anthonydillon Thank you for updating it!
