### ISSUE TITLE
[Whitepaper] Smart Start] - Build takeover and engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#7812]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/193Rdm62tRugCxkQ2YBRK2hlP4bctPi_AAuDFz7fvRsU/edit#gid=738287198) and [design](2918):
 
- [ ] build takeover
- [ ] build engage page
- [ ] add takeover to `/takeovers/index.html`
- [ ] add takeover to `/index.html`
- [ ] add engage page to `/engage/index.html`
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by anthonydillon** [comment]
Blocked on the PDF

**Comment by SirSamTumless** [comment]
https://pages.ubuntu.com/rs/066-EOV-335/images/IoT_Device_time2market_30.06.20.pdf
