### ISSUE TITLE
Some tutorials are blue, some are black

### ISSUE THREAD

**Issue by fitojb** [canonical-web-and-design/ubuntu.com#7821]
![image](https://user-images.githubusercontent.com/554953/85420774-45fa0d00-b539-11ea-85b2-af4de250d048.png)

---
*Reported from: https://ubuntu.com/tutorials*

**Comment by anthonydillon** [comment]
@fitojb Thank you for taking the time to report this issue. Looks like the link parsing is missing some links. They should all have the `p-link--soft` class applied.

**Comment by fitojb** [comment]
Still the case, alas
![image](https://user-images.githubusercontent.com/554953/118709224-53b82100-b7e2-11eb-8b2c-d3683ec09105.png)

**Comment by mtruj013** [comment]
Resolved
![Screenshot 2021-09-17 at 17 43 57](https://user-images.githubusercontent.com/17607612/133816661-63524465-fedb-4f5c-9235-66e0cbcbf4e7.png)
