### ISSUE TITLE
User Interview: UA discovery and purchasing

### ISSUE THREAD

**Issue by wgx** [canonical-web-and-design/ubuntu.com#7828]
Write-ups here: 

https://docs.google.com/document/d/1bOra-3-Ibdb4x_LRWnEVIqKekm_MuEwpT2uJh2Eg9L4/edit#

https://docs.google.com/document/d/1PlbPFuENuPQT-xmJLvyFkNuQetb8cQW4zpAOQyverCM/edit#

**Comment by wgx** [comment]
@matthewpaulthomas @meralonso The only fairly-actionable thing to come out of the user interviews was that, while the 'wizard-like' approach was really well received, it was felt to be too "long" and would involve a lot of scrolling. Maybe we could think about reducing the vertical spacing in a future iteration so it feels more _dense_ and the users feel like they can get through it more quickly. That's it, overall they loved the direction we're taking.

**Comment by wgx** [comment]
##4 Key takeaways

**Peace of mind**: SLAs (24/5 vs 24/7) should be prominent
**Discount**: users expect a discount for annual payment if monthly vs annual is an option
**Explain**: what is covered in each support level clearly
**Density**: user would like to accomplish more on a single page with less vertical scrolling

**Comment by matthewpaulthomas** [comment]
Thanks @wgx!

> **Peace of mind:** SLAs (24/5 vs 24/7) should be prominent

For purchasing, I’ve asked @meralonso to [distinguish the primary and secondary text in the SLA options](https://miro.com/app/board/o9J_kr5Ty8s=/?openComment=3074457348624440961). For example, the “24/5” and “24/7” could be larger.

For the already-purchased state, this is covered by #7137.

> **Discount:** users expect a discount for annual payment if monthly vs annual is an option

Not an issue until/unless we offer a choice between monthly and annual.

> **Explain:** what is covered in each support level clearly

Reducing our current three levels of description (/advantage, /pricing/infra, and /uasd) would help here. So will including more things in the /advantage table (Landscape, tech support, CIS).

> **Density:** user would like to accomplish more on a single page with less vertical scrolling

I’ve made [six suggestions](https://miro.com/app/board/o9J_kr5Ty8s=/?moveToWidget=3074457348607550679&cot=3) for shortening the page (alongside various suggestions for other changes).
