### ISSUE TITLE
Next iteration of http://cdimage.ubuntu.com/daily-live/pending/ vanilization, move from apache dir mod to static index.html

### ISSUE THREAD

**Issue by xnox** [canonical-web-and-design/ubuntu.com#7830]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

Sometime ago we vanillized http://cdimage.ubuntu.com/daily-live/pending/ however it still relies on apache to generate the directory listing.

It means that every request to cdimage.ubuntu.com (or releases.ubuntu.com) requires apache to spin cpu cycles to generate the same page over again.

I'd like to move into direction of lp:ubuntu-cdimage code generating static index.html, instead of HEADER.html / FOOTER.html, such that there is full control to the design team how to generate are represent the file listing too.

I think we are flexible as to which templating engine is used to generate the index.html, but it has to be a static file which lp:ubuntu-cdimage builds, when it knows which files are supposed to be published in which folder.

There is certain amount of dynamism of the amount of cards generated, and the amount of files shows. I.e. checkout http://cdimage.ubuntu.com/releases/focal/release/ for example. But like lp:cdimage which is python3 code can spit out headers, cards, filelisting in whichever templating format needed to merge things and create a nice looking static index.html which has a nice HEADER, a nice FOOTER, and a file listing.

## Process

These files should not exist:
* http://cdimage.ubuntu.com/daily-live/pending/HEADER.html
* http://cdimage.ubuntu.com/daily-live/pending/FOOTER.html

This one should exist:
* http://cdimage.ubuntu.com/daily-live/pending/index.html

**Comment by anthonydillon** [comment]
Thanks for getting in touch @xnox. This is great news and welcomed improvement. 

I have a few questions before the work can be scheuled:
- Is there are particular deadline/timeline for this work to align with?
- Will you or your team be building implementing the lp:cdimage (I don't seem to have access to review)
- Would you prefer us to provide you with an HTML template to use which is likely to look a lot like the view-source of the current site with template loops and conditionals in some basic form?

**Comment by xnox** [comment]
> Thanks for getting in touch @xnox. This is great news and welcomed improvement.
> 
> I have a few questions before the work can be scheuled:
> 
> * Is there are particular deadline/timeline for this work to align with?
Not really. It can be done any time.

> * Will you or your team be building implementing the lp:cdimage (I don't seem to have access to review)
I'm not sure where you got the `lp:cdimage` bit from, that doesn't exist. The code that generates cdimages.ubuntu.com, is bzr branches of `lp:ubuntu-cdimage` i.e. https://code.launchpad.net/~ubuntu-cdimage/ubuntu-cdimage/mainline and is public.

Yes, I do expect that given a template plus which context/objects it needs to be called with, I will integrate that into lp:ubuntu-cdimage itself.

> * Would you prefer us to provide you with an HTML template to use which is likely to look a lot like the view-source of the current site with template loops and conditionals in some basic form?

Yes that.

And also what the format the loops/conditionals to be supplied as. Most likely the file listing for example will be iterator of `os.listdir()` or some such.

So it will mostly be re-write / redoing https://bazaar.launchpad.net/~ubuntu-cdimage/ubuntu-cdimage/mainline/view/head:/lib/cdimage/tree.py#L1067

You can see that in that file we have a lot of conditionals already, to figure out which blurbs of text to include / which files to publish. And then we just assemble `HEADER.html`, badly.  I hope we can replace that interactive code to something better, like a call to jinja template to do everything. And like probably have jinja template as a separate file.

jinja is just an example, I don't really mind which templating engine/langauge the webteam chooses to use.

**Comment by anthonydillon** [comment]
Thanks for the info. We will schedule this task shortly and let you know when we are aiming for. 

The web team uses Jinja in all cases. Therefore, I would suggest Jinja should be the templating language of choice.

**Comment by xnox** [comment]
Ooooh http://code.nabla.net/doc/jinja2/api/jinja2/bccache/jinja2.bccache.listdir.html jinja can list directories all by itself. hence I guess it can generate a file listing of a directory we ask it to generate the index for, all by itself. I wonder if there are already templates somewhere out there, which mimick something that looks like a directory listing already.

**Comment by steverydz** [comment]
Note to self: Add GTM

**Comment by pmahnke** [comment]
@steverydz 

#### Install Google Tag Manager

Copy the code below and paste it on to every page of your website.
Paste this code as high in the <head> of the page as possible:
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NCSV5D2');</script>
<!-- End Google Tag Manager -->
```

Additionally, paste this code immediately after the opening <body> tag:

```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NCSV5D2"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

For more information about installing the Google Tag Manager snippet, visit our Quick Start Guide .

**Comment by steverydz** [comment]
@xnox I've used a static site generator to build this. All the dynamic data is in `src/_data/site.json`. 

By running `npm run build` you will get a static `index.html` in `_site`.

Will this solve your problem?

https://github.com/steverydz/cdimage.ubuntu.com

**Comment by xnox** [comment]
> @xnox I've used a static site generator to build this. All the dynamic data is in `src/_data/site.json`.
> 
> By running `npm run build` you will get a static `index.html` in `_site`.
> 
> Will this solve your problem?
> 
> https://github.com/steverydz/cdimage.ubuntu.com

This is a promising start. In a way I would wish it would read more things off disk by itself, rather than expecting the data to be passed in (i.e. size / last modification of the files / etc).

It does seem like we have way too many conditionals in https://bazaar.launchpad.net/~ubuntu-cdimage/ubuntu-cdimage/mainline/view/head:/lib/cdimage/tree.py which should be refactored into something that is templatable.

I will play around with the site you provided, and see how well it can be integrated. with what we already have.

For example the cards need to be dynamically generated based on matching / available sites. because they are different between http://releases.ubuntu.com/20.04.1/ and http://cdimage.ubuntu.com/releases/20.04.1/release/ and so on.

generating json into a file, calling npm run build, getting more files and moving them about, is inconvenient, but oh well. Cause calling a function from python, to marry a directory of files with a template and store result into blah file would have been slightly easier to migrate to. But i kind of like the .json schema / contract, as to what is being iterated.

ps. haven't used liquid before so need to check what it can do for us.
