### ISSUE TITLE
RPi 4 - Ubuntu server 20.04 - Wifi doesn't work at boot

### ISSUE THREAD

**Issue by BLu85** [canonical-web-and-design/ubuntu.com#7838]
I followed this https://ubuntu.com/tutorials/how-to-install-ubuntu-on-your-raspberry-pi#3-wifi-or-ethernet
but the RPi4 doesn't connect to the Wi-Fi.
I tried to follow this thread https://www.raspberrypi.org/forums/viewtopic.php?t=255997
but haven't seen a clean solution. It would be good to have clear and unique instructions to get connected to the Wi-Fi at boot without using a sceen and an ethernet cable.

Many thanks for what you guys do.

**Comment by SirSamTumless** [comment]
@rhys-the-davies Any updates on this?

**Comment by rhys-the-davies** [comment]
It slipped through the cracks, unfortunately. I've fixed the tutorial now though and it works again for me. Let me know if the problem persists. 

The fix is less than ideal but we're working on a more permanent, friendly solution too.

**Comment by pmahnke** [comment]
@BLu85 let us know if the updated tutorial helps.  Reopen the issue if it doesn't.
