### ISSUE TITLE
Intel Apollo Lake platform fails on CPU2017 [5003b00001VeOiFx0]   

### ISSUE THREAD

**Issue by robinwangsmc** [canonical-web-and-design/ubuntu.com#7847]
Here is the result of Ubuntu 18.04 with Intel Apollo Lake platfrom

1. The kernel dmesg log still logged "CMCI storm detected" message. Please refer to file "A2SAN-LN4-C_ubuntu-18.04_kern.jpg" and “A2SAN-LN4-C_ubuntu-18.04_kern.log.20200620”.

2. The rate_int, speed_int, speed_fp test in CPU2017 still failed with errors.
   a. 557.xz_r test item in rate_int reports data miscompare error. (Please refer to CPU2017.001.jpg)
   b. 657.xz_s test item in speed_int reports "System unable to allocate necessary resources for OMP thread". (Please refer to 
         CPU2017.003.jpg)

3. The system was reboot during the speed_fp test running.

And please get all files from below FTP link
dataharbor.supermicro.com.tw
Port: 22
Protocol: SFTP (SSH2)
Username: robinwang_guest$robinw
Pasword: robin@SMC

---
*Reported from: https://ubuntu.com/community*

**Comment by pmahnke** [comment]
- emailed this to Lukasz - 7/7/20

**Comment by pmahnke** [comment]
@robinwangsmc I have emailed the kernel team directly.  This repo is for the ubuntu.com website.  If you want to pursue this, can you [refile the bug here](https://help.ubuntu.com/community/ReportingBugs).

Closing here.
