### ISSUE TITLE
missing LSNs?

### ISSUE THREAD

**Issue by setharnold** [canonical-web-and-design/ubuntu.com#7861]
Hello, nice shiny new USN site. It appears to be missing the LSNs though, which partners have asked us to provide in the same website. eg:

https://usn.ubuntu.com/lsn/0068-1/
from 10 jun 2020 isn't among the entries from 9 jun through 11 jun on:
https://ubuntu.com/security/notices?page=2
https://ubuntu.com/security/notices?page=3

Thanks

---
*Reported from: https://ubuntu.com/security/notices?page=3*

**Comment by nottrobin** [comment]
Sorry I've been meaning to respond to this for a while.

We hadn't been told and weren't aware that any LSN pages were live on usn.ubuntu.com until the 11th hour, so we haven't yet considered how they fit into the new experience. When we became aware of them, we discussed this with Lech and Mark Morlino, and maybe Steve Beattie (I think) and decided that we shouldn't delay the release of https://ubuntu.com/security/notices while we figure out how to support LSNs.

So for the time being LSNs are still visible on the old site (e.g. https://usn.ubuntu.com/lsn/0068-1/) until we get a chance to look into how they will fit into the new experience.

Leaving this open.

**Comment by matthewpaulthomas** [comment]
### [URLs](https://docs.google.com/document/d/183fLUXOLL17_baS617aX7Sj133n4lLfS6-rLhXXv9I0/edit#heading=h.ua7qthpl074)

I had already specified the URL format: “ubuntu.com/security/notices/{id} (for example … ubuntu.com/security/notices/LSN-4123123)”

### [LSN page](https://docs.google.com/document/d/183fLUXOLL17_baS617aX7Sj133n4lLfS6-rLhXXv9I0/edit#heading=h.bbi2iqqwhp35)

Similar changes to the USN page, including “Releases” and “Packages” sections, Livepatch versions converted to a table, and all packages and CVEs linked.

### [Main page](https://docs.google.com/document/d/183fLUXOLL17_baS617aX7Sj133n4lLfS6-rLhXXv9I0/edit#heading=h.kwalgbisu6l9)

The main heading changes from “Ubuntu Security Notices” to just “Security Notices”. The intro paragraph becomes two sentences distinguishing Ubuntu Security Notices from Livepatch Security Notices.

### [Search](https://docs.google.com/document/d/183fLUXOLL17_baS617aX7Sj133n4lLfS6-rLhXXv9I0/edit#heading=h.d1q60a90lkyx)

I’m unsure as to whether we need to let you filter just USNs or just LSNs when searching. If we don’t, no design changes are required.

**Comment by nottrobin** [comment]
> @matthewpaulthomas: I’m unsure as to whether we need to let you filter just USNs or just LSNs when searching. If we don’t, no design changes are required.

@lechsandecki are you able to tell us whether we should be encouraging people to search for LSNs explicitly?

**Comment by matthewpaulthomas** [comment]
@wgx Hi, could you review this design please? Specification sections linked above. Thanks.

**Comment by wgx** [comment]
👍  +1 from me, one comment left for a future iteration maybe.
