### ISSUE TITLE
The upload image in Media gallery is broken 

### ISSUE THREAD

**Issue by campbieil** [canonical-web-and-design/ubuntu.com#7863]
To reproduce go to the blog admin interface, go in the Media Gallery and try to upload an image (you will see a lot of failed uploads).
Suspecting Cloudinary ? 

We could use asset server as work around but this does not solve the issue of featured images

---
*Reported from: https://ubuntu.com/blog admin interface

**Comment by pmahnke** [comment]
It is not cloudinary, that is added only on the website side, not in wordpress.

I have filed an RT with IS for this - https://portal.admin.canonical.com/C126666/.

I am closing this as it isn't the right place for it.
