### ISSUE TITLE
Blog 500 Error.

### ISSUE THREAD

**Issue by AceXintense** [canonical-web-and-design/ubuntu.com#7872]
## Summary

The blog page does not currently work and is giving users a 500 page.

## Process

Locate to : https://ubuntu.com/blog 
You will be presented with a 500 server error page.

## Current and expected result

Load in the content / blog posts

**Comment by AceXintense** [comment]
This has now been fixed thanks guys!

**Comment by pmahnke** [comment]
@AceXintense thanks for filing this.  IS turned a debugger on and it broke the content feeds briefly.  It is fixed now.
