### ISSUE TITLE
Allow filtering CVEs by component

### ISSUE THREAD

**Issue by mssalvatore** [canonical-web-and-design/ubuntu.com#7882]
Currently, https://staging.ubuntu.com/security/cve provides some sorting/filtering capability. It's important for the Ubuntu Security Team that CVEs can be filtered based on which component the package is in (i.e. main vs. universe vs. multiverse vs. restricted).

**Comment by steverydz** [comment]
Duplicate of https://github.com/canonical-web-and-design/ubuntu.com/issues/7927 and https://github.com/canonical-web-and-design/ubuntu.com/issues/7924
