### ISSUE TITLE
CVEs: Package name filter returns unwanted packages

### ISSUE THREAD

**Issue by mssalvatore** [canonical-web-and-design/ubuntu.com#7883]
The CVEs on https://staging.ubuntu.com/security/cve can be filtered by package, however, the current filtering is not specific enough. For example, if I want to see all of the CVEs that affect the package "git", I also get results for gitlab, golang-github-containers-buildah, golang-code.gitea-git, gitaly, etc. I also get results for some packages which do not contain the string "git", such as hhvm.

I would expect a quick and easy way (perhaps via regex) that would allow me to see only the CVEs affecting a single package.

**Comment by steverydz** [comment]
I think this might be part of a larger UX discussion? Obviously there'll be technical considerations too.

@matthewpaulthomas @nottrobin @albertkol do you have any thoughts on this?

**Comment by matthewpaulthomas** [comment]
I intended that the search be for exact package names, not substrings: you shouldn’t have to know and remember to use a regex to get just the package you asked for.

Separately, regex search in the package field would be a nice enhancement. For ease of understanding, I think it would be best to introduce that, and regex search in the description field, at the same time.

**Comment by nottrobin** [comment]
So it sounds like it's definitely simplest to make the package search only match the exact (presumably, case-insensitive) package name for now.

The regex version probably needs a tiny bit more consideration - e.g. how do you indicate you're entering a regex rather than a package name? Is there overlap between regex control characters and existing package names? Most people will not be expecting to talk regex, and almost certainly won't know how.

**Comment by nottrobin** [comment]
I think making the package search only exact matches is a single line change: https://github.com/canonical-web-and-design/ubuntu.com/pull/7994

**Comment by mssalvatore** [comment]
Having the search perform exact matching sounds like a good solution. We might consider an "advanced search" feature in the future that could do filter on all sorts of things and potentially allow for regex or wildcard searches.

**Comment by nottrobin** [comment]
I believe this should be resolved in https://github.com/canonical-web-and-design/ubuntu.com/issues/7926 (@albertkol please update here if I misspoke)

**Comment by matthewpaulthomas** [comment]
Since this report is conflating two issues, I’ve split off the feature request for regex search into #8023.
