### ISSUE TITLE
Reduce the vertically space at the top of the appliance page

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#7904]
We were given some feedback on the appliance page that the logos were cut off on screen https://pasteboard.co/JgyVywN.png.

**Comment by anthonydillon** [comment]
@waynecrosby could you help to reduce the vertical space in the hero of the appliance page.

Here are a few simple attempts but nothing feels quite right:
![Screenshot_2020-07-07 Ubuntu Appliance Ubuntu](https://user-images.githubusercontent.com/1413534/86814398-44702f00-c079-11ea-98f9-ffa106bcda8f.png)

![Screenshot_2020-07-07 Ubuntu Appliance Ubuntu(1)](https://user-images.githubusercontent.com/1413534/86814414-49cd7980-c079-11ea-8c50-54c493471c9a.png)

**Comment by pmahnke** [comment]
topped?

![image](https://user-images.githubusercontent.com/441217/86815992-36bba900-c07b-11ea-8911-a5bcc07fa3bc.png)

**Comment by anthonydillon** [comment]
@pmahnke yeah maybe even bring then two sections together?

**Comment by waynecrosby** [comment]
@pmahnke @anthonydillon I was going to try that, I would try remove the <hr> between the 2 sections and just leave a bit of space

**Comment by waynecrosby** [comment]
![Appliances Reduced](https://user-images.githubusercontent.com/42238722/86895830-f43ab080-c0fc-11ea-80e9-3149660fa554.png)

**Comment by anthonydillon** [comment]
Looks great thanks @waynecrosby
