### ISSUE TITLE
[usn website] please provide a json version of items under /security/notices/

### ISSUE THREAD

**Issue by stevebeattie** [canonical-web-and-design/ubuntu.com#7916]
## Summary

Please provide an endpoint that provides JSON versions of the notices under /security/notices/

This is useful for the security team to ensure that a given security notice has been published. It would also be useful for users that wish to track security notices programmatically; the security team provides a JSON of all our USNs, but working with all of them to extract the information from one is overkill.

Thank you.

**Comment by albertkol** [comment]
Get notice:
https://ubuntu.com/security/api/notices/<notice_id>
- returns notice with id <notice_id>
- 404 if no notice found with the id

Get notices:
https://ubuntu.com/security/api/notices
- accepts two get parameters: limit, offset. These will paginate the results returned. Offset defaults to 0. Limit defaults to 20.
