### ISSUE TITLE
Microsoft locking up Ubuntu

### ISSUE THREAD

**Issue by jraff9** [canonical-web-and-design/ubuntu.com#7921]
Fri, 10 Jul 2020 18:44:38 -0400 
A few minutes ago I was browsing Pinterest when I get an alert
obstensively from Windows indicating my Windows ID key blah
blah blah. I could NOT do anything with the computer what ever
was done blocked any keystroke. I tried every key on the keyboard
NOTHING! The mouse would disapear and reapear. NOTHING worked!
I finally shut down the computer and restarted it. Now I'm writing
this note. What gives?
Who gave Microsoft the right to invade my Ubuntu computer and
lock it up?
From my point of view Microsoft is the offending party and
I am the offended.
---
https://www.tacorelish.com/hotel-hacks-make-travels-convenient/5/?D10c=1&D_4_6_10cALL=1&D_10_20cALL=1&A10c=1
---
I was viewing the page when some advertisement came up that 
looked interresting. I clicked on it and EVERYTHING locked up!

---
*Reported from: https://ubuntu.com/*

**Comment by anthonydillon** [comment]
Sorry to hear you are having trouble with your Ubuntu system. This issue list are for issues with the website. Unfortunately, we cannot provide Ubuntu support via this channel.

Please file a bug on the Ubuntu project.
