### ISSUE TITLE
[USN] - Bad error message for USN payload with duplicate CVEs

### ISSUE THREAD

**Issue by jpmartinspt** [canonical-web-and-design/ubuntu.com#7946]
# Issue
If you try to create a USN and the payload contains the same CVE twice under the `cves` key, the endpoint returns and error with a message the following message `<Response [400]> {"message":"Notice USN-4-1 already exists"}`, this is happening because we end up trying to create the relation twice and that raises an `IntegrityError` that we wer only expecting to get for trying to duplicate a primary key.

Example USNs:  4-1, 125-1, 330-1, 332-1, 333-1, 1617-1 and 2670-1 in https://usn.ubuntu.com/usn-db/database-all.json

# Todo
- Validate on marshmallow there are no duplicate CVEs.
- Discuss the message we return for Integrity errors.
- Push the integrity error to sentry.

**Comment by albertkol** [comment]
@jpmartinspt 

How about instead of the `Todo` list, we just do a `set(data["cve"])` to get only the unique `cve.id` values and insert them. 

We do not need to worry about separating the messages for `Integrity` errors.
We also do not need to spam sentry with more errors and we also do not need to fix them.

**Comment by jpmartinspt** [comment]
I'm torn, not the biggest fan of fixing bad payloads for the user.. but in this case maybe it's OK.
As for the errors, you don't need to fix them but in this case it would give you immediate visibility of what the problem was. I had to set-up everything in order to find out what the issue was and if I was reporting the error I could have just gone to sentry.
@jkfran @tbille thoughts?

**Comment by jkfran** [comment]
I don't mind applying Albert solution.

> Example USNs: 4-1, 125-1, 330-1, 332-1, 333-1, 1617-1 and 2670-1 in https://usn.ubuntu.com/usn-db/database-all.json

Can we let them know even if we fix it on our side?
