### ISSUE TITLE
Logo error

### ISSUE THREAD

**Issue by RFMVasconcelos** [canonical-web-and-design/ubuntu.com#7962]
![image](https://user-images.githubusercontent.com/27001378/87958512-89e52100-caa9-11ea-9327-5e0bea6dad86.png)

---
*Reported from: https://ubuntu.com/managed*

**Comment by bartaz** [comment]
It seems that using text instead of logo is intentional (as per https://github.com/canonical-web-and-design/ubuntu.com/pull/7246), but I agree it looks broken.

Maybe logo + label (to name specific edition) would be ok?

**Comment by SirSamTumless** [comment]
This is temporary as we been instructed by our legal team.
