### ISSUE TITLE
Design ubuntu.com homepage 

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#7969]
[Copy doc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit)

**Comment by meralonso** [comment]
@pmahnke @SirSamTumless I have laid out a couple of options following copy doc. As you can see they are quite long and repetitive. I have other options (more interesting) that I'd like to discuss with you tomorrow if you have some time.

![Homepage Copy 1](https://user-images.githubusercontent.com/65166314/88945869-cde8da80-d28e-11ea-8903-71923aeb73c8.jpg)

![Homepage Copy 2](https://user-images.githubusercontent.com/65166314/88945882-d214f800-d28e-11ea-8fd8-3f5b8aa83049.jpg)

**Comment by anthonydillon** [comment]
I like the content flow of option A. Option B feels longer.

**Comment by pmahnke** [comment]
I agree with Ant, A feels more scalable and the logos more balanced.

**Comment by meralonso** [comment]
@spencerbygraves @pmahnke two options below -

A / logos at the bottom of each section

![Homepage Copy 1](https://user-images.githubusercontent.com/65166314/89190200-06432e00-d599-11ea-8e4b-04f650fba545.jpg)

B / Illustration at the top of each title and all logos at the end

![Homepage Copy 3](https://user-images.githubusercontent.com/65166314/89190230-0f33ff80-d599-11ea-8d4c-735b95c0c3b0.jpg)

As discussed with @pmahnke on friday we could mix both options and use illustration + logos. Please let me know what you think.

I also tried to arranged content like this (below) but it looks a bit unbalanced

![Screenshot 2020-08-03 at 14 45 22](https://user-images.githubusercontent.com/65166314/89190164-fb889900-d598-11ea-8822-37de05375e26.png)

**Comment by pmahnke** [comment]
I don't think logos at the end works.  So the first option.

**Comment by spencerbygraves** [comment]
I prefer option A too. It's quite busy with the logos so I don't think we need to combine it with the illustrations.

**Comment by meralonso** [comment]
Thanks @spencerbygraves @pmahnke then it'd be something like the img below.
Also, could we only have 6 logo max per row?

![Homepage Copy 1](https://user-images.githubusercontent.com/65166314/89206712-95f4d680-d5b1-11ea-8657-62d0be04df73.jpg)

**Comment by pmahnke** [comment]
@meralonso I will get them to max 6 per row, but can you prepare them all?

**Comment by meralonso** [comment]
@pmahnke Sure, just let me know which ones don't go there and I'll export the rest. For the logos at the top - do you want me to export them b/w?

**Comment by pmahnke** [comment]
@meralons for the top ones, usually companies have b&w ones for print, if we can get those it would be best; otherwise, we can add a css overlay to colour ones.

**Comment by meralonso** [comment]
Hmmm... getting all of them may be difficult. Many companies just use css on partners logos, it's easier

**Comment by meralonso** [comment]
Assets -

Modern enterprise open source
[Amazon Web Services](https://assets.ubuntu.com/v1/8f53a448-AmazonWebServices_logo.svg)
[Azure](https://assets.ubuntu.com/v1/22fd6473-MicrosoftAzure_logo.svg)
[Google ](https://assets.ubuntu.com/v1/b0716ed5-Google_logo.svg)
[AT&T](https://assets.ubuntu.com/v1/b76ad53c-AT%26T_logo.svg)
[Netflix](https://assets.ubuntu.com/v1/ae0456eb-Netflix_logo.svg)
