### ISSUE TITLE
CVE results: Improve which columns appear

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7991]
Currently, [the new CVE pages](https://staging.ubuntu.com/security/cve) show four Ubuntu version columns, regardless of search: 20.04 LTS, 18.04 LTS, 16.04 LTS, and 14.04 ESM.
![image](https://user-images.githubusercontent.com/19801137/88383267-1b061180-cda2-11ea-8194-7d9871512ad5.png)

In comparison, [the old CVE pages]() show six Ubuntu version columns (and have no search): 12.04 ESM, 14.04 ESM, 16.04 LTS, 18.04 LTS, Ubuntu 20.04 LTS, and Groovy.

![image](https://user-images.githubusercontent.com/19801137/88383310-2e18e180-cda2-11ea-9f23-209ac911f881.png)

Neither is ideal: the new tables omit many versions, while even the old table does not show status in 19.10 (despite [the site recording this information](https://github.com/canonical-web-and-design/ubuntu.com/issues/7989)).

We need to design and implement sensible behaviour for the columns:
- What versions should be shown by default, for example in the “Recent CVEs” table?
- Should the columns shown vary depending on what you’ve searched for? For example, if you search just for CVEs affecting 19.10, should the 19.10 column be the only one that appears?
  - If so, what should happen if you specify half a dozen version-status criteria? Should the table scroll horizontally?

[From meeting with Robin and Albert.]

**Comment by matthewpaulthomas** [comment]
[Proposal](https://docs.google.com/document/d/1VuAElUpFay7MBFNmE3NhSyY9TkXiqHcA1ZHQ11AYO-Q/edit#heading=h.ka8fp99zeqhg):

>  By default, the “relevant Ubuntu versions” for a CVE listing (including the “Recent CVEs” list) should be every current release plus any development release: for example, in July 2020, this would be 16.04 LTS, 18.04 LTS, 19.10, 20.04 LTS, and Groovy.
>
> However, if from an “Ubuntu version” search menu you choose:
> - Any individual version, then just that version should be shown.
> - “Any current release”, then all releases in Basic Security Maintenance should be shown: for example, in July 2020, this would be 16.04 LTS, 18.04 LTS, 19.10, and 20.04 LTS.
> - A combination of those, then the combination should be shown.
>
> (This may not show the ideal choice of versions for an “Any” search. But calculating those for every matching CVE would be too onerous.)
>
> Regardless of selection, if the resulting table has too many columns to fit on screen at once, then the version columns should scroll horizontally as a single block.

The new defaults might mean the table as a whole needs to use a smaller font size than normal. If so, I think that’s perfectly fine.

@albertkol Does this look reasonable?

**Comment by albertkol** [comment]
@matthewpaulthomas so I am looking at finding a way to dynamically display the default releases.

Wouldn't "relevant Ubuntu versions" include any release that is still under ESM?

For 2020-07-27 would be:
```
 Precise Pangolin | 12.04   | precise  | t   | f           | 2012-04-26 00:00:00 | 2021-04-30 00:00:00 | 2012-04-26 00:00:00
 Trusty Tahr      | 14.04   | trusty   | t   | f           | 2014-04-17 00:00:00 | 2022-04-30 00:00:00 | 2019-04-30 00:00:00
 Xenial Xerus     | 16.04   | xenial   | t   | f           | 2016-04-21 00:00:00 | 2024-04-30 00:00:00 | 2021-04-30 00:00:00
 Bionic Beaver    | 18.04   | bionic   | t   | f           | 2018-04-26 00:00:00 | 2028-04-30 00:00:00 | 2023-04-30 00:00:00
 Eoan Ermine      | 19.10   | eoan     | f   | f           | 2019-10-17 00:00:00 | 2020-07-31 00:00:00 | 2019-10-17 00:00:00
 Focal Fossa      | 20.04   | focal    | t   | f           | 2020-04-23 00:00:00 | 2030-04-30 00:00:00 | 2025-04-30 00:00:00

```

Wouldn't we want to include 14.04 and 12.04?

**Comment by matthewpaulthomas** [comment]
@albertkol Good question. (And thanks for showing those dates — I didn’t know about the shorter EOL dates for 12.04 and 14.04.)

For most people looking at this table, the ESM columns will not be directly relevant — either they’ll be using a newer Ubuntu version (most likely), or most of the fixes in those columns (especially in “Recent CVEs”) will require a UA subscription that they don’t have. (Or maybe they won’t be using Ubuntu at all yet, but evaluating whether to adopt the latest LTS.)

So this is more about getting a good-looking table. If we show too few columns, it may look like we just started doing security fixes, when really we’ve been doing them for 16 years. But if we show too many, the most recent release will be scrolled off the edge of the screen (because they should be in chronological order, not reverse order like they are now).

If we stick with the current policy, where ESM is for ten years, LTS is for five years, and interim releases last 9 months: 
Months after LTS release | Example date | Columns if we exclude ESMs | Columns if we include ESMs
-|-|-|-
0 ~ 3|2020-07-16|5 (16.04, 18.04, 19.10, 20.04, Groovy)|7 (12.04, 14.04, 16.04, 18.04, 19.10, 20.04, Groovy)
3 ~ 6|2020-07-17|4 (16.04, 18.04, 20.04, Groovy)|6 (12.04, 14.04, 16.04, 18.04, 20.04, Groovy)
6 ~ 9|Nov 2020|5 (16.04, 18.04, 20.04, 20.10, Happy¹)|7 (12.04, 14.04, 16.04, 18.04, 20.04, 20.10, Happy)
9 ~ 12|Feb 2021|5 (16.04, 18.04, 20.04, 20.10, Happy)|7 (12.04, 14.04, 16.04, 18.04, 20.04, 20.10, Happy)
12 ~ 15|May 2025²|5 (22.04, 24.04, 24.10, 25.04, Radiant)|**8** (16.04, 18.04, 20.04, 22.04, 24.04, 24.10, 21.04, Radiant)
15 ~ 18|Aug 2025|4 (22.04, 24.04, 25.04, Radiant)|7 (16.04, 18.04, 20.04, 22.04, 24.04, 25.04, Radiant)
18 ~ 21|Nov 2025|5 (22.04, 24.04, 25.04, 25.10, Sunny)|**8** (16.04, 18.04, 20.04, 22.04, 24.04, 25.04, 25.10, Sunny)
21 ~ 24|Feb 2025|4 (22.04, 24.04, 25.10, Sunny)|7 (16.04, 18.04, 20.04, 22.04, 24.04, 25.10, Sunny)

¹ Not real codenames, just for illustration
² Jumping forward four years to avoid the exception that 12.04 and 14.04 have shorter ESM than later LTSes will

Feel free to check my calculations (I’ve probably made _at least_ one mistake). Anyway, I think four columns is okay (as shown by the site currently), five columns will be okay (though we might need a smaller font), but eight would be just too much.

@clagom Would you like to review this, please?

**Comment by SirSamTumless** [comment]
Hi @clagom  - would you mind giving this a quick review as it is blocking other work.

**Comment by clagom** [comment]
Reviewed, looks nice

**Comment by SirSamTumless** [comment]
Thanks!

**Comment by matthewpaulthomas** [comment]
Thanks @clagom. [Spec updated](https://docs.google.com/document/d/1VuAElUpFay7MBFNmE3NhSyY9TkXiqHcA1ZHQ11AYO-Q/edit#heading=h.ka8fp99zeqhg), now ready for implementation.
