### ISSUE TITLE
CVE results: Handle packages moving between components

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#7992]
Sometimes Ubuntu packages move between components in successive Ubuntu versions: [a package may be promoted from Universe to Main](https://wiki.ubuntu.com/MainInclusionProcess), and conversely, a deprecated package (such as [unity](https://packages.ubuntu.com/search?keywords=unity&searchon=names&exact=1&suite=all&section=all) or [python2.7](https://packages.ubuntu.com/search?keywords=python2.7&searchon=names&exact=1&suite=all&section=all)) may be demoted from Main to Universe.

The CVE search will let you search by component, _and_ CVE results show status in multiple Ubuntu versions at once. That combination means we need to design and implement what happens when a package moves between components. For example:
- If you search just for CVEs in a particular component, should we show a package if it was _ever_ in that component, or just if it is currently?
- If the columns we show (#7991) include those where the package was not in the relevant component, should we still show those table cells, or demote them in some way?
- What if the columns we’d show are _only_ those where the package was not in the relevant component? Should we change the columns?

[From meeting with Robin and Albert.]

**Comment by matthewpaulthomas** [comment]
> - If you search just for CVEs in a particular component, should we show a package if it was _ever_ in that component, or just if it is currently?

Proposal: We should return CVEs from a package if it was ever in the specified component. It would not make sense to limit it to the component from the current release, when you might also be limiting the search to a release/releases that _aren’t_ the current one.

> - If the columns we show (#7991) include those where the package was not in the relevant component, should we still show those table cells, or demote them in some way?

Proposal: Do not change the cells. The visual design of the cells is complex enough (with two independent colour ranges, one for priority and one for status) that adding a third effect would muddle it.

> - What if the columns we’d show are only those where the package was not in the relevant component? Should we change the columns?

Proposal: Do not change the columns. It is likely that the matching Ubuntu versions would be a long consecutive range (for example, a package that was in Main for every Ubuntu version up to 17.10, and was then demoted), so it would be impractical to show them all; and there would seldom be an obvious reason to choose one over the others.

**Comment by albertkol** [comment]
> What if the columns we’d show are only those where the package was not in the relevant component? Should we change the columns?

Should we list the package at all? ..since the package does not have the relevant component in any of the releases listed in the table columns.

**Comment by matthewpaulthomas** [comment]
@albertkol By “list the package” do you mean “return CVEs from that package”? If so, I think yes, absolutely, because the CVEs match the criteria you asked for. If you do want CVEs just from current versions, you can search for that specifically with “[Any current (including Groovy)](https://docs.google.com/document/d/1VuAElUpFay7MBFNmE3NhSyY9TkXiqHcA1ZHQ11AYO-Q/edit#bookmark=id.jzmf6qyiy6f3)”.

@lilyvidenova Would you have time to review this design please? The background of [which version columns we show by default is in the UI spec](https://docs.google.com/document/d/1VuAElUpFay7MBFNmE3NhSyY9TkXiqHcA1ZHQ11AYO-Q/edit#heading=h.ka8fp99zeqhg). The proposal above is about what happens when a package transits in or out of your search criteria over time, or matches the criteria in a column that we don’t show by default.

**Comment by matthewpaulthomas** [comment]
@ziheliu214 Hi, would you have time to review this? Let me know if you have any questions. Thanks.

**Comment by ziheliu214** [comment]
> @ziheliu214 Hi, would you have time to review this? Let me know if you have any questions. Thanks.

Hi MPT yes will do it now

**Comment by ziheliu214** [comment]
> > * If you search just for CVEs in a particular component, should we show a package if it was _ever_ in that component, or just if it is currently?
> 
> Proposal: We should return CVEs from a package if it was ever in the specified component. It would not make sense to limit it to the component from the current release, when you might also be limiting the search to a release/releases that _aren’t_ the current one.
> 
> > * If the columns we show (#7991) include those where the package was not in the relevant component, should we still show those table cells, or demote them in some way?
> 
> Proposal: Do not change the cells. The visual design of the cells is complex enough (with two independent colour ranges, one for priority and one for status) that adding a third effect would muddle it.
> 
> > * What if the columns we’d show are only those where the package was not in the relevant component? Should we change the columns?
> 
> Proposal: Do not change the columns. It is likely that the matching Ubuntu versions would be a long consecutive range (for example, a package that was in Main for every Ubuntu version up to 17.10, and was then demoted), so it would be impractical to show them all; and there would seldom be an obvious reason to choose one over the others.

Agree with this proposal. 

If space allows & if the 'component' is an important value, maybe considering adding a column displaying it? showing 'current component' with a possibility to track its history (to explain why it's universal but still displayed under the filter of main)? 
![image](https://user-images.githubusercontent.com/61144986/89562372-c8047380-d811-11ea-82d0-e912e02b9f71.png)

**Comment by matthewpaulthomas** [comment]
Thanks @ziheliu214.

> If space allows & if the 'component' is an important value, maybe considering adding a column displaying it?

The purpose of the component filter is mainly to remove irrelevant results, not really as interesting information in itself. If later we decide it is interesting to show, our first step would be listing it for each package×component combination on the individual CVE pages, rather than in the results tables.

[Specification updated](https://docs.google.com/document/d/1VuAElUpFay7MBFNmE3NhSyY9TkXiqHcA1ZHQ11AYO-Q/edit#heading=h.aoek8nxke7k9) and ready for impelementation.
