### ISSUE TITLE
Multiple instances of the debounce function should be consolidated

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/ubuntu.com#7998]
There are three (soon to be four once https://github.com/canonical-web-and-design/ubuntu.com/pull/7997 is merged) `debounce` functions throughout the codebase. We should make a utility function that we import where we need it.

Current places where this can be seen:
- https://github.com/canonical-web-and-design/ubuntu.com/blob/master/static/js/src/release-chart.js#L36
- https://github.com/canonical-web-and-design/ubuntu.com/blob/master/static/js/src/imageBuilder.js#L355
- https://github.com/canonical-web-and-design/ubuntu.com/blob/master/static/js/src/desktop-statistics.js#L3

It will also be in https://github.com/canonical-web-and-design/ubuntu.com/tree/master/templates/automotive/_chassis_animation.html

There is a PR (https://github.com/canonical-web-and-design/ubuntu.com/pull/7923) which adds a `debounce` module so this task shouldn't be done until that is merged.

**Comment by sowasred2012** [comment]
@steverydz might not be merged today, but I've got that in a shop PR: https://github.com/canonical-web-and-design/ubuntu.com/pull/7923/files#diff-3f10464984eb1f1268c6b7fc8f1f66e4

**Comment by steverydz** [comment]
Thanks @sowasred2012. This should wait on that to be merged in that case, and then we can move all the other instances to use the new module.
