### ISSUE TITLE
Use debounce utility on the automotive page

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/ubuntu.com#8003]
Refactor https://github.com/canonical-web-and-design/ubuntu.com/blob/master/templates/automotive/_chassis_animation.html so that it uses the debounce utility (https://github.com/canonical-web-and-design/ubuntu.com/blob/master/static/js/src/utils/debounce.js)

**Comment by anthonydillon** [comment]
@steverydz I was in the page making an update so thought I would just make this change as a drive-by.
