### ISSUE TITLE
Disable the auto-download of appliance images

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#8021]
## Summary
On the appliance pages, we auto-download the image when a user visits the page. This causes issues on mobile devices or users that are on limited/expensive band-width.

## Process
- Go to https://ubuntu.com/appliance/plex/raspberry-pi
- See the download is automatically triggered

## Current and expected result
- The resulting page should contain a clear call to action to trigger the download.

**Comment by rhys-the-davies** [comment]
+1
