### ISSUE TITLE
Build Kubecon page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#8039]
Based on this [copy doc](https://docs.google.com/document/d/1qZGlO8ecig760hXn-8DG3fw52LNHfTM7WKwAHu_DpXc/edit#heading=h.u4au08x6u58f).

**Comment by pmahnke** [comment]
@SirSamTumless did you get that image of the focal t-shirt from @marcushas?

**Comment by SirSamTumless** [comment]
![FocalFossa--t-shirt-black.png](https://images.zenhubusercontent.com/5cb4608c97df763a9090bdeb/68026b9f-2776-4926-a2f6-3f9db5178678)
