### ISSUE TITLE
There are two Link to 16.04 Articles. This looks outdated and ugly

### ISSUE THREAD

**Issue by guettli** [canonical-web-and-design/ubuntu.com#8074]
---
*Reported from: https://ubuntu.com/tutorials?topic=desktop*

**Comment by pmahnke** [comment]
@guettli technically, 16.04 is still a supported version of Ubuntu.  We wouldn't recommend using it; however, there are some systems that it might still be best for.  I assume you don't like that it is older?  We keep it because the installer is different from 18.04 and 20.04.

**Comment by anthonydillon** [comment]
We would like to continue to support users of 16.04 and plan to drop this content on the 21.04 release.
