### ISSUE TITLE
[Case study] GMO Pepabo  - Build the  Engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#8112]
## Requirements

Please build an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1H7dMhhbCp4iSe0T0rhOlaQipA-M0gvHjxn-hPpNaXjQ/edit#gid=738287198) and [design](3021):
 

- [ ] build engage page
- [ ] add engage page to `/engage/index.html`
- [ ] build a [social banner](https://tools.demos.haus/) and use the 1200px x 630px one
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by steverydz** [comment]
@SirSamTumless the brief isn't filled out for this? no copy doc or headings https://docs.google.com/spreadsheets/d/1H7dMhhbCp4iSe0T0rhOlaQipA-M0gvHjxn-hPpNaXjQ/edit#gid=1271849439

**Comment by SirSamTumless** [comment]
@steverydz I have chased them! Will update you when they get back to me

**Comment by SirSamTumless** [comment]
PDF  https://pages.ubuntu.com/rs/066-EOV-335/images/GMO Pepabo Case study 8.pdf

Chased MKTG for the MKTO id.

**Comment by steverydz** [comment]
@SirSamTumless still waiting on the marketo form ID for this to go live

**Comment by carkod** [comment]
Once this is done, can we add this to [discourse](https://discourse.ubuntu.com/t/how-to-add-engage-pages/18185)?

**Comment by SirSamTumless** [comment]
It's here, it's here 🙌 ! Here is the form ID: FO3688A1ZN12LA1 for the case study.

**Comment by steverydz** [comment]
@SirSamTumless PR https://github.com/canonical-web-and-design/ubuntu.com/pull/8284
