### ISSUE TITLE
[Event] CloudNative Days Tokyo 2020  - Build the engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#8118]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/document/d/1DvtZtxdTSqbDeP_Y-N0O7wf11KcVwWJP8vrVpXX_qew/edit) and [design](3021):
 
- [ ] build engage page
- [ ] add engage page to `/engage/index.html`
- [ ] build a [social banner](https://tools.demos.haus/) and use the 1200px x 630px one
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by SirSamTumless** [comment]
Awaiting translated copy.

**Comment by SirSamTumless** [comment]
https://docs.google.com/document/d/10DG5YnFFEoFTAlM3g2fo5mTtCyI6UXKKDfDSEuGGzvQ/edit @steverydz here's the JP copy

**Comment by steverydz** [comment]
@SirSamTumless the page will need to be designed, also this will be two parts - the page will have to go live on jp before the takeover on ubuntu.com as they are two separate code bases

**Comment by SirSamTumless** [comment]
@steverydz I don't think it has a takeover - I have created an issue for @meralonso to for the design of the page.

**Comment by SirSamTumless** [comment]
@anthonydillon Looking at @meralonso issue it looks like you've had a crack at building this? Marketing needs this page live early tomorrow. Do you think it is feasible for it just to be design reviewed?
