### ISSUE TITLE
[Takeover] Smart Start - Build the Takeover 

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#8119]
## Requirements

Please build a takeover  based on this [brief](https://docs.google.com/spreadsheets/d/193Rdm62tRugCxkQ2YBRK2hlP4bctPi_AAuDFz7fvRsU/edit?ts=5f325452#gid=2113339190) and [design](3021):
 
- [ ] build takeover
- [ ] add takeover to `/takeovers/index.html`
- [ ] add takeover to `/index.html`
- [ ] build a [social banner](https://tools.demos.haus/) and use the 1200px x 630px one
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

Note; the Engage page was done, we just need a takeover done for it.

**Comment by steverydz** [comment]
@SirSamTumless no PDF, UTM or URL

**Comment by SirSamTumless** [comment]
@steverydz Here's the URL https://github.com/canonical-web-and-design/ubuntu.com/blob/master/templates/engage/smart-start-whitepaper.md or https://ubuntu.com/engage/smart-start-whitepaper 

and the UTM www.ubuntu.com/engage/smart-start-whitepaper?utm_source=Takeover&utm_medium=Takeover&utm_campaign=CY20_IOT_SmartStart_WP_Timetomarket

**Comment by steverydz** [comment]
@SirSamTumless still need PDF
