### ISSUE TITLE
Errors i found after installing Ubuntu/Nextcloud appliance on a RPi 4

### ISSUE THREAD

**Issue by MakerStuff** [canonical-web-and-design/ubuntu.com#8143]
## Problems with Ubuntu/Nextcloud appliance:
* certification
    * installation of tools via apt? / apt is missing
* a2enmod does not work / command not found
* admin validation for settings (eg.: settings -> administration -> share -> enforce password) can be skipped. Effect unknown / indicator changes

## Steps to reproduce
Follow along the [official tutorial](https://ubuntu.com/appliance/nextcloud/raspberry-pi).

---
*Reported from: https://ubuntu.com/appliance/nextcloud*

**Comment by SirSamTumless** [comment]
@rhys-the-davies Would you mind looking into this please?

**Comment by rhys-the-davies** [comment]
These github notifications seem to keep getting lost in my inbox, sorry for the delay @SirSamTumless. Though I don't fully understand the issue here. I'm going to add Kyle Fazzari to the repo if I can so he can take a look as he's the snap maintainer.

**Comment by kyrofa** [comment]
Thanks for looping me in @rhys-the-davies.

> * installation of tools via apt? / apt is missing

Ubuntu Appliances use [Ubuntu Core](https://ubuntu.com/core), a distribution of Ubuntu intended for IoT/devices. Ubuntu Core is based entirely upon [snaps](https://snapcraft.io/). It doesn't support Debian packages, as you've noticed. You can, however, install [lxd](https://snapcraft.io/lxd) or [docker](https://snapcraft.io/docker), create an image, and install Debian packages in there if you need some.

> * a2enmod does not work / command not found

That's correct. The Nextcloud snap contains a web server that (assuming you enabled HTTPS) is setup and ready for production workloads, but it doesn't expose the ability to tweak it.

> * admin validation for settings (eg.: settings -> administration -> share -> enforce password) can be skipped. Effect unknown / indicator changes

I'm afraid I don't know what you're saying, here. What is the issue you're trying to raise?

**Comment by SirSamTumless** [comment]
Hopefully this is resolved. Please re-open if you still have this issue.
