### ISSUE TITLE
/openstack/managed contextual footer is redundant and off-topic

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#8151]
1\. Go to [ubuntu.com/openstack/managed](https://ubuntu.com/openstack/managed).
2\. Scroll down to the orange stripe.

What you see | What’s wrong
-|-
Canonical provides managed services option for OpenStack.|Incomplete sentence — should be either “**a** managed services option” or “managed services option**s**”.
[Learn more ›](https://ubuntu.com/openstack/managed) | It’s not “more”, it’s linking to the page you’re already on!
[ Contact us ] [ Contact us ] | These buttons both do exactly the same thing as the “Let’s discuss” button immediately above.
Further reading|The listed articles are all [about Kubernetes](https://ubuntu.com/blog/tag/kubernetes), not about OpenStack.

I have not found a copydoc for this section. [The copydoc for the page](https://docs.google.com/document/d/1g38PPPhEP0Z66eM_gezfUyUwAr5e9vGfTHJDWV8gZlE/edit) links to [an ubuntu.com contextual footer copydoc](https://docs.google.com/document/d/1kq0SPv-PAIfL9nHGxgNDpHhr5OplE2iNaZZiqG4RT48/edit) that contains 14 other footers but not this one.

This section doesn’t seem to be reused anywhere else (though the first third is included in [a standalone page that presumably isn’t supposed to exist](https://ubuntu.com/about/base_about)).

If 2/3 of it is redundant with the rest of the page, the other 1/3 is off-topic, it has no copydoc, and it isn’t reused, perhaps this section should be removed altogether. One possibility would be replacing it with an “OpenStack news” section consisting of a feed from [/blog/tag/openstack](https://ubuntu.com/blog/tag/openstack).

---
*Reported from: https://ubuntu.com/openstack/managed*

**Comment by SirSamTumless** [comment]
@tytus-kurek Please could you give this a read through and let us know what you think?

**Comment by pmahnke** [comment]
@tytus-kurek I will fix this.

@matthewpaulthomas you clearly don't know how our contextual footers work.  Set up a 30 min meeting and I will talk you through it so you can be less upset and provide more helpful issues.

**Comment by matthewpaulthomas** [comment]
@pmahnke Thanks for working on this — I wasn’t expecting it to be such high priority. I understand how contextual footers work, which is why I investigated whether this one was used anywhere else. However, when I evaluate designs I always try to adopt the POV of someone who doesn’t know any of the implementation, because (for example) someone disoriented by a self-link or redundant buttons won’t be mollified by knowing that our templating system made the bugs more likely. At a stretch, suggesting no contextual footer at all might be misinterpreted as “upset”, but it’s the approach already taken on [/openstack/compare](https://ubuntu.com/openstack/compare).
