### ISSUE TITLE
Design presentation of package component on CVE pages

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#8155]
The CVEs main page lets you filter CVEs by component — that is, by whether they affect any packages  that are in a given component in any release.

However, when you get to the page for an individual CVE, you do not see which package(s) for which release(s) match that filter. This makes a CVE’s presence in those search results mysterious.

This can be fixed by adding the component for each package-release combination to the individual CVE page.

**Comment by albertkol** [comment]
@matthewpaulthomas 

Is this what you had in mind?

![image.png](https://images.zenhubusercontent.com/5ee7415a47536a7869302593/c59c2472-00d6-4459-9f8e-aedf3816b9e8)

**Comment by matthewpaulthomas** [comment]
Ah, that’s great, thanks! Better than what I had in mind, actually.

Data glitch: “Upstream” is not an Ubuntu version, so packages don’t have a “component” Upstream. That cell should contain just an em dash “—”.

Another small tweak: there should be the same gap on both sides of the coloured status strips.

**Comment by albertkol** [comment]
It stays blocked until we have packages with component type universe.

**Comment by matthewpaulthomas** [comment]
[Specification updated](https://docs.google.com/document/d/1VuAElUpFay7MBFNmE3NhSyY9TkXiqHcA1ZHQ11AYO-Q/edit#heading=h.9a0ml5bppl8c).

> Another small tweak: there should be the same gap on both sides of the coloured status strips.

I have moved the Status column after the Component column, partly because the Component column will be quite narrow (reducing scanning required), and partly so that there will be only one transition between thin-grey and thick-coloured top borders rather than two.
