### ISSUE TITLE
Ubuntu Desktop 20.04 is not downloading

### ISSUE THREAD

**Issue by DragonTrail99** [canonical-web-and-design/ubuntu.com#8164]
---
*Reported from: https://ubuntu.com/download/desktop*

**Comment by carkod** [comment]
Hi @DragonTrail99,

Thanks for posting this issue. Can you provide us more information about the issue you are having? E.g.:
- What browser and Operating System are you using?
- Have you tried directly using the [download link](https://releases.ubuntu.com/20.04.1/ubuntu-20.04.1-desktop-amd64.iso?_ga=2.210154397.905016343.1599787621-1789892908.1596887378)?
- Do you have any pop-up blockers that might be interfering? 
- Are you behind a firewall or VPN?

**Comment by SirSamTumless** [comment]
Hopefully this issue is resolved. If not, please re-open it.
