### ISSUE TITLE
Amend the ubuntu.com homepage

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#8171]
Amends have come in from the PdMs and Mark on the homepage designs. They can be found in the [copy doc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit).

@lyubomir-popov Has made a template a template which could help and be found here: https://drive.google.com/drive/folders/1cmolEmQf11XwdiKH1YOGenGvuM1BD9uf

**Comment by meralonso** [comment]
@pmahnke I've updated homepage and have a couple of questions for you:
- Covid message could possibly go on a sort of cookie message?
- There's two links on several sections "learn more" and "contact us" - should we use a button and a link? maybe the neutral button instead of the primary? What do you think?

![Homepage v4](https://user-images.githubusercontent.com/65166314/91418725-723c4d80-e84a-11ea-8cf2-50f15a759202.jpg)

**Comment by pmahnke** [comment]
> Covid message could possibly go on a sort of cookie message?

I have removed it, for now, we will need to find another way to have them later, perhaps in the takeover banner itself? or as a spotlighted item in the blog section?

> There's two links on several sections "learn more" and "contact us" - should we use a button and a link? maybe the neutral button instead of the primary? What do you think?

I think Mark and Lech wanted it as links for now, but perhaps we can ask @caldav and he could test it?

**Comment by meralonso** [comment]
@pmahnke some ideas for the logo cloud:

![Homepage v4](https://user-images.githubusercontent.com/65166314/91554288-bdc42980-e926-11ea-9af8-e3c1d891dcdf.jpg)

![Homepage v4 Copy](https://user-images.githubusercontent.com/65166314/91554332-d5031700-e926-11ea-846e-874e5eecbfb4.jpg)

![Homepage v4 Copy 2](https://user-images.githubusercontent.com/65166314/91554376-e3e9c980-e926-11ea-9739-1b8b0acaf26f.jpg)

**Comment by meralonso** [comment]
@anthonydillon resized logos below - 

Modern enterprise open source
[AT&T](https://assets.ubuntu.com/v1/d8f890fb-logo-at%26t.svg)
[Google Cloud](https://assets.ubuntu.com/v1/901d5a91-Google+Cloud.png)
[Netflix](https://assets.ubuntu.com/v1/9dccb64d-Neflix.png)
[AWS](https://assets.ubuntu.com/v1/43d45da9-Anbox-logo-aws.png)
[Azure](https://assets.ubuntu.com/v1/d5e90eed-Microsoft+Azure.png)

Open source security:
[Nist](https://assets.ubuntu.com/v1/4f916821-NIST_logo.png)
[CSEC](https://assets.ubuntu.com/v1/906a6abb-csec_logo.png)
[@sec](https://assets.ubuntu.com/v1/acd3f22d-%40sec_logo.png) 
[CIS](https://assets.ubuntu.com/v1/f84dc60c-cis_logo.png)
[DISA](https://assets.ubuntu.com/v1/8049bb5f-DISA_logo.png)
