### ISSUE TITLE
Error in the text on the site

### ISSUE THREAD

**Issue by ergcode** [canonical-web-and-design/ubuntu.com#8176]
I found a gross error on https://ubuntu.com/desktop.
"Visually stunning, wherever it’s used
Ubuntu gets the most from your screen, with high definition and touchscreen support. 20.04 has a new default theme, Yaru, as well as integrated light and dark themes, resulting in Ubuntu getting a fresh new look while maintaining its signature feel. "

Ubuntu GNOME 3 - Cannot be used for day-to-day use with touch controls. The sensor is working. But managing the OS is almost impossible.
I tested it on 7 devices with touch controls, different manufacturers and years of release:
- I could not install Ubuntu without a keyboard. While filling in the account data, it is impossible to enter data in the password field and its confirmation. After connecting the keyboard on the fly - the device was not detected in the OS. Tested with various x86 tablets and keyboards.
- Any touch of the screen - duplicated twice or three times. Impossible to type or just manage apps. On some devices, the problem is less pronounced.
- Scrolling with a sensor in any application has a serious problem. If, while scrolling, you slide your finger over a menu item or link, but do not release your finger from the screen, the link will open.
- Unable to use the text selection tool. The elements are just microscopic.
- Touch control can only be used when the interface scaling is increased to 150-200%. However, some of the GNOME 3 elements are not scalable and cannot be used.
- In the OS settings, you cannot configure the on-screen keyboard, calibrate the sensor, configure the sensor control.

---
*Reported from: https://ubuntu.com/desktop*

**Comment by anthonydillon** [comment]
@ergcode thank you very much for taking the time to report this issue to us.

The content is stating touchscreen is supported at a high level and we appreciate these bugs are annoying. Please could you file these issues on the Ubuntu project itself?
https://bugs.launchpad.net/ubuntu
