### ISSUE TITLE
[Event] CloudNative Days Tokyo 2020 - Design the engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#8192]
Please design the page based on [this copy docx](https://docs.google.com/document/d/10DG5YnFFEoFTAlM3g2fo5mTtCyI6UXKKDfDSEuGGzvQ/edit).

For further information, [the brief can be found here](https://docs.google.com/document/d/1DvtZtxdTSqbDeP_Y-N0O7wf11KcVwWJP8vrVpXX_qew/edit#heading=h.meo0azuz09li).

For any content questions please reach out to amber.charitos@canonical.com or anastasia.valti@canonical.com.

**Comment by anthonydillon** [comment]
Dup

**Comment by steverydz** [comment]
@meralonso as mentioned in https://github.com/canonical-web-and-design/web-squad/issues/3062#issuecomment-685467142, this is the correct ticket

**Comment by cristinadresch** [comment]
@meralonso this is ready for you to work on, would you be able to do it this week?

**Comment by meralonso** [comment]
@cristinadresch @steverydz sorry but I'm still confused with this project - which is the translated copy I have to use? There's a copy doc and a brief template and they look like different events.
Which are the assets I have to design, takeover + engage page?

![Screenshot 2020-09-03 at 12 32 56](https://user-images.githubusercontent.com/65166314/92104572-cbbff180-ede1-11ea-88f7-4b2824ed3726.png)

![Screenshot 2020-09-03 at 12 33 11](https://user-images.githubusercontent.com/65166314/92104630-e1cdb200-ede1-11ea-8d98-4e08241db3f5.png)

**Comment by cristinadresch** [comment]
@meralonso I added the english and japan copy docs to [the epic description here](https://github.com/canonical-web-and-design/web-squad/issues/3061). But let me know if you need more clarification!

**Comment by meralonso** [comment]
Thanks @cristinadresch I've used the copy 'Ubuntu at CloudNative Days Tokyo 2020 / Watch the live demo stream' on assets below.
@waynecrosby what do you think?

Takeover

![Takeover - CloudNative Days Tokyo 2020](https://user-images.githubusercontent.com/65166314/92111607-d9c73f80-edec-11ea-9d51-3ee821e9fc5d.png)

Engage page
 
![Engage page - CloudNative Days Tokyo 2020](https://user-images.githubusercontent.com/65166314/92111642-e64b9800-edec-11ea-8858-b5c72a69e14d.png)

**Comment by waynecrosby** [comment]
@meralonso Can we add some suru elements to the grad background in the Engage page? Can you also use this illustration as we try not to use the solid approach here as it looks like our old pictogram style that is no longer used, thanks:
https://assets.ubuntu.com/v1/62a43ae9-Ubuntu-cloud.svg

**Comment by meralonso** [comment]
Thanks for the illustration @waynecrosby - I've updated the assets. RE engage page, I've used the template I always use (the one on the [drive](https://drive.google.com/drive/u/2/folders/1elo_W8y7xYwIiK3M5KIG9fLBV9NuV-nW)) is there any other one available or should I just create that for scratch for this artwork?

Takeover

![Takeover - CloudNative Days Tokyo 2020](https://user-images.githubusercontent.com/65166314/92124330-f15af400-edfd-11ea-8f64-6bb9c62d928b.png)

Engage page

![Engage page - CloudNative Days Tokyo 2020](https://user-images.githubusercontent.com/65166314/92124368-fb7cf280-edfd-11ea-9dde-a54b323db018.png)

**Comment by waynecrosby** [comment]
@meralonso Looks good, don't worry about the suru in this version, it might be because it's a Marketo generated page that we don't have too much control over. I'll engage Ant about updating it at another time. :)

**Comment by meralonso** [comment]
Great, thanks @waynecrosby 
@cristinadresch @anthonydillon I think this is ready to go!

**Comment by cristinadresch** [comment]
thanks @meralonso maybe i'm confused about this, but wondering if you looked at designing the whole page? at the bottom there there's the tshirt content. @anthonydillon would that be helpful?

**Comment by meralonso** [comment]
> thanks @meralonso maybe i'm confused about this, but wondering if you looked at designing the whole page? at the bottom there there's the tshirt content. @anthonydillon would that be helpful?

I've been confused with this one since the beginning @cristinadresch 😅  I'm happy to design the rest of the page @anthonydillon just let me know

**Comment by anthonydillon** [comment]
@meralonso let me take a pass and will ask if it needs a full design. Cheers.

**Comment by anthonydillon** [comment]
@cristinadresch @meralonso to help clear things up. This is just a single new page on jp.ubuntu.com.

Summary:
URL (will be): https://jp.ubuntu.com/cloudnativedasytokyo2020
Copy doc (in english): https://docs.google.com/document/d/1KdT9rlYyhCkDcsIGcrSaPKlo1yawZrTt1otHv3WlFSU/edit
Copy doc (in Japanese): https://docs.google.com/document/d/10DG5YnFFEoFTAlM3g2fo5mTtCyI6UXKKDfDSEuGGzvQ/edit

I could go ahead and build it something like this, but if you want to design feel free:
![pasted image 0](https://user-images.githubusercontent.com/1413534/92269405-0443f600-eedc-11ea-809d-114db3c8cf30.png)
