### ISSUE TITLE
Clicking the close button of a modal contact form triggers a submitted event

### ISSUE THREAD

**Issue by caldav** [canonical-web-and-design/ubuntu.com#8220]
## Summary

Clicking the close button of a modal contact form triggers a submitted event in addition to the expected "close" event.

## Ways to debug

* [Google Analytics debugger for Chrome](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna)
* Adding a console message to the "submitted" event function in `dynamic-contact-form.js`

**Comment by SirSamTumless** [comment]
@caldav Is this still an issue?

**Comment by steverydz** [comment]
@caldav I'm closing this as it doesn't seem to be an issue anymore
