### ISSUE TITLE
CUBE Indicative wireframes i2

### ISSUE THREAD

**Issue by cassiocassio** [canonical-web-and-design/ubuntu.com#8229]
https://zpl.io/ampEGl6

**Comment by cassiocassio** [comment]
@waynecrosby @marcushas 

Can you have a peek and then let's talk about

- general feedback
- areas of the pages, icons, navigation ripe for branding
- which of the ideas's you've proposed so far are front runners, and how they might work with these flows

**Comment by SirSamTumless** [comment]
@cassiocassio Any updates on this?

**Comment by cassiocassio** [comment]
Nothing new

**Comment by cassiocassio** [comment]
Nothing new

**Comment by SirSamTumless** [comment]
Can this be closed?
