### ISSUE TITLE
Stripe payment method needs to be set before we can show VAT

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#8235]
Encountered a wrinkle whilst implementing the VAT/purchase preview endpoint:

- we want to show the VAT to the user on the payment method screen (the first in the payment modal)
- the contracts API requires us to have created a payment method in Stripe, including address, so that they can make their VAT calculations based on what is in Stripe
- we don't create the payment method until the user has clicked "Continue" i.e. they are moving to the second screen of the modal
- this means, at the moment the contracts service doesn't have an address to work with and just assumes VAT applies regardless

Possible solutions to be investigated/validated:
- can we send an address to the VAT/purchase preview endpoint to get the figures we need without creating a payment method?
- can we only show VAT and Total figures on the second screen of the modal, when a payment method has been created?
- can we somehow create a temporary payment method when the user has filled out the required information, whose only purpose is to be used to calculate VAT and Total, then automatically discarded?

#### Tangentially related question:
- it looks like VAT is being returned in USD. I'm not certain what the rules are in other VAT-applicable countries, but the UK requires that VAT totals are shown in GBP, can we have that total returned in the appropriate currency?

Tagging @alnvdl too

**Comment by matthewpaulthomas** [comment]
> - can we send an address to the VAT/purchase preview endpoint to get the figures we need without creating a payment method?

A variation of this:
- Is there some non-Stripe mechanism we can use to determine VAT existence+rate before creating the payment method?

> - can we only show VAT and Total figures on the second screen of the modal, when a payment method has been created?

Well, we can, but this is the last resort. The amount of tax added might tip you over a threshold where you can’t:
- pay with this particular card; or
- pay by yourself, so you need to get approval/payment from someone else in your organisation; or
- afford the service at all.

So I’d rather avoid a situation where we’re keeping around a payment method that you aren’t going to use.

> at the moment the contracts service doesn't have an address to work with and just assumes VAT applies regardless

Since tax rates are different in different countries, how does it “assume VAT applies”?

**Comment by sowasred2012** [comment]
> Since tax rates are different in different countries, how does it “assume VAT applies”?

Adding this to the list of questions to pose to Allan - I don't yet know for certain, but I suspect it's based on a previously stored payment method/address. My experience of it so far has been, on an account on which I've previously made test purchases, sending a request to the VAT/purchase preview endpoint that consists only of an account ID and a list of products in my cart (i.e. no address information whatsoever), and getting a response that includes a VAT amount.

I think/hope the easiest solution would be to pass the selected country and (if present) a VAT number to the VAT/purchase preview endpoint.

**Comment by sowasred2012** [comment]
Closing - this has since been addressed and fixed as part of this upcoming PR https://github.com/canonical-web-and-design/ubuntu.com/pull/8244
