### ISSUE TITLE
/advantage/subscribe: Choosing machine type doesn’t focus quantity field

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#8247]
1\. Open /advantage/subscribe on an [`advantage-shop`](https://github.com/canonical-web-and-design/ubuntu.com/tree/advantage-shop) branch (for example, https://ubuntu-com-8244.demos.haus/advantage)
2\. Choose Servers, Other VMs, or Desktops

What happens:
- The page scrolls to the “How many” field

What should happen:
- The page scrolls to the “How many” field
- The field is focused so that you can type in it

[Discovered while testing #8244.]

**Comment by matthewpaulthomas** [comment]
The scrolling behaviour was dropped altogether as part of #8244. This was a quick way of fixing the problem that the page was bouncing up and down when using arrow keys to navigate between machine types.

However, this problem still exists as described: choosing a machine type doesn’t focus the quantity field. And the combination of (a) highly spacious layout and (b) lack of scrolling means the next step often isn’t visible, so it’s not clear what to do next.

![image](https://user-images.githubusercontent.com/19801137/96426509-3774e700-11f5-11eb-8f41-b6811d0a89c6.png)

Ideally, whenever you actually choose a machine type (by clicking, Space, or Enter), _if_ the quantity field is not already visible, the page scrolls smoothly just enough to reveal it, and then it’s focused. That way you can still see and double-check your machine-type choice if you need to.

**Comment by steverydz** [comment]
@matthewpaulthomas do you think we should have a selected state on the chosen option? By moving the focus to the quantity field there is no blue outline on the selected product, therefore nothing to indicate which option is selected.

**Comment by matthewpaulthomas** [comment]
@steverydz The selected item has a grey background. It’s a very light grey, so there might be a contrast problem. Perhaps take a photo (not just a screenshot) of how it appears on your screen and report a new issue.
