### ISSUE TITLE
[Smart start] static contact us form

### ISSUE THREAD

**Issue by carkod** [canonical-web-and-design/ubuntu.com#8257]
The static contact page can be copied from the maas.io/contact-us page.
This form will be in the smart-start/contact-us page

**Comment by carkod** [comment]
Using dynamic contact form

**Comment by pmahnke** [comment]
@carkod we need static and dynamic for people who don't have javascript turned on.

**Comment by anthonydillon** [comment]
@carkod You are linking to an existing contact us right? /contact-us/form

**Comment by anthonydillon** [comment]
@pmahnke this issue is that the discourse-docs module does not allow to static pages in the discourse path. Therefore the path /smart-start is claimed by the discourse docs module we can't put a static page at /smart-start/contact-us.

**Comment by carkod** [comment]
> @carkod You are linking to an existing contact us right? /contact-us/form

@pmahnke is linking to /support/contact-us [here](https://github.com/canonical-web-and-design/ubuntu.com/pull/8317) , which I think is fine? because we also need a thank-you for the modal form  /support/thank-you
