### ISSUE TITLE
Redesign /what-is-kubeflow

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#8261]

**Comment by meralonso** [comment]
Hey @SirSamTumless @RFMVasconcelos is there a copy doc for this page?

**Comment by SirSamTumless** [comment]
Yup - it's in the EPIC, but you can find it here too https://docs.google.com/document/d/1m-96RlGkbzFa1KaGAxYFpY0ztIlsTuViCjXSAlErQlg/edit#

**Comment by meralonso** [comment]
@SirSamTumless @spencerbygraves what do you think of this? 

![Kubeflow - What is Kubeflow](https://user-images.githubusercontent.com/65166314/94143965-d6b1f300-fe70-11ea-95d2-f9b9d83947f0.png)

**Comment by spencerbygraves** [comment]
Thanks @meralonso looks good.

**Comment by RFMVasconcelos** [comment]
Hi @meralonso! Thank you for taking on this task!

`What is Kubeflow?` section: Would it be possible to do 1 list of text items with a logo cloud on the right? 

The idea was for it to look like a list of components with a 1 liner description and have the logos appear as soon as the user scrolls. Please start with the Jupyter and Tensorflow logos :)

**Comment by meralonso** [comment]
Hey @RFMVasconcelos I have updated the design -  let me know if you are happy with it

![Kubeflow - What is Kubeflow Copy 2](https://user-images.githubusercontent.com/65166314/94437158-aaaeae80-019d-11eb-8d28-a65d8fd2a5e8.png)

**Comment by RFMVasconcelos** [comment]
Hi @meralonso, thank you for getting back to me on this! A few points:

- Contributor logos:
> - Can we remove vertical space around logos? We should have "What's inside Kubeflow?" above the fold, to show people that they should scroll?
> - **Intel logo:** Is this the latest intel logo?

- **What's inside Kubeflow:** 
> - Can we try removing separation lines between components?
> - The logo cloud looks weird this way. Could we find a way for it to look more like the copy doc? Maybe create an image with the cloud and add it as an image?

- **Why MLOps**: 
> - Could we have the quote just between the title and the paragraph and not break into columns? 
> - "Area = effort + code" - can we center with image?

**Comment by meralonso** [comment]
Hey @RFMVasconcelos I'm following vanilla patterns to build my design, and unfortunately some of your comments don't match those patterns.

- I drew a red line to show you what's above the fold - you can always swap 'contributors logos' and 'What's inside Kubeflow?' sections if the last one needs to be higher on the page.

- **What's inside Kubeflow?** - I have removed lines and centered logos within the column.

- **Why MLOps** / 
We usually follow this style for quotes, or go for a whole strip but without breaking title and copy.
We don't center align text unless there's a good reason for that.

![Kubeflow - What is Kubeflow Copy](https://user-images.githubusercontent.com/65166314/94567822-28d98680-026c-11eb-9d64-53b0f032248f.png)

**Comment by SirSamTumless** [comment]
@RFMVasconcelos I think this is good to go and @meralonso has addressed your comments so I am closing this.

**Comment by RFMVasconcelos** [comment]
Hey @SirSamTumless and @meralonso,

Thank you for the help here! 🚀 

Quick typo in **Why MLOps?** quote: "Wit (...) -> "It (...)".

Text below the image is a caption. Not sure what is the standard for that (I think it may be more clear centered, but I leave it up to you).

Many thanks!
