### ISSUE TITLE
Broken download link - ubuntu-20.04.1-desktop

### ISSUE THREAD

**Issue by dhilmathy** [canonical-web-and-design/ubuntu.com#8270]
20.04.1 ISO download link is broken.

https://ubuntu-releases.hbcse.tifr.res.in/ubuntu-releases/20.04.1/ubuntu-20.04.1-desktop-amd64.iso

---
*Reported from: https://ubuntu.com/

**Comment by anthonydillon** [comment]
@dhilmathy thank you very much for taking the time to report this issue.

I have requested that the mirror list be updated.

**Comment by anthonydillon** [comment]
Awaiting RT#127433

**Comment by jeet9026** [comment]
> 20.04.1 ISO download link is broken.
> 
> https://ubuntu-releases.hbcse.tifr.res.in/ubuntu-releases/20.04.1/ubuntu-20.04.1-desktop-amd64.iso
> 
> *Reported from: https://ubuntu.com/

i am facing same problem

**Comment by anthonydillon** [comment]
@jeet9026 We have cleared the cache. Can you check again.

**Comment by dhilmathy** [comment]
@anthonydillon it's still the same. Says "Not Found".

**Comment by jeet9026** [comment]
*Thank you so much, now i can download it thanks again for your quick
respond. i am so thankfull to you* 😊😊

**Comment by anthonydillon** [comment]
No problem @jeet9026.

@dhilmathy can you confirm you are able to download now too?

**Comment by dhilmathy** [comment]
@anthonydillon I wonder why it's not working for me still.

![image](https://user-images.githubusercontent.com/15025473/93174683-057ee980-f74c-11ea-9c05-cf8ed1d6d9d2.png)

**Comment by anthonydillon** [comment]
@dhilmathy did you use the website to download again? That mirror will not work but the website should select a different one now.

**Comment by dhilmathy** [comment]
@anthonydillon my bad, i was trying with older link. It's working when i am trying to download from website. Thanks!

**Comment by anthonydillon** [comment]
@dhilmathy thanks, glad to hear it.
