### ISSUE TITLE
error 404 

### ISSUE THREAD

**Issue by jeet9026** [canonical-web-and-design/ubuntu.com#8272]
---
*Reported from: https://ubuntu.com/download/desktop/thank-you?version=20.04.1&architecture=amd64

i have an issue to downloading ubuntu 20.04 desktop so kindly fix it, i need it very much 

reply asap.

**Comment by tbille** [comment]
hi @jeet9026,
Thanks for reporting this issue.

it seems we have an issue with some download mirrors on our side.
In the mean time you can find the image here: http://releases.ubuntu.com/20.04.1/

**Comment by anthonydillon** [comment]
Thank you, @jeet9026 could you let us know what URL is 404'ing? This will help us discover the mirror with the issue.

**Comment by tbille** [comment]
This seems to be resolved. Closing the issue.

@jeet9026 feel free to reopen if you see this error again.
