### ISSUE TITLE
Consider removing LiveChat from some security pages

### ISSUE THREAD

**Issue by mssalvatore** [canonical-web-and-design/ubuntu.com#8301]
## Summary

It is my assumption that the majority of the users/audience for ubuntu.com/security/notices and ubuntu.com/security/cves are sysadmins and engineers who are trying to get their jobs done. If this is true, the LiveChat assistance window that pops up is a distraction and an interruption, rather than an asset. It blocks essential data from view in some pages so it cannot be ignored.

In order to not annoy our users, I would like to recommend that the LiveChat assistance pop-up be disabled on ubuntu.com/security/cve and ubuntu.com/security/notice. This probably requires a broader discussion about who the audience is for these pages.

## Process

Go to ubuntu.com/security/cve and wait a few seconds.

## Current and expected result

After waiting some period of time, a chat window will pop up and someone will ask, "How may I help you?" For me, the answer is, "You may help me by leaving me alone. I'm trying to get my job done."

## Screenshot

![Screenshot_20200915_185256](https://user-images.githubusercontent.com/19957806/93272977-b7d2a300-f784-11ea-84c1-d76c5ec5da60.png)

**Comment by carkod** [comment]
We may want to involve Marketing or our CVEs/ESM/USNs product manager

**Comment by pmahnke** [comment]
@carkod I have emailed @campbieil

**Comment by Khutch25** [comment]
@campbieil @pmahnke So I saw this and chatted with @caldav about it and my suggestion would be we prevent livechat from initiating greetings on technical pages like these. To do this, I have raised [this issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/8305) for @anthonydillon to hopefully look into, as I believe you have fixed livechat bugs before?

**Comment by pmahnke** [comment]
I think Gunner has to do it.

**Comment by caldav** [comment]
Until we figure out a good way to selectively remove greetings (right now, they have page rules but also other rules based on time on page, etc and all the rules are OR based), I've simply removed LiveChat on /notices and /cve. We can close this issue for now.

**Comment by mssalvatore** [comment]
Thanks :)

**Comment by mssalvatore** [comment]
@caldav It looks like LiveChat is back on /cve. It's still gone on /notices.

**Comment by caldav** [comment]
Ouch, typo. Fixed.
