### ISSUE TITLE
Fix Livechat greetings (pop-up) bug so we can disable selectively on technical pages

### ISSUE THREAD

**Issue by Khutch25** [canonical-web-and-design/ubuntu.com#8305]
Hello! Raising this issue per conversations with @caldav to see if we could get the team to look at a bug in livechat that prevents us from disabling the pop up livechat greeting selectively on technical pages like /security/notices or any of the /docs pages.

David looked into this and apparently there are a lot of rules and if one is removed it still pops up through another rule like "10 seconds on a page", "returning visitor", etc.

**Comment by anthonydillon** [comment]
This is managed purely by the livechat admin. I do not have access. Maybe someone in sales?

**Comment by Khutch25** [comment]
For now Gunner disabled the greeting and @caldav is going to remove it from the /server/docs and /security/notices pages until we are able to find out how to link to it.
