### ISSUE TITLE
Roll out the new cookie policy across ubuntu.com

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#8309]
We need to coordinate a release of the cookie policy 3.x project:
- Bump the version in the `package.json` and test the cookie values work
- Add a global variable to GTM with the contents of the cookie
- Update the triggers to be conditional on the value of the cookie

**Comment by anthonydillon** [comment]
@pmahnke bumped this estimate for the GTM work which is complex for this project.

**Comment by pmahnke** [comment]
@cassiocassio why did you reopen this?
