### ISSUE TITLE
/advantage, /advantage/subscribe: Payment dialog doesn’t disable on submit

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#8319]
1\. Go to /advantage.
2\. Choose “Renew” or (once [`advantage-shop`](https://github.com/canonical-web-and-design/ubuntu.com/tree/advantage-shop) is merged) “Add another subscription” > “Purchase a subscription”.
3\. In the dialog, fill in the details and choose “Continue”.
4\. Choose “Pay”.

What happens:
3, 4. While the dialog is submitting, apart from “Continue”, all the other buttons and controls remain usable.

What should happen:
3, 4. While the dialog is submitting, [all the controls should be disabled](https://docs.google.com/document/d/1K65n3NpZCh7EWDXKLhG31seGJ2jKbW6lqw3BwV2mlnU/edit#heading=h.jwi4rns7fr68).

[Noticed during review of #8244.]

**Comment by sowasred2012** [comment]
Related feedback from @wgx:
> The spinner that appears in the the lower left is too subtle - the spinner should be larger, in the center and should 'block' input to prevent the user interacting with the view while payment details are submitted to Stripe.

**Comment by matthewpaulthomas** [comment]
Disabling the form will, by itself, make the spinner more noticeable.

If that’s not enough, we could make a case that Vanilla’s indeterminate spinner should be more obvious. It’s small, bland, and a small fraction of it moves, compared to the equivalents in [Material](https://material.io/components/progress-indicators#circular-progress-indicators), [Windows](https://docs.microsoft.com/en-us/uwp/api/Microsoft.UI.Xaml.Controls.ProgressRing?view=winui-2.4#remarks), [Carbon](https://www.carbondesignsystem.com/components/loading/usage#live-demo), or even [macOS](https://developer.apple.com/design/human-interface-guidelines/macos/indicators/progress-indicators/).

If that’s _still_ not enough, then we could center the spinner over the dialog contents. I’d rather leave that as a last resort, to avoid visual awkwardness of the spinner clashing with something underneath it.

**Comment by anthonydillon** [comment]
Both the Cancel and Continue buttons are disabled while purchasing? Is there something else that should be disabled?

**Comment by matthewpaulthomas** [comment]
Yes, [the whole form should be disabled](https://docs.google.com/document/d/1K65n3NpZCh7EWDXKLhG31seGJ2jKbW6lqw3BwV2mlnU/edit#heading=h.jwi4rns7fr68).
