### ISSUE TITLE
/advantage: Some subscriptions omitted or combined

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#8321]
A customer has multiple UA subscriptions, ending on 26 August, 6 September, 21 October, 2 December, and 7 January.

On /advantage, they see only one subscription, starting on 25 August and ending on 7 January. This suggests that the earlier subscriptions are being either conflated with the last one, or omitted altogether.

**Comment by steverydz** [comment]
I see multiple subscriptions on /advantage. Is this issue still valid?

**Comment by matthewpaulthomas** [comment]
@steverydz The first step will be to contact Hayley F. to find out which customer it is (I think she was the one who reported the problem in one of our UA meetings). Second to find a way to display the UI as it is displayed to that customer.
