### ISSUE TITLE
Blog imagery pixelation in feature image

### ISSUE THREAD

**Issue by Khutch25** [canonical-web-and-design/ubuntu.com#8341]
All blog images are resized in the preview image, causing pixelation of the image. Can this be looked at and fixed? Not sure if the solution is uploading a different feature image size, but this is the case with all of our blog posts with the image previews (I included two other examples below).

https://ubuntu.com/blog/design-and-web-team-summary-16th-september-2020
https://ubuntu.com/blog/an-introduction-to-testing-robot-code

---
*Reported from: https://ubuntu.com/blog/nosql-databases-what-is-mongodb-and-its-use-cases*

**Comment by SirSamTumless** [comment]
@Khutch25 Could you please provide a screenshot of the issue.

**Comment by Khutch25** [comment]
![Screenshot 2020-09-23 at 10 53 45](https://user-images.githubusercontent.com/42180941/93997329-3209b580-fd8b-11ea-9051-f79c41114005.png)
![Screenshot 2020-09-22 at 18 13 51](https://user-images.githubusercontent.com/42180941/93997341-3504a600-fd8b-11ea-99b7-97b74f1a3b19.png)
![Screenshot 2020-09-23 at 10 51 14](https://user-images.githubusercontent.com/42180941/93997342-3635d300-fd8b-11ea-8580-4d24abbc132d.png)
![Screenshot 2020-09-22 at 18 10 32](https://user-images.githubusercontent.com/42180941/93997349-3635d300-fd8b-11ea-8b69-c03641819f80.png)
![Screenshot 2020-09-23 at 10 50 15](https://user-images.githubusercontent.com/42180941/93997350-36ce6980-fd8b-11ea-908d-ba4a1f318c47.png)

**Comment by Khutch25** [comment]
You can see in any format, feature images (or really images for that matter) are pixelated and fuzzy in the URL preview images (see screenshots from where I pinged myself blog links on MatterMost), in the featured image section of the blog cards, and within the blog posts themselves.

Not sure if it's a wordpress bug, or if we need to get sizing recommendations from the design team?

**Comment by SirSamTumless** [comment]
Is it just happening on MM?

**Comment by Khutch25** [comment]
@SirSamTumless You can see it's happening on the blog itself. Any image that has text looks pixelated.

**Comment by pmahnke** [comment]
is this better?

![image](https://user-images.githubusercontent.com/441217/94140857-d0694a00-fe63-11ea-99cd-c13439053298.png)

https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,e_sharpen,w_330/https://ubuntu.com/wp-content/uploads/f680/Design-and-Web-Team-Blog.jpg


![image](https://user-images.githubusercontent.com/441217/94140933-f1319f80-fe63-11ea-912d-9b9b0729e0c6.png)

https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,e_sharpen,w_330/https://ubuntu.com/wp-content/uploads/d1bf/The-State-of-Robotics.jpg

**Comment by Khutch25** [comment]
It definitely looks better! What did you do?

**Comment by pmahnke** [comment]
added ,'e-sharpen' to the cloudinary string
