### ISSUE TITLE
Ubuntu Server iso download link is obscured and hidden from users

### ISSUE THREAD

**Issue by gorbehnare** [canonical-web-and-design/ubuntu.com#8354]
In order to download Ubuntu Server ISO a user (especially a new user) will be visiting the link, and the "Option 2" and "Option 3" are so obscured (under-emphasized, as if "Option 3" is being deliberately hidden). 

It took my students and I about 20min to figure out where to click to actually download the ISO file. I can just give students direct link to list of mirrors, but this is actually like teaching them "they want to sell you something instead of giving you the goods, so you have to go in from the backdoor if you want the OS". 

I don't know if this is a deliberate marketing decision, or beginnings of moving to a new type of business model, but either way this way of treating (new) customers does not reflect well on Ubuntu or Canonical (your existing users can figure it out, or search for a mirror because they know what they are looking for, but new users are being deliberately lead to believe that they need to signup for something called "Multipass"). 

---
*Reported from: https://ubuntu.com/download/server*

**Comment by tytus-kurek** [comment]
@gorbehnare thanks for raising that. User experience is very important to us. I'm happy to discuss the rationale behind this change over email. Would you mind reaching out to me at tytus.kurek@canonical.com ?
