### ISSUE TITLE
Page description doesn't reflect the content as UA service description

### ISSUE THREAD

**Issue by nobuto-m** [canonical-web-and-design/ubuntu.com#8355]
The page is about UA service description as in the enterprise support service, but somehow the page has a description about "How to deploy Ceph for Kubernetes" which doesn't make sense.

```
$ curl -s https://ubuntu.com/legal/ubuntu-advantage-service-description | grep :description
  <meta name="twitter:description" content="How to get Ceph deployed and related to Kubernetes in order to have a default storage class. This allows for easy storage allocation.">
  <meta property="og:description" content="How to get Ceph deployed and related to Kubernetes in order to have a default storage class. This allows for easy storage allocation.">
```

---
*Reported from: https://ubuntu.com/legal/ubuntu-advantage-service-description*

**Comment by pmahnke** [comment]
@nobuto-m thanks, we are going to be updating this page next iteration, so I will fix it then.

**Comment by pmahnke** [comment]
@nobuto-m thanks for finding this.  I assume someone copyed the page template from the ceph page.  I have updated it.
