### ISSUE TITLE
Create /appliance/rocket-chat

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#8358]
[Brief doc](https://docs.google.com/document/d/1cp8qGmKwpoLUmenlOHc6j6MILkiVLh9mEaqIv_VLZSU/edit?disco=AAAAIvZwPLg&ts=5f6cc323&usp_dm=true)

Create:

- [x] /appliance/rocket-chat
- [x] /appliance/rocket-chat/raspbery-pi2
- [x] /appliance/rocket-chat/raspbery-pi
- [x] /appliance/rocket-chat/intel-nuc

Add:
- [x] /appliance/portfolio

Update:
- [x] featured include, replace mosquitto

**Comment by anthonydillon** [comment]
These should be appliance/rocket-chat right?

**Comment by pmahnke** [comment]
copy pasting... yes
