### ISSUE TITLE
Update /legal/ubuntu-advantage-service-terms

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#8359]
Wait for @lechsandecki +1

- [Brief](https://docs.google.com/document/d/1N-PEWFsHf20pzInRzdD0RR0t3752hpDCFCdl4rgASGs/edit)

**Comment by SirSamTumless** [comment]
@lechsandecki Have you check this over?

**Comment by lechsandecki** [comment]
It talks about the UA Apps so we need to wait until the rest is ready before disclosing the new UASD. I think that we postpone till early November

**Comment by SirSamTumless** [comment]
@lechsandecki Aer these good to go?
