### ISSUE TITLE
CVEs in Universe packages aren’t shown

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#8367]
The new CVE pages do not show CVEs in Universe packages, because the CVE import does not include them.

This means:
- the new CVE pages are still less functional than [the old ones](https://people.canonical.com/~ubuntu-security/cve/universe.html)
- the component field of the search form is ineffective, and therefore hidden.

This is needed by November-ish for product promotion purposes.

**Comment by albertkol** [comment]
Blocked by security.
