### ISSUE TITLE
Series as a selection step

### ISSUE THREAD

**Issue by urosj** [canonical-web-and-design/ubuntu.com#8378]
In the current design it looks like I *have* to select series, or if I dont, it seems the selection is made for me to default with 20.04. It might mislead me that I have to select 5 desktops for 20.04 and 5 desktops for 18.04, only to find out that they all add up to 10 in the cart above. I find the series part a bit confusing.

Do we also track the choice of series anywhere if the selection is the UI? Could it be that this UI component is done clearly that it only has informative value?

**Comment by wgx** [comment]
> Is it usual that an estate would have lots of different versions of ubuntu?
> 
> I don’t know how common it is to have a multi-Ubuntu-release organisation
> 
> but the current UI could give the impression that the whole subscription must be on the same release, which isn’t the case
> 
> We could solve that by changing from tabs to checkboxes — but that would make it look even more as if the choice has an effect on your purchase, when it doesn’t
> 
> Could we somehow make it more of an 'information panel' rather than a step in the 'wizard' ? 
> 
> An earlier question: do we think we need to fix this?
> 
> Yeah, I’m wondering about funky visual design to make the section look like it’s a set of index cards or something
> 
> just to emphasise that it’s not part of the form


**To raise in user interviews next week.**
