### ISSUE TITLE
Icon on "Get your free token" doesn't expand the dropdown on /advantage

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#8383]
Reported by Uros in Mattermost:

>if i click on the arrow part of the "Get your free token" button, it doesnt expand
>if i click anywhere else in that button area, it's fine
>but the arrow, the UI element just gets highlighted and that's it
>btw. this is on the /advantage not the testing site

**Comment by anthonydillon** [comment]
Fixed by https://github.com/canonical-web-and-design/ubuntu.com/pull/8525

**Comment by anthonydillon** [comment]
This has merged.
