### ISSUE TITLE
Logo white backgrounds in gray sections

### ISSUE THREAD

**Issue by Khutch25** [canonical-web-and-design/ubuntu.com#8385]
Hello - @lechsandecki noticed that with the addition of the webinar card, it moved the other sections with logos with white backgrounds into sections with gray backgrounds, so now you can see there are logos with white backgrounds. 

Can the section background/order be updated, or can the logos be updated to have transparent backgrounds?
---
*Reported from: https://ubuntu.com/security/certifications*

**Comment by pmahnke** [comment]
I have updated the logos with transparent ones
