### ISSUE TITLE
No upper bound to the amount of subscriptions a user can buy

### ISSUE THREAD

**Issue by wgx** [canonical-web-and-design/ubuntu.com#8393]
It's possible to request licences for 999999999999999999999999999 machines. There should be some sensible upper bound to the amount you can buy to prevent us attempting to bill a quintillion dollars through Stripe.

**Comment by matthewpaulthomas** [comment]
From discussion with UA team members, 1000 is a reasonable maximum. [Spec updated](https://docs.google.com/document/d/1K65n3NpZCh7EWDXKLhG31seGJ2jKbW6lqw3BwV2mlnU/edit#bookmark=id.sw7domezfvel).
