### ISSUE TITLE
Stripe checkout not localised for UK users

### ISSUE THREAD

**Issue by wgx** [canonical-web-and-design/ubuntu.com#8396]
Once the locale is changed to United Kingdom, it should be possible to show "Postcode" in the Stripe checkout UI - rather than ZIP which won't be known to some UK users, and will be left blank, resulting in a failed payment. 

I would also recommend moving the card entry Stripe control to be *below* the rest of the fields on the page so this makes more sense to users because of the postal code and tax line item. 

![image](https://user-images.githubusercontent.com/930099/94693054-2b4ee580-032b-11eb-8dee-aa8f4974e983.png)

**Comment by sowasred2012** [comment]
Stripe infers a country from the card number - in this instance, 4242 4242 4242 4242 is a US card, so it is correctly showing a ZIP field. If you were to use a UK test card (4000008260000000), you would see a postcode field appear.
