### ISSUE TITLE
[Datasheet] Core 20

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#8404]

**Comment by SirSamTumless** [comment]
Waiting on sign-off of the content from Sarah.

**Comment by SirSamTumless** [comment]
Waiting on Galem to provide image links.

**Comment by SirSamTumless** [comment]
[Ubuntu_Core20_Datasheet-02.11.20.pdf](https://github.com/canonical-web-and-design/ubuntu.com/files/5476674/Ubuntu_Core20_Datasheet-02.11.20.pdf)

@waynecrosby Can you review this?

**Comment by waynecrosby** [comment]
Sure I'll take a look

**Comment by SirSamTumless** [comment]
@xxl007 Please find the datasheet attached

**Comment by xxl007** [comment]
@SirSamTumless thanks for this. It looks awesome. I have spotted some typos, and some words not in sync with updates following Sarah's comments. I have highlighted the diffs in yellow in the [copydoc](https://docs.google.com/document/d/1GjW2SohGnRVbtFC1Emv8uUjzYcIwxyO84XCpUOaUR3g/edit?usp=sharing)

Also, there seems to be a typo in the first illustration! **"Lean Ubuntu"** rather than "Learn Ubuntu".

**Comment by SirSamTumless** [comment]
@xxl007 Please could you re-highlight the changes on this sheet https://docs.google.com/document/d/1RnaDAEMm0yhoSj6A1_4YOAx7pUsNYf8JezOQyXOl9Yw/edit#heading=h.a5mcl1crysfl as we cana't share the one above with our UpWork. Alternatively  you can move that file to your own drive and change the access to be shared with "anyone".

**Comment by xxl007** [comment]
Done. I have transferred it to my drive and changed access to "anyone". Thanks.

**Comment by SirSamTumless** [comment]
[Ubuntu_Core20_Datasheet-06.11.20.pdf](https://github.com/canonical-web-and-design/ubuntu.com/files/5500786/Ubuntu_Core20_Datasheet-06.11.20.pdf)

@xxl007 Please review the attached.

**Comment by xxl007** [comment]
Thanks for the update @SirSamTumless . The only thing missing is the correction of the typo in the first illustration:

**"Lean Ubuntu"** rather than "Learn Ubuntu", please.

Otherwise perfect, it looks awesome.

**Comment by SirSamTumless** [comment]
[Ubuntu_Core20_Datasheet-06.11.20 2.pdf](https://github.com/canonic@xxl007 web-and-design/ubuntu.com/files/5501273/Ubuntu_Core20_Datasheet-06.11.20.2.pdf)

Here you go @xx Let me know if it is good!

**Comment by xxl007** [comment]
Perfect thanks!
