### ISSUE TITLE
[Cases study] PAC Radar - Design the Takeover +  Engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#8425]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1ciQOsfcZKpPVGEYALSqzKBovGTjOg9UJ5mduwCn43Dc/edit#gid=0) and [design](3021):
 
- [ ] build takeover
- [x] build engage page
- [ ] add takeover to `/takeovers/index.html`
- [ ] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [ ] build a [social banner](https://tools.demos.haus/) and use the 1200px x 630px one
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by SirSamTumless** [comment]
Please don't put takeover live, just engage page.

**Comment by bethcollins92** [comment]
engage page created on discourse and live here: https://ubuntu.com/engage/pac-radar
