### ISSUE TITLE
[COPY UPDATE] /what-is-ros - "What is ROS"

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#8429]
Please update /what-is-ros - "What is ROS" from the [copy doc](https://docs.google.com/document/d/1yX2Ikcn1fgIKX3el8fKWQt7SGxSwY633TfW5V1lwUuc/edit?ts=5f7af517#heading=h.vbzgtki4500k)

**Comment by meralonso** [comment]
@SirSamTumless this page looked a bit old and not aligned with the other pages (overview and community). @bethcollins92 if you can update the design that'll be great 

![Robotics - What is ROS](https://user-images.githubusercontent.com/65166314/96573833-f6e99c00-12ce-11eb-837f-d8dd5aee7940.png)

**Comment by meralonso** [comment]
@bethcollins92 I have updated last 'Join the community section'. Asset [here](https://assets.ubuntu.com/v1/69237fec-ROS-10-years.png)

![Robotics - What is ROS](https://user-images.githubusercontent.com/65166314/96594713-34f4b900-12eb-11eb-9376-d1b68da6d34e.png)
