### ISSUE TITLE
Error 500: internal server error

### ISSUE THREAD

**Issue by xxl007** [canonical-web-and-design/ubuntu.com#8433]
Many visitors (including myself) have reported an error 500 while visiting the pages under https://ubuntu.com/smart-start/guide/...
---
*Reported from: https://ubuntu.com/smart-start/guide*

**Comment by pmahnke** [comment]
like when? can you provide more details as to timings?  also, when are you removing that silly menu at the top of each page?

**Comment by anthonydillon** [comment]
I am not seeing error reports for smart-start in sentry. There are a number of errors in engage section. Are you referring to that section?

**Comment by tbille** [comment]
Status:
1. I am investigating on discourse side if there is a limitation for private categories & api requests done.
2. Checking in the list of IPs on discourse if it gets blocked  and update to allow IP all the time

**Comment by tbille** [comment]
it seems there is a limit for [users API keys](https://meta.discourse.org/t/global-rate-limits-and-throttling-in-discourse/78612). Default: 20.

We can investigate as a temporary before release to update the API key to be a admin API key and update the limit ratio for those keys.

**Comment by carkod** [comment]
[RT](https://portal.admin.canonical.com/C128082) in progress
