### ISSUE TITLE
Engage thank you page issues

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#8440]
1. They say 'webinar, whitepaper'

![image](https://user-images.githubusercontent.com/441217/95500835-54ace880-099f-11eb-83ad-c84c599d2738.png)

It should just say whitepaper in this case.

2. They have _other_ language engage pages recommended.

![image](https://user-images.githubusercontent.com/441217/95500881-6b533f80-099f-11eb-9626-243f741e5264.png)

It should only show engage pages in the same language.

---
*Reported from: https://ubuntu.com/engage/vmware-to-charmed-openstack/thank-you*

**Comment by carkod** [comment]
Fixed. https://ubuntu.com/engage/vmware-to-charmed-openstack/thank-you

**Comment by pmahnke** [comment]
@carkod point 2 doesn't look fixed? am I missing something?
