### ISSUE TITLE
Multipass logo edges are cut on big screens on Chromium Version 85.0.4183.121

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/ubuntu.com#8461]
![image](https://user-images.githubusercontent.com/40214246/95882952-36b20000-0d72-11eb-8aed-ffff26986041.png)

---
*Reported from: https://ubuntu.com/appliance/adguard*

**Comment by SirSamTumless** [comment]
Have you zoomed out in the screnshot above?

**Comment by pmahnke** [comment]
Need to change `style="width:30%"` to actual px

**Comment by solazio** [comment]
> Have you zoomed out in the screenshot above?

NO, I just have a big scree. It works fine in FF.
