### ISSUE TITLE
Ubuntu server alternate download for ARM is 20.10

### ISSUE THREAD

**Issue by dannf** [canonical-web-and-design/ubuntu.com#8497]
The ubuntu download page for server presents various alternative downloads. But its weird that we have an ARM/20.10 download there. I mean, 20.10 isn't GA yet, and there's no option for ARM 20.04 - which I'd expect.

---
*Reported from: https://ubuntu.com/download/server*

**Comment by SirSamTumless** [comment]
Could you look into this please @tytus-kurek?

**Comment by tytus-kurek** [comment]
So there is an error on the page compared to what's in the copy doc:

https://docs.google.com/document/d/12kr3JvN3ALMdr5IPOheMwOaf-ygvEulFo5D7x-0ag0k/edit

There are two sections:
- Alternative downloads - the first bullet in this section should be "Ubuntu Server 20.10", but currently it's "Ubuntu Server for ARM"
- Alternative architectures - this section looks all good

**Comment by pmahnke** [comment]
@dannf thanks, there were a few errors, we have fixed it for the 20.10 release tomorrow

**Comment by dannf** [comment]
On Wed, Oct 21, 2020 at 11:27 AM Peter Mahnke <notifications@github.com> wrote:
>
> @dannf thanks, there were a few errors, we have fixed it for the 20.10 release tomorrow

Fantastic! Nice work.
