### ISSUE TITLE
Zip code doesn't switch to regional equivalents when inputting billing details

### ISSUE THREAD

**Issue by alysonrose88** [canonical-web-and-design/ubuntu.com#8498]
Not sure if this is due to the limitations of the staging environment or an actual issue, but when I input my billing address during payment, the zip code field does not switch to postcode after I switch region to U.K. (this seems to be true of all non US regions). The field would not accept my U.K. postcode, so I ended up using a U.K. address with an LA zip code to complete the payment.

**Comment by sowasred2012** [comment]
Based on the credit card number, Stripe is able to infer the country the card was issued in, and presents the user with the appropriate zip/postal field accordingly - the 4242 4242 4242 4242 test card is US based, hence the zip field. You can test other countries and territories with Stripe's [international test cards](https://stripe.com/docs/testing#international-cards).
