### ISSUE TITLE
Physical subscriptions do not show availability for guests

### ISSUE THREAD

**Issue by alysonrose88** [canonical-web-and-design/ubuntu.com#8499]
The way that UAI for physical servers appears in /advantage suggests there is not unlimited guest support: under the 'attached' column, you see no. of attached/no. of physical machines covered. This will definitely be confusing for some customers. I have also spoken to customers running lots of or ephemeral guests on physical hosts who like to keep track of how many attached machines they have in total (though I am guessing attached VMs would show up in that field too, and the customer would see something like 100/10 machines attached?)

I wonder if we could indicate when a customer has unlimited guest support, perhaps as a note that appears in the box with the UA attach commands or as a note that appears in the box with the start and end date of subscription. Are we able to get that granular with what we show customers?

**Comment by sowasred2012** [comment]
If attached machines count is larger than physical machine allowance count, we only show the number of attached machines i.e. the user in your example would see "100" rather than "100/10". Doesn't solve the wider point you're making though!

**Comment by matthewpaulthomas** [comment]
I had not heard of “unlimited guest support” until now — it doesn’t seem to be mentioned in the service description, or anywhere else on ubuntu.com.

A few questions to help me with the design:

- Does this apply just to Virtual Server subscriptions, or do you get unlimited guests with Desktop and Physical Server subscriptions too?
  - If it’s for Virtual Server subscriptions, what is the purpose of letting you specify a quantity when purchasing? (As opposed to just buying it or not.)

- Is there an API for us to tell which attachments are guests and which aren’t?

**Comment by alysonrose88** [comment]
The unlimited support is mentioned in this part of the service description: https://ubuntu.com/legal/ubuntu-advantage-service-description#uasd-subscription

"When an Ubuntu Advantage subscription is attached to a physical host running a Covered Hypervisor, it covers the same services for all Ubuntu guests on that host."

- It applies only to Physical Server subscriptions, with all Ubuntu-based virtual machines and containers running on top of a covered server included
- I think we don't have an API, IIRC Uros knows a little more on that

**Comment by matthewpaulthomas** [comment]
I’ve designed a fix for this as part of [web-squad#3650](https://github.com/canonical-web-and-design/web-squad/issues/3650).

[Specification updated](https://docs.google.com/document/d/1K65n3NpZCh7EWDXKLhG31seGJ2jKbW6lqw3BwV2mlnU/edit#heading=h.f7dy3jcidqik):
> The “Machines” column should contain:
> …
>the number of machines “Attached:” — and, if it is a physical server subscription, an explanation that “You can have multiple attached VMs on one server.”

**Comment by wgx** [comment]
This will be tackled in 22.04 with Machine Activity.
