### ISSUE TITLE
/advantage/subscribe: E-mail address not appropriate as account name

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#8522]
From [CS team review of the new UA purchase process](https://docs.google.com/document/d/1kRqawNqi3ISXPqGohaAyu-QQEJlrGZiVv-Bn8bQfago/edit#heading=h.gt47y3jxsduu):
> Account name needs to be provided as part of the payment experience. The email is not enough and not correct for naming accounts. Multiple accounts with the same name are ok but probably we want to postpone an incremental number in case of clashes.

**Comment by anthonydillon** [comment]
@matthewpaulthomas are you working on a wireframe of the solution?

**Comment by matthewpaulthomas** [comment]
@frankban Something like this?

![payment-details-fields](https://user-images.githubusercontent.com/19801137/96612784-19db7680-12f6-11eb-97b2-0fce8dcee9d6.png)

**Comment by frankban** [comment]
Looks good to me. I am working on a branch that enables that. We can then have a follow-up branch that fixes the form.
