### ISSUE TITLE
Ubuntu FIPS link is 404

### ISSUE THREAD

**Issue by AJCxZ0** [canonical-web-and-design/ubuntu.com#8531]
Link to [Ubuntu FIPS](https://security-certs.docs.ubuntu.com/en/fips-16) [Corrected URL] is 404.

---
*Reported from: https://ubuntu.com/blog/fips-140-2-stay-compliant-and-secure-with-canonical*

**Comment by pmahnke** [comment]
I think it is the docs link - https://docs.ubuntu.com/security-certs/en/fips-16 @lechsandecki

**Comment by lechsandecki** [comment]
interesting, not sure why it's gone.
good catch -if needed we could link to https://ubuntu.com/security/certifications#fips instead
