### ISSUE TITLE
ua shop payment form: make it clear that the provided email will have to be used for retrieving the contract later, when signing in

### ISSUE THREAD

**Issue by frankban** [canonical-web-and-design/ubuntu.com#8536]
Feedback from commercial systems CIP130.

**Comment by matthewpaulthomas** [comment]
Thanks for spotting this. [This was already in the design](https://docs.google.com/document/d/1K65n3NpZCh7EWDXKLhG31seGJ2jKbW6lqw3BwV2mlnU/edit#heading=h.mz73r7dju49w), but hasn’t been implemented yet: “When you choose ‘Buy now…’ … The e-mail address field should have a caption: ‘We’ll also send setup instructions to this address.’.”
