### ISSUE TITLE
ua shop: VAT handling improvements

### ISSUE THREAD

**Issue by frankban** [canonical-web-and-design/ubuntu.com#8538]
The current way of handling VAT is simplistic. We should gather requirements from finance and fix the form accordingly.
This must be done in sync with commercial systems, as backend changes might be necessary.
This could involve asking whether the customer is making a company purchase vs personal.
Not a blocker for shop release.

**Comment by wgx** [comment]
@frankban We derive the VAT amount from the API, so closing.
