### ISSUE TITLE
ua shop: improve upselling experience

### ISSUE THREAD

**Issue by frankban** [canonical-web-and-design/ubuntu.com#8539]
There is no need to re-build a product when upselling. I know that Will already have initial mockups for this, but wanted to capture this as a bug. If a bug already exists, feel free to mark this as duplicate.

**Comment by matthewpaulthomas** [comment]
@frankban By “upselling” in this context do you mean being persuaded to:
a. choose Standard when you’d initially chosen Essential, or Advanced when you’d initially chosen Standard;
b. add UA for a set of machines of a different type, as part of the same purchase;
c. something else?

**Comment by frankban** [comment]
Adding more machines to an existing contract. Today I buy uai-standard-virtual for 2 machines. Tomorrow I want to byt 3 more, for uai-standard-virtual.

**Comment by matthewpaulthomas** [comment]
Ah, so not part of the same purchase at all. That’s a bit different from the usual meaning. In [the UA priorities list](https://docs.google.com/spreadsheets/d/12G7YS6XlmxKzIIqmBVdtoR1VmCCqeuaTBGT1gGTC_Tg/edit) this is “Change number of licenses”.

**Comment by sowasred2012** [comment]
There's a related discussion [here](https://github.com/canonical-web-and-design/ubuntu.com/issues/8392)

**Comment by matthewpaulthomas** [comment]
Sorry I’d overlooked this report. This feature is now in progress, with the implementation part covered by #9048.
