### ISSUE TITLE
ua shop: Implement a page for retrieving/downloading receipts

### ISSUE THREAD

**Issue by frankban** [canonical-web-and-design/ubuntu.com#8540]
They will be sent via email, but that's probably not sufficient.
IIRC, I've seen mockup about a similar page in the context of an extended /advantage experience.
Feedback from commercial systems CIP130.

**Comment by matthewpaulthomas** [comment]
We had recorded this in [the UA priorities list](https://docs.google.com/spreadsheets/d/12G7YS6XlmxKzIIqmBVdtoR1VmCCqeuaTBGT1gGTC_Tg/edit) as “Access past invoices”.

**Comment by matthewpaulthomas** [comment]
@elioqoshi @wgx This page could also be where your current credit balance is shown.

**Comment by elioqoshi** [comment]
Yeah that is sensible. I think @wgx mockup showed a place where invoices could be accessed?

**Comment by wgx** [comment]
![image](https://user-images.githubusercontent.com/930099/106019613-bf9f3e00-60ba-11eb-98e0-5d9163466e16.png)

Proto is here: https://www.sketch.com/s/68a07784-0c6d-49b8-9eb7-4d711af601eb/a/0wMdDe/play

It does, however, depend on the new "User profile in navigation bar" work that @anasereijo and @cassiocassio were working on for CUBE.

**Comment by anasereijo** [comment]
> ![image](https://user-images.githubusercontent.com/930099/106019613-bf9f3e00-60ba-11eb-98e0-5d9163466e16.png)
> 
> Proto is here: https://www.sketch.com/s/68a07784-0c6d-49b8-9eb7-4d711af601eb/a/0wMdDe/play
> 
> It does, however, depend on the new "User profile in navigation bar" work that @anasereijo and @cassiocassio were working on for CUBE.

@wgx thanks for sharing this. If this is something that you think needs to be in the user profile dropdown @cassiocassio and I will take it into consideration when finalising the UX and Design.

**Comment by cassiocassio** [comment]
Is this not a truer picture of u.com secondary nav for the support / navigation?

(and similar for CUBE, if we're hunting for a home for "account / settings / payment methods / history"

<img width="1268" alt="Screenshot 2021-01-27 at 17 11 05" src="https://user-images.githubusercontent.com/4593556/106027490-d77ac000-60c2-11eb-82d3-b418b409e8f9.png">

**Comment by wgx** [comment]
@cassiocassio Martin is right - this makes way more sense. The user dropdown should be for global things, and the sub-nav for product related things, like Invoices, Payment Methods, etc.

**Comment by elioqoshi** [comment]
@wgx @SirSamTumless do we need to pick this up again?

**Comment by wgx** [comment]
@elioqoshi If it gets prioritised into the next cycle then we'll approach it.

**Comment by elioqoshi** [comment]
Yep, just making sure we clean up these older issues.

**Comment by wgx** [comment]
This can be closed - reflected in current iteration work: https://github.com/canonical-web-and-design/master-epics/issues/282
