### ISSUE TITLE
Floating Raspberry 

### ISSUE THREAD

**Issue by rhys-the-davies** [canonical-web-and-design/ubuntu.com#8574]
The image of the Raspberry Pi logo has managed to move across the page and looks strange. Can we put it back? 

---
*Reported from: https://ubuntu.com/download/raspberry-pi*

**Comment by bethcollins92** [comment]
This issue has been fixed already, it was correct in staging but hadn't been deployed to prod. Now the fix is live 👍

**Comment by rhys-the-davies** [comment]
It doesn't look live ... ? 

For me it now jumps from the correct position, to here:
![Screenshot from 2020-10-23 12-38-47](https://user-images.githubusercontent.com/56505487/96999258-cdc64700-152c-11eb-92a0-b1e072b3fd98.png)

**Comment by bethcollins92** [comment]
@rhys-the-davies We're thinking it's a problem with caching - looking into it now 👍

**Comment by bethcollins92** [comment]
@rhys-the-davies Can you try now please?
