### ISSUE TITLE
Map not displaying

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#8582]
---
*Reported from: https://ubuntu.com/desktop/statistics*

**Comment by anthonydillon** [comment]
`/static/js/data/world-110m-country-names.tsv` is missing

**Comment by pmahnke** [comment]
and the json file

https://raw.githubusercontent.com/heaversm/d3-prototypes/master/app/json/world-110m-country-names%20copy.tsv

https://github.com/d3/d3.github.com/blob/master/world-110m.v1.json
