### ISSUE TITLE
[Whitepaper] Enterprise Kubernetes challenges  (IT) - Build the Takeover +  Engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#8586]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1mcDzKheGVezIF3gNhpbEd7-GM9siycXF6ul77Zw-dlg/edit?ts=5f85c9f2#gid=0) and [the old design](https://github.com/canonical-web-and-design/ubuntu.com/issues/8115):
 
- [x] build takeover
- [x] build engage page
- [x] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [ ] build a [social banner](https://tools.demos.haus/) and use the 1200px x 630px one
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by bethcollins92** [comment]
Waiting on PDF

**Comment by SirSamTumless** [comment]
https://pages.ubuntu.com/rs/066-EOV-335/images/IT_Accelerate_Kubernetes_enterprise_16.11.20.pdf 

PDF is here

**Comment by bethcollins92** [comment]
See engage page here: https://ubuntu.com/engage/it/deployment-azienda-manuale
Edit on [discourse](https://discourse.ubuntu.com/t/cinque-strategie-per-accelerare-limplementazione-di-kubernetes-nellimpresa/19381)
See takeover live on homepage when browser language is Italian
