### ISSUE TITLE
[Whitepaper] Redhat (JP) - Build the Takeover +  Engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#8587]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/13firz3mP7JA2NmCLFLS_o51uCyqMgpwgK05KswPW-Ww/edit#gid=0) and [old design](https://github.com/canonical-web-and-design/ubuntu.com/pull/8000):
 
- [x] build takeover
- [x] build engage page
- [ ] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [ ] add engage page to `/engage/index.html`
- [ ] build a [social banner](https://tools.demos.haus/) and use the 1200px x 630px one
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by SirSamTumless** [comment]
PDF link https://pages.ubuntu.com/rs/066-EOV-335/images/JP_Comparing.OpenStack_05.11.20.pdf

**Comment by AmberCharitos** [comment]
@SirSamTumless when will this become visible on the site? :)

**Comment by SirSamTumless** [comment]
Should be visible now @AmberCharitos

**Comment by bethcollins92** [comment]
Social banner - 

![image](https://user-images.githubusercontent.com/58959073/98568566-24f84580-22a9-11eb-99c0-7ce717b6a5dd.png)
