### ISSUE TITLE
[new /cloud page] design page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#8593]
Based on this [brief](https://docs.google.com/document/d/1FBS07dSAdKx6ApC_jQn1IJGoSjYsGCG3xN2JiiVnOZ0/edit#heading=h.meo0azuz09li) and this [copy doc](https://docs.google.com/document/d/1DJZFADvRr_hrHzRWJrUTJxAM2ocZJ_ZWEnQVdKi6JBE/edit), design and build the /cloud page

**Comment by meralonso** [comment]
@spencerbygraves what do you think of this layout? @waynecrosby it'd be great if you can help me find the right illustrations!

![Cloud](https://user-images.githubusercontent.com/65166314/98128820-a8382680-1eb8-11eb-8780-44d55bae2dac.png)

**Comment by waynecrosby** [comment]
@meralonso Here are some illustrations to use:
Private vs Public Header:
https://assets.ubuntu.com/v1/ab87e245-Private-v-Public-Mulit-Cloud.svg

Private Cloud:
https://assets.ubuntu.com/v1/f25ccac7-Private+Cloud.svg

Public Cloud:
https://assets.ubuntu.com/v1/a3694a61-Public+Cloud.svg

Hybrid Cloud:
https://assets.ubuntu.com/v1/45120edb-Hybrid+Cloud.svg

Multi-Cloud:
https://assets.ubuntu.com/v1/04d70172-Multi-Cloud.svg

Edge Cloud:
https://assets.ubuntu.com/v1/f24913d5-Edge+Cloud.svg

**Comment by meralonso** [comment]
@waynecrosby one of the cloud shape has moved on the multi-cloud illustration and I can't fix it, could you please have a look?

![Uploading Screenshot 2020-11-10 at 09.58.04.png…]()

@spencerbygraves what do you think of this design below?

![Cloud](https://user-images.githubusercontent.com/65166314/98658579-83720200-2343-11eb-93c0-5563bb51e9e4.png)

**Comment by waynecrosby** [comment]
@meralonso Here is an updated graphic to use:
https://assets.ubuntu.com/v1/dd0465c8-Multi-Cloud.svg

**Comment by meralonso** [comment]
> @meralonso Here is an updated graphic to use:
> https://assets.ubuntu.com/v1/dd0465c8-Multi-Cloud.svg

cool, thanks @waynecrosby @spencerbygraves - this is ready to go @SirSamTumless
