### ISSUE TITLE
20.10 engage page - change whitepaper form to webinar 

### ISSUE THREAD

**Issue by AmberCharitos** [canonical-web-and-design/ubuntu.com#8607]
## Summary

https://ubuntu.com/engage/ubuntu-20.10 page which is being linked from the takeover has a form to download a whitepaper and is sending to a 404 page instead of being a link to this BrightTalk webinar https://www.brighttalk.com/webcast/6793/448578

**Comment by pmahnke** [comment]
Fixed, it requires a blank line for 'form_id'
