### ISSUE TITLE
Raspberry Pi images are 404ing

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#8628]
Reported to webmaster:

I want to use the image for a project I am working on but it seems this link is down or not working at the moment:

https://ubuntu.com/download/raspberry-pi/thank-you?version=18.04.4&architecture=arm64+raspi3

The link that links to the download is here: 
https://wiki.ubuntu.com/ARM/RaspberryPi

Is this img still available? Thank you so much for your help.

**Comment by pmahnke** [comment]
The iso images changed their naming format slightly. We are not even promoting them on ubuntu.com any more. It would be a fair bit of work to make them work and I don't think it is worth it.  However, you can still get them here: http://cdimage.ubuntu.com/releases/bionic/release/.

As far as I see the wiki doesn't link to ubuntu.com.

**Comment by anthonydillon** [comment]
Can they add redirects when renaming images? There are a lot of links out there to the old links including every image link on the wiki.

**Comment by pmahnke** [comment]
I see, on the wiki, it was pointing to 18.04.**4** not .5, I have updated that.

**Comment by anthonydillon** [comment]
Thanks @pmahnke I think that covers this issue and the raspberry pi team will update the wiki page at some point.
