### ISSUE TITLE
500: Server error

### ISSUE THREAD

**Issue by thishanr** [canonical-web-and-design/ubuntu.com#8630]
500: Server error . https://ubuntu.com/engage/vmware-to-charmed-openstack?utm_source=google_ad&utm_medium=discovery&utm_campaign=7013z000001Whfd&gclid=CjwKCAjw0On8BRAgEiwAincsHHUuiPaIEp-Uscn7Vh7inNNM5V24s7giJ-v_NWkh8R4GMhGYt9T7pxoCv0QQAvD_BwE

**Comment by carkod** [comment]
@thishanr Hi. Thanks for reporting this. This morning our colleagues were updating rate limits, so this issue is fixed now. Feel free to reopen if it occurs again.
