### ISSUE TITLE
/advantage: “Sign out” is too (?) prominent

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#8633]
From Lech’s review of the UA shop with Peter, Dean and David:
> the "log out" button seems is very prominent on /advantage when logged in

**Comment by matthewpaulthomas** [comment]
This is how it currently looks:

> ![image](https://user-images.githubusercontent.com/19801137/98222079-4aebb600-1f48-11eb-9a60-001ae5200d98.png)

I think this request could be satisfied by following the layout I sketched in September last year:

![image](https://user-images.githubusercontent.com/19801137/98222240-79699100-1f48-11eb-868e-fa4e70a1e1ac.png)

In addition, because the button is inline, I think it would be appropriate to use [the Dense style](https://vanillaframework.io/docs/patterns/buttons#dense).

> ![image](https://user-images.githubusercontent.com/19801137/98223654-55a74a80-1f4a-11eb-80cd-6c84e7ed2f33.png)

**Comment by sowasred2012** [comment]
We originally had it inline as per the sketch, although it was using `is-inline`, rather than `is-dense`. Long emails/anything that caused the line to wrap led to a bad look with just `is-inline`, and this PR (https://github.com/canonical-web-and-design/ubuntu.com/pull/7860) addressed that by moving it below the text. Maybe using `is-dense` as well solves the issue.

**Comment by matthewpaulthomas** [comment]
@sowasred2012 Thanks for digging that up! I don’t think `is-dense` will make it wrap any less often than it did before. However, it’s likely to wrap on narrow viewports, and narrow viewports _also_ trigger [vanilla-framework#3387](https://github.com/canonical-web-and-design/vanilla-framework/issues/3387), which contributes to the bad look.

We could make the button part of a wrapped line much less often, if it was inline only when the viewport is wider than `$breakpoint-medium`. I’m not sure of the best way to do that. We could have two copies of the button, an inline one that’s hidden on narrow screens and a block one that’s hidden on wide screens, but that seems like a bit of a hack. Or we could duplicate all the current `is-inline` styles behind a viewport-width media query, but that duplication also seems like a hack (missing out on any changes to `is-inline` in future).
