### ISSUE TITLE
429 Too Many Requests on discuourse.ubuntu.com when visiting ubuntu.com

### ISSUE THREAD

**Issue by darkalia** [canonical-web-and-design/ubuntu.com#8675]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

We observe some HTTP 500 from now and then, occasionally causing a blip from our monitoring in Site24x7 on www.ubuntu.com

## Process

No step involved, mostly. Here is a the log of 2 requests affected by the issue (but there several affected the same way, which can cause an error on the client). : https://pastebin.canonical.com/p/N3pcwXRbjT/

Discourse seems to have some rate limit per default (https://meta.discourse.org/t/global-rate-limits-and-throttling-in-discourse/78612) and the error shown by discourse seem to come from the same IP, which is the openstack router doing a NAT (https://pastebin.canonical.com/p/BfJd4wYmv6/)

**Comment by tbille** [comment]
Fixed with https://github.com/canonical-web-and-design/ubuntu.com/pull/8674
