### ISSUE TITLE
Design /kubernetes/compare

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/ubuntu.com#8679]
[Copy doc can be found here](https://docs.google.com/document/d/1JngYmRhohPo62yU72V1xpzCCILI21SmHKKttBxHjPog/edit?ts=5faa80b7).

**Comment by SirSamTumless** [comment]
Waiting on the copy doc to be finished.

**Comment by anasereijo** [comment]
Hi @spencerbygraves ,

After discussing with Will and Alex the use of the 5-stars rating or using the "difficulty bars" (from tutorials) we decided that it makes more sense to use "difficulty bars".

See below 2 versions and please let me know your thoughts.

![compare](https://user-images.githubusercontent.com/36884067/99524025-bf364880-298f-11eb-8d33-d685f1ab7824.jpg)

![compare copy](https://user-images.githubusercontent.com/36884067/99524036-c2c9cf80-298f-11eb-85bd-8afe9aa6c515.jpg)

**Comment by spencerbygraves** [comment]
Thanks @anasereijo. On both the tutorials and whitepaper examples there is some context given to explain what the dots mean, I'm not sure if these would immediately be understood. Is there a way of including that?

![image](https://user-images.githubusercontent.com/9105999/99528961-f3613780-2996-11eb-8879-9e517a391c77.png)

![image](https://user-images.githubusercontent.com/9105999/99529019-0f64d900-2997-11eb-9e5e-3375285d2b8d.png)

Also, the text says "Kubernetes by Canonical". I wonder if Aubergine might be more appropriate?

Thanks.

**Comment by anasereijo** [comment]
Thanks for your help. 

I asked Will his thoughts and he suggested having the following text along with the table. I will check with him if it's better to have it at the top or at the bottom of the table.

![compare](https://user-images.githubusercontent.com/36884067/99539043-aa64af80-29a5-11eb-9d3f-6d1ec43cb573.jpg)

**Comment by spencerbygraves** [comment]
@anasereijo ok, thanks. I think that will help.

**Comment by wgx** [comment]
Top of the table looks good to me @anasereijo @bethcollins92 
@ me when you want a UX review on a demo version
