### ISSUE TITLE
Remove TCO calculator and Apps from nav menu on /kubernetes

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/ubuntu.com#8681]
Here is the [brief](https://docs.google.com/document/d/1Aj4-s8AgsWFjNLRAATCLP9iAob63UKdntObyS3YHfUQ/edit)

**Comment by anthonydillon** [comment]
Done as part of https://github.com/canonical-web-and-design/ubuntu.com/pull/8711
