### ISSUE TITLE
ubuntu.com/security/cve bullies you into accepting cookies

### ISSUE THREAD

**Issue by mssalvatore** [canonical-web-and-design/ubuntu.com#8691]
## Summary

ubuntu.com/security/cve gives you the option to accept cookies or "Manage your tracker settings". When you click the button to manage tracker settings, there are 2 optional sliders and a button labeled "Save preferences". If you leave both the "Performance" and "Functionality" sliders in the off position and click "Save preferences", it seems that preferences are not saved. The next page you visit will again prompt you to accept cookies.

## Process
1) Visit ubuntu.com/security/cve
2) When prompted, click the "Manage your tracker settings" button.
3) Ensure both the Performance and Functionality sliders are in the off position (default).
4) Click the "Save preferences" button.
5) Click a link to any CVE.

## Current and expected result

**Current result:** Even though I saved my tracker settings with Performance and Functionality turned off, I am prompted to either accept all cookies or manage my tracker settings.

**Expected result:** If I leave Performance and Functionality settings disabled and click "Save preferences", I expect my preferences to be saved. I expect when I visit subsequent pages I'll not be incessantly prompted to allow the site to collect more information from me.

## Browser details
Firefox 82.0 (64-bit)

**Comment by anthonydillon** [comment]
@mssalvatore Thanks for filing this issue. I am using the same browser but do not get the same behaviour. See below:
![Peek 2020-11-06 16-55](https://user-images.githubusercontent.com/1413534/98393336-0b5cc100-2051-11eb-823d-f62220aa4756.gif)

**Comment by mssalvatore** [comment]
@anthonydillon Interesting. I tried in a private browsing window and the website behaves as it does in your recording. I'm still seeing the behavior in my regular browsing window, however.

My cookies look slightly different from yours.

![cookies](https://user-images.githubusercontent.com/19957806/98543595-bbecdf80-2260-11eb-83e9-ae4a12b4d690.png)

Saving preferences does not change the value of the cookie for the /security path.

**Comment by anthonydillon** [comment]
@mssalvatore thanks for the screenshot of your cookies. I have found the issue and have a fix proposed to the cookie-policy module. Sorry about this but should be resolved shortly. 

If you would like a short term fix you can simply delete your cookie with the `/security` path. That will allow the script to use the value of the root path cookie.
