### ISSUE TITLE
[Whitepaper] Red Hat comparison (IT) - Build the Takeover +  Engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#8697]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/17vzkRhbK3yN5_BfmdLleZQbmYjxv0oUf3Nil9gwvHs4/edit?ts=5f913482#gid=0) and [past design](https://github.com/canonical-web-and-design/jp.ubuntu.com/pull/265):
 
- [x] build takeover
- [x] build engage page
- [x] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [x] build a [social banner](https://tools.demos.haus/) and use the 1200px x 630px one
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by SirSamTumless** [comment]
@andreeamun We are waiting on engage page copy.

**Comment by andreeamun** [comment]
The engage page is here https://docs.google.com/document/d/1_03rgA16BRNrsdrRvN28CcSYr-pz2Uqv2rbAUzokSac/edit
Updated in the Brief as well

**Comment by SirSamTumless** [comment]
@andreeamun Could you add the PDF to the MKTO page please.
[IT_Comparing.OpenStack_09.11.20.pdf](https://github.com/canonical-web-and-design/ubuntu.com/files/5545739/IT_Comparing.OpenStack_09.11.20.pdf)

**Comment by andreeamun** [comment]
I added the PDF to the Mkto page: https://pages.ubuntu.com/rs/066-EOV-335/images/IT_Comparing.OpenStack_09.11.20.pdf (this is the pdf)

**Comment by bethcollins92** [comment]
See engage page here: https://ubuntu.com/engage/it/redhat-openstack-confronto-manuale
Edit on discourse [here](https://discourse.ubuntu.com/t/confronto-fra-red-hats-openstack-platform-e-charmed-openstack-di-canaonical/19362)
See takeover on ubuntu.com when browser language is Italian
