### ISSUE TITLE
[Whitepaper] Charmed OpenStack Adoption (FR) - Design the Takeover +  Engage page

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#8702]
## Requirements

Please build a takeover and an engage page based on this [brief](https://docs.google.com/spreadsheets/d/1xyGWH-qu_hmh2obqz322fQq5IuRSqpTK8glSuQ46Hww/edit#gid=0) and [design](https://github.com/canonical-web-and-design/ubuntu.com/pull/8290):
 
- [x] build takeover
- [x] build engage page
- [x] add takeover to `/takeovers/index.html`
- [x] add takeover to `/index.html`
- [x] add engage page to `/engage/index.html`
- [x] build a [social banner](https://tools.demos.haus/) and use the 1200px x 630px one
- [ ] test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by SirSamTumless** [comment]
https://pages.ubuntu.com/rs/066-EOV-335/images/FR_OpenStack_adoption_deployment_11.11.20.2.pdf

**Comment by bethcollins92** [comment]
See engage page here: https://ubuntu.com/engage/fr/guide-adoption-openstack 
Edit on discourse [here](https://discourse.ubuntu.com/t/confronto-fra-red-hats-openstack-platform-e-charmed-openstack-di-canaonical/19361)
See takeover live on ubuntu.com when browser language is French
