### ISSUE TITLE
[/aws/outposts] design banner

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#8704]
Create a new /aws/outposts page - nearly a copy of /aws page layout and text.

- [brief](https://docs.google.com/document/d/1eqD-XVqudPlCLYOPI7hV-fnHmGzb7L9tXj2TwGNz0-c/edit?ts=5fa858aa)
- [copy doc](https://docs.google.com/document/d/1aXtrGHw7AcZ_qrov3kJahRtgsmbNx7eH5aWFlIySpfE/edit#)

Can you create a banner based on these images:

- https://d1.awsstatic.com/Compute/product-icon_AWS_Frontier_125_squid-ink.69f43e8e7d22b9799ce3a862421a4647f39108ec.png
- https://d1.awsstatic.com/partner-network/re19_partner_marketing/AWS_APN_PartnerNetwork_ServiceReady_Dark%20copy.34a7ee474b839b8e45c271bf4c4952dae6209f64.png 

![](https://d1.awsstatic.com/Compute/product-icon_AWS_Frontier_125_squid-ink.69f43e8e7d22b9799ce3a862421a4647f39108ec.png)
![](https://d1.awsstatic.com/partner-network/re19_partner_marketing/AWS_APN_PartnerNetwork_ServiceReady_Dark%20copy.34a7ee474b839b8e45c271bf4c4952dae6209f64.png)

**Comment by meralonso** [comment]
@waynecrosby can I use this image instead of the proposed one? @spencerbygraves @spencerbygraves what do you think?

![aws - outposts](https://user-images.githubusercontent.com/65166314/98663879-f1212c80-2349-11eb-8de4-4dc079506fff.jpg)

**Comment by waynecrosby** [comment]
@meralonso I think it works fine :)

**Comment by spencerbygraves** [comment]
@meralonso looks good, thanks.

**Comment by meralonso** [comment]
@pmahnke asset [here](https://assets.ubuntu.com/v1/6c8b8dd4-AWS-outposts.svg)
