### ISSUE TITLE
UA maintenance page

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#8710]
In the UA catchup meeting on 10/11/20, it was suggested (and met with approval by the meeting attendees) that it would be useful to have a "maintenance" page we can quickly enable if we should need to disable either the dashboard or the shop for any reason.

**Comment by sowasred2012** [comment]
@pmahnke @matthewpaulthomas could either of you suggest copy for the page, and I'll get it built?

**Comment by pmahnke** [comment]
@matthewpaulthomas are you doing this?
