### ISSUE TITLE
map is missing from /desktop/statistics 

### ISSUE THREAD

**Issue by FrancescaGranatoLondon** [canonical-web-and-design/ubuntu.com#8722]
On the lovely /desktop/statistics page, the map is missing from the 'Where are Ubuntu users?' section. I'm using Chrome Version 86.0.4240.193. Hope this is a quick fix :-)

---
*Reported from: https://ubuntu.com/desktop/statistics*

**Comment by SirSamTumless** [comment]
Thanks for flagging, this has been capture in #8582

**Comment by FrancescaGranatoLondon** [comment]
Thanks so much.
