### ISSUE TITLE
Update Mkto Form ID

### ISSUE THREAD

**Issue by Khutch25** [canonical-web-and-design/ubuntu.com#8727]
Hello @bethcollins92 this is my fault - I put the same form ID value for the Red Hat whitepaper and the kubernetes whitepaper. Can you update the form ID on the Red Hat whitepaper page to this: mktoForm_3732 ?

Marked this high priority because there are ads linking to this page that are pending approval.

---
*Reported from: https://ubuntu.com/engage/es/redhat-openstack-comparacion-manual*

**Comment by SirSamTumless** [comment]
That should be fixed: https://discourse.ubuntu.com/t/comparando-la-plataforma-openstack-de-red-hat-y-la-charmed-openstack-de-canonical/19194

**Comment by Khutch25** [comment]
Amazing, thank you!
