### ISSUE TITLE
UA shop: form needs to collect more granular customer info

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#8738]
**From the aborted shop launch:**

Bo and Hayley have stated that the form _needs_ to collect the following:

- first name
- last name
- street
- city
- country
  - with a (validated) state if the country is US or Canada

This was what came through to Bo, and she was not a fan, so the release was blocked:

![image](https://user-images.githubusercontent.com/2376968/98999704-1ff8f780-2530-11eb-89a4-07109909a769.png)

**Comment by sowasred2012** [comment]
@SirSamTumless @pmahnke looping you guys in - CS team want to try a launch again next Tuesday, if we can do this.

**Comment by anthonydillon** [comment]
Does this mean we need to revert the shop from master?

**Comment by pmahnke** [comment]
I assume so.  I have emailed Uros, Kayley and Lech for more information.

**Comment by sowasred2012** [comment]
I don't think we do - the changes to the dashboard aren't reliant on the shop being accessible, so that could go live, and we could redirect /advantage to buy.u.c for the time being.

**Comment by anthonydillon** [comment]
Problem is people use the advantage dashboard already. There is no other way to get UA tokens. We could try and remove any buttons/links into the purchasing flow but risky.
