### ISSUE TITLE
Link not working on LinkedIn 

### ISSUE THREAD

**Issue by amart82** [canonical-web-and-design/ubuntu.com#8743]
Hello, 

It seems that this link was shared on LinkedIn and it for some reason it kept directing the viewers to the blog home page and not the actual announcement. It also defaulted the preview picture to a dog wrapped around a blanket. Is there any intel as to why this could have happened? 

---
*Reported from: https://ubuntu.com/blog/canonical's-open-operator-collection-extends-kubernetes-operators-to-traditional-linux-and-windows-applications*

**Comment by pmahnke** [comment]
I have been looking at this.  I suspect it is because of the apostrophy in the url and is a bug on the linkedin side.  I have spoken to Aldo and Sarah about this.  Closing the issue.
