### ISSUE TITLE
/download/raspberry-pi - alignment in the table headings

### ISSUE THREAD

**Issue by andreeamun** [canonical-web-and-design/ubuntu.com#8749]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

There is a table on the page and the text from the header is not aligned: "Raspberry Pi 400" is aligned upper than the other ones. 

Also, if it possible, can we split the title differently? "Install Ubuntu on a" - first row  "Raspberry Pi 2, 3 or 4"- second row. At the moment, "Install Ubuntu on a Raspberry" is on the first row and "Pi 2, 3 or 4" is on the second row, so it splits the name "Raspberry Pi" which does not look good. 

## Process

1. Update the title so it moves the title "Raspberry Pi" on the same line, preferably the second line
2. Look at the alignment on the header of the table 

## Current and expected result

1. The text from the header (from "Download your Ubuntu Pi image" ) should be aligned on the same line ("Raspberry Pi 400" moved a little bit lower)
2. The title will pe split different (Raspberry Pi will go together on the second line)

## Screenshot

![image](https://user-images.githubusercontent.com/69309418/99288342-1d561500-2844-11eb-8f60-7c6620c6133f.png)

![image](https://user-images.githubusercontent.com/69309418/99288561-758d1700-2844-11eb-9e15-921205b55e31.png)

**Comment by rhys-the-davies** [comment]
After playing with screen size it looks like you found the one size where the text is aligned, when I view it, in Chrome and FireFox, the text is still miss-aligned:

![Screenshot from 2020-11-20 09-54-10](https://user-images.githubusercontent.com/56505487/99786831-e10e0780-2b16-11eb-9a5d-cfad857483ed.png)

**Comment by andreeamun** [comment]
Do we have any update on this?

**Comment by SirSamTumless** [comment]
This was fixed but only on smaller screens.
