### ISSUE TITLE
livepatch datasheet pdf not updated 

### ISSUE THREAD

**Issue by aldrikfr** [canonical-web-and-design/ubuntu.com#8750]
Hi,

the datasheet pdf that can be downloaded on the website doesn't mention 20.4 LTS as a version supporting livepatch.
(https://assets.ubuntu.com/v1/ef19ede0-Datasheet_Livepatch_AW_Web_30.07.18.pdf)

Best regards,
Aldrik

---
*Reported from: https://ubuntu.com/security/livepatch*

**Comment by SirSamTumless** [comment]
@Khutch25 Is updating this part of your remit?

**Comment by Khutch25** [comment]
> @Khutch25 Is updating this part of your remit?

Yes. If it's a small update to include 20.04, I'm sure we can just to the copy doc and have Lorena update. But may be a good opportunity for @alxchalkias [to review](https://assets.ubuntu.com/v1/ef19ede0-Datasheet_Livepatch_AW_Web_30.07.18.pdf) the datasheet to see if it needs any additional updates?

**Comment by Khutch25** [comment]
To update here, I've added a suggested edit update to the [Livepatch datasheet copy doc](https://docs.google.com/document/d/11kApsyR7cY6M0UAuL_RPV2vTrm-twjmtlPJ5nqDxHmE/edit) and pinged @alxchalkias and Uros for their review, edits and +1.
