### ISSUE TITLE
[UA shop handover] advantage shop: improve handling of renewals

### ISSUE THREAD

**Issue by frankban** [canonical-web-and-design/ubuntu.com#8755]
When getting renewals from the backend, we are currently interested in pending ones (which we provide the ability to renew) and recently done one (which we highlight in UX).
This could lead to customers not being able to renew two renewals subsequently, because the first one in chronological order would be in done state, therefore masking the second renewal.
We need a more general handling of renewals, possibly separating them in 3 lists: pending for showing the button, done for highlighting contracts that were recently renewed, and in error, for exposing that error condition in the page, and perhaps inviting customers to contact us.

**Comment by SirSamTumless** [comment]
@frankban Is this still relevant?

**Comment by frankban** [comment]
I think so, unless someone worked on this.

**Comment by wgx** [comment]
The new UI exposes them separately, fixed.
