### ISSUE TITLE
UA Shop: machine usage display may display the wrong count

### ISSUE THREAD

**Issue by alnvdl** [canonical-web-and-design/ubuntu.com#8759]
The current code for calculating allowances seems to be mixing active machines with attached machines:

https://github.com/canonical-web-and-design/ubuntu.com/blob/13e6bf7f2028a0d882133d71d93e43f0b4a4a918/webapp/views.py#L569-L581

At the moment in ua-contracts, we're in a situation where:
- we use two allowance metrics: `attached-machines` and `active-machines`;
- a contract may have allowances with these two types of metrics, at the same time.

In the long term, neither metric should be used for this purpose anymore. We're still discussing how we want to model this going forward.

Regardless of what we decide, in order for the web interface to be accurate now and most likely in the future, it'd be best if you just summed up all allowance values when displaying, regardless of the metric name.

**Comment by alnvdl** [comment]
I started a PR for fixing this: https://github.com/canonical-web-and-design/ubuntu.com/pull/8760

**Comment by urosj** [comment]
Wait. no, that's also wrong. You can't just make a sum of "attached" and "active" and say that's better.
