### ISSUE TITLE
[Ubuntu Pro FIPS on Azure] Design page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#8770]
Design /azure/pro/fips page.

- [brief](https://docs.google.com/document/d/1xDgi-nCAnD3FK8k-K4HzZqyrE-WlJ7jLMPATblSfxnU/edit?ts=5fb59b62#)
- [/azure/pro/fips copy doc](https://docs.google.com/document/d/1Djxdzjy78bau8ELM4-MNGoM2YRa_QjpN1xJ4H4GjFyw/edit?usp=sharing)

**Comment by spencerbygraves** [comment]
@SirSamTumless @pmahnke here's the design, just need an illustration for the second last section.

![image](https://user-images.githubusercontent.com/9105999/100377162-a588a700-3008-11eb-89bb-ce6fe578bb78.png)

**Comment by anasereijo** [comment]
Hi @spencerbygraves, thanks for doing this! I have a suggestion.

On the Get Ubuntu Pro FIPS strip, I think we could use the [slanted strip](https://ubuntu.com/0_docs/content_strips) we created a while ago to keep consistency.

**Comment by spencerbygraves** [comment]
Thanks @anasereijo, that sounds good 👍

**Comment by spencerbygraves** [comment]
@SirSamTumless I've updated the design to use the [slanted strip](https://ubuntu.com/0_docs/content_strips) and added an [illustration](https://assets.ubuntu.com/v1/69d31769-updates-security-maintenance.svg) for the compliance section.

![image](https://user-images.githubusercontent.com/9105999/100445079-6a3bb600-30a4-11eb-8cd3-8fa5cef8bd92.png)

**Comment by spencerbygraves** [comment]
@albertkol here are the images you need.

[Compliance made easy](https://www.brighttalk.com/communication/452063/preview_1605631360.png)
[Compliance and the most comprehensive...](https://assets.ubuntu.com/v1/69d31769-updates-security-maintenance.svg)
[Optimised scaling in the cloud](https://assets.ubuntu.com/v1/6a2310d3-optimised-scaling-in-the-cloud.png)
