### ISSUE TITLE
[Ubuntu Pro FIPS on Azure] Build /azure/fips page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#8771]
Build /azure/fips page - easier if _after_ the contact us work

- [brief](https://docs.google.com/document/d/1xDgi-nCAnD3FK8k-K4HzZqyrE-WlJ7jLMPATblSfxnU/edit?ts=5fb59b62#)
- [/azure/pro/fips copy doc](https://docs.google.com/document/d/1Djxdzjy78bau8ELM4-MNGoM2YRa_QjpN1xJ4H4GjFyw/edit?usp=sharing)
- Add to navigation.yaml

**Comment by Khutch25** [comment]
@pmahnke FYI also have the [AWS FIPS page copy doc](https://docs.google.com/document/d/1RIUejzxrQwvT-qQGG_FhRIaTVzZb07o6mZeiYkaBdqk/edit#heading=h.txyflacnpot1). They are updated in [the brief](https://docs.google.com/document/d/1xDgi-nCAnD3FK8k-K4HzZqyrE-WlJ7jLMPATblSfxnU/edit?ts=5fb59b62#) you link above as well.
