### ISSUE TITLE
[Ubuntu Pro FIPS on Azure] Build modal contact-us

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#8772]
Build /azure/pro/fips#get-in-touch page as well as extend the no-js version of the form.

- [brief](https://docs.google.com/document/d/1xDgi-nCAnD3FK8k-K4HzZqyrE-WlJ7jLMPATblSfxnU/edit?ts=5fb59b62#)
- [modal form copy doc](https://docs.google.com/document/d/1GbPw_OOy84ez5B3EFqH_P26nV85qo3-iv1kHE2PjSEc/edit) - ask @pmahnke for help

**Comment by Khutch25** [comment]
@albertkol I think the form ID was missing from the brief. Here is the Azure FIPS contact form ID: 3791

**Comment by pmahnke** [comment]
so @albertkol you need to move this snippet from the base_azure.html file  

```
  <!-- Set default Marketo information for contact form below-->
  <div class="u-hide" id="contact-form-container" data-form-location="/shared/forms/interactive/azure" data-form-id="3564" data-lp-id="" data-return-url="https://www.ubuntu.com/azure/thank-you" data-lp-url="https://www.ubuntu.com/azure/contact-us">
  </div>
```

to every page and change the form id on the fips page.
