### ISSUE TITLE
[Ubuntu Pro FIPS on Azure] Add pro/fips to /azure and /azure/pro pages

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#8774]
Add links to /azure/pro/fips on the /azure and /azure/pro pages (copy coming)

- [brief](https://docs.google.com/document/d/1xDgi-nCAnD3FK8k-K4HzZqyrE-WlJ7jLMPATblSfxnU/edit?ts=5fb59b62#)

**Comment by Khutch25** [comment]
@pmahnke FYI the [Azure FIPS page copy doc](https://docs.google.com/document/d/1Djxdzjy78bau8ELM4-MNGoM2YRa_QjpN1xJ4H4GjFyw/edit?usp=sharing) and the [AWS FIPS page copy doc](https://docs.google.com/document/d/1RIUejzxrQwvT-qQGG_FhRIaTVzZb07o6mZeiYkaBdqk/edit?usp=sharing). They are updated in [the brief](https://docs.google.com/document/d/1xDgi-nCAnD3FK8k-K4HzZqyrE-WlJ7jLMPATblSfxnU/edit?usp=sharing) you link above as well.

**Comment by SirSamTumless** [comment]
@Khutch25 What is the URL structure of this page; the new page created was /azure/fips. You mention here /azure/pro/fips. Which one is it?

**Comment by pmahnke** [comment]
just /azure/fips like that /aws one

**Comment by albertkol** [comment]
@SirSamTumless @pmahnke 

I am a bit confused where to add the links. I would expect copy docs of the /azure and /azure/pro pages which show where to add them, but I only see the copy docs of the /azure/fips page.

**Comment by Khutch25** [comment]
Not sure if this clarifies the questions, but there are two FIPS pages - one for Azure and one for AWS. The page urls should be:

- [/azure/fips](https://docs.google.com/document/d/1xDgi-nCAnD3FK8k-K4HzZqyrE-WlJ7jLMPATblSfxnU/edit)
- [/aws/fips](https://docs.google.com/document/d/1RIUejzxrQwvT-qQGG_FhRIaTVzZb07o6mZeiYkaBdqk/edit)

These should also both be listed in the secondary/sub-navigation for each 'Azure' and 'AWS' bubble, like how it is set up for the Azure FIPS page:

![Screenshot 2020-12-10 at 10 12 10](https://user-images.githubusercontent.com/42180941/101758511-521a5c80-3ad0-11eb-8230-1e6d806f7dab.png)

Unsure if it also should be added to the mega menu in the Public cloud section, but will leave that with @pmahnke to feedback on.

![Screenshot 2020-12-10 at 10 13 05](https://user-images.githubusercontent.com/42180941/101758595-6bbba400-3ad0-11eb-9a9b-f0fd2bdbebef.png)

**Comment by albertkol** [comment]
The azure/fips link is already in the secondary navigation.. and the work on the aws/fips will be done as a separate issue. 

@pmahnke do we want to add the links in the Public cloud section as @Khutch25 describes above? If the answer is no, I think we can close this issue.
