### ISSUE TITLE
[Webinar] AI deployment and inference

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#8784]
Create **[Webinar] AI deployment and inference** based on the [brief](https://docs.google.com/spreadsheets/d/1W3IgEb5TeTPMwLyo2TnETGk5WIF_VqG6oXjQOwzPr4Y/edit#gid=0)

**Comment by bethcollins92** [comment]
@SirSamTumless This brief isn't for the Al deployment and inference

**Comment by bethcollins92** [comment]
Brief doesn't include Engage page info - but engage status is true. Blocked by this

**Comment by SirSamTumless** [comment]
@bethcollins92 Isn't this engough? https://docs.google.com/document/d/1LlmvHCP5-qkxXJXN_NEl3aGe0gDPZ7OQUoWrd6TDYC4/edit#

**Comment by bethcollins92** [comment]
@SirSamTumless Yeh that's fine, this was an old comment from when I was waiting for the engage copy. Still don't have the Webinar code though

**Comment by SirSamTumless** [comment]
Finally got it: https://www.brighttalk.com/webcast/6793/451777

**Comment by bethcollins92** [comment]
Engage page here: https://ubuntu.com/engage/ai-deployment-and-inference
Edit on discourse: https://discourse.ubuntu.com/t/ai-deployment-and-inference/19692
See takeover live on ubuntu.com
