### ISSUE TITLE
[Webinar] Ubuntu Pro AWS

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#8785]
Create **[Webinar] Ubuntu Pro AWS** based on the [brief](https://docs.google.com/spreadsheets/d/1ap1Ew5AEs42JMYOFwvKb1m4pi4gGk2X-bES57zAA_jc/edit#gid=1271849439)

**Comment by bethcollins92** [comment]
See Engage page here: https://ubuntu.com/engage/ubuntu-pro-for-aws
Edit [here](https://discourse.ubuntu.com/t/ubuntu-pro-for-aws/19600)
Takeover live on [ubuntu.com](https://ubuntu.com/)
