### ISSUE TITLE
Navigation - confusing jump from Support > Pricing

### ISSUE THREAD

**Issue by ajbeattie** [canonical-web-and-design/ubuntu.com#8787]
## Summary

When navigating in the `Support` subsection of the site, clicking the `Pricing` tab takes you to a different subsection, even though all of the other tabs in the same level stay within the `Support` section. This pattern is also present in other subsections.

## Expected result

The tabs listed after the `Support` subsection title all lead to pages within the same subsection.

## Screenshot

<img width="1493" alt="Screen Shot 2020-11-20 at 10 36 03 AM" src="https://user-images.githubusercontent.com/6845951/99826559-26820300-2b1e-11eb-8ff0-47f19627f0c6.png">

<img width="1495" alt="Screen Shot 2020-11-20 at 10 36 12 AM" src="https://user-images.githubusercontent.com/6845951/99826575-2c77e400-2b1e-11eb-94fd-5bdc8b5c6869.png">

**Comment by pmahnke** [comment]
@ajbeattie this was purposely added when we moved pricing out of support; however, I think with /advantage we can remove it.
