### ISSUE TITLE
/engage/finance - new URL to redirect

### ISSUE THREAD

**Issue by andreeamun** [canonical-web-and-design/ubuntu.com#8788]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

Update the URL of the engage page: ubuntu.com/engage/finance to ubuntu.com/engage/ubuntu-finance-sector-whitepaper

## Process

1. Move the page (on discourse) to ubuntu.com/engage/ubuntu-finance-sector-whitepaper
2. Add the redirect

## Current and expected result

Trying to optimize the URL to get more optimal traffic

## Screenshot

N/A 

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

**Comment by pmahnke** [comment]
@andreeamun @caldav this is a bit of a problem.

We can do it, but it will be _very_ messy to do it often.

How important is this? How much does it help? How can we avoid doing it a lot?

**Comment by caldav** [comment]
@pmahnke it's messy indeed, it's a case of a bad URL that should have been caught before it went live (and now, it has several ad campaigns attached to it). Happy to gatekeep future engage pages publication.

**Comment by pmahnke** [comment]
@caldav also, since it is now 2 sites and 2 changes to make the redirect work, we have to try and time the release of both changes
