### ISSUE TITLE
Engage pages are listed when not active

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#8789]
While writing up the iteration report I noticed that the "Cinque strategie per accelerare l’implementazione di Kubernetes nell’impresa" engage page with is listed at /engage linked to discourse. I assume that is due to the engage page is not active. I would think then it shouldn't be listed?

**Comment by pmahnke** [comment]
@anthonydillon this might be fixed by #8761, which you are meant to review?

**Comment by anthonydillon** [comment]
Yeah it will will choose this one as it's almost ready
