### ISSUE TITLE
[Webinar] Managed Apps Finance Webinar

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#8806]
Create **[Webinar] Managed Apps Finance Webinar** based on the [brief](https://docs.google.com/spreadsheets/d/1BJ-931RKwDgu81CAKnifTAnqUHXW_IUDirNTbrVIHhY/edit#gid=1011867606)

**Comment by Khutch25** [comment]
There are two ESM webinar issues, so I assume this one is meant to be the other one I briefed in, based on the brief link - the [Managed Apps Finance Webinar](https://docs.google.com/spreadsheets/d/19TsEce5LHt9_3lTzGWqOrk4WkpVU7OhDVVjVAGd7Yco/edit?ts=5fb65e7a#gid=0).

**Comment by Khutch25** [comment]
Hoping to get this webinar page live as soon as possible, so happy to create it through the discourse engage page process, just waiting for some feedback on the issues I ran into with the ESM page here: https://github.com/canonical-web-and-design/ubuntu.com/issues/8786

**Comment by pmahnke** [comment]
I did a [new format brief](https://docs.google.com/spreadsheets/d/1BJ-931RKwDgu81CAKnifTAnqUHXW_IUDirNTbrVIHhY/edit#gid=1011867606)

**Comment by pmahnke** [comment]
@Khutch25 I put this live as well, we will do the next one together.
