### ISSUE TITLE
[UA shop] add feature flag to easily switch between staging and live environments

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#8828]
From a meeting on 27/11/20 with @nottrobin, @ClementChaumel and @sowasred2012, and is a follow up to the conversation that happened here: https://github.com/canonical-web-and-design/meeting-notes/issues/597

When developing UA renewals and shop, 99% of the time you need to be working with the staging variants of the contracts API and Stripe implementation, but the outcome of the conversation linked to above was that any external services should be configured to use their production variants by default.

The solution I used when working on the initial launch of the shop was to have a feature branch that I'd committed staging values for the API and Stripe to, and any shop work would be merged into that, so I only actually had to change those values back to production once, when the shop was finally launched.

Now that the shop is live, and Clement is working on bug fixes and feature requests that will be merged straight into master, having to update those values and then remember to change them back is going to get old pretty quickly, so in a meeting with Robin we discussed potential solutions. 

One that we thought would work well with the current setup is to have a feature flag that would tell the site to use staging versions of the API and Stripe, so if a user was to append `?ua_staging=true` to the URL, you'd get the shop staging environment.

**Comment by anthonydillon** [comment]
@sowasred2012 can you add an estimate for this please?
