### ISSUE TITLE
CVE tables: “Does not exist” wraps to 3 lines

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#8832]
CVE results tables are much less information-dense than they could be, because many of the cells contain the text “Does not exist”, and that text wraps to three lines.

![image](https://user-images.githubusercontent.com/19801137/100539519-0d203b80-322f-11eb-815b-8e58dc22c1bd.png)

(These should also be the least prominent cells in the table, but being almost the _only_ cells that wrap to three lines challenges this.)

These cells have plenty of width for “Does not exist” to occupy two lines rather than three:

![image](https://user-images.githubusercontent.com/19801137/100539745-705e9d80-3230-11eb-8ed7-9a7975bd47c0.png)

It doesn’t use this space because it is leaving room for an “ℹ️” icon alongside. However:
- Cells generally don’t need to leave room for this icon; it could float over top on hover.
- There’s no point in “Does not exist” cells particularly leaving room for this icon, because they don’t have it anyway!

What should happen: either
- no cells should leave room for the “ℹ️” icon, because it floats over top if necessary; or
- “Does not exist” cells in particular shouldn’t leave room for the “ℹ️” icon, because they doesn’t have it.

---
*Reported from: https://ubuntu.com/security/cve*

**Comment by SirSamTumless** [comment]
Could this be a - ?
