### ISSUE TITLE
/security/cve: Enter doesn’t submit the search

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#8833]
1\. Go to [the CVE page](https://ubuntu.com/security/cve).
2\. Type something in the search field, and press Enter/Return.

What happens: Nothing.

What should happen: The search should be performed.

This is because [browsers associate Enter/Return with the first button in a form](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission) — and the first button in this form isn’t the “Search” button, it’s the “–” button for removing a version-status row.

I don’t think there’s a practical way to change this just in HTML, so this probably needs [a JS override](https://www.w3schools.com/howto/howto_js_trigger_button_enter.asp) to click the “Search” button on Enter.

---
*Reported from: https://ubuntu.com/security/cve*

**Comment by anthonydillon** [comment]
This is still an issue
