### ISSUE TITLE
[Ubuntu FIPS for AWS] Update /shared/forms/interactive/aws

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#8850]
Per the [copy doc](https://docs.google.com/document/d/1YyCKB1rTnjxqgdECPJczHBHGGZEjQvkLOJkaRtCyFpU/edit#) this will be nearly identical to the Azure one.

**Comment by Khutch25** [comment]
Form ID: 3790

**Comment by albertkol** [comment]
I noticed the azure fips form was using the form ID 3564. I changed it now to 3791.

**Comment by Khutch25** [comment]
> I noticed the azure fips form was using the form ID 3564. I changed it now to 3791.

Woohoo, thanks for catching that!! 🙌
