### ISSUE TITLE
The use of whitespace is sub-optimal in doc menus

### ISSUE THREAD

**Issue by pmatulis** [canonical-web-and-design/ubuntu.com#8856]
## Summary

The use of whitespace can be improved in the documentation menus of our projects. So far I've only detected this on  [ubuntu.com/ceph/docs](https://ubuntu.com/ceph/docs) but I believe we use a standard framework everywhere.

1. I have to doctor the source text (removing all blank lines) in order to get an almost-good rendering. I'm not convinced I should have to do this:

![image](https://user-images.githubusercontent.com/6303808/100931343-6a7aed80-34b8-11eb-9362-56fe3833fcae.png)

If I do not I get way too much whitespace:

![image](https://user-images.githubusercontent.com/6303808/100925965-b6299900-34b0-11eb-93bd-4c7c7e67b005.png)

2. Even with doctoring I cannot get rid of the extraneous whitespace before a main header (above "Operations"):

![image](https://user-images.githubusercontent.com/6303808/100931450-8d0d0680-34b8-11eb-9d21-d332a4a7ee27.png)

3. The extra space inserted between, say, a ### header and a ## may also not be great. I feel it gives an odd appearance (between "Replacing OSD disks" and "Power cycling nodes"):  

![image](https://user-images.githubusercontent.com/6303808/100931974-3653fc80-34b9-11eb-8d92-c4d709d6774a.png)

## Current and expected result

This is subjective but IMO the current result is an unattractive menu. The expected result is that it looks nice and crisp.

## Browser details

Google Chrome
Version 87.0.4280.66 (Official Build) (64-bit)

BTW, mybrowser.fyi is deprecated and reference to it should be removed from this GH project's bug template:

![image](https://user-images.githubusercontent.com/6303808/100929627-ec1d4c00-34b5-11eb-8f58-bdf18b261d33.png)

**Comment by anthonydillon** [comment]
Thanks, @pmatulis is far from optimal. I believe the true fix would be to do these two things:
 - [ ] Create a [Vanilla documentation template](https://vanillaframework.io/docs/examples/layouts/documentation)
 - [ ] Apply the new template to all docs on the site
