### ISSUE TITLE
webteam-app credentials in LastPass missing 2FA details

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#8866]
I was trying to create GitHub access tokens for use on https://github.com/canonical-web-and-design/vanilla-framework/pull/3441, and was told that we have an account for this purpose: webteam-app.

The entry for the account in LastPass contains username/password, but not the required 2FA, so we can't currently login.

**Comment by pmahnke** [comment]
I put the 2fa secret in the notes on the entry in lastpass
