### ISSUE TITLE
[ESM Apps] Build plan selector changes

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#8870]
Build the changes specified in [web-squad#3556](https://github.com/canonical-web-and-design/web-squad/issues/3556).

**Comment by anasereijo** [comment]
@ClementChaumel can you please estimate this? thanks

**Comment by anasereijo** [comment]
@ClementChaumel this is ready for you. 

check design here: https://github.com/canonical-web-and-design/master-epics/issues/234#issuecomment-746178227
