### ISSUE TITLE
After shutdown, I cannot power it up again.

### ISSUE THREAD

**Issue by JoPhiGURU** [canonical-web-and-design/ubuntu.com#8872]
As the title says, I can shut down the raspberry pi 400, by clicking Power Off/Log Out. But when it's done, I cannot power it on, by using Fn+(Powersymbol) or (Powersymbol). I have to unplug it completely and replug the power-supply. From former models I know, that this can damage the sd-card.

Please help to avoid this.
Do you need more details about this?

Thx,
JoPhi

---
*Reported from: https://ubuntu.com/blog/raspberry-pi-400-with-ubuntu-support*

**Comment by RCMainak** [comment]
This is not the right place to report this issue. This repo is for the development of the ubuntu.com website, not the OS. You may want to file a bug report in [launchpad](https://help.ubuntu.com/community/ReportingBugs)

**Comment by JoPhiGURU** [comment]
Thank you, I mixed something up. 🤗
