### ISSUE TITLE
Icon for external link for a png seems odd

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-web-and-design/ubuntu.com#8874]
![imageremotelink](https://user-images.githubusercontent.com/24707086/101212846-dfb80100-3625-11eb-96b4-0a6162f31ece.png)

The fact that there is an icon for an "external link" attached to a png seems odd to me.
---
*Reported from: https://ubuntu.com/ceph/docs*

**Comment by anthonydillon** [comment]
This should be fixed by https://github.com/canonical-web-and-design/ubuntu.com/pull/8876
