### ISSUE TITLE
Visual design: Global vs. contextual footer borders seem reversed

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#8877]
This has been bothering me for a few years. On ubuntu.com, all pages (that I’ve seen) have a global footer:

![image](https://user-images.githubusercontent.com/19801137/101275760-26ca0180-37a0-11eb-963c-898c096c3f46.png)

Many, but not all, also have a “contextual footer” above the global footer:

![image](https://user-images.githubusercontent.com/19801137/101275781-46f9c080-37a0-11eb-9e20-44f2aa8a65a3.png)

The contextual footer’s top border (a 0.1875rem orange strip) is much more vivid than the global footer’s top border (a light grey drop shadow).

**The problem:** On pages that don’t have a contextual footer — like [/kernel](https://ubuntu.com/kernel), or [/advantage/subscribe](https://ubuntu.com/advantage/subscribe) — there is, therefore, much less border after the main page contents than on pages that do. Where the last section happens to have a grey background — as in these two examples — there seems to be no particular border before the sitemap at all, so it could be misinterpreted as part of the page body.

![image](https://user-images.githubusercontent.com/19801137/101276119-d607d800-37a2-11eb-942e-68a62554cab3.png)

**I suggest:** This can be fixed by swapping the two borders — the contextual footer should have the grey shadow border (or maybe something else entirely), while the global footer has the orange strip.

As a bonus, this could lead us to pay more attention to the contents of the contextual footer when it is present, checking that it’s relevant and doesn’t duplicate material from the rest of the page.

---
*Reported from: https://ubuntu.com/kernel*

**Comment by anthonydillon** [comment]
I agree this would be more consistent cross pages and clearer by having the vivid border on at the end of the page context. It would form a clear boundary at the end of the page and entering the footer navigation.
