### ISSUE TITLE
Get the full USN name list of Ubuntu 1604

### ISSUE THREAD

**Issue by liangming2003** [canonical-web-and-design/ubuntu.com#8878]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

I want get all the USN names of Ubuntu 1604, Is there any way I can get the full USN name list (1359 items) from your website instead of scraping the search result page by page (136 pages)? I guess your website used to have a webpage (https://usn.ubuntu.com/releases/ubuntu-16.04-lts/) for this. Thanks.

## Process

[List the steps to replicate the issue.]

## Current and expected result

[Describe what happened and what you expected.]

## Screenshot

![image001](https://user-images.githubusercontent.com/13327028/101323737-22870c80-38a4-11eb-8221-dc50ee5cf73d.png)

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

**Comment by albertkol** [comment]
Hello @liangming2003,

An easy way to get the notices would be to use our notices endpoint https://ubuntu.com/security/notices.json.
To get the 16.04 just do this: https://ubuntu.com/security/notices.json?release=xenial

The full documentation of the API is here: https://ubuntu.com/security/api/docs

For any bugs or suggestions, please create an issue here: https://github.com/canonical-web-and-design/ubuntu-com-security-api/issues

Albert

**Comment by liangming2003** [comment]
Thanks, but this is not what I wanted. There are only 10 USN listed in the json file. I want all USNs listed in one page or one json file.
also, Json file like this "https://ubuntu.com/security/notices.json?release=xenial&page=4“ does not work.
