### ISSUE TITLE
X-Frame-Options header

### ISSUE THREAD

**Issue by setharnold** [canonical-web-and-design/ubuntu.com#8899]
Hello, we received a message from Sakshi Patil suggesting that we should use the `X-Frame-Options` header on our web properties to reduce the risks due to clickjacking attacks. Can you investigate this header and see if this should be use on our web properties, and which ones should be included?

Thanks

---
*Reported from: https://ubuntu.com/*

**Comment by pmahnke** [comment]
For reference - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

**Comment by nottrobin** [comment]
This seems like a good idea. As we get more logged-in functions on ubuntu.com, we probably have a few not-so-juicy attack vectors to worry about, with the advantage store and other future plans. Snapcraft is probably more juicy with its snap admin stuff, so we should check that too.

We should be careful though that we don't block any places where we actually *want* people to run iframes. I think maybe this could be relevant to snapcraft for badges or cards or something. If badges are coming to ubuntu.com, we also need to make sure this is considered there.

Does anyone know of other places we actually want people to run iframes?

**Comment by nottrobin** [comment]
If we do this I think we should probably consider adding a few other headers too, e.g.:

![image](https://user-images.githubusercontent.com/519935/103525480-35770780-4e77-11eb-91c7-bf530f77817c.png)

From https://securityheaders.com/?q=https%3A%2F%2Fubuntu.com&followRedirects=on

**Comment by setharnold** [comment]
Nice, those all look like good candidates to add, yes. Thanks
