### ISSUE TITLE
Azure marketplace link shows non Canonical results

### ISSUE THREAD

**Issue by campbieil** [canonical-web-and-design/ubuntu.com#8903]
In this sentence:
You can buy [Ubuntu Pro on the Azure Marketplace](https://azuremarketplace.microsoft.com/en-us/marketplace/apps?search=Ubuntu%20Pro&page=1) at an hourly, per-machine rate, with all UA software features included.
Can we change the link to the marketplace from:
[https://azuremarketplace.microsoft.com/en-us/marketplace/apps?search=Ubuntu%20Pro&page=1
](https://azuremarketplace.microsoft.com/en-us/marketplace/apps?search=Ubuntu%20Pro&page=1
)
to 
[https://azuremarketplace.microsoft.com/en-us/marketplace/apps?search=%22Ubuntu%20Pro%22%20&page=1
](https://azuremarketplace.microsoft.com/en-us/marketplace/apps?search=%22Ubuntu%20Pro%22%20&page=1
)

*Reported from: https://ubuntu.com/advantage/subscribe*

**Comment by anthonydillon** [comment]
@campbieil that link 404s for me.

**Comment by pmahnke** [comment]
It seems no search works as a GET string.

How about: 

You can buy [Ubuntu Pro 20.04 LTS](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/canonical.0001-com-ubuntu-pro-focal), [18.04 LTS](https://azuremarketplace.microsoft.com/en-gb/marketplace/apps/canonical.0001-com-ubuntu-pro-bionic), [16.04 LTS](https://azuremarketplace.microsoft.com/en-gb/marketplace/apps/canonical.0001-com-ubuntu-pro-xenial) and [14.04 LTS](https://azuremarketplace.microsoft.com/en-gb/marketplace/apps/canonical.0001-com-ubuntu-pro-trusty) on the Azure Marketplace at an hourly, per-machine rate, with all UA software features included.</span>

```
<span>You can buy <a href="https://azuremarketplace.microsoft.com/en-us/marketplace/apps/canonical.0001-com-ubuntu-pro-focal" class="p-link--external">Ubuntu Pro 20.04 LTS</a>, <a href="https://azuremarketplace.microsoft.com/en-gb/marketplace/apps/canonical.0001-com-ubuntu-pro-bionic" class="p-link--external">18.04 LTS</a>, <a href="https://azuremarketplace.microsoft.com/en-gb/marketplace/apps/canonical.0001-com-ubuntu-pro-xenial" class="p-link--external">16.04 LTS</a> and <a href="https://azuremarketplace.microsoft.com/en-gb/marketplace/apps/canonical.0001-com-ubuntu-pro-trusty" class="p-link--external">14.04 LTS</a> on the Azure Marketplace at an hourly, per-machine rate, with all UA software features included.</span>
```

**Comment by anthonydillon** [comment]
Does anyone have a better link?

**Comment by anthonydillon** [comment]
I assume there is still no better link at the moment. Closing for now but please reopen if there is something better to use.
