### ISSUE TITLE
Appliance page title changes

### ISSUE THREAD

**Issue by rhys-the-davies** [canonical-web-and-design/ubuntu.com#8914]
helloo o/ 

Let's change the titles of each Appliance specific page and their instructional pages. This is to increase their SEO ranking, at the moment they are a mixture of different things, I'd like to set them all the appliance pages e.g ubuntu.com/appliance/plex to:

"Install `<appliance name>`"

And then the instructional pages e.g ubuntu.com/appliance/plex/raspberrypi to:

"Install `<appliance name>` on `<hardware>`"

---
*Reported from: https://ubuntu.com/appliance/plex*

**Comment by pmahnke** [comment]
@rhys-the-davies can you update all the copy docs?

**Comment by rhys-the-davies** [comment]
Certainly, where do you want me to do that exactly? For example, in the plex copy doc: https://docs.google.com/document/d/1zgOl4GCK6O6Clv6oxp-DXDSKYIKO2pvpXaYXALiTlpo/edit I can't find the exact text I see when I hover over the tab with the pipes (|) and all?

**Comment by matthewpaulthomas** [comment]
@rhys-the-davies Page titles are usually defined in the filename of the Google Doc itself. But in your example, this is currently “index - "Build the Plex Media Ubuntu appliance"”, which doesn’t match what was implemented. (I haven’t seen the spreadsheet Peter’s referring to, so maybe the titles are redefined there.)

I’ve changed all the titles to one of these forms:
- “Install {appliance name}”
- “Install {appliance name} on a {hardware}” (or “on a**n** {hardware}”, in the case of “an Intel NUC”)
- “Try the {appliance name} Ubuntu Appliance in a virtual machine” (left unchanged).
