### ISSUE TITLE
Not clear that UA prices are annual

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#8932]
[/advantage/subscribe](https://ubuntu.com/advantage/subscribe) makes clear that once it shows you a price, it’s per year.

However, other pages list prices without making this clear:
- https://ubuntu.com/advantage
- https://ubuntu.com/pricing/infra
- https://ubuntu.com/legal/ubuntu-advantage-service-description

This will become more important once monthly prices are introduced.

[Reported by the field sales team via David Callé.]

**Comment by matthewpaulthomas** [comment]
So I think the simplest fix for this is the same on each of the three pages: add “/ year” to each of the machine types.

![image](https://user-images.githubusercontent.com/19801137/105063131-462c9d80-5a73-11eb-8ece-e0803951eb3d.png)

**Comment by elioqoshi** [comment]
@matthewpaulthomas mentioned also in https://github.com/canonical-web-and-design/ubuntu.com/pull/9068#issuecomment-765378939

Shouldn't we be adding /year to every column of the pricing instead. I'd say it's slightly clearer and is a used pattern on other products.

**Comment by matthewpaulthomas** [comment]
I’d rather print “/year” 3 times than 9 (or soon, 12).

But we could take the opportunity to address the long-standing problem that it’s not obvious where the features end and the prices begin.

![image](https://user-images.githubusercontent.com/19801137/105496094-ec1b1a80-5cb4-11eb-8172-7f9a196226be.png)

A bonus of doing that would be that we’d only need to print “per year” once rather than 3 times.

What do you think, @anasereijo? Is it reasonable to have a second header row in a table like that? Or would we need to add vertical spacing to make it two altogether separate tables? (The downside is that we’d then have to repeat “Essential” “Standard” “Advanced”.)

**Comment by elioqoshi** [comment]
I do think there is a better way to display it in one table but I don't have a better idea right now. Maybe @anasereijo has some better ideas indeed.

**Comment by anthonydillon** [comment]
Currently Vanilla had no `tfoot` styling difference. Maybe by add a district style to the table footer and putting prices in a `tfoot` that would suffice?

**Comment by pmahnke** [comment]
With a second header, it could say 'Annual pricing' in the first column.

**Comment by anasereijo** [comment]
I don't think it's a bad idea to repeat /year but with the help of @anthonydillon we came up with a few solutions using vanilla.

A) /year in all pricing cells with a grey background

![image](https://user-images.githubusercontent.com/36884067/105510375-791a9f80-5cc6-11eb-843f-d51a417d097a.png)


B) pricing section within the table
We moved pricing to the top of the table as we thought people will be interested in pricing first and then checking out what's included (but this is a UX thing so I'll leave it for you guys :) )

![image](https://user-images.githubusercontent.com/36884067/105510126-32c54080-5cc6-11eb-8c71-c92e2495f5c9.png)

**Comment by pmahnke** [comment]
I like B better, not sure if we should have prices first though.

**Comment by elioqoshi** [comment]
Thanks @anasereijo ! I feel similar to Peter, B in the opposite order (Features and then Prices) would be great.

**Comment by anasereijo** [comment]
@anthonydillon do you still have the code for option B? 

I will close this now as I think it will be fixed [here](https://github.com/canonical-web-and-design/ubuntu.com/pull/9068#issuecomment-765378939)

**Comment by anthonydillon** [comment]
It's just inline styles. Would need to think it thought in Vanilla.
