### ISSUE TITLE
/security - fix illustration proportions 

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#8953]
the illustration on "Find out why the UK Government ..." section looks squashed.

how it looks like:
<img width="1435" alt="Screenshot 2020-12-18 at 15 24 06" src="https://user-images.githubusercontent.com/36884067/102631279-6cde7800-4145-11eb-929c-7d5ed3a2fff1.png">

---
*Reported from: https://ubuntu.com/security*

**Comment by SirSamTumless** [comment]
What should it be @anasereijo?

**Comment by anasereijo** [comment]
> What should it be @anasereijo?

should be the original size
