### ISSUE TITLE
UA subscriptions: Build display of latest/next/summarised payments

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#8965]
Display the summary of payments, and the previous/next payment details, for subscriptions as [described in the specification](https://docs.google.com/document/d/1K65n3NpZCh7EWDXKLhG31seGJ2jKbW6lqw3BwV2mlnU/edit#heading=h.q653zkl5xi23).

(This was [designed in web-squad#3502](https://github.com/canonical-web-and-design/web-squad/issues/3502).)

**Comment by SirSamTumless** [comment]
@wgx Is this captured in your wirefame?
