### ISSUE TITLE
UA subscriptions: Build cancellation function

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#8966]
Build the cancellation function for a recurring subscription, as [described in the specification](https://docs.google.com/document/d/1K65n3NpZCh7EWDXKLhG31seGJ2jKbW6lqw3BwV2mlnU/edit#heading=h.ael1exmk6jt5).

(This was designed in [web-squad#3519](https://github.com/canonical-web-and-design/web-squad/issues/3519).)

**Comment by SirSamTumless** [comment]
Is this covered by other issues @ClementChaumel ?
