### ISSUE TITLE
UA subscriptions: Build period selection

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#8968]
Build the UI for choosing between monthly automatic and annual manual billing when buying a UA plan.

This is being designed in [web-squad#3501](https://github.com/canonical-web-and-design/web-squad/issues/3501).

**Comment by anasereijo** [comment]
@ClementChaumel this is ready for you. Let me know if you have any questions!

[design](https://zpl.io/bzKveXl)
[UX](https://github.com/canonical-web-and-design/web-squad/issues/3501)

**Comment by anasereijo** [comment]
closing this as we are not doing it anymore
