### ISSUE TITLE
Engage pages shouldn't bring down the homepage in case of failure

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/ubuntu.com#8996]
If discourse goes down, the homepage is not working. This shouldn't happen. There should be some default information displayed in case the engage pages go down.

**Comment by nottrobin** [comment]
Duplicate of https://github.com/canonical-web-and-design/web-squad/issues/3615. Or rather, mine was a duplicate of this, but mine was scheduled already so mine wins ;)
