### ISSUE TITLE
UA instructions for attach + Livepatch don’t work for 16.04/18.04

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-web-and-design/ubuntu.com#9001]
## Summary
The instructions for attaching your machines to UA are confusing.

1. Clicking the **Attached** tab says 

> To attach a machine: sudo ua attach TOKEN

This does not work on Ubuntu 16.04 or Ubuntu 18.04, with no instructions of what to do for these versions of Ubuntu. Customers are expecting that they have to attach their machines to get support, and they aren't able to.

2. Clicking the **Livepatch** tab presents instructions for using Livepatch. The instructions say:

> To activate Livepatch: | sudo snap install canonical-livepatch && sudo canonical-livepatch enable TOKEN

Running this on a 16.04 machine results in:

`2021/01/08 10:22:21 error executing enable: cannot enable machine: bad server status 401 (URL: https://livepatch.canonical.com/api/machine-tokens) server response: unauthorized`

After talking with [~cs](https://chat.canonical.com/canonical/pl/4ohoyytf7bbpjrneamkfnciz3y) it was determined that the key on /advantage is only for use with the UA client, if you aren't using the UA client you should use the token from auth.livepatch.canonical.com. This is not at all clear from /advantage and results in frustration for users.

## Screenshot

https://ubuntu.com/advantage

**Comment by matthewpaulthomas** [comment]
Thanks @cjohnston1158. This is really two bugs:

- We specified the instructions for old and new clients for the various services, but neglected to do that for attaching. That’s easily fixed, as long as we know what to do instead. Is it correct to say that for the old client there is no equivalent of “attaching” at all?

- The Livepatch instructions have the wrong token. This was my fault, because I gave “QA+1” to #8632, when if I’d tried the instructions I would have noticed that they didn’t work.

**Comment by matthewpaulthomas** [comment]
I’ve fixed the attachment instructions. Fixing the Livepatch token will require someone with greater skills than me, like @ClementChaumel or @sowasred2012.

**Comment by cjohnston1158** [comment]
@matthewpaulthomas a quick fix would be to adjust the instructions to use the token/instructions from auth.livepatch.canonical.com for 16.04/18.04. This would be a huge improvement and follow the style of instructions for certifications.

**Comment by matthewpaulthomas** [comment]
@cjohnston1158 Thanks for the suggestion. I’ve linked to auth.livepatch.canonical.com for the short term, and reported #9105 for a longer-term fix.
