### ISSUE TITLE
[UA shop] Unable to renew UA Infrastructure essential

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#9006]
From [livechat](https://my.livechatinc.com/tickets/PS8N5)

> Tue, 29 Dec 2020, 06:35 pm
> Message: Hi,
> I tried to renew the subcription but there is some error which makes impossible to enter payment card. You seem to have some javascript problem on the site.

Note: this is pretty old

**Comment by anthonydillon** [comment]
Looks like we have a short contracts service outage: https://sentry.is.canonical.com/canonical/ubuntu-com/issues/12753
