### ISSUE TITLE
VMWare to Charmed OpenStack takeover image

### ISSUE THREAD

**Issue by AmberCharitos** [canonical-web-and-design/ubuntu.com#9016]
Need the sizing added for an image that will be on a takeover briefed here: https://docs.google.com/spreadsheets/d/1RNCKO_UnGFN_ljGSz0eu53XsLP4RKDCI3_BbiZyzS60/edit#gid=1011867606

Happy to use the existing asset: https://assets.ubuntu.com/v1/2d935f28-openstack-cloud.svg

These are the fields I need filled in for this asset: 
Image width
Image height
Equal cols
Background

**Comment by anasereijo** [comment]
@AmberCharitos I updated the brief with a new Illustration. (the one you suggested is an older version)
