### ISSUE TITLE
Update Landscape line item in UAI table

### ISSUE THREAD

**Issue by Khutch25** [canonical-web-and-design/ubuntu.com#9030]
Please update Landscape line item to: 

Ubuntu systems management with Landscape

This is currently written this way on these pages:

- /advantage/subscribe
- /telco
- /pricing/infra

Also, please add it to /advantage table.

---
*Reported from: https://ubuntu.com/advantage/subscribe*

**Comment by pmahnke** [comment]
in Title case like that?

**Comment by Khutch25** [comment]
@pmahnke Sorry, matching the current case of 'systems management' which is lower case. I edited the comment above.
