### ISSUE TITLE
Add new copy doc to Ubuntu Copy Doc extension for /managed page

### ISSUE THREAD

**Issue by Khutch25** [canonical-web-and-design/ubuntu.com#9035]
It looks like the old /managed copy doc was deleted when Nilay left (see image of below error), so please replace the copy doc on the managed page in the extension with this copy doc: https://docs.google.com/document/d/1fLRWW-Gtslaia2ypSrLJVBxZVHo5FY5Q84o97Gs2-w4/edit?usp=sharing

![Screenshot 2021-01-15 at 13 22 13](https://user-images.githubusercontent.com/42180941/104732178-bc0fcc80-5734-11eb-8788-a962c2489289.png)

---
*Reported from: https://ubuntu.com/managed*

**Comment by SirSamTumless** [comment]
Is this still an issue @Khutch25 ?

**Comment by Khutch25** [comment]
@SirSamTumless yes. If you have the plugin, you can see for yourself :P
