### ISSUE TITLE
fix global nav on 320px viewport

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#9039]
What it looks like:

<img width="378" alt="Screenshot 2021-01-15 at 15 40 00" src="https://user-images.githubusercontent.com/36884067/104747158-17978580-5748-11eb-994c-0a5c549228bb.png">

How it should look like:

Products should be in the same row as canonical and we are hiring links

---
*Reported from: https://ubuntu.com/*

**Comment by anthonydillon** [comment]
What would you recommend? We could hide hiring on extra small screens?

**Comment by pmahnke** [comment]
Could it say 'Jobs'?  Is there a `.u-hide-veryverysmall`?

![image](https://user-images.githubusercontent.com/441217/109779353-c9f2b180-7bfd-11eb-9d5e-63661e78a900.png)

**Comment by mtruj013** [comment]
Issue has been fixed

![Screenshot 2021-09-17 at 15 34 55](https://user-images.githubusercontent.com/17607612/133791512-1560da7f-92e2-4994-95e9-b4c648f4f4c5.png)
