### ISSUE TITLE
[search for docs] ceph docs 

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#9049]

**Comment by carkod** [comment]
@SirSamTumless Need to go through this with a UX, who is available? robin is concerned about duplicating search boxes, as we already have ubuntu.com search box.

**Comment by SirSamTumless** [comment]
This is something @elioqoshi could look into.

**Comment by anasereijo** [comment]
might be relevant to mention that we also have search on [tutorials](https://ubuntu.com/tutorials)

**Comment by elioqoshi** [comment]
Might be a good reference for this:
https://ux.stackexchange.com/questions/123500/is-it-ok-have-to-have-two-search-bars-on-the-same-page

tl;dr: As long as the context is clearly differentiated it should be fine to have 2 search boxes. Might be worth specifying in the label what you are searching for.

Ideally we would do some user interviews for this to back this decision up. We probably might not have the time to do this now. I'd assume changing the global search box label from `Search` to `Search ubuntu.com` might be beneficial here as well.

**Comment by pmahnke** [comment]
I agree, with some good placeholder text or button text, it could be pretty
clear.

>

**Comment by cassiocassio** [comment]
@elioqoshi see @anasereijo 's visuals https://zpl.io/VxNjdOk for next-gen search, which is part of adding  login.

the text reads "Search on ubuntu.com"
