### ISSUE TITLE
UA pricing payment cycle unclear on ubuntu.com/advantage

### ISSUE THREAD

**Issue by elioqoshi** [canonical-web-and-design/ubuntu.com#9054]
It's currently unclear to what time cycle the pricing on https://ubuntu.com/advantage refers to:

![image.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/4fa1e168-9593-498a-832d-a47ccf8a84c8)

It only becomes clear this is the annual cost if the user actively starts buying a subscription.

**Comment by wgx** [comment]
@elioqoshi A valid point, but I _think_ this is due to be replaced with this: https://www.sketch.com/s/840eea9a-8c11-49ff-896c-8e55a55e9764/a/v50K5e/play ... at some point. cc @lechsandecki

**Comment by elioqoshi** [comment]
I figured, just couldn't find another issue for it (which wouldn't be surprising if I missed it)

**Comment by elioqoshi** [comment]
This has been addressed here:
https://github.com/canonical-web-and-design/ubuntu.com/issues/8932#issuecomment-765562024
