### ISSUE TITLE
SetStripeCustomerInfo getting called twice at roughly the same time

### ISSUE THREAD

**Issue by alnvdl** [canonical-web-and-design/ubuntu.com#9088]
The shop is apparently calling the `SetStripeCustomerInfo` endpoint of ua-contracts twice in a very short amount of time when VAT numbers are being set, which causes the method to become confused as it deletes some sub-resources of the customer in Stripe (namely, the tax ID). So we end up getting error messages like this in our logs:

```
{"code":"resource_missing","doc_url":"https://stripe.com/docs/error-codes/resource-missing","status":404,"message":"Customer ... does not have a TaxID object ...","param":"id","request_id":"req_...","type":"invalid_request_error"}
```

We could instead lock the customer in the contract service so that this doesn't get called twice and return a dedicated error for that, but the problem remains: the frontend is calling us twice at very close intervals, possibly before the response for the previous request is returned, which is not very efficient and can lead to errors.

I don't know the exact steps to reproduce this, but it's happening quite a lot in production. I think it tends to happen when the customer makes a mistake with their VAT number.

**Comment by alnvdl** [comment]
This seems to be affecting customers in production. I don't have hard evidence, but I think this bug may be preventing customers who made a first purchase with a VAT number from purchasing again. I wasn't able to test this on staging; is there an URL that we can always use to test the web interface against staging ua-contracts? I'd need that to gather more evidence.

**Comment by ClementChaumel** [comment]
To test against staging backend you can use the query param 'test-backend' like this: https://ubuntu.com/advantage/subscribe?test_backend=true

**Comment by alnvdl** [comment]
I managed to reproduce this on staging. These are the steps (might take a few tries because this is a concurrency issue):
1. Create SSO account
2. Try to make a first purchase logged-in while using a VAT number

ua-contracts was called 5 times to set customer information, and the 4th call failed, derailing the whole thing:
```
{"level":"info","ts":"2021-01-25T18:50:29.850Z","msg":"served","trace_id":"2e8cad03-9aad-45d3-9b2b-562832faca9f","proto":"HTTP/1.1","path":"/v1/accounts/aBV8jyblgCRKXnISnepMV8Vx5Xrg3PGsN9J5-HfiGkoc/customer-info/stripe","latency_in_ms":1356,"status":200,"size_in_bytes":184,"client_ip":"162.213.33.24","user_agent":"python-requests/2.25.1"}
{"level":"info","ts":"2021-01-25T18:50:32.583Z","msg":"served","trace_id":"9708191c-7a2f-4b9c-81ab-a2a98804534f","proto":"HTTP/1.1","path":"/v1/accounts/aBV8jyblgCRKXnISnepMV8Vx5Xrg3PGsN9J5-HfiGkoc/customer-info/stripe","latency_in_ms":2376,"status":200,"size_in_bytes":184,"client_ip":"162.213.33.24","user_agent":"python-requests/2.25.1"}
{"level":"info","ts":"2021-01-25T18:50:39.574Z","msg":"served","trace_id":"062b3f7b-dd30-4e73-b5fc-b224dc4c7076","proto":"HTTP/1.1","path":"/v1/accounts/aBV8jyblgCRKXnISnepMV8Vx5Xrg3PGsN9J5-HfiGkoc/customer-info/stripe","latency_in_ms":367,"status":200,"size_in_bytes":526,"client_ip":"162.213.33.24","user_agent":"python-requests/2.25.1"}
{"level":"info","ts":"2021-01-25T18:50:41.549Z","msg":"served","trace_id":"441386a2-ac20-4c72-90c5-7d604a6081a1","proto":"HTTP/1.1","path":"/v1/accounts/aBV8jyblgCRKXnISnepMV8Vx5Xrg3PGsN9J5-HfiGkoc/customer-info/stripe","latency_in_ms":1580,"status":500,"size_in_bytes":449,"client_ip":"162.213.33.24","user_agent":"python-requests/2.25.1"}
{"level":"info","ts":"2021-01-25T18:50:42.278Z","msg":"served","trace_id":"30539bf4-8dbb-4d0a-9ce8-5b85b9577eb5","proto":"HTTP/1.1","path":"/v1/accounts/aBV8jyblgCRKXnISnepMV8Vx5Xrg3PGsN9J5-HfiGkoc/customer-info/stripe","latency_in_ms":2356,"status":200,"size_in_bytes":184,"client_ip":"162.213.33.24","user_agent":"python-requests/2.25.1"}
```

Ideally, this would be just one call, but I understand we want to provide instant feedback on all fields, so that part is fine.

However, many of these calls are made in short succession, and it may be that one of the calls is made while Stripe is still running the other one. The frontend should only send another call if the previous one returned something already.

We could change ua-contracts to return some other error, but it'd still be an error, so I don't think it'd help you guys much.

Also, the `test_backend=true` thing doesn't seem to work well with the staging environment, it constantly thinks I'm not logged in, and I have to navigate between pages and put the flag every time.

**Comment by wgx** [comment]
Fixed by subsequent refactor.
