### ISSUE TITLE
Stuckstack webinar - should be embedded in page

### ISSUE THREAD

**Issue by AmberCharitos** [canonical-web-and-design/ubuntu.com#9093]
## Summary

https://pages.ubuntu.com/stuckstack_webinar_upgrades_register.html, which is linked from the u.c/openstack/features page should have an embedded webinar but does not appear to.

**Comment by sowasred2012** [comment]
@AmberCharitos is this still an issue? If I fill out the form on that page, I'm taken to the webinar.
