### ISSUE TITLE
https://ubuntu.com/kernel/lifecycle needs updating for HWE-by-default in 20.04

### ISSUE THREAD

**Issue by iainlane** [canonical-web-and-design/ubuntu.com#9101]
For Ubuntu Desktop in 20.04 we install the HWE kernel "track" by default for everyone. This means that everyone starts out at 5.4 at 20.04.0 time, and then rolls forward to 5.8 at around 20.04.2 time, so on.

This is a change - in previous LTS releases only people who installed from .2 would have been on HWE; everyone who installed earlier would have been on the release (GA) kernel forever.

We need to update this page to reflect this because it's a bit misleading currently. The rest of the content could do with an update too.

@xnox has updated [this wiki page](https://wiki.ubuntu.com/Kernel/LTSEnablementStack) which could probably serve as a good basis for any updated copy.

---
*Reported from: https://ubuntu.com/kernel/lifecycle*

**Comment by xnox** [comment]
> This means that everyone starts out at 5.4 at 20.04.0 time, and then rolls forward to 5.8 at around 20.04.2 time, so on.

To be more precise I'd say that "most" start out with v5.4 and roll forward to v5.8 etc.

Some will start out with v5.6 or v5.10, but all eventually roll to newer things, on per-sku basis.

In flavour speak that is most track "HWE" kernel flavour, and some SKUs track "OEM" kernel flavour.

Both of which are rolling (evergreen) flavours.

**Comment by iainlane** [comment]
> To be more precise

If we can avoid making it as complicated as that it would be better I think.

**Comment by SirSamTumless** [comment]
@rhys-the-davies Could you update the copy doc then ping canoical editors?

**Comment by anthonydillon** [comment]
Deadline for Thursday the 4th of Feb
