### ISSUE TITLE
Replace auth.livepatch.canonical.com with ubuntu.com/advantage

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#9105]
[auth.livepatch.canonical.com](https://auth.livepatch.canonical.com/) provides Livepatch setup instructions, for personal or paid use on 14.04/16.04/18.04, including a user-specific token. This has several drawbacks:
- it gives no instructions for 20.04 LTS users
- the linked instructions for 14.04 users are out of date (they should now use the `ua` command instead)
- it’s isolated from the setup instructions for all other UA services.

Meanwhile, [ubuntu.com/advantage](https://ubuntu.com/advantage) provides Livepatch instructions for 14.04 and 20.04 LTS. I specified that it should also provide instructions for Ubuntu 16.04 and 18.04 LTS. Unfortunately these instructions included a token that doesn’t work (the UA token, rather than the standalone Livepatch token). So in #9104 I’ve replaced the instructions with a link to auth.livepatch.canonical.com.

A more thorough fix would involve either:
- replacing the link I just added, on /advantage, with instructions containing the correct token from livepatch.canonical.com

Or:
- the `ua` command being shipped on 16.04 and 18.04
- the 16.04-/18.04-specific instructions being removed from /advantage’s “Livepatch” cells altogether, because they can now use `ua` instead.

Either way, the last step would be:
- retiring auth.livepatch.canonical.com, replacing it with a redirect to ubuntu.com/advantage.

**Comment by SirSamTumless** [comment]
@lechsandecki Can you review the proposal above?

**Comment by SirSamTumless** [comment]
@frankban Do you think we still need this site at all anymore?

**Comment by albertkol** [comment]
Closing this. If it becomes relevant open a new one.
