### ISSUE TITLE
Ubuntu Advantage shop is making excessive API requests to shop backend

### ISSUE THREAD

**Issue by cmars** [canonical-web-and-design/ubuntu.com#9108]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

Customer reported an issue with the shop, saying they were unable to make a purchase. When we went to go investigate, we found a high number of API requests for the customer in question.

## Process

Unsure, but we assume it was a normal purchase at buy.ubuntu.com.

## Current and expected result

The high number of repeated API calls in a short period of time seems like it could be indicative of a problem in the web frontend.

This internal link has a log of the API calls we received on our side. As you can see, they are all for the same user and account in a short timespan.

https://pastebin.canonical.com/p/PpvVkJ2tsC/

## Screenshot

Not available.

## Browser details

Not available.

**Comment by wgx** [comment]
We believe this is resolved, please re-open if this is still present.
