### ISSUE TITLE
UC20 - /core/features/ota-updates page

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#9123]
#### [copy doc](https://docs.google.com/document/d/1CftibGyQdcto7E-tUnpwZOXMJsvOegAqk0FyoL3kQEA/edit#)

- [x] UX first pass
- [x] Design first pass
- [x] Brand to design illustrations (@waynecrosby)
- [x] Ready for build

**Comment by wgx** [comment]
@anasereijo did a brief pass, the animations need work IMO. Won't have any more free time to devote to this today, but I can look again next week if needed.

**Comment by anasereijo** [comment]
First design pass done

**Comment by waynecrosby** [comment]
Here are the updated GIFs:

https://assets.ubuntu.com/v1/7b24c736-OTA-GIF_1_WHT.gif
https://assets.ubuntu.com/v1/bb60ec1a-OTA-GIF_1_Transparent.gif

https://assets.ubuntu.com/v1/a0077922-OTA-GIF_2_WHT.gif
https://assets.ubuntu.com/v1/a015f4cb-OTA-GIF_2_Transparent.gif

https://assets.ubuntu.com/v1/454d7467-OTA-GIF_3_WHT.gif
https://assets.ubuntu.com/v1/32e4c162-OTA-GIF_3_Transparent.gif

https://assets.ubuntu.com/v1/8247250c-OTA-GIF_4_WHT.gif
https://assets.ubuntu.com/v1/54777fe1-OTA-GIF_4_Transparent.gif

https://assets.ubuntu.com/v1/f41edfe8-OTA-GIF_5_WHT.gif
https://assets.ubuntu.com/v1/6c90dd33-OTA-GIF_5_Transparent.gif

**Comment by anasereijo** [comment]
Amazing, Wayne! Thanks

**Comment by anasereijo** [comment]
@bethcollins92 this is ready for you!
