### ISSUE TITLE
Verification of domain for Facebook

### ISSUE THREAD

**Issue by AmberCharitos** [canonical-web-and-design/ubuntu.com#9136]
Verification needed for Facebook ads - options are DNS verification, Meta tag or HTML file. Only one needed, whichever is easier - I can press verify in Facebook when done 

Meta tag: ![Screenshot 2021-02-01 at 10 58 09](https://user-images.githubusercontent.com/67629430/106449894-6188a700-647c-11eb-8ac3-02080c9de54f.png)

HTML file upload: ![Screenshot 2021-02-01 at 10 58 54](https://user-images.githubusercontent.com/67629430/106449989-7feea280-647c-11eb-8237-e709939271a6.png)

DNS: ![Screenshot 2021-02-01 at 10 55 38](https://user-images.githubusercontent.com/67629430/106449596-08207800-647c-11eb-85a3-f79af8860026.png)

**Comment by AmberCharitos** [comment]
DNS TXT record (for copy and paste): facebook-domain-verification=zxp9j79g1gy2xenbu9ll964pttk5hu

Meta tag: <meta name="facebook-domain-verification" content="zxp9j79g1gy2xenbu9ll964pttk5hu" />

I can send you the HTML file if you want to use this version of verification

**Comment by anthonydillon** [comment]
@AmberCharitos the verification meta tag has been added and pushed live. You can hit the button.

**Comment by AmberCharitos** [comment]
Thanks @anthonydillon
