### ISSUE TITLE
[Kubeflow news] Design twitter and contact us link

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#9138]
Create **Add contact and twitter to Kubeflow News** based on the [brief](https://docs.google.com/document/d/1wzGk9rTyO-7ow_zdF8lpECMkDu1rLiCKq7CHPFwENtA/edit?ts=5ffc500e)

Design links for 'follow us on twitter' and 'Contact us with your kubeflow news' - perhaps boxes in the right rail? or header?

**Comment by anasereijo** [comment]
Hi @RFMVasconcelos and @andreeamun-zz,

see below my suggestions for Kubeflow news contact us and Twitter links.
Please let me know your thoughts.


### Contact us

- link on the hero section, below the intro text
- link on the footer

### Follow us on Twitter

- below the Newsletter form

### other tweaks/improvements 

- I can see we have now pagination: could we then reduce the number of posts visible? I suggest having around 5.

![Kubeflow news](https://user-images.githubusercontent.com/36884067/108347101-0d015d80-71d8-11eb-9efb-671ff6d92fec.jpg)

**Comment by RFMVasconcelos** [comment]
Looking good @anasereijo! 5 posts per page sounds good
