### ISSUE TITLE
[Kubeflow news] Build twitter and contact us link

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#9139]
Create **Add contact and twitter to Kubeflow News** based on the [brief](https://docs.google.com/document/d/1wzGk9rTyO-7ow_zdF8lpECMkDu1rLiCKq7CHPFwENtA/edit?ts=5ffc500e)

Build links for 'follow us on twitter' and 'Contact us with your kubeflow news' - perhaps boxes in the right rail? or header?

**Comment by anasereijo** [comment]
devs this is ready for you https://github.com/canonical-web-and-design/ubuntu.com/issues/9138

**Comment by pmahnke** [comment]
https://publish.twitter.com/?buttonLarge=on&buttonType=FollowButton&query=kubeflownews&widget=Button

the button should be Large

**Comment by anasereijo** [comment]
@pmahnke @bethcollins92 I assigned you both so this won't get "lost". Feel free to unassign yourself

**Comment by bethcollins92** [comment]
@pmahnke where should the "Contact us with your kubeflow news" link to? Do I need to create a contact us form?

**Comment by anasereijo** [comment]
> @pmahnke where should the "Contact us with your kubeflow news" link to? Do I need to create a contact us form?

Hey @bethcollins92 I believe someone answered that same question in the [brief](https://docs.google.com/document/d/1wzGk9rTyO-7ow_zdF8lpECMkDu1rLiCKq7CHPFwENtA/edit?ts=5ffc500e)

**Comment by bethcollins92** [comment]
> > @pmahnke where should the "Contact us with your kubeflow news" link to? Do I need to create a contact us form?
> 
> Hey @bethcollins92 I believe someone answered that same question in the [brief](https://docs.google.com/document/d/1wzGk9rTyO-7ow_zdF8lpECMkDu1rLiCKq7CHPFwENtA/edit?ts=5ffc500e)

ahhh thank you @anasereijo, didn't see those comments!
