### ISSUE TITLE
Incorrect date on renewed contract

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#9141]
## Summary

A customer has reported seeing an incorrect date on their contract after renewing, causing confusion as to whether the renewal actually happened or not.

## Current and expected result

In the screenshot below, their contract shows an end date of 29/01/20, but should show an end date of 29/01/22. CS/contracts API team (@alnvdl) have confirmed that the contract has the expected date. 

## Screenshot

![Screenshot from 2021-02-01 14-28-51](https://user-images.githubusercontent.com/2376968/106472631-c3f0a000-649a-11eb-8e29-5287621b7f07.png)

**Comment by anthonydillon** [comment]
According to the CS team these dates are always likely to be an approximation.
