### ISSUE TITLE
[UA-Shop] Add a page to allow user to manage and resolve payment issues on Purchases

### ISSUE THREAD

**Issue by brotich** [canonical-web-and-design/ubuntu.com#9174]
**Summary**

We need to provide a way for customer to see and resolve common payment issues after the initial payment flow.

**Scenario**
for example:
1. I start to make purchase on the shop for UA essential desktop through the normal purchase flow.
2. I navigate away from the page before authorizing the payment i.e 3Ds flow
3. The purchase shall remain in incomplete and will be cancelled by Stripe in about 24 hours

**possible solution**
To recover from the above we need a page that:
- will allow customer to see all pending purchases for their account (log in may be necessary).
- fix payment issue i.e authorize payments, change payment method for the purchase.
- after that, ping ua contracts to complete the purchase with the payment method provided.

The page link above shall be used as a link in an email that Stripe sends to the user when the payment fails. see https://stripe.com/docs/receipts#failed-payment-alerts

**UA backend endpoint**
1. Use `GET http://<contracts-url>/v1/accounts/<account-id>/marketplace/canonical-ua/subscriptions` to get a list of all the subscriptions for the account.
the subscriptions with pending purchases shall be populated as below:
```json
{
    "subscriptions": [
        {
            "pendingPurchases": [
                "pxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            ],
            "subscription": {
                "accountID": "axxxxxxxxxxxxxxxxxxxxxxxxxxx"
                ....
            }
        }
    ]
}
```
2. use `POST /v1/purchase/{purchaseID}/payment/stripe/{invoiceID}` to instruct ua contracts to complete the purchase.
 see https://github.com/CanonicalLtd/ua-contracts/blob/5c590ffeaef45b23509e7e40b03d04d023c03c8a/docs/contracts.yaml#L2768-L2806 for more details

**Optional/Good to have**
- it could be awesome if we could have a banner at /advantage informing the user that there is a pending purchase that need their attention.

**Comment by brotich** [comment]
@ClementChaumel kindly take a look at this and advice

**Comment by SirSamTumless** [comment]
Hi - some of the issues you've flagged has already been deployed, other issues are pending and some tie into future features.

**Comment by albertkol** [comment]
Most of this has been done:
- we do display a notification on /advantage to inform the user that there is a pending purchase that need their attention.
- they can also fix pending purchases by going to /advantage

The only missing bit is displaying pending payments, but we might add it together with the "Payments and Invoices" work.

Closing this issue.
