### ISSUE TITLE
[Suggestion] Use newer version of Memtest86+

### ISSUE THREAD

**Issue by Omcsesz** [canonical-web-and-design/ubuntu.com#9176]
Hello, All!

I recently downloaded the latest version of Ubuntu Live 20.10., but the image contains a rather old version of Memtest86+ (v5.01). is there a reason why it is not updated?

**Comment by pmahnke** [comment]
Thank you for filing this bug; unfortunately, it is not the right place to report this particular issue. 

This repo is for the development of the ubuntu.com website, not the OS. 

You may want to [file a bug report in launchpad](https://bugs.launchpad.net/ubuntu).  

Here is information on [how to report a bug](https://help.ubuntu.com/community/ReportingBugs).
