### ISSUE TITLE
UA Subscription overview table redesign

### ISSUE THREAD

**Issue by elioqoshi** [canonical-web-and-design/ubuntu.com#9177]
When managing subscriptions on UA, there are currently multiple chevrons expanding the row into different views:

![image.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/fca6e40c-8e12-40d5-8ac8-7281f6f4f0b8)

It would be great if we can redesign this properly as the current pattern used is very odd and not a widely used interaction. I have experimented on 2 different proposals to address this, basically taking the various row options and moving them into the expanded view of the row as tab menu items.

A
![image.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/e74cb426-07f6-441c-8407-778f9c21e8c2)

B
![image.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/0d8ff50e-f976-4e39-84a1-12447c4b2fa2)

## Considerations:
- The table is currently not in Vanilla and UA subscriptions is currently the only place where this pattern is used (to the extent of my limited knowledge)
- The vertical tabs are not in Vanilla and not used anywhere else. Regardless of the decision whether the whole tables should be part of Vanilla, a new Tab component should be part of Vanilla.
- Horizontal tabs are already present in Vanilla and can be used right away. Visually it might be problematic though as the relationship between the parent row and its child items might not be clear.
- MPT was not a fan of this solution as it would increase the number of clicks a user would need to access an option by 1. However @wgx argues that users don't arrive often here and that wouldn't be a critical factor (I agree).

I'd like to take this on once we get a chance, as well as with @anasereijo doing the visual design changes.

**Comment by elioqoshi** [comment]
As a reference, this came up for the first time in the UA resizing interaction work:
https://github.com/canonical-web-and-design/web-squad/issues/3650#issuecomment-764667048

To quote mpt:

> _Option B would be a big change to the table in general. Maybe we’ll need to switch to something like that as we add more columns, for Landscape and for tech support. But I hope not, because I think it’s really straightforward to be able to click the ESM cell and get info just about ESM, the Livepatch cell and get just info about Livepatch, etc. Our onboarding for new subscriptions takes advantage of that directness._

I do think it's worth to revisit that sentiment.

**Comment by anthonydillon** [comment]
I prefer option B:
- as the pattern already exists in therefore development is easier.
- works better on small screens as a vertical tab list would need to switch for small screens
- I see the concern with the confusion with the row above. I believe distinct styling would resolve this. For example, clear background change.
- as an extension, I think it would be good to explore switching the tabs to something like ["Overview", "Services", "Settings"]. Allowing use to organise the content by its purpose. For example the Services tab would cover whats available and how to enable it. And settings would contain actions, such as rename, scale, delete, etc.

My 2 cents.

**Comment by elioqoshi** [comment]
These are very valid points @anthonydillon , thanks! If we can address the distinct styling and reorganize the options by purpose, Option B would be ideal yes.

**Comment by clagom** [comment]
I think the proposed explorations miss a visual connection that highlights which row is currently open. Something to look at during the visual phase; the chevron would rotate as well.
On a side note, for expanding elements we currently use "+" in Vanilla, although we discussed during design sessions that we would prefer to use the chevron in these cases.

**Comment by cassiocassio** [comment]
@anasereijo and @lyubomir-popov can you bring a link to your explorations of the drop-down-cell here for reference?

**Comment by anasereijo** [comment]
> @anasereijo and @lyubomir-popov can you bring a link to your explorations of the drop-down-cell here for reference?

sure, I will upload everything on zelpin later today and post the link here

**Comment by elioqoshi** [comment]
We are looking at this table experience in this cycle in a more hollistic way, so taking a step back to scope what's needed for it. The current scope in this issue doesn't fit with the expectations for it so closing it.
