### ISSUE TITLE
Non default filesystem / mount options

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#9190]
**Outline**
Subiquity currently always uses the default options when creating and when mounting a filesystem. While Ubuntu strives to offer good defaults, there are reasons why a user might want to use non-default options for these.

**Comment by elioqoshi** [comment]
Referencing @clagom work on Subiquity 18.10 as a reference here:
https://drive.google.com/drive/u/2/folders/1CBBCoZV3_Tn3TgFiLULHuxoPZeoRoquC

**Comment by elioqoshi** [comment]
This can be considered wrapped up. We can still look at polishing it up in the implementation stage. 

Reference specs: https://docs.google.com/document/d/1rsapWIKR9xR3sXE56WUEETSvnZkxJH4RqrvJCKK7IWI/edit#heading=h.v8vlh9f5o0cz
