### ISSUE TITLE
Need Help: Making sense of the current dockerized setup

### ISSUE THREAD

**Issue by kcq** [canonical-web-and-design/ubuntu.com#9198]
@nottrobin It used to be possible to run the app in a single container, but now there's an interesting and a slightly non-standard multi-container setup and I wonder if you can help out making sense of it, so I can update the DockerSlim example ( https://github.com/docker-slim/examples/tree/master/3rdparty/ubuntu-com ).

I see the docker-compose.yml file, but it only has the PG database. The `run` shell scripts seems to do a bit of magic to do various things in containers (looks like it will connect to the network created by docker-compose). I assume it's related to the `dotrun` tool you created.

I'd like to have a pure `docker-compose` setup and I need your help figuring out the configs (especially the CMD params for the web app container).

**Comment by nottrobin** [comment]
For building the production image, only the Dockerfile is relevant. Both the docker-compose file and the run script are purely for local development.

To actually build the image is something like `DOCKER_BUILDKIT=1 docker build .`. Maybe with a couple of argument, I can't quite remember.

The Dockerfile uses [multistage builds](https://docs.docker.com/develop/develop-images/multistage-build/) to prep the resources (install deps, build CSS & js) and makes use of [buildkit](https://docs.docker.com/develop/develop-images/build_enhancements/) for creating pip and npm cache layers to speed up subsequent builds.

It should all work with a normal docker install, as long as you set `DOCKER_BUILDKIT=1`.

**Comment by x-private-one** [comment]
Building it is pretty straight forward... Running it is tricky :-) The `docker run` call has a lot of parameters and I wonder, which ones I really need and which ones are optional. For example, here are the `docker run` params in the `docker_run` function:
```
        --name ${container_name}     `# Name the container` \
        --rm                         `# Remove the container once it's finished`  \
        --volume "$(pwd):$(pwd)"     `# Mirror current directory inside container`  \
        --workdir "$(pwd)"           `# Set current directory to the image's work directory`  \
        --volume ${etc_volume}:/etc  `# Use etc with corresponding user added`  \
        --volume ${usr_local_volume}:/usr/local/       `# Bind local folder to volume`  \
        --volume ${cache_volume}:/home/shared/.cache/  `# Bind cache to volume` \
        --env COMMIT_ID=${commit_id} `# Pass through the commit ID` \
        ${network}                   `# Network settings, if needed` \
        ${env_file}                  `# Pass any files of environment variables to the container`  \
        ${env_vars}                  `# Pass explicit environment variables to the container`  \
        ${http_proxy}                `# Include HTTP proxy if needed`  \
        ${tty}                       `# Attach a pseudo-terminal, if relevant`  \
        ${docker_run_options}        `# Extra options`  \
        ${dev_image} $@              `# Run command in the image`
```

The environment variables is probably the most important part there. I assume, there's a set of env vars that must be provided (while others are optional). Is it the env vars in the `.env` file or is there more?

**Comment by nottrobin** [comment]
It looks like you're pulling these arguments from [the `run` script](https://github.com/canonical-web-and-design/ubuntu.com/blob/master/run). As I said above, this is for local development. If you want to show `docker-slim` can build ubuntu.com, I suggest you ignore that file, and local development in general, completely. Unless you're trying to show that `docker-slim` can support local development? That would be a completely different conversation.

If all you want to do is get it running then you don't need any of the `--volume`s or `--workdir`. `--env COMMIT_ID` is irrelevant and not used. `--rm` and `--name` are about local container management and should be familiar to anyone used to running docker, and are not required but are things the user can choose to set if they like. All the others options are again for our specific tooling and can also be ignored.

## Running the site

This took me an embarrassingly long time to get running, so not surprised you might have struggled =)

I just checked and you can build the image simply with `docker build` although I would recommend tagging it so you can refer to it later. However, I did realise after posting my previous message that the image is still dependent on a database. Hopefully we're gonna remove this soon.

So at present, this is the best way to get the site basically running with `docker`, but without setting it up for local development:

``` bash
docker build --tag ubuntu-com .  # Build the site image
docker run --rm --detach --env POSTGRES_PASSWORD=pw --name db postgres  # Run a blank database
DB_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' db)  # get its IP address
docker run --publish 80:80 --env SECRET_KEY=ohsosecret --env DATABASE_URL=postgres://postgres:pw@${DB_IP}:5432/postgres --tty --interactive ubuntu-com
```

Now go to http://localhost to see the ubuntu.com website running =)

**Comment by kcq** [comment]
@nottrobin Thanks a lot! Not having the database dependency will be great :) My containers were failing at runtime because of the missing DATABASE_URL env var. I wasn't sure how many other env vars were necessary and if there were any additional requirements on top of that. Looks like I should be good with setting SECRET_KEY and DATABASE_URL.

**Comment by nottrobin** [comment]
Great! This is resolved then? Closing, let me know if you want it reopened.
