### ISSUE TITLE
Newletter sign up doesnt work

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#9205]
The sign up on https://ubuntu.com/internet-of-things/edgex#subscribe does not work anymore.

**Comment by caldav** [comment]
Same here: https://ubuntu.com/whitepapers/beta/robotics.

Probably requires the same fix as https://github.com/canonical-web-and-design/ubuntu.com/pull/8939

**Comment by SirSamTumless** [comment]
Could you please give this a priority and estimate it, then triage it if it isn't being worked on this iteration?
