### ISSUE TITLE
Background submit CUBE beta apply for access form

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/ubuntu.com#9208]
Submit form to marketo without being redirected to the thank-you page

**Comment by bethcollins92** [comment]
@anthonydillon Would you be able to elaborate on this please and help me understand why background submit is better in this situation? Also, I took a look at the `backgroundSubmit` function on ubuntu.com and it seems this is a function for all marketo forms, so not sure why/how this form is different? I can change the redirect to remain on `/cube` instead of going to a thank you page but feel there is more to it. Thanks!

**Comment by anthonydillon** [comment]
I don't mind which one you go for. My comment is about landing on the thank you page. I would expect a form to appear in a model which then lands me back where I was. 

If you go for the redirect it would be nice to land back on the course you applied for, with a message saying thanks for your interest. 

Also, I assume we would want to know the popularity of the courses. So would be worth add a hidden field with the course as extra data.
