### ISSUE TITLE
[COPY UPDATE] charmed-osm.com

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#9224]
Please edit chared-osm.com based on the [copy doc](https://docs.google.com/document/d/1mKfttykmrc4ub_LkqdRGIE_x9WgR1NGr7ulxrLvIZXk/edit?ts=60224421#heading=h.m6z8ibpxu8wt).

**Comment by anthonydillon** [comment]
For the blog feed:
You will want to import the latest-news package, for example: https://github.com/canonical-web-and-design/ubuntu.com/blob/master/package.json#L75

Then you could take Peters include and use that: https://github.com/canonical-web-and-design/ubuntu.com/blob/fe922d66a64b91ffe089cdc3af09b4de4ddf0492/templates/shared/_latest_news_strip.html#L52

Include with the following: https://github.com/canonical-web-and-design/ubuntu.com/blob/e377d69761c239657c943e049cede9cf50cdcab2/templates/wsl/index.html#L396

The tag id you will need are:
charmed OSM: 3572
OSM: 3527
_**To find these** jump on VPN and go to https://admin.insights.ubuntu.com/wp-admin/edit-tags.php?taxonomy=post_tag&post_type=post&s=osm and see the tag_ID in the URL when hovering over the tag links_

Give me a shout if you get stuck on anything.
