### ISSUE TITLE
UA - Add tests to make sure we send the correct address

### ISSUE THREAD

**Issue by ClementChaumel** [canonical-web-and-design/ubuntu.com#9227]
We recently fixed a bug with the modal so we should add tests to make sure it doesn't happen again 
https://github.com/canonical-web-and-design/ubuntu.com/pull/9222#issuecomment-777421776

**Comment by cristinadresch** [comment]
Blocked until we decide on the checkout redesign

**Comment by albertkol** [comment]
Checkout will be rebuilt. We can close this one.
