### ISSUE TITLE
Loss of tabs and design on ubuntu.com/openstack

### ISSUE THREAD

**Issue by pmatulis** [canonical-web-and-design/ubuntu.com#9229]
On https://ubuntu.com/openstack there is a second-level row of tabs (e.g. 'Overview', 'What is OpenStack'). Every tab's resulting page preserves this row of tabs and colour/design with the exception of 'TCO calculator'.

**Comment by pmahnke** [comment]
This was because it used to be accessible from 2 sections of the site.  I will update it.
