### ISSUE TITLE
[COPY UPDATE] Enterprise menu

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#9236]
Please update the enterprise menu based on this [copy doc](https://docs.google.com/document/d/1YBdQvLuqEpEQr_QqyycxMhZr4OaLapMlNJyYKCmPJsQ/edit?ts=602658ab).

**Comment by RFMVasconcelos** [comment]
Thank you @SirSamTumless and @bethcollins92 !
