### ISSUE TITLE
Product documentation is not searchable

### ISSUE THREAD

**Issue by pmatulis** [canonical-web-and-design/ubuntu.com#9243]
The search facility present in the header of all ubuntu.com sites, including product documentation pages such as

* https://ubuntu.com/kubernetes/docs
* https://ubuntu.com/ceph/docs

does not specifically search the respective project's doc pages. It has some other kind of unknown scope, which is a separate issue.

As is, product documentation is not searchable.

Example:

A user is on the Kubernetes doc page and searches for `kubectl`. This term is used abundantly in this doc set but the facility yields the following top three results:

1. https://ubuntu.com/blog/kubectl-and-friends-as-a-snap
2. https://microk8s.io/docs/working-with-kubectl
3. https://snapcraft.io/kubectl
 
The [MAAS](https://maas.io/docs) and [Snap](https://snapcraft.io/docs) documentation do not suffer from this problem (search works very well), but they are not hosted on ubuntu.com.

**Comment by SirSamTumless** [comment]
@pmatulis Thanks for flagging, we are aware of this and plan to add search to our docs soon.
