### ISSUE TITLE
Regression on 3DS purchases?

### ISSUE THREAD

**Issue by alnvdl** [canonical-web-and-design/ubuntu.com#9256]
Run the following steps on **staging**:

1. Make a purchase using the 3DS test card: `4000 0027 6000 3184`. I tested with a first purchase in the account, but I think it doesn't matter.

2. Watch the request logs. You will see the purchase polling return something like the following:
    
       {"accountID":"aBZbDwi8dxXwenKfsz2PL-YRCOgYoe4guW6OMK4okc1M","createdAt":"2021-02-18T13:36:33.123Z","createdBy":"4ddz7sG","id":"pANiGf9KeHxksbBqPnRLfLFFDPP5BW9mOYaGm5UXTXrg","lastModified":"2021-02-18T13:36:34.892Z","purchaseItems":[{"metric":"active-machines","productListingID":"lAPB3Mfq9enJCr2o8iELqzjgYjjiCAWsSNCXv8wHF_-Q","value":3}],"status":"processing","subscriptionID":"sADg5hDxJ9euj7svCTH-ymSRcKWaYgiKK2O6WxT2GKyQ"}
    

If I get the same purchase from ua-contracts logged-in as the same user at the same time, I get the following:

    $ curl -X GET ${CONTRACTS_URL}v1/purchase/pANiGf9KeHxksbBqPnRLfLFFDPP5BW9mOYaGm5UXTXrg -H "Authorization: Macaroon $MACAROON"
    {"accountID":"aBZbDwi8dxXwenKfsz2PL-YRCOgYoe4guW6OMK4okc1M","createdAt":"2021-02-18T13:36:33.123Z","createdBy":"4ddz7sG","id":"pANiGf9KeHxksbBqPnRLfLFFDPP5BW9mOYaGm5UXTXrg","invoice":{"currency":"usd","customerAddress":{"city":"City","country":"BR","line1":"R 123","line2":"","postal_code":"123456","state":""},"customerEmail":"allan.vidal+dev@canonical.com","customerName":"Allan (dev)","id":{"IDs":["in_1IMCgHCzjFajHovd0fPYanan"],"origin":"Stripe"},"identifier":"23C7042D-0001","lineItems":[{"currency":"usd","description":"3 machine × UA Infrastructure - Standard (Desktop) (at $150.00 / year)","planID":{"IDs":["CQC221902"],"origin":"Stripe"},"proRatedAmount":45000,"quantity":3}],"paymentStatus":{"piClientSecret":"<secret-here>","status":"need_3ds_authorization"},"reason":"subscription_create","status":"open","subscriptionID":{"IDs":["sub_Iy8ybZ5Xn0gOyB"],"origin":"Stripe"},"total":45000},"lastModified":"2021-02-18T13:36:34.892Z","purchaseItems":[{"metric":"active-machines","productListingID":"lAPB3Mfq9enJCr2o8iELqzjgYjjiCAWsSNCXv8wHF_-Q","value":3}],"status":"processing","stripeInvoices":[{"id":"in_1IMCgHCzjFajHovd0fPYanan","last_update":"2021-02-18T13:36:36.295955Z","pi_secret":"<secret-here>","pi_status":"requires_action","subscription_status":"incomplete"}],"subscriptionID":"sADg5hDxJ9euj7svCTH-ymSRcKWaYgiKK2O6WxT2GKyQ"}

Note how the response returned by the frontend-backend is missing the `stripeInvoices` field.

I couldn't find a good explanation for that, and it could be an issue in ua-contracts, but I don't know where to start looking. It would be nice to have visibility into what the frontent-backend is getting from ua-contracts in this case.

**Comment by anthonydillon** [comment]
@ClementChaumel @albertkol could you investigate this and try and find a cause? If nothing jumps out, let's schedule a call with @alnvdl to try and debug together.

**Comment by anthonydillon** [comment]
From @alnvdl on MatterMost:
> what is puzzling me is the fact that (in theory) the frontend code is just calling ua-contracts directly and passing the json along, but somehow, that JSON is missing an important field. If anyone could try to reproduce this while looking at some enriched logs showing who's returning what, that would probably lead us to discover the root cause

> oh... it just occurred to me: caching... again...

**Comment by alnvdl** [comment]
I found the reason, it's the evil cache, again:
```
x-cache-status: HIT from content-cache-gs2/0
```

The result of getting a purchase should never be cached. I'd go as far as saying that nothing under `/advantage` should be cached at all.
