### ISSUE TITLE
Case-sensitive USN search

### ISSUE THREAD

**Issue by aostromich** [canonical-web-and-design/ubuntu.com#9260]
Hello,

The search on https://ubuntu.com/security/notices is case-sensitive. For example, [searching "jackson"](https://ubuntu.com/security/notices?order=newest&release=&details=jackson) returns no results while ["Jackson" does have hits](https://ubuntu.com/security/notices?order=newest&release=&details=Jackson).
This is unexpected behaviour and makes searching finicky, would it be possible to make this search case-insensitive?

Thanks!

**Comment by minkyngkm** [comment]
Seems it's been all fixed.

![image.png](https://images.zenhubusercontent.com/6107a8f6f31b48581e4d4f93/0af5a340-9729-4aa9-a5db-77312a2c7414)
![image.png](https://images.zenhubusercontent.com/6107a8f6f31b48581e4d4f93/64b8dcd2-15a3-4928-81f3-c15b76b99b97)
