### ISSUE TITLE
Juju documentation links point to the user forum

### ISSUE THREAD

**Issue by pmatulis** [canonical-web-and-design/ubuntu.com#9270]
Links in the [Juju documentation](https://juju.is/docs) are starting to point directly to the Juju [user forum](https://discourse.charmhub.io/) (Discourse). Here are a couple of reasons for **not** doing this:

1. Once at the new site the reader loses their bearings as a navigation menu is no longer accessible. The reader becomes lost.
2. It's inexplicable and frustrating. The reader wonders why this is happening, especially when they discover that those pages exist on the doc site.

**Comment by anthonydillon** [comment]
@pmatulis this is the repo for ubuntu.com issues, 

The current implementation of discourse docs stipulates that any documentation page that is not in the navigation of the docs should link to discourse as it is not part of the main documentation content. Please file an issue on the discourse module if you would like to [request a change to this behaviour](https://github.com/canonical-web-and-design/canonicalwebteam.discourse/issues).
