### ISSUE TITLE
KeyError: 'macaroon_root'

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#9283]
https://sentry.is.canonical.com/canonical/ubuntu-com/issues/9570/?referrer=github_plugin

```
KeyError: 'macaroon_root'
(4 additional frame(s) were not displayed)
...
  File "flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "site-packages/flask_openid.py", line 510, in decorated
    return self.after_login_func(OpenIDResponse(
  File "webapp/login.py", line 84, in after_login
    root = Macaroon.deserialize(flask.session.pop("macaroon_root"))
  File "werkzeug/datastructures.py", line 269, in pop
    rv = super(UpdateDictMixin, self).pop(key)

KeyError: 'macaroon_root'
```

**Comment by SirSamTumless** [comment]
@jpmartinspt Could you please triage this?

**Comment by jpmartinspt** [comment]
@nottrobin should we just check for `macaroon_root` and if not redirect back to the login page? seems like it's what we do on snapcraft, but if you have a different opinion let me know!

**Comment by nottrobin** [comment]
@jpmartinspt do we know what's actually happening here? Why is this error being seen?

**Comment by jpmartinspt** [comment]
From the quick look I had a possible cause would be for you to loose your session in between a login and the after_login function being called... but I haven't managed to reproduce the issue yet.

**Comment by nottrobin** [comment]
Ah that sounds quite possible. I guess there might be 2 possibilities:

1. The client restarted or something else that might have cleared the cookies in the middle of the log in process
2. The client is deliberately blocking cookies

I assume we should be able to reproduce this by deleting ubuntu.com cookies while on the login.ubuntu.com page, before being redirected back.

For scenario 1, the best thing to do might be to simply send the client through the login process again, if the session is missing. However this could send clients in scenario 2 into a redirect loop.

So probably the best thing to do is to show a special error page explaining that your session is unexpectedly empty and that you might want to try logging in again, or returning to your original page (if we know what it was). With an appropriate HTTP status.

**Comment by jpmartinspt** [comment]
@nottrobin  @anthonydillon  Does this look alright?
![image.png](https://images.zenhubusercontent.com/5b96701996c0801aed18b6f5/32cb02af-8ff4-4835-a026-fd2da31c924b)

**Comment by anthonydillon** [comment]
> @nottrobin  @anthonydillon  Does this look alright?
> ![image.png](https://images.zenhubusercontent.com/5b96701996c0801aed18b6f5/32cb02af-8ff4-4835-a026-fd2da31c924b)

Do you mean does the error page look ok? Looks good to me. One day I'll fix the broken logo padding on error pages 😃
