### ISSUE TITLE
Image sizing for webinar [needed by end of day] 

### ISSUE THREAD

**Issue by AmberCharitos** [canonical-web-and-design/ubuntu.com#9296]
## Summary

Please could I have the below: 

Image width
Image height
Equal cols
Background
for this image: https://assets.ubuntu.com/v1/720e50fa-UC20_advanced_security_features.svg

added in this sheet: 
https://docs.google.com/spreadsheets/d/10L8DZWxieIVU_kW4c2Jki9uwSaSxEFuNZNkXIpDieZo/edit#gid=1011867606

**Comment by pmahnke** [comment]
@AmberCharitos that's too big an image for a takeover... @anasereijo ?  Is there an alternative?
Why the tight deadline?

**Comment by AmberCharitos** [comment]
Ah I didn't realise, would it work for an engage page? 

We have a webinar tomorrow where we are going to announce this new one and need a place to send people to. I thought I'd already tagged canonical-editors but I must have made a mistake

**Comment by anasereijo** [comment]
Hi @AmberCharitos

That illustration is too complex and big for a hero section (top of the page next to intro copy).
I suggest using something more generic and smaller, like this one:
[https://assets.ubuntu.com/v1/1fbe51df-UC20_Full-disc-encryption.svg](https://assets.ubuntu.com/v1/1fbe51df-UC20_Full-disc-encryption.svg) width:200px; height:200px

**Comment by anasereijo** [comment]
@AmberCharitos I can't edit the brief so I left all details in the comment above.
