### ISSUE TITLE
Clicked link to download eBook and there is nothing there that directs me to the contents of the book.

### ISSUE THREAD

**Issue by popester582** [canonical-web-and-design/ubuntu.com#9303]
---
*Reported from: https://pages.ubuntu.com/CIO_Report.html?utm_source=marketo

**Comment by pmahnke** [comment]
@popester582 do you have javascript turned off?  It should take you to a thank you page with a link to : https://pages.ubuntu.com/rs/066-EOV-335/images/eBook_Cio-guide_%28Tom%29_04.16_AW.pdf
