### ISSUE TITLE
The instructions on the page do not result in a working ubuntu core

### ISSUE THREAD

**Issue by nmav** [canonical-web-and-design/ubuntu.com#9306]
At the section `Install kvm` I needed to replace `sudo apt install qemu-kvm` with `sudo apt install qemu-kvm ovmf`

At the section `Launch KVM ` I needed to append:
`-drive file=/usr/share/OVMF/OVMF_CODE.fd,if=pflash,format=raw,unit=0,readonly=on`

---
*Reported from: https://ubuntu.com/download/kvm*

**Comment by nmav** [comment]
The fixes above were suggested with @degville

**Comment by SirSamTumless** [comment]
Thanks for flagging this, I have asked @xxl007 to make the changes on the copy doc here; https://docs.google.com/document/d/1FHIArLpuAyLe2gnDwymefvzc4Lg8dSGvN8QAl8wX18Q/edit#heading=h.y5kr0riv2frn
