### ISSUE TITLE
Inconsistent beta application forms

### ISSUE THREAD

**Issue by lex-joy** [canonical-web-and-design/ubuntu.com#9316]
At the bottom of the page, the user can click a green **Apply for Beta Access** button, which brings up a prompt to apply. If the user right-clicks the button and opens it in a new tab instead, an entirely different prompt is displayed.

Please make sure we only use one prompt in all scenarios. CUBE prefers the standard left-clicked prompt, but we would like to request that some text be changed:

* Instead of "Join the CUBE beta test" (which suggests that enrollment is a sure bet), please use "Apply for the CUBE beta."
* Instead of "How should we get in touch?" (which suggests other options besides email), we would prefer "Provide your contact information to join the beta candidate pool."

Thank you!

---
*Reported from: https://ubuntu.com/cube/microcerts*

**Comment by anthonydillon** [comment]
It is a bad idea for us to block opening in New tab. We change the link to just "#get-in-touch" if we don't care about users with JavaScript disabled on this platform?

**Comment by lex-joy** [comment]
It's fine if we allow new tabs to open. The issue is that the new-tab form uses different text, so it looks odd. As long as both versions look identical, we'll be happy!

**Comment by anthonydillon** [comment]
Ah text-wise. For sure :+1:

**Comment by SirSamTumless** [comment]
I am adding this work in for next iteration.
