### ISSUE TITLE
Changes to thank-you message

### ISSUE THREAD

**Issue by lex-joy** [canonical-web-and-design/ubuntu.com#9317]
Please make the following changes to the text on the thank-you page:

* Add "the" before "CUBE beta."
* Change the subtitle text to: "We will be in touch if you are selected for the beta."

Thanks for your help!

---
*Reported from: https://ubuntu.com/cube/thank-you?aliId=eyJpIjoiS0p4bUZrN2FZaEVKRmF4QiIsInQiOiIyc0Irb0hBNnNvWlI3UW90VUYzeXZRPT0ifQ==*

**Comment by SirSamTumless** [comment]
I am adding this work for next iteration (starting next week).
