### ISSUE TITLE
wlan0 and ssh connection not working as described

### ISSUE THREAD

**Issue by and1ti** [canonical-web-and-design/ubuntu.com#9323]
Hi. Just tried to install ubuntu 20.04 server on rpi4, following described steps on https://ubuntu.com/tutorials/how-to-install-ubuntu-on-your-raspberry-pi#4-boot-ubuntu-server. Unfortunately it's not working as described:
- The Pi4 cannot establish a connection via wlan0. I entered everything correctly to network-config - I swear. It's also not working after mentioned "sudo reboot". One has to follow https://raspberrypi.stackexchange.com/questions/111722/rpi-4-running-ubuntu-server-20-04-cant-connect-to-wifi to make it work.
- afterwards, trying to connect from a notebook via ssh to the raspi is also not working.
`$ ssh ubuntu@192.168.0.123`
`ssh: connect to host 192.168.0.123 port 22: Connection refused)`
What helped was to first create ssh-keys (-> https://www.garron.me/en/linux/sshd-no-hostkeys-available-exiting.html)
Would be nice if the how-to could be updated. maybe there are some different steps to make it work out-of-the-box. tku.

**Comment by pmahnke** [comment]
@rhys-the-davies can you help with this?  Seems like the tutorial needs updating.

**Comment by rhys-the-davies** [comment]
Apologies for not replying way earlier. I made changes to the tutorial to address the first issue a long while ago. And I've just checked the second, it has worked for me each time, but there were some issues on old images which have been solved and included in the latest releases. 

It definitely works for me out of the box on hirsute (which finally fixed the eth0 and wlan0 on first boot issues), but there are issues with eth0 on first boot on the groovy images and I can't remember if focal .2 included all the necessary workarounds for netplan but it should have. 

So @and1ti could I ask you to give it another go and see if you run into the same issue? If you do, could you let us know the release and file the issue over here: https://github.com/canonical/cloud-init if its an ssh problem, or here: https://github.com/canonical/netplan if its a network problem, where I and our engineers on Pi can see it and we'll bump it up our priority list.  

Once again, sorry for the _huge_ delay

**Comment by and1ti** [comment]
Hi @rhys-the-davies, never mind and thanks for your response. :slightly_smiling_face: 
The used pi4 is meanwhile up and running for a while, but I will try to test it again on weekend.

**Comment by rhys-the-davies** [comment]
Crackin' thank you 😄  if you run into an issue again could you head over here and let me know: https://discourse.ubuntu.com/t/how-to-install-ubuntu-server-on-your-raspberry-pi/14660/93 it'll be much easier to help you and if for some reason I can't help I can point the right people at you 😊

**Comment by pmahnke** [comment]
Thanks @rhys-the-davies and @and1ti ... closing this for now anyway
