### ISSUE TITLE
Using a test card in production triggers the wrong error message

### ISSUE THREAD

**Issue by alnvdl** [canonical-web-and-design/ubuntu.com#9324]
If one tries to use a test card in the production instance of the shop, Stripe returns the following error when trying to add that card by calling `POST https://api.stripe.com/v1/payment_methods`:
```
{
  "error": {
    "code": "card_declined",
    "decline_code": "live_mode_test_card",
    "doc_url": "https://stripe.com/docs/error-codes/card-declined",
    "message": "Your card was declined. Your request was in live mode, but used a known test card.",
    "type": "card_error"
  }
}
```

That error is not listed here: https://github.com/canonical-web-and-design/ubuntu.com/blob/master/static/js/src/advantage/error-handler.js#L1

So it means if someone tries to use a test card in production, the error message will be very confusing. That would typically be a developer.

Without a card set, one should also not call the purchase preview endpoint, because it will then return an error saying that the purchase cannot be simulated due to the card being missing. But doing that is apparently harmless, and the customer can proceed to making the purchase if they instead input a valid credit card.

**Comment by SirSamTumless** [comment]
@ClementChaumel Please triage this.
