### ISSUE TITLE
/advantage: Excess space after intro section

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/ubuntu.com#9326]
When you are not signed in, there is much more space between the end of the intro (“Sign in” / “Buy a subscription”) and the beginning of the next section (“Free for personal use”) than there is at the top of the page.

> ![Screenshot 2021-02-27 at 17 06 36](https://user-images.githubusercontent.com/19801137/109375057-8ad31080-791e-11eb-8392-cca7e66c8dd1.png)

Similarly, when you _are_ signed in, there is much more space between the end of the intro (“You are signed in as…”) and the beginning of the next section (“Your paid subscriptions”) than there is at the top of the page.

The cause seems to be the same in both cases:
- the intro section has `padding-top: 6rem`, but `4rem` of this is taken up by the Suru gradient, leaving only **2rem** between the intro and the gradient
- the intro section has `padding-bottom: 4rem`, and the following section has `padding-top: 1.5rem`, making a total of **4.5rem** space between the sections.

What you should see: More-closely-related things should be nearer than less-closely-related things. The first section should be nearer to the second section than to the page decoration.

---
*Reported from: https://ubuntu.com/advantage*

**Comment by pmahnke** [comment]
This has been redesigned, closing.

Also, 'Hello from a planning sprint!'
