### ISSUE TITLE
The Meet panel of the Community drop down does not indicate support resources

### ISSUE THREAD

**Issue by diddledan** [canonical-web-and-design/ubuntu.com#9338]
While thinking about how people end-up at discourse in response to https://discourse.ubuntu.com/t/support-requests-part-27/21208 I had a look at Ubuntu.com. There I found that the Community dropdown menu has support resources listed under the heading of "Meet". It is unclear that these resources are for support so as a naive user I might overlook the panel altogether and end up looking at the Contribute panel instead which has the following wording that becomes the next-best match for someone looking for support "Discourse is a meeting point for people who shape the direction of Ubuntu. We recommend you start there."

![Screenshot of Ubuntu.com showing the issue of the Meet panel being incorrectly named](https://user-images.githubusercontent.com/147548/109730264-2380bf00-7bb1-11eb-8edc-66c7da0fbd1b.png)

I recommend that either the Meet panel be renamed along with changing the wording of each item beneath to indicate that they offer support; or, change the Contribute panel to remove the "we recommend you start there"; or, both?

![Gif of two characters agreeing that both is good](https://media1.giphy.com/media/3o7aCRloybJlXpNjSU/giphy.gif?cid=ecf05e47rdtd8ow8mnyu45zd63mx7h7i61vhslja6vm922an&rid=giphy.gif)

---
*Reported from: https://ubuntu.com/*

**Comment by pmahnke** [comment]
@diddledan and @popey

What about this?

![image](https://user-images.githubusercontent.com/441217/110961447-bb1ba580-8347-11eb-8edf-68c105793f7c.png)
