### ISSUE TITLE
Ubuntu Discourse is not for support

### ISSUE THREAD

**Issue by diddledan** [canonical-web-and-design/ubuntu.com#9339]
The Ubuntu Discourse link in the Download page's "Helping hands" panel should not be there. This is likely leading to __some__ users turning up at Ubuntu Discourse and posting requesting for help. See https://discourse.ubuntu.com/t/support-requests-part-27/21208/2 for more about these users going to the Discourse.

![Screenshot of Ubuntu.com's Desktop ISO download page showing the "Helping hands" panel with a link to the Ubuntu Discourse](https://user-images.githubusercontent.com/147548/109732501-35646100-7bb5-11eb-8aa6-0edaaf1fe757.png)

---
*Reported from: https://ubuntu.com/download/desktop*

**Comment by pmahnke** [comment]
@diddledan thanks for the issue, I have replaced discourse with launchpad answers.  I also looked around and didn't really find other links that were as support oriented, but if you do, let us know.
