### ISSUE TITLE
Landscape is not listed in the table detailing UAI services

### ISSUE THREAD

**Issue by alysonrose88** [canonical-web-and-design/ubuntu.com#9342]
When you click on the 'add subscription' button, the table that opens detailing the services included with UAI does not mention Landscape.

---
*Reported from: https://ubuntu.com/advantage*

**Comment by wgx** [comment]
@alysonrose88 Great point. I'll go ahead and make copy changes and design changes to a few other tickets now to reflect this - to ensure we're not forgetting Landscape on the new designs. 👍🏽
