### ISSUE TITLE
'Watch the webinar' button for non-webinar engage page

### ISSUE THREAD

**Issue by Khutch25** [canonical-web-and-design/ubuntu.com#9349]
There is a button on the [Spanish ESM engage page](https://ubuntu.com/engage/es/esm) for 'Watch the webinar' when on mobile or smaller screens (see screenshot), but the page is labeled as a blog in the [engage page mapping table
](https://discourse.ubuntu.com/t/engage-pages-and-takeovers/17229)
Here is the [brief](https://docs.google.com/spreadsheets/d/1qDZoqYCSP0OG5Jp2E1Widq17ENJZvGVSFTr1s8vDTGg/edit#gid=767630650) and [discourse topic](https://discourse.ubuntu.com/t/mantenimiento-de-seguridad-extendido/20747).

![Screenshot 2021-03-04 at 11 52 06](https://user-images.githubusercontent.com/42180941/109960576-e0be0480-7ce0-11eb-87ef-763d8c31bd5b.png)

Can the button be updated to 'Contacta con nosotros' and link here: https://pages.ubuntu.com/contactenos.html 
OR Can it be removed?
 

---
*Reported from: https://ubuntu.com/engage/es/esm

**Comment by pmahnke** [comment]
@carkod I fixed it as it was my brief that is the issue. But I do wonder if we want to show buttons if they aren't webinars?

**Comment by carkod** [comment]
> @carkod I fixed it as it was my brief that is the issue. But I do wonder if we want to show buttons if they aren't webinars?

@pmahnke Yeah, I thought they were hiding if none was provided. Do we want to make the `primary_cta` optional?
