### ISSUE TITLE
Battery and sound card issues.

### ISSUE THREAD

**Issue by TheANCAPBoy** [canonical-web-and-design/ubuntu.com#9352]
--- I have an HP x2 210 G2, and I have tried Ubuntu 20.04 and it gave me problems showing the battery, it did not even detect it, I solved that error by switching to Ubuntu 20.10, but there was an error that still persisted in this version and in 20.04, and is that the sound card is not detected and there are no drivers installed for it. Only the sound works through the laptop's own speakers and not through the jack port, since when I connect the headphones, the sound continues to come out of the laptop's speakers..
![Screenshot from 2021-03-03 19-42-38](https://user-images.githubusercontent.com/80054356/109989513-db74b000-7d08-11eb-8f51-3dd72edc1290.png)

*Reported from: https://ubuntu.com/*

**Comment by anthonydillon** [comment]
Hello @TheANCAPBoy 

Sorry to hear you are having a problem with your Ubuntu system. Unfortunately, I cannot provide support via this channel as I am a member of the web team.

If you could report a bug on Ubuntu at https://bugs.launchpad.net/ubuntu or ask your question as a topic on https://discourse.ubuntu.com/c/support-help-requests and you should receive a quick response.
