### ISSUE TITLE
UA renewal customers getting "Voided invoices cannot be paid." messages intermittently

### ISSUE THREAD

**Issue by cmars** [canonical-web-and-design/ubuntu.com#9363]
We get occasional cases from Customer Success where customers are getting this error "Voided invoices cannot be paid." when purchasing a renewal for a UA contract that was originally purchased through Shopify.

There's no double-charging or anything bad going on, other than that it scares the users -- they don't know what it means and they open a support case :) Which is reasonable...

From our side on the backend, it looks like a payment was attempted on an invoice that is no longer pending -- it may have been cancelled, payment declined, or expired due to non-payment or non-authorization (in the case of 3DS).

My hunch on this (being unfamiliar with the web frontend implementation) is that maybe the UI is attempting to process a payment with Stripe on a purchase, without checking the state of that purchase with the shop backend first? I could see cases where the page is left open and the page JS (or maybe server-side session -- however the UI works) has a stale state w.r.t the latest in Stripe. The shop backend likely to have an up-to-date state on a purchase because it's constantly getting updates via the Stripe webhook -- so perhaps (re-)checking with the shop backend before processing that payment would resolve this?

Here's an example of what we see on our side when this happens: https://pastebin.canonical.com/p/fC9BjQWjh7/

**Comment by alnvdl** [comment]
Complementing @cmars report (that pastebin is set to expire in one day), this is the error we get:
```
2021-03-05 03:53:02+00 | 24fe4e0c-d5ae-40ae-b25e-f703fa75aadf |          | {"status":400,"message":"Voided invoices cannot be paid.","request_id":"req_ZZnsLl8KGYdZNi","type":"invalid_request_error"}
```

This happens in the endpoint that is called to retry invoice payments. This error is returned when you make the call to retry payment for an invoice that was already voided (because of lack of payment). This specific customer had previously attempted to buy on Feb 25th (which failed), and then again today (on Mar 5th, which succeeded).

**Comment by SirSamTumless** [comment]
@ClementChaumel Please triage ths.

**Comment by SirSamTumless** [comment]
@ClementChaumel is this still an issue?

**Comment by ClementChaumel** [comment]
Yes, I think so. We might need to have a talk with @albertkol and someone from the CS team to get to the bottom of this.

**Comment by albertkol** [comment]
This has not moved for a long time. If it's still a problem, we can re-open.
