### ISSUE TITLE
[UA-Shop] 3Ds payment failures

### ISSUE THREAD

**Issue by brotich** [canonical-web-and-design/ubuntu.com#9370]
## Summary
A problem may occur when making payment for a subscription on the shop if the 3Ds challenge is not completed on time.

## Process
1. navigate to the /advantage staging test environment
![image](https://user-images.githubusercontent.com/23168146/110502082-e9ad3c80-810b-11eb-970a-7cb080ac5f72.png)

2. select items to purchase i.e Desktop UA
3. on the payment details use a card that requires 3Ds payment i.e  `4000000000003220`. fill in all the other details on the page as required
![image](https://user-images.githubusercontent.com/23168146/110501480-45c39100-810b-11eb-9c92-5834a7644cd9.png)

4. Click on the page to make payment. When the 3Ds prompt comes up, do not click on any of the options to pass or fail the authentication.
![image](https://user-images.githubusercontent.com/23168146/110501595-64298c80-810b-11eb-8508-02c5e9b2835e.png)

5. after about 1 min, the page will redirect to /advantage/subscribe page. 
![image](https://user-images.githubusercontent.com/23168146/110501710-828f8800-810b-11eb-84fc-29f26eae542b.png)

## Current and expected result
the page redirects to the /advantage/subscribe page, denoting a successful payment. however the customer has not authorized the payment and the purchase will not be processed.

**Comment by alnvdl** [comment]
I don't see this same behavior in the reference shop in ua-contracts (the 3DS modal never closes), so I think this is probably caused by some timer in the purchase modal.

One way to indirectly solve this issue while keeping the timer as-is would be to direct the user to the async payment resolution flow, once it gets implemented for monthly subscription renewals. That async flow should be able to handle 3DS and declined cards (see: https://github.com/CanonicalLtd/ua-contracts/blob/6af2e3ffee8a0b43be4ae9d47c4f356d61b703d8/web/src/Shop.js#L998).

**Comment by wgx** [comment]
@alnvdl Yes, they'd have a subscription with a "payment issue" which, if left un-fixed, will cancel after its grace period of 14 days. They can head to the payment settings view and add a card - which will trigger a new 3DS challenge.

**Comment by alnvdl** [comment]
@wgx This is an issue currently affecting customers in production. I think the payment issue notice and payment resolution page are not yet publicly available, right?

Just removing this timeout that closes the 3DS modal (which shouldn't be there in the first place) would fix this issue.

**Comment by wgx** [comment]
@alnvdl Totally agree, there should be no artificial timeout introduced - we just wait for them to complete the 3DS, and if eventually Stripe times out, the payment abandoned.

**Comment by anthonydillon** [comment]
Can this issue be estimated please?
