### ISSUE TITLE
/gov page edits and reactivation

### ISSUE THREAD

**Issue by Khutch25** [canonical-web-and-design/ubuntu.com#9378]
Legal and other teams tagged have reviewed the /gov page with some copy changes, left as suggested edits in the [copy document](https://docs.google.com/document/d/1umM1XMEzqeXklPkyCjDr98Q-RvwCcNNXgwNwfLoynTo/edit#heading=h.h8lo4gnw0yf).
 
With a FedGov webinar on Monday, I would love to add this page as an attachment to the webinar if possible - could the text edits be made before Monday afternoon @SirSamTumless ?

**Comment by SirSamTumless** [comment]
@Khutch25 Could you please resolve any comments that are not needed, as there are quite a few there.

**Comment by Khutch25** [comment]
> @Khutch25 Could you please resolve any comments that are not needed, as there are quite a few there.

@SirSamTumless Done! Only comments tied to a suggested edit are left.

**Comment by SirSamTumless** [comment]
@bethcollins92 Would you be able to jump on this today when you get a chance?

**Comment by bethcollins92** [comment]
> @bethcollins92 Would you be able to jump on this today when you get a chance?

Yep sure 🤙
