### ISSUE TITLE
Blog: featured images are very small at tablet breakpoint

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#9388]
## Summary

Between ~410px and and 875px wide, featured images don't take up the full width of the card component, leading to a lot of white space.

## Process

- Visit https://ubuntu.com/blog
- Resize browser to 800px wide

## Current and expected result

Current: as described in the summary
Expected: images should take up the available width, and/or a multi column layout to apply on tablet breakpoints so there's never so much space for an image to fill.

## Screenshot

![FireShot Capture 028 - Ubuntu Blog - Ubuntu - ubuntu com](https://user-images.githubusercontent.com/2376968/111135862-0ff03380-8575-11eb-9cfa-0ee112bcbf13.png)

**Comment by anthonydillon** [comment]
@sowasred2012 thanks, we will try to jump on this soon.
