### ISSUE TITLE
cis-hardened-ubuntu-cyber-attack-and-malware-prevention-for-mission-critical-systems missing important information

### ISSUE THREAD

**Issue by nmav** [canonical-web-and-design/ubuntu.com#9396]
This page is redirecting to ubuntu advantage page for more information, which in turn redirects back to this one. This is a cycling reference and doesn't provide the information to the customer. The right information is at:
https://security-certs.docs.ubuntu.com/en/cis-18-16

Could you change the last paragraph from:
```CIS automation tooling can be used in virtual machines, private and public clouds as well as on-premises and desktops. The tooling is available for Ubuntu 16.04 LTS and Ubuntu 18.04 LTS with  Ubuntu Advantage for Infrastructure. Check out the full list of Ubuntu security certifications and hardening standards.```
To:
```
CIS automation tooling can be used in virtual machines, private and public clouds as well as on-premises and desktops. The 
tooling is available for Ubuntu 16.04 LTS and Ubuntu 18.04 LTS with Ubuntu Advantage for Infrastructure. Check out the 
<a href="https://security-certs.docs.ubuntu.com/en/cis-18-16">CIS tooling instructions</a>.
```

---
*Reported from: https://ubuntu.com/blog/cis-hardened-ubuntu-cyber-attack-and-malware-prevention-for-mission-critical-systems*

**Comment by pmahnke** [comment]
@nmav I have emailed you.  You should be able to edit the post yourself.  Assuming you speak to Vineetha.  Let me know if you prefere we updated it on this occasion.
