### ISSUE TITLE
The word 'sites' is truncated on ubuntu.com

### ISSUE THREAD

**Issue by wgx** [canonical-web-and-design/ubuntu.com#9402]
The word 'sites' is truncated on ubuntu.com

![image](https://user-images.githubusercontent.com/930099/111454978-2df09c00-870d-11eb-84b2-21cdbd49f61a.png)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:86.0) Gecko/20100101 Firefox/86.0

---
*Reported from: https://ubuntu.com/*

**Comment by anthonydillon** [comment]
This issue will be resolved with the rebuild of the search based on the design. https://github.com/canonical-web-and-design/ubuntu.com/issues/9290
