### ISSUE TITLE
Add links to 16-04 page

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/ubuntu.com#9414]
Add links in mutliple places for the new 16-04 page See this [comment](https://docs.google.com/document/d/1wclofqY9b3v_M9igpkYn6or5uXx0B_Xb_nVVzGBbOLY/edit?disco=AAAALJrPkOw) 

Please include a link to this page - ubuntu.com/16-04 - in the below places:
- Footer - see #9418
- ESM page: /security/esm - Need [copy](https://docs.google.com/document/d/1RBZX3PJPvODxRlcnIS10Ii4SkIMH5Fm74EmsMQ0cnic/edit#) from @Khutch25 
- Release pages: releases.ubuntu.com/16.04.7 - **need to ask the foundations team**
- Card on blog post - **Ask @caldav**

**Comment by Khutch25** [comment]
@bethcollins92 I have added a suggested snippet and link to the 16-04 page on the [ESM page](https://docs.google.com/document/d/1RBZX3PJPvODxRlcnIS10Ii4SkIMH5Fm74EmsMQ0cnic/edit#). Thank you for catching and flagging this!!

@caldav Let me know if you need any help on the blog card side of things.

**Comment by anthonydillon** [comment]
@SirSamTumless this one ready to go? Can we have this assigned this iteration? What is the question?

**Comment by SirSamTumless** [comment]
It waws "@caldav Let me know if you need any help on the blog card side of things."

**Comment by caldav** [comment]
Duh, missed this. I'll do a PR.
