### ISSUE TITLE
There is no download link for the ebook

### ISSUE THREAD

**Issue by jpbourke** [canonical-web-and-design/ubuntu.com#9436]
There is no form to fill or download link ...

Tried using Chrome and Edge.

---
*Reported from: https://pages.ubuntu.com/telco-cloudification-ebook.html?utm_source=marketo

**Comment by anthonydillon** [comment]
Hello @jpbourke, I see the form but it is injected via JS so there maybe something blocking the JS from loading such as uBlock extension? You can get the ebook from the main site too: https://ubuntu.com/engage/telco-cloudification-ebook.

**Comment by pmahnke** [comment]
No reply, so closing; however, if it is still an issue, please reopen.
