### ISSUE TITLE
Update Link on Azure Pro Page

### ISSUE THREAD

**Issue by lindseylopez** [canonical-web-and-design/ubuntu.com#9447]
We now have a new pro data sheet. Please update the link at the top of the page to point to the new data sheet linked below.
https://assets.ubuntu.com/v1/26408fa0-UbuntuPro_Azure_Datasheet_21.pdf 

---
*Reported from: https://ubuntu.com/azure/pro*

**Comment by anthonydillon** [comment]
@jpmartinspt can you update the link to the new datasheet to the top of this page please. I have updated the copy doc.
