### ISSUE TITLE
Mention of 14.04 LTS on ubuntu advantage page is probably outdated

### ISSUE THREAD

**Issue by setharnold** [canonical-web-and-design/ubuntu.com#9451]
Hello, I noticed some surprising text on the ubuntu advantage main page:

"Initially, free subscription is available for Ubuntu 14.04 LTS only"

14.04 is now in ESM stage and not free. Probably this sentence can be deleted.

Thanks

---
*Reported from: https://ubuntu.com/advantage*

**Comment by lechsandecki** [comment]
Thanks for reporting that. We indeed offer both: paid subscriptions for enterprises and free subscriptions for personal use. 

The text you reported here is under the “free for Personal use” section. There is also another section on this page that describes prices and plans for enterprise use. 

I feel that the information on that page is correct but perhaps needs a UX review to make sure that it's easy to understand what is what. 

Anyhow, thanks for reporting that!

**Comment by anthonydillon** [comment]
@wgx could you take a look and see if there is something that could demystify this content, please?

**Comment by wgx** [comment]
How about changing:

>Initially, free subscription is available for Ubuntu 14.04 LTS only

to:

Ubuntu 14.04 LTS machines can receive Extended Security Maintenance (ESM) updates and other Ubuntu Advantage benefits.

**Comment by wgx** [comment]
Updated the copydoc
