### ISSUE TITLE
A search for a term in the notice title doesn't return a result

### ISSUE THREAD

**Issue by wgx** [canonical-web-and-design/ubuntu.com#9454]
Try searching for: https://ubuntu.com/security/notices?order=newest&release=&details=openjpeg

I would expect

https://ubuntu.com/security/notices/USN-4880-1

to be returned, but no results are returned. 

---
*Reported from: https://ubuntu.com/security/notices?order=newest

**Comment by SirSamTumless** [comment]
@albertkol Please triage this accordingly.

**Comment by albertkol** [comment]
Right now the search box looks looks for notices that match the text by notice.id, notice.details or any notice.cves id.

Title is indeed ignored. We could have the title included in the search.

**Comment by mhampl** [comment]
In case that it is not yet covered in the proposal above, please include the (source) package name in the items to search for a match.
