### ISSUE TITLE
Elongated blog cards 

### ISSUE THREAD

**Issue by rhys-the-davies** [canonical-web-and-design/ubuntu.com#9462]
Helloo o/ was noodling around on the blog site and noticed the cards next to the newsletter seemed very long, with lots of blank space. Is this intentional or something going wrong? It seems like they're stretching to match the dimensions of the newsletter form. 

![Screenshot from 2021-03-25 15-37-57](https://user-images.githubusercontent.com/56505487/112500576-68e37700-8d80-11eb-84cd-470704c8d307.png)

I also noted that the blog cards get shorter as you scroll down, which seems more intentional, but perhaps these elongated cards are a consequence of that? It just doesn't seem like a good use of space

---
*Reported from: https://ubuntu.com/blog*

**Comment by pmahnke** [comment]
@rhys-the-davies the cards are in rows.  The height of the row is as tall as the tallest item, which, in this case, is the newsletter signup card.  This is why it is tall.  We would have to come up with a new design of that form to make it smaller.

**Comment by rhys-the-davies** [comment]
Okay so not a bug, cool cool :)
