### ISSUE TITLE
UA shop: Changing payment method and then changing subscription leaves user in a confused/broken state

### ISSUE THREAD

**Issue by alnvdl** [canonical-web-and-design/ubuntu.com#9463]
**Tested with**: https://ubuntu-com-9240.demos.haus/advantage/subscribe?test_backend=true
**Steps to reproduce**:
1. Purchase 2x uai-essential-desktop on an empty account
2. Change the subscription: increase it to 4
3. Change credit card to 4000 0000 0000 0341
4. Try to change quantity to 6 using the existing contract accordion

**Result**: no error or alert is shown, subscription disappears, see screenshot. Customer cannot make new purchases.
![purchase_stuck](https://user-images.githubusercontent.com/3459649/112520652-641bc480-8d7a-11eb-8e94-af6e517c4a75.png)

**Comment by SirSamTumless** [comment]
This is needed for release.
