### ISSUE TITLE
UA shop: Next subscription payment presented without taxes

### ISSUE THREAD

**Issue by alnvdl** [canonical-web-and-design/ubuntu.com#9464]
**Tested with**: https://ubuntu-com-9240.demos.haus/advantage/subscribe?test_backend=true
**Steps to reproduce**:
1. Purchase 3x uai-essential-desktop monthly on an empty account using country as UK and VAT number as GB123456789.

**Result**: `/advantage` shows: "See Your next recurring payment of $7.50 will be taken on 25 April 2021."

I think this could be improved to say that the amount excludes any taxes that may apply.

We don't yet have a way in the backend to just get the next invoice and its tax amount.

We could work on that for after the release if you think that's a good idea.

**Comment by wgx** [comment]
Agree it's misleading. 

1. Add a secondary few words, as you suggest, after the 'next payment' line:

>"Your next recurring payment of $7.50 will be taken on 25 April 2021, **excluding any applicable taxes.**"

2. Please do add the item to the backlog to extend the endpoint to return a 'with taxes' amount as an option so we can do this more clearly in a future version.

**Comment by wgx** [comment]
@anasereijo will you take a look design-wise at how this might look on the view?

**Comment by anasereijo** [comment]
@wgx this is how it will look with that extra bit of text
<img width="1213" alt="Screenshot 2021-04-12 at 10 08 52" src="https://user-images.githubusercontent.com/36884067/114378025-31960800-9b7f-11eb-8e0c-a1e3837e3d9b.png">

**Comment by anasereijo** [comment]
@albertkol @ClementChaumel do you know if this has work been done?

**Comment by ClementChaumel** [comment]
Closing in favour of https://github.com/canonical-web-and-design/ubuntu.com/issues/9464
