### ISSUE TITLE
UA shop: Cancel subscription button has an awkward moment without feedback

### ISSUE THREAD

**Issue by alnvdl** [canonical-web-and-design/ubuntu.com#9467]
**Tested with**: https://ubuntu-com-9240.demos.haus/advantage/subscribe?test_backend=true
**Steps to reproduce**:

1. Purchase 2x uai-essential-desktop on an empty account
2. Clicking the "Cancel subscription" button

**Result**: there's a moment without any feedback, and I can't know whether I clicked it or not.

**Comment by wgx** [comment]
We should always aim to show the user some visual feedback that "something is happening" - in this case showing a spinner until the request completes would be ideal.
