### ISSUE TITLE
UA shop: Subscription cancellation message could be improved

### ISSUE THREAD

**Issue by alnvdl** [canonical-web-and-design/ubuntu.com#9468]
**Tested with**: https://ubuntu-com-9240.demos.haus/advantage/subscribe?test_backend=true
Many of our customers have allowances directly negotiated outside of the shop. We should indicate that when cancelling subscription so that it's clear that other allowances they have are not impacted by cancelling their shop subscription. A suggestion:

> If you cancel this subscription:
> 
>    - No additional charge will be incurred.
>    - The 3 machines will stop receiving updates and services at the end of the billing period.
>    - **If you have additional allowances purchased outside of the shop (e.g., directly with Canonical), you will still be entitled to those allowances.**

**Comment by wgx** [comment]
I'm not sure about this. 

The main use case, I believe is:

- User buys online in shop, uses shop to manage their subscription.

The case you're describing:

- User buys outside of the shop, then uses the shop to cancel that subscription

...feels like an edge case that we shouldn't complicate the main UI with. 

Over to @lechsandecki for an opinion.

**Comment by elioqoshi** [comment]
I like that change of heart and agree. Feels like a crucial feature, especially if we want to allow in the future that customers can purchase subscriptions now which start being active at a later date.

**Comment by ClementChaumel** [comment]
Hey, is this still relevant and if so is it ready to be built?

**Comment by wgx** [comment]
@ClementChaumel yes, looks like its a line of text on the cancel modal dialog:

>Additional subscriptions purchased directly with Canonical will not be affected.

**Comment by wgx** [comment]
Add the above line of copy to the UI
