### ISSUE TITLE
livepatch enable command requires sudo

### ISSUE THREAD

**Issue by blackboxsw** [canonical-web-and-design/ubuntu.com#9472]
The expanded detail text for enablign livepatch state the command
`ua enable livepatch`   it should be `sudo ua enable livepatch` (just like all UA comands)

Much thanks,
New site details look great
---
*Reported from: https://ubuntu.com/advantage*

**Comment by wgx** [comment]
Following discussion with @blackboxsw have resolved to close this for now.
