### ISSUE TITLE
When i try live cd from usb stick, will data on desktop be persisted????

### ISSUE THREAD

**Issue by jsutil37** [canonical-web-and-design/ubuntu.com#9479]
When i try live cd from usb stick, will data on desktop be persisted????
If not, any non-persistent location should be made read-only. I believe that i lost a large amount of personal data.
Please consider as critical highest priority bug.

**Comment by anthonydillon** [comment]
Sorry to hear you may have lost personal data. Unfortunately, we cannot provide support via this project as it is the project for the website and its content.

If you could report a bug on Ubuntu at https://bugs.launchpad.net/ubuntu or ask your question as a topic on https://discourse.ubuntu.com/c/support-help-requests and you should receive a quick response.
