### ISSUE TITLE
ua-shop: number of machines and canceled subscriptions

### ISSUE THREAD

**Issue by frankban** [canonical-web-and-design/ubuntu.com#9481]
## Summary

The number of allowed active machines is not displayed correctly in case allowance comes from both a canceled subsription (that will expire at the end of the month) and an active one.

## Process

I buy 3 machines of product X, paying monthly.
I cancel the subscription.
I buy 3 more machines of product X.

## Current and expected result

Currently I only see the 3 machines for the new active subscription.
But, until the end of the month, I actually also have the 3 ones from previous canceled subscriptions, not represented in the page.

**Comment by SirSamTumless** [comment]
@frankban Can you get back to Clem?

**Comment by wgx** [comment]
@lechsandecki I think we decided, did we not, that canceled subscriptions are instantly removed from the view as the user has no further need for them.

**Comment by elioqoshi** [comment]
Is this still relevant? @frankban ff yes, could you elaborate on @ClementChaumel question?

**Comment by pmahnke** [comment]
Closing; however, @frankban, if you think it is still valid, reopen.
