### ISSUE TITLE
IoT subnav goes missing on certain pages

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/ubuntu.com#9504]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

This was pointed out in the [/embedded copy doc](https://docs.google.com/document/d/15Tz87YRg4SnX4DWGOSl2TDTHLSStJoma879xHnF0nuo/edit?disco=AAAAIMvAjvY):

Certain pages, /embedded, /robotics and /automotive, are all linked to from the /internet-of-things subnav, but don't show the subnav, which is inconsistent with the other pages the subnav links to.

## Process

- Go to /internet-of-things
- Click each link in the subnav
- See that the subnav disappears on /embedded, /robotics (it actually changes to a completely different one) and /automotive

### Current:
![iot-nav](https://user-images.githubusercontent.com/2376968/113679922-37d84000-96b8-11eb-9125-4f2c3a7ee81f.gif)

### Expected:
Either those pages share the same subnav, or aren't included in /internet-of-things's subnav

**Comment by SirSamTumless** [comment]
@xxl007 Are you happy for us to remove /robotics from IOT as it has its own bubble?

**Comment by pmahnke** [comment]
We should just do this.  Robotics are in the overview as well.
