### ISSUE TITLE
Update ubuntu.com/gcp

### ISSUE THREAD

**Issue by hugohuangtao** [canonical-web-and-design/ubuntu.com#9509]
Hi there, Ubuntu Pro has been launched in GCP. Cloud you change "Launching soon" into "Try Ubuntu Pro on GCP Console"? 
<img width="861" alt="Screenshot 2021-04-06 at 19 28 55" src="https://user-images.githubusercontent.com/56487433/113763249-7afdd780-96e7-11eb-9a72-91570ad69c55.png">
<img width="207" alt="Screenshot 2021-04-06 at 19 26 35" src="https://user-images.githubusercontent.com/56487433/113763255-7c2f0480-96e7-11eb-893c-0068b9256195.png">
<img width="393" alt="Screenshot 2021-04-06 at 19 25 59" src="https://user-images.githubusercontent.com/56487433/113763256-7c2f0480-96e7-11eb-87fe-0c6c45d093ba.png">

Could you also add "Ubuntu Pro for GCP" in the support section?
May I send you the datasheet when I finish it?
Many thanks,
Hugo

_Originally posted by @hugohuangtao in https://github.com/canonical-web-and-design/ubuntu.com/issues/9437#issuecomment-814367196_

**Comment by SirSamTumless** [comment]
Hi Hugo - would you mind sending canonical editors a brief?

**Comment by hugohuangtao** [comment]
> Hi Hugo - would you mind sending canonical editors a brief?

Hi Sam, at https://ubuntu.com/gcp, could you remove "launching soon" and "coming soon" please? Ubuntu Pro has launched last week.
![image](https://user-images.githubusercontent.com/56487433/113937611-6e50b080-97c7-11eb-9705-7c9a776910d6.png)
![image](https://user-images.githubusercontent.com/56487433/113937642-7872af00-97c7-11eb-8bb1-22499d179b11.png)
Many thanks!

**Comment by lechsandecki** [comment]
we also want to correct one issue. Could you change "3-6%" to "3-4.5%" , please?

**Comment by hugohuangtao** [comment]
> we also want to correct one issue. Could you change "3-6%" to "3-4.5%" , please?

"3-6%" is correct. Google has cheap machines, which makes Pro has a higher percentage of its total cost.

**Comment by pmahnke** [comment]
for now I have used 4.5... @lechsandecki please confirm what's right

**Comment by lechsandecki** [comment]
@hugohuangtao  I didn't know that it's different for google. Thanks for clarifying that, Hugo.
@pmahnke let's keep it on 3-6% for google only, as suggested by Hugo. apologies for the confusion

**Comment by pmahnke** [comment]
ok, updated the copy docs and pages.
