### ISSUE TITLE
autoinstall / cloud-init documentation ambiguous and confusing about information location

### ISSUE THREAD

**Issue by hadmut** [canonical-web-and-design/ubuntu.com#9515]
Hi, 
I was just testing a lot with different kinds of cloud-init-based installation and running 20.04 server images, including using the cloud image with kvm, booting over PXE and using the iso image for autoinstallation. 

Unfortunately, the docs explain the semantics of the cloud-init files only, but leave important questions open, especially where to put information and how things work together. 

E.g.  there are two or sometimes three files mentioned, user-data, meta-data and vendor-data. But it's not defined, what it is good for to have these three files and what goes in which. Meanwhile I have an idea what they are used for, but I am still unsure whether they are interpreted the same way and just concatenated, or differ in the way what contents they can carry. 

Then it depends on the kind of installation where information needs to be put. 

- sometimes it's written directly into user-data. 
- sometimes it needs to be done in user-data ander the tag autoinstall:
  and then, sometimes entries (like timezone) work only if put as

autoinstall:
   user-data:
    timezone: "Europe/Berlin"

while the locale can be put directly under autoinstall to become effective:

autoinstall:
  locale: "de_DE.UTF-8"

Since when is the timezone a user-data, while the locale isn't? 

This is confusing and costs a severe amount of time to figure out things by testing. 

Except from that, I had wasted a lot of time to hunt bugs and problems, because in contrast to the kickstarter files used for ubuntu up to 18.04 or the ignition files used in CoreOS, cloud-init remains active after first boot and keeps changing system settings, sometimes severely breaking the function of the system, including opening dangerous security holes (e.g. by reverting the system to unsecury passwords or ssh keys without noticing), but there is no description, not even a warning, that this is called „autoinstallation”, but keeps modifying the system forever. 

---
*Reported from: https://ubuntu.com/server/docs/install/autoinstall-quickstart*

**Comment by dbungert** [comment]
wakey wakey

**Comment by pmahnke** [comment]
asking the engineering team.

**Comment by sowasred2012** [comment]
@pmahnke did you get a response from the engineering team?

**Comment by pmahnke** [comment]
@sowasred2012 I have ask Matthieu Clemenceau for an update and he hasn't got back to me yet.

**Comment by mclemenceau** [comment]
@pmahnke @sowasred2012 - discussing with cloud-init and subiquity team at the moment to identify a possible solution. Sorry for the delay, this has been open for a while.

**Comment by sowasred2012** [comment]
@mclemenceau what was the outcome of the discussion?

**Comment by dbungert** [comment]
1. As far as relevant documentation goes:
   - https://ubuntu.com/server/docs/install/autoinstall is the introduction document for autoinstall
   - https://ubuntu.com/server/docs/install/autoinstall-quickstart provides some examples on how to get started with practical usage
   - https://ubuntu.com/server/docs/install/autoinstall-reference is the reference manual covering it in the best detail we have 
   - https://cloudinit.readthedocs.io/en/latest/ is what I use for cloud-init

2. As to the differences on what data should be included inside the `user-data` section or not, here is how you know:
   - if you see something in the cloud-init documentation, that should go in the `user-data` section of the autoinstall file
   - if it's documented in the autoinstall reference it should _not_ go in the `user-data` section
   - There are some config items that are covered in both - `locale` is one example, it honestly shouldn't matter if you put it in `user-data` or not

3. To the problem of cloud-init resetting values - this is a bug.  I attempted to reproduce this but didn't have luck doing so.  I do however see a `99-installer.cfg` file on the test system, so to me it could be that there are cases where cloud-init could decide to reapply that config, and that is not the correct behavior.    I want to continue to track this issue - we're talking to the cloud-init folks on the best way to proceed - and have moved this to the Subiquity bug tracker at [LP:#1956539](https://bugs.launchpad.net/subiquity/+bug/1956539)

**Comment by sowasred2012** [comment]
Closing, as @dbungert mentioned, this is being tracked on Launchpad now: https://bugs.launchpad.net/subiquity/+bug/1956539
