### ISSUE TITLE
Beta shop says I don't need to attach machines to set up UA services

### ISSUE THREAD

**Issue by cmars** [canonical-web-and-design/ubuntu.com#9517]
When I go to the beta shop at https://ubuntu-com-9240.demos.haus/advantage, it says "You don’t need to attach machines before setting up UA services." for Ubuntu 16.04 and 18.04.

![Screenshot from 2021-04-07 12-06-34](https://user-images.githubusercontent.com/23741/113906989-77775880-979a-11eb-9f44-927ca46cb87c.png)

Is this because the UA client hasn't been officially released for these series yet?

Perhaps this will be addressed soon, but I would expect this to either link to documentation on how to actually set up access to services with the "old" UA client, or to assume that the new UA client is already released in this copy, if it is expected to be released along with the beta shop.

I think it is misleading as it is though; as a customer I would read this and think that 16.04 and 18.04 automatically enable all the UA services with no special instructions required -- which is not the case.

**Comment by wgx** [comment]
@lechsandecki please confirm the expected behaviour for 16.04 and 18.04 and I'll make the relevant changes (if any).

**Comment by lechsandecki** [comment]
FOR NOW IT SHOULD BE: 

If you run Ubuntu 16.04 LTS or Ubuntu 18.04 LTS you might need to install the ua client first. In that case. First, add the PPA containing it:

$ sudo add-apt-repository ppa:ua-client/stable
$ sudo apt-get update

Now install the UA client:

$ sudo apt install ubuntu-advantage-tools

ONCE WE SRU THE UA CLIENT TO XENIAL AND BIONIC, IT WILL BE THE SAME AS FOR 14.04 AND 20.04

**Comment by davecore82** [comment]
For what it's worth, the original shop has the same issue  https://ubuntu.com/advantage 
![uashop](https://user-images.githubusercontent.com/3519585/114760358-3698ba00-9d2d-11eb-907f-83d6048e37e6.png)

**Comment by wgx** [comment]
Thanks! Agree it needs a fix. We have the new copy now from @lechsandecki - @SirSamTumless can you prioritise this into a future iteration please?

**Comment by wgx** [comment]
Copy:

##Ubuntu 16.04 and 18.04 LTS

You may need to install the UA client first. First, add the PPA containing it:

`$ sudo add-apt-repository ppa:ua-client/stable`
`$ sudo apt-get update`

Now install the UA client:

`$ sudo apt install ubuntu-advantage-tools`

**Comment by SirSamTumless** [comment]
@ClementChaumel Would you have time to look at this this iteration?

**Comment by ClementChaumel** [comment]
Hey, what about this copy? (it only appears for new subscriptions)
![image](https://user-images.githubusercontent.com/11927929/114883700-7337e480-9e05-11eb-8a4c-e8288ac2a2c7.png)
Should I replace it as well?

**Comment by wgx** [comment]
Yes, please replace.
