### ISSUE TITLE
Add meta image to 16.04 LTS page

### ISSUE THREAD

**Issue by Khutch25** [canonical-web-and-design/ubuntu.com#9519]
Would it be possible to add a meta image to the 16.04 page metadata? In social media previews, there is no image preview.

---
*Reported from: https://ubuntu.com/16-04*

**Comment by SirSamTumless** [comment]
@waynecrosby Could you link the right 16.04 image here?

**Comment by SirSamTumless** [comment]
@waynecrosby Could you please update me on this?
