### ISSUE TITLE
'AI and ML on Kubernetes' link in main nav error

### ISSUE THREAD

**Issue by Khutch25** [canonical-web-and-design/ubuntu.com#9520]
When navigating to Enterprise > Kubernetes > AI and ML on Kubernetes on the site, I get a 404 error.

![Screenshot 2021-04-08 at 13 52 00](https://user-images.githubusercontent.com/42180941/114029800-cba13c00-9871-11eb-8a2d-ac92580a4424.png)

Can this page be updated to the correct page - do you know where this should link @alxchalkias @RFMVasconcelos ?

---
*Reported from: https://ubuntu.com/ai/features*

**Comment by RFMVasconcelos** [comment]
Thank you for pointing this out @Khutch25! We're on it! 

Commented in [this internal doc](https://docs.google.com/document/d/1YBdQvLuqEpEQr_QqyycxMhZr4OaLapMlNJyYKCmPJsQ/edit#heading=h.x5bjdjaazslx)

**Comment by SirSamTumless** [comment]
What page do you want this to actually link to?

**Comment by RFMVasconcelos** [comment]
@SirSamTumless please point it to https://ubuntu.com/ai/what-is-kubeflow
