### ISSUE TITLE
www.ubuntu.com redirection to release notes is broken again

### ISSUE THREAD

**Issue by oSoMoN** [canonical-web-and-design/ubuntu.com#9523]
This is https://github.com/canonical-web-and-design/ubuntu.com/issues/7129 that was probably fixed at the time it was closed, but is happening again.

All Ubuntu ISOs include a file (`/media/cdrom/.disk/release_notes_url`) which contains a link to the release notes. Its contents look like this:

http://www.ubuntu.com/getubuntu/releasenotes?os=ubuntu&ver=21.04&lang=${LANG}

This now redirects to https://ubuntu.com/download?os=ubuntu&ver=21.04&lang=${LANG} which is not the release notes for that release.

This was reported as [a bug against ubiquity](https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1910871), the Ubuntu desktop installer.

The actual release notes for a given release are at https://wiki.ubuntu.com/${CODENAME}/ReleaseNotes, e.g. https://wiki.ubuntu.com/HirsuteHippo/ReleaseNotes.

**Comment by xnox** [comment]
Last time we did it with url pattern rewrites in apache config itself. I wonder if it is tripping up at lack of `www` now. When the redirector webapp got decommissioned.

**Comment by nottrobin** [comment]
This worked fine until https://github.com/canonical-web-and-design/ubuntu.com/pull/8589. And if we switch that back it will work fine again.

@pmahnke what else do you need to be redirected to `/download` under `/getubuntu`?

**Comment by pmahnke** [comment]
@nottrobin let's assume nothing for right now, I will check the webmaster tools to get more details urls that are failing.

**Comment by nottrobin** [comment]
Reverting that change in https://github.com/canonical-web-and-design/ubuntu.com/pull/9568

**Comment by oSoMoN** [comment]
Thanks @nottrobin and @pmahnke, I can confirm this now works as expected.
