### ISSUE TITLE
LSN sample on staging

### ISSUE THREAD

**Issue by albertkol** [canonical-web-and-design/ubuntu.com#9529]
We have a sample of LSN on staging at:
https://staging.ubuntu.com/security/notices/LSN-0075-1

We are following UX provided by Matthew(https://docs.google.com/document/d/183fLUXOLL17_baS617aX7Sj133n4lLfS6-rLhXXv9I0/edit#) a good while ago, with some small changes: 
- releases are listed as buttons instead of a list, to keep the pattern from USN
- Support information data was restructured and moved in the Software Description section

This issue servers the purpose of getting a confirmation that we are happy with how it looks. After we can start importing the LSNs to production.

**Comment by nmav** [comment]
That probably should be on me. I'm not familiar with the old request so let me get into to it.

**Comment by nmav** [comment]
LGTM, what's the next step @albertkol ?

**Comment by anthonydillon** [comment]
@albertkol could you estimate this please

**Comment by albertkol** [comment]
@nmav Sorry for my late reply.

Thank you for looking at this. I will communicate it to the Kernel team and they will start pushing all LSNs to production.
