### ISSUE TITLE
Typographic quotes in <pre />-Block

### ISSUE THREAD

**Issue by neuged** [canonical-web-and-design/ubuntu.com#9535]
Just wanted to let you know that something on your page seems to convert quotes in code blocks `"..."` to typographic quotes (`“...”`), breaking the commands mentioned in the Code-Block, e.g. on [this page](https://ubuntu.com/blog/private-home-directories-for-ubuntu-21-04), the command

```
echo “HOME_MODE 0750” | sudo tee -a /etc/login.defs
```
will not work as expected, adding the expression with the typographic qutoes to the file without reporting an error.

---
*Reported from: https://ubuntu.com/blog/private-home-directories-for-ubuntu-21-04*

**Comment by anthonydillon** [comment]
Thank you for taking the time to report this issue to us. The content on the page has been updated.
