### ISSUE TITLE
Unknown errors in the shop

### ISSUE THREAD

**Issue by alnvdl** [canonical-web-and-design/ubuntu.com#9543]
Ever since we released renewals, we have had customers contacting us from time to time saying they are getting the following error message:

> Sorry, there was an unknown error with the payment. Check the details and try again. Contact Canonical sales if the problem persists.

This message is triggered here whenever the error is `undefined`:
https://github.com/canonical-web-and-design/ubuntu.com/blob/a94d0d0a6be4d32540c5dd0fe79064aca1292cba/static/js/src/ua-payment-modal.js#L879-L886

Which happens in the following places:

https://github.com/canonical-web-and-design/ubuntu.com/blob/a94d0d0a6be4d32540c5dd0fe79064aca1292cba/static/js/src/ua-payment-modal.js#L508

https://github.com/canonical-web-and-design/ubuntu.com/blob/a94d0d0a6be4d32540c5dd0fe79064aca1292cba/static/js/src/ua-payment-modal.js#L670

https://github.com/canonical-web-and-design/ubuntu.com/blob/a94d0d0a6be4d32540c5dd0fe79064aca1292cba/static/js/src/ua-payment-modal.js#L797

https://github.com/canonical-web-and-design/ubuntu.com/blob/a94d0d0a6be4d32540c5dd0fe79064aca1292cba/static/js/src/ua-payment-modal.js#L871

https://github.com/canonical-web-and-design/ubuntu.com/blob/a94d0d0a6be4d32540c5dd0fe79064aca1292cba/static/js/src/ua-payment-modal.js#L875

https://github.com/canonical-web-and-design/ubuntu.com/blob/a94d0d0a6be4d32540c5dd0fe79064aca1292cba/static/js/src/ua-payment-modal.js#L922

https://github.com/canonical-web-and-design/ubuntu.com/blob/a94d0d0a6be4d32540c5dd0fe79064aca1292cba/static/js/src/ua-payment-modal.js#L941

Since this is happening in multiple places for completely different causes, it's very hard for us to figure out what is wrong. Would it be possible to:
- append the name of the function in which the error happens;
- and get a string representation of the any errors in that message that gets displayed to the customer?

**Comment by anthonydillon** [comment]
Thank you @alnvdl. 

We should be recording these issues with the Sentry. Then we can display the Sentry id to the user and they can report that. That will give us both non-reported issues which we should be regularly addressing and give us the full stack trace of the exact issue the particular customer is hitting.

**Comment by ariannalozano** [comment]
@alnvdl @anthonydillon Regarding this issue, I wonder if it would be better to redirect the customer to the Customer Success team at customersuccess@canonical.com versus the Sales team if they are receiving this error. More recently when a customer is having an issue purchasing from the store they will chat with the SDRs on Livechat or call into the Sales phone number and speak with the SDRs. It is usually the case where these customers do not meet the $2,500 purchase minimum for support to speak with a Sales Rep. It may be better to redirect the customer directly to the Canonical group that will be able to assist them quickly.

**Comment by anthonydillon** [comment]
Absolutely agree, we should have contact support provided on the advantage portal. @wgx is this something we can add?

**Comment by wgx** [comment]
@anthonydillon Agree we should have a link. 

Interestingly, the 'contact us' button in the footer of /advantage (signed in) (left hand side) - opens the ESM Apps Beta form, not the main contact page... Maybe it should go to customersuccess@... instead ? 

![image](https://user-images.githubusercontent.com/930099/115421686-1026c300-a1f4-11eb-9951-869ad2d5e401.png)

**Comment by SirSamTumless** [comment]
@ClementChaumel Is going to add sentry to the frontend.
