### ISSUE TITLE
Add GCP to /advantage/subscribe (dev)

### ISSUE THREAD

**Issue by ClementChaumel** [canonical-web-and-design/ubuntu.com#9548]
Implement the changes from the copydoc: https://docs.google.com/document/d/1UqL8YJH9ywvOXnrt3syY0U8fiOakfAGWmLS9uerwAWk/edit?disco=AAAAIGPWbxc&ts=6076a9df&usp_dm=true

**Comment by SirSamTumless** [comment]
@lechsandecki Can you confirm this is the correct link; https://console.cloud.google.com/marketplace/product/ubuntu-os-pro-cloud/ubuntu-pro-focal

**Comment by lechsandecki** [comment]
I think that we should use that instead:
https://console.cloud.google.com/marketplace/browse?q=ubuntu%20pro%20canonical
