### ISSUE TITLE
u.c/advantage confusing UX

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-web-and-design/ubuntu.com#9559]
When a customer purchases UA-I Physical they receive support for the physical machines as well as all containers/VMs on that machine. When the customer logs in to get their token they see that they have a subscription for X number of physical machines, but it doesn't say anything about containers/VMs on those machines. This is a confusing UX for customers, leading them to ask questions about how they register more than just X number of physical machines.

---
*Reported from: https://ubuntu.com/advantage*

**Comment by wgx** [comment]
Thanks for this @cjohnston1158  - we have an item to redesign this UI fully, and I'll add this valid point to our plan. We definitely should be making things more clear to users, but it might be that marketing or docs pages are the best place to explain this. Leave it with us.
