### ISSUE TITLE
None of the links for the other operating systems go anywhere

### ISSUE THREAD

**Issue by lisack** [canonical-web-and-design/ubuntu.com#9560]
Trying to install ubuntu for my Raspberry PI, using MacOS, but can't follow the tutorial because I can't install the image-copying s/w, due to the link for my O/S's instructions not working.  Tried the others too.  No dice

**Comment by sowasred2012** [comment]
@lisack sorry you had this problem, it looks like the page was updated and the links are now working. I'll close this issue.
