### ISSUE TITLE
Payment pops up before I get to quantity

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#9573]
I was purchasing on my phone but as soon as I select the support level the payment pop up appears. Which means I missed the quantity and took me a while to find it. Can we just make the payment sticky when you get to it?

![Screenshot_20210420-115527](https://user-images.githubusercontent.com/1413534/115385189-c0ce9b80-a1cf-11eb-94fb-f605e13e8873.jpg)

**Comment by ClementChaumel** [comment]
I think this comes from product owners wanting to show the price as soon as possible and at all times on the page.
I agree it's not a great experience on mobile / smaller screens though. @wgx @elioqoshi thoughts?

**Comment by wgx** [comment]
@elioqoshi please can you handle this one

**Comment by elioqoshi** [comment]
Sure, will take a look today

**Comment by elioqoshi** [comment]
Sorry for the delay here.

@ClementChaumel Can we identify if the user is on a mobile and make the pricing sticky only after all steps are finished? 

If that's not possible we should simply show the pricing after the quantity is selected, for mobile users at least.

**Comment by ClementChaumel** [comment]
The issue is that the form is "completed" after support is chosen since the quantity defaults to 1.
Showing the pricing only after the quantity is selected could be done by removing the default but since it's the last field it would defeat our goal of "Always showing price on screen as soon as possible"

**Comment by elioqoshi** [comment]
> Showing the pricing only after the quantity is selected could be done by removing the default but since it's the last field it would defeat our goal of "Always showing price on screen as soon as possible"

Yeah, my question is whether the behaviour for mobile could be different than desktop or would that be weird?

One way to mitigate this is to automatic scroll to the quantity step anchor point after selecting customer support, so the sticky pricing would likely not cover the quantity step.
