### ISSUE TITLE
[21.04] design takeover 

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#9577]

**Comment by anasereijo** [comment]
Hi @AmberCharitos can you please share with me the text for this takeover? I am working on the illustration. thank you

**Comment by AmberCharitos** [comment]
Ubuntu Server 21.04
Introducing native integration with Microsoft SQL Server
Download

Learn about new features and migration from CentOS ›

**Comment by AmberCharitos** [comment]
I actually already created a takeover for this and it is currently active = false in discourse. So feel free to delete it there and replace with your new design
![Screenshot 2021-04-21 at 09 57 44](https://user-images.githubusercontent.com/67629430/115526520-064e9f80-a288-11eb-93a5-498cb65d4524.png)

**Comment by anasereijo** [comment]
thanks @AmberCharitos I will send you the image with the correct sizing

**Comment by AmberCharitos** [comment]
Perfect thanks!

**Comment by anasereijo** [comment]
@AmberCharitos please use this [illustration](https://assets.ubuntu.com/v1/b9c5264f-Hirsuit_Hippo_Colour_takeover.svg) width: 412px height: 173px

thank you

**Comment by AmberCharitos** [comment]
Great thank you!

**Comment by AmberCharitos** [comment]
![Screenshot 2021-04-22 at 11 40 00](https://user-images.githubusercontent.com/67629430/115701227-7c720580-a35f-11eb-848e-14c05214a974.png)

@anasereijo  Are you happy with this?

**Comment by anasereijo** [comment]
Hi @AmberCharitos, @pmahnke and I already amended the takeover this morning. Thank you

**Comment by AmberCharitos** [comment]
Ok I will revert to how it was then. In future could you let me know, as I was under the impression it needed to be updated with the image and size you provided above. Thanks

**Comment by AmberCharitos** [comment]
![Screenshot 2021-04-22 at 11 57 27](https://user-images.githubusercontent.com/67629430/115703341-ebe8f480-a361-11eb-905a-9c465eb378d8.png)

To confirm this is what is should look like?

**Comment by anthonydillon** [comment]
@AmberCharitos FYI, I have updated the illustration to https://assets.ubuntu.com/v1/84cb7d7d-Hirsuit_Hippo_Colour_takeover.svg

**Comment by AmberCharitos** [comment]
Thanks for letting me know :)
