### ISSUE TITLE
Raspberry Pi Imager for Windows link returns 404

### ISSUE THREAD

**Issue by mikeblome** [canonical-web-and-design/ubuntu.com#9579]
On this page:
https://ubuntu.com/tutorials/how-to-install-ubuntu-desktop-on-raspberry-pi-4#2-prepare-the-sd-card

the [Imager for Windows](https://downloads.raspberrypi.org/imager/imager.exe) link returns 404

**Comment by pmahnke** [comment]
@mikeblome thanks for letting us know.  I have updated all the imager download links.

Windows is - https://downloads.raspberrypi.org/imager/imager_latest.exe
