### ISSUE TITLE
Show the correct ESM value for ESM Apps

### ISSUE THREAD

**Issue by ClementChaumel** [canonical-web-and-design/ubuntu.com#9586]
On the /advantage table, the ESM column should display the correct value for apps instead of always displaying "infra'
![image.png](https://images.zenhubusercontent.com/5894789951aa2c30577369fa/ab0dcf75-d5b6-4e9e-910d-95a48e39f318)

We need this before launching ESM Apps

**Comment by albertkol** [comment]
RIP old UI.
