### ISSUE TITLE
[COPY UPDATE] Ubuntu 16.04 lts - ubuntu.com/16-04

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#9602]
Please update Ubuntu 16.04 lts - ubuntu.com/16-04 from the [copy doc](https://docs.google.com/document/d/1wclofqY9b3v_M9igpkYn6or5uXx0B_Xb_nVVzGBbOLY/edit?usp=drivesdk)

**Comment by caldav** [comment]
In addition to this: in the 2nd nav, "16-04" should read "16.04 LTS"

**Comment by Khutch25** [comment]
I also just added another edit to the [copy doc](https://docs.google.com/document/d/1wclofqY9b3v_M9igpkYn6or5uXx0B_Xb_nVVzGBbOLY/edit?ts=60829008#) now that we have the /16-04/azure page live > I have suggested that we replace the Azure Pro page link in the ESM on public clouds section with the [/16-04/azure page](https://ubuntu.com/16-04/azure).

**Comment by Khutch25** [comment]
I also just added myself as an assignee so I can track progress in the MM connector :)
