### ISSUE TITLE
ubuntu.com/advantage: Remove the older packages versions

### ISSUE THREAD

**Issue by nmav** [canonical-web-and-design/ubuntu.com#9607]
## Summary

The logged in version of ubuntu.com/advantage says:
"FIPS 140-2 Level 1 certified packages use older software versions. Use them only if your organisation requires it."
this text should be replaced with
"FIPS 140-2 Level 1 certified packages"

Similarly for CC:
"CC-EAL2 certified packages use older software versions. Use them only if your organisation requires it."
replaced by
"CC-EAL2 certified packages and configuration"

## Screenshot

![screenshot](https://user-images.githubusercontent.com/1745073/115855136-37b3a080-a42b-11eb-9652-2a8337908881.png)

**Comment by SirSamTumless** [comment]
@nmav Could you please edit the copy doc and assign canonical editors

**Comment by nmav** [comment]
> @nmav Could you please edit the copy doc and assign canonical editors

There is no copydoc I can edit. What I see from the plugin is this page, which seems to have deviated from the actual html page:
https://docs.google.com/document/d/1K65n3NpZCh7EWDXKLhG31seGJ2jKbW6lqw3BwV2mlnU/edit#heading=h.nleu1cdig11l

**Comment by SirSamTumless** [comment]
@nmav The copy doc is outdated - I will make sure it gets sorted. You can find the up to date ones here: https://drive.google.com/drive/folders/1SO3p5ZfX31vYrOz53ebsTo64_L6-38GZ

**Comment by nmav** [comment]
@SirSamTumless the text I'm referring to is not in any of the copy docs. Let me know what you'd like me to do to have this change included.

**Comment by SirSamTumless** [comment]
@lechsandecki I can see this getting really tricky to sort out when we get loads of products in the feature. I think we should create some sort of product catalog copy doc or something. In the meantime, I will get this in our backlog @nmav.
