### ISSUE TITLE
[security website] Updating the hirsute release to mark it no longer in devel failed

### ISSUE THREAD

**Issue by stevebeattie** [canonical-web-and-design/ubuntu.com#9617]
## Summary

Attempting to update the hirsute 21.04 release to mark at as no longer in devel failed, due to it already existing.

## Process

Using the script https://git.launchpad.net/ubuntu-cve-tracker/tree/scripts/post-release-to-web-cve-tracker.py, 
attempts to post the following to `https://ubuntu.com/security/releases.json`:
```
{
    "name": "Hirsute Hippo",
    "version": "21.04",
    "codename": "hirsute",
    "lts": "False",
    "development": "False",
    "release_date": "2021-04-22",
    "esm_expires": "2022-01-31",
    "support_expires": "2022-01-31",
}
```
resulted in the following error:
```
<Response [400]> {"message":"Release with [codename:'hirsute'] or [version:'21.04'] or [name:'Hirsute Hippo'] already exists"}
```
Looking at the [swagger page](https://ubuntu.com/security/api/docs#/default/post_security_releases_json), it appears it only accepts new postings, as well as a delete target. I can't query the release to determine if it has already been marked as not in development any more.

Is it okay to delete the existing hirsute release? We will be pushing CVEs with hirsute entries shortly, though we have not pushed any USNs for 21.04 yet. Should we be waiting until the release is out of development before adding it to the website? I'm not sure whether the releases only interact with the USN website or the CVE tracker as well.
 
## Current and expected result

I expected to be able to update the status of the hirsute release.

**Comment by albertkol** [comment]
@stevebeattie for as much as I am aware the development property of the release is not used in any way. So I think we do not need to worry about that before importing CVEs or Notices to the database.

However I finished the PR that adds the endpoint that would allow release updates. 

Deleting is usually not a right call, since we might have CVEs or Notices attached to the release already.

**Comment by albertkol** [comment]
@stevebeattie the API has a GET and a PUT method for a release.

To test it out I updated myself the `development` from True to False for the `hirsute` release. But next time anyone will be able to do it.
