### ISSUE TITLE
UA shop: Failure to notify user about payment error

### ISSUE THREAD

**Issue by alnvdl** [canonical-web-and-design/ubuntu.com#9638]
**Steps to reproduce:**
1. Make any purchase (I bought 3x UAI Desktop Advanced) using card 4000 000 0000 0341 (valid, but can't be charged).

2. Payment never concludes, even though ua-contracts returns the following advice in the invoice:
    ```json
    "paymentStatus": {
        "lastPaymentError": "generic_decline",
        "status": "need_another_payment_method"
    }
    ```
    Or if you are still using the legacy field, it's also there:
    ```json
    "stripeInvoices": [{
            "id": "in_1IkvgUCzjFajHovd7jyUBW11",
            "last_update": "2021-04-27T18:31:12.696134Z",
            "pi_decline_code": "generic_decline",
            "pi_status": "requires_payment_method",
            "subscription_status": "incomplete"
    }]
    ```

**Other notes:**
- The payment fails and the user does not get any warning (the modal just closes).
- No banner is displayed to the user about their subscription having a problem, and they can still try to make new purchases, even though it's getting stuck as soon as the modal opens (because they have a purchase stuck that must be solved first).

**Comment by wgx** [comment]
>The payment fails and the user does not get any warning (the modal just closes).

The user should see a 'red' warning notification bar in the payment modal telling them of a payment error. 

>No banner is displayed to the user about their subscription having a problem.

The "Payment problem" banner notification should be displayed across the /advantage view.
