### ISSUE TITLE
UA shop: payment failing due to 3DS does not trigger an authorization request

### ISSUE THREAD

**Issue by alnvdl** [canonical-web-and-design/ubuntu.com#9640]
**Steps to reproduce:**
1. Make any purchase using card 4000 0027 6000 3184.

2. Try to update the subscription to increase # of machines. It will fail (silently, see #9639).

3. Go to `/advantage/payment-methods`.

**What is expected**: a button prompting the user to authorize the payment that is pending 3DS authorization.

**What happens**: the payment is still stuck, but nothing gets displayed.

**Comment by wgx** [comment]
@albertkol We've discussed on a separate issue: https://github.com/canonical-web-and-design/web-squad/issues/3950

>a button prompting the user to authorize the payment that is pending 3DS authorization.

There is no button - but the /payment-methods view should trigger any stuck purchase which will show the Stripe 3DS/SCA modal
