### ISSUE TITLE
UA shop: can edit a subscription while an edit is already pending

### ISSUE THREAD

**Issue by alnvdl** [canonical-web-and-design/ubuntu.com#9641]
**Steps to reproduce**:
The same as #9639 or #9640.

**What is expected**: if a previous purchase subscription is stuck for a subscription, the "Change subscription" button should be greyed out.

**What happens**: user can edit the subscription, which fails but causes the spinner to be displayed forever.

**Comment by wgx** [comment]
Agree:

>If a previous purchase subscription is stuck for a subscription, the "Change subscription" button should be greyed out.

**Comment by elioqoshi** [comment]
Nice and simple, greying out the button should suffice, yep.

**Comment by albertkol** [comment]
@wgx should we not display a message next to the disabled button telling the user why the button is disabled?

They might not have seen the notification telling them about the existing pending payment. Even if they do see it, the notification does not imply in any way that subscription modifications are disabled until they fix the problem.

![image.png](https://images.zenhubusercontent.com/5ee7415a47536a7869302593/a8658cd6-2559-46c7-85b2-53798e062265)

**Comment by wgx** [comment]
@albertkol It's not essential - we have to believe that our notification banner is urgent enough, and I think it is.

We could show a tooltip on hover of the button:

> There is a problem with your payment method

But in my view it's not essential.
