### ISSUE TITLE
New contact page - due 6 May 2021

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/ubuntu.com#9698]
We need a new page put on /azure/private-offer

- image - https://assets.ubuntu.com/v1/a25fbd66-ubuntu-microsoft-azure-offer.png (w 340 x h 195)
- [Copy doc](https://docs.google.com/document/d/1ZgV1ZiyHJe3UNQkj0I-OCpZ4MIAWLHheig2Q2rclcuk/edit)
- do not add to the footer or subnav
- form, use the fields from the engage pages with the id 3888
- layout like an engage page (form on the right)
- thank you can be /azure/thank-you

**Comment by anthonydillon** [comment]
Could this not just be an engage page? Seems strange to add "official" pages to a section and hide them from navigation.

**Comment by pmahnke** [comment]
No, it cannot, engage pages are 1) public, 2) classified as resources (whitepapers, etc) 3) take you to the download thank you page.  The user experience would be poor and it would  not be private.

This was discussed in detail with Marketing and Carlos yesterday.

**Comment by pmahnke** [comment]
I think it should be a hidden page in the azure navigation as well, I missed that in my issue.

**Comment by anasereijo** [comment]
happy to give design guidance on this if needed.
