### ISSUE TITLE
copy updates on /azure private offer page

### ISSUE THREAD

**Issue by lindseylopez** [canonical-web-and-design/ubuntu.com#9709]
Can we add before the key features bullets "Please complete the form on the right to be contacted by Canonical and discuss how private offer for Ubuntu Pro on Azure can meet your needs."

and can we change the text/link at the bottom from 'Visit the Azure Marketplace to download Ubuntu Pro' to [Learn more about Ubuntu Pro](https://ubuntu.com/azure/pro)

Change first part of copy from "Top banks,  large telcos and leading retailers all rely on Ubuntu on Azure. They innovate on Ubuntu because they trust that their production and mission-critical workloads are reliable and available. " to "All industries including top banks,  large telcos and leading retailers all rely on Ubuntu on Azure. They innovate on Ubuntu because they trust that their production and mission-critical workloads are reliable and available."

Also updated / commented changes in copy doc: https://docs.google.com/document/d/1ZgV1ZiyHJe3UNQkj0I-OCpZ4MIAWLHheig2Q2rclcuk/edit

thank you!

---
*Reported from: https://ubuntu.com/azure/private-offer*

**Comment by lindseylopez** [comment]
When I go to https://ubuntu.com/azure/private-offer I am not seeing the changes made but I see the issue is closed. I even tried via an incognito window. Were the changes made? Thank you!

**Comment by lindseylopez** [comment]
Thank you, sorry new to how the changes/updates work. Thank you for your help!

**Comment by lindseylopez** [comment]
Hi team, I see that it still says "Visit the Azure Marketplace to download Ubuntu Pro ›" instead of "Learn more about Ubuntu Pro" and linked here: https://ubuntu.com/azure/pro 

Is this still updating?

**Comment by jpmartinspt** [comment]
@lindseylopez I just updated that on https://github.com/canonical-web-and-design/ubuntu.com/pull/9723. Going to deploy soon.
