### ISSUE TITLE
Repository hit it's no original 

### ISSUE THREAD

**Issue by misrules** [canonical-web-and-design/ubuntu.com#9725]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

[Please describe the issue.]

## Process

[List the steps to replicate the issue.]

## Current and expected result

[Describe what happened and what you expected.]

## Screenshot

[If relevant, please include a screenshot.]

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

**Comment by anthonydillon** [comment]
Please take the time to provide more information and reopen.
