### ISSUE TITLE
Download not triggered on the thank you page

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/ubuntu.com#9727]
When hitting this page the download should be triggered after 3 seconds.

Getting:
```
Uncaught TypeError: window.initImageDownload is not a function
    <anonymous> https://ubuntu.com/download/desktop/thank-you?version=20.04.2.0&architecture=amd64:1625
thank-you:1625:14
```

---
*Reported from: https://ubuntu.com/download/desktop/thank-you?version=20.04.2.0

**Comment by pmahnke** [comment]
I can't replicate this, is it the `:1625`

Also there is no Architecture

https://ubuntu.com/download/desktop/thank-you?version=20.04.2.0&architecture=amd64 is the correct link.
