### ISSUE TITLE
Display auto renewal's next payment with taxes

### ISSUE THREAD

**Issue by ClementChaumel** [canonical-web-and-design/ubuntu.com#9736]
Allan said that it is now possible to get the next payment with taxes:
https://github.com/canonical-web-and-design/ubuntu.com/pull/9731#issuecomment-836976876

And Will confirmed that this is what we want to display to users.

**Comment by albertkol** [comment]
@wgx It seems like we display the text about the next recurring payment even if we have auto-renewal turned off.

I will hide the text as part of this issue, if the auto-renewal is turned off.

![image.png](https://images.zenhubusercontent.com/5ee7415a47536a7869302593/1bd104a2-be96-4e8c-ac1d-bdc5d9bfc452)

**Comment by wgx** [comment]
@albertkol yes please do hide if auto-renewal is off :)
