### ISSUE TITLE
"Upgrading" link on 1.21/components 404's

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-web-and-design/ubuntu.com#9752]
The Upgrade button on [Components of CK 1.21](https://ubuntu.com/kubernetes/docs/1.21/components) 404's.

---
*Reported from: https://ubuntu.com/kubernetes/docs/1.21/components*

**Comment by johnsca** [comment]
The fix for this is already pending in #9701

**Comment by anthonydillon** [comment]
Fix has landed and is live.
