### ISSUE TITLE
[COPY UPDATE] livepatch

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#9758]
Please update livepatch from the [copy doc](https://docs.google.com/document/d/1g_Ip5MzlBRpbM2wULpSnsR5XaHJVWgLPLdq8_7fCHrs/edit?usp=drivesdk)

**Comment by nmav** [comment]
Please use the original copydoc at:
https://docs.google.com/document/d/1Ofw9bQ4I40gy9hDIjuDMApz6sDK8qSdHI03-oY7xs-A/edit

The one linked above is one in progress and not complete yet!
