### ISSUE TITLE
[COPY UPDATE] financial-services - "Financial services"

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/ubuntu.com#9773]
Please update financial-services - "Financial services" from the [copy doc](https://docs.google.com/document/d/1SEd2nV0GplBTG4lZ9RuhjNXrphU22nGP4Fpgd5g_9BQ/edit)

**Comment by bethcollins92** [comment]
@SirSamTumless please see this comment https://docs.google.com/document/d/1o9s_MFaiZZIS26tusRi0ALNrcqUihhTSZgxS55oHZj4/edit?disco=AAAAMqlrCyg

**Comment by SirSamTumless** [comment]
I linked the wrong doc - the right copy change is her: https://docs.google.com/document/d/1SEd2nV0GplBTG4lZ9RuhjNXrphU22nGP4Fpgd5g_9BQ/edit
