### ISSUE TITLE
CUBE Microcert graphic not filling.

### ISSUE THREAD

**Issue by KellenRenshaw** [canonical-web-and-design/ubuntu.com#9788]
## Summary

When viewing https://ubuntu.com/cube/microcerts, the graphic to the right of "Your road to CUBE" doesn't change with the earned Microcerts. Our understanding was that it would fill in as they were earned.

**Comment by bethcollins92** [comment]
fixed here https://github.com/canonical-web-and-design/ubuntu.com/pull/9798
