### ISSUE TITLE
Not able to scroll in login page

### ISSUE THREAD

**Issue by Omcsesz** [canonical-web-and-design/ubuntu.com#9792]
## Summary

Hello, Team!

When I try to register in https://login.launchpad.net/6DNyCWdN7DauI0GO/+login, I'm not able to scroll down (see attachment).

## Process

1. Open the page: https://login.launchpad.net/6DNyCWdN7DauI0GO/+login
2. Check the option: "I don’t have an Ubuntu One account"
3. Try to scroll :)

## Current and expected result

Current: I'm not able to scroll.
Expected: I should be able to scroll.

## Screenshot

[image](https://user-images.githubusercontent.com/1839739/119023717-932d6b80-b9a2-11eb-95a7-8b68cf4a540d.png)

## Browser details
Firefox 88.0.1 (64-bit)

**Comment by anthonydillon** [comment]
@Omcsesz I have tried this out on FF 88.0.1 but cannot replicate this. Could you try this in a private window to see if it's a browser add-on?

**Comment by Omcsesz** [comment]
Hi, Anthony!

I tried it in a private window, and the issue persists.

**Comment by anthonydillon** [comment]
Sorry for the delayed reply. @Omcsesz would you mind disabling add-ons or using a different browser. We believe it might be an add-on interfering with the UI.

**Comment by Omcsesz** [comment]
@anthonydillon I tried it after disabling all add-ons, but I still get the same behaviour.

**Comment by anthonydillon** [comment]
I think I have found the issue. I have proposed an update to the cookie policy module on the login.ubuntu.com site. Once merged and live it should allow you to scroll.

**Comment by Omcsesz** [comment]
Super!
I'm looking forward for it!

**Comment by Omcsesz** [comment]
Any progress?

**Comment by anthonydillon** [comment]
Sorry for the delay. The potential fix has landed. Just awaiting it to be released to staging to test.

**Comment by anthonydillon** [comment]
@Omcsesz we have rolled out an update to the cookie policy module which I think was the culprit. Would you mind refreshing and checking again?

**Comment by Omcsesz** [comment]
> 
> 
> @Omcsesz we have rolled out an update to the cookie policy module which I think was the culprit. Would you mind refreshing and checking again?

Now it scrolls, thank you!
