### ISSUE TITLE
Add Raspberry Pi 4 support info

### ISSUE THREAD

**Issue by rafrafek** [canonical-web-and-design/ubuntu.com#9796]
Currently Raspberry Pi 4 is not listed on Ubuntu Desktop 21.04 download page. 
Please add information whether it is supported or not. 

![Screenshot_20210522-152712259](https://user-images.githubusercontent.com/23004737/119228220-4a94c000-bb12-11eb-95ca-d05c96842b39.png)

---
*Reported from: https://ubuntu.com/download/raspberry-pi*

**Comment by SirSamTumless** [comment]
@rhys-the-davies Please could you let me know if you're the right person to look into this?

**Comment by rhys-the-davies** [comment]
Yep, that was a mistake when the release dropped that came from a misunderstanding between Peter and Lukasz, the Raspberry Pi 4 (4GB & 8GB) **should** be on that list 👍🏼

**Comment by pmahnke** [comment]
@rhys-the-davies go and blame me... ;-)
