### ISSUE TITLE
Search indexer should not index irclogs.ubuntu.com

### ISSUE THREAD

**Issue by tomreyn** [canonical-web-and-design/ubuntu.com#9797]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

ubuntu.com search indexer should not index irclogs.ubuntu.com

## Process

https://ubuntu.com/search?q=irclogs+fuck

## Current and expected result

Current:
Hits from IRC logs are returned, including NFSW content.

Expected:
No results

## Screenshot

Not relevant.

## Browser details

Not relevant.

**Comment by nottrobin** [comment]
Thanks @tomreyn for raising this, it's an interesting question.

After a fair bit of consideration, we think this is not something we want to do.

We do not as a company, as far as I'm aware, have a strong stance against expletives. It would of course be unprofessional to include them in official company communication, but we don't go out of our way to prevent users using them. E.g.:

https://snapcraft.io/thefuck
https://ubuntu.com/search?q=fuck

The Ubuntu search is quite clearly a portal to other content, not the host of that content itself, much like google.com is for the web at large. It isn't ubuntu.com's job to censor search results.

And I believe irclogs.ubuntu.com is potentially quite a useful resource to be able to find through ubuntu.com's search. It could contain some very useful information on esoteric topics.

So I'm going to close this now. Thanks again.
