### ISSUE TITLE
Navbar too tall? 

### ISSUE THREAD

**Issue by RFMVasconcelos** [canonical-web-and-design/ubuntu.com#9814]
Unsure if this is the desired state of the navbar, looks odd. 

![image](https://user-images.githubusercontent.com/27001378/119660085-c0f13500-be26-11eb-8e8a-8e097d9964cd.png)

---
*Reported from: https://ubuntu.com/*

**Comment by bartaz** [comment]
This looks related to vanilla 2.30 update. We updated top navigation styling. Any custom styling in the project (which I guess ubuntu.com has a lot of) needs to be revisited and updated accordingly.
