### ISSUE TITLE
https://ubuntu.com/advantage does not list CIS compliance tooling

### ISSUE THREAD

**Issue by nmav** [canonical-web-and-design/ubuntu.com#9819]
**Describe the bug**
The comparison table among essential, standard and advanced do not mention "[CIS compliance](https://ubuntu.com/security/certifications) tooling", that is available to all tiers
https://ubuntu.com/advantage

The location it should be placed, is under the FIPS140 certified modules.

The copydoc seems to not reflect the contents of the page, so I didn't use it for reporting it.

**Comment by SirSamTumless** [comment]
@lechsandecki Could you please take a look t this

**Comment by lechsandecki** [comment]
+1 on @nmav request. CIS compliance tooling should be listed in that table

**Comment by SirSamTumless** [comment]
@lechsandecki Could you make sure the copy doc is up to date and then @ me?

**Comment by wgx** [comment]
@lechsandecki Closing, please open a new issue with copydoc if this is still required.

**Comment by lechsandecki** [comment]
we should reopen that. I wasnt able to edit the UA features table in the
copydoc because the copy doc for that page seems not to exist. +Will Grant
***@***.***>, do you know where that table lives?

**Comment by wgx** [comment]
Reopening - we will find it! :)

**Comment by petesfrench** [comment]
@lechsandecki is this the [copydoc](https://docs.google.com/document/d/14dC7RR70h7TqrYrFb06SrQVn3hIv_XPsfgLLSYX0JJM/edit) you were looking for?

**Comment by albertkol** [comment]
@lechsandecki please update the copydoc! https://docs.google.com/document/d/14dC7RR70h7TqrYrFb06SrQVn3hIv_XPsfgLLSYX0JJM/edit

**Comment by albertkol** [comment]
This is very old. If we wand to do this, please re-open.
