### ISSUE TITLE
Write UX Blog post for ubuntu.com

### ISSUE THREAD

**Issue by wgx** [canonical-web-and-design/ubuntu.com#9823]
is here: https://docs.google.com/document/d/1cfPxw6_Wou79cDzxLJ_Ovv_1YKKrcUTNJhCv-C3n7AI/edit#

**Comment by wgx** [comment]
Writing a blog post - just making sure we get the points for it. :)

**Comment by wgx** [comment]
@clagom @anasereijo would you like to have a look, maybe suggest some edits? 

@anasereijo you will see there's a section for you at the bottom (or not, can remove...)

**Comment by clagom** [comment]
I like it, Will. Brief, to the point and clear. If you can find a good example, would be great to link the discovery/interview part to the UX/wiframe one with some practical example (e.g. "this IA or this interaction X generated from X need"). Not always possible, but if something in these terms comes to mind, worth mentioning it.

**Comment by anasereijo** [comment]
✅ done! nice work @wgx

**Comment by pmahnke** [comment]
I performed my grammar police role as well; however, it is very good.

**Comment by wgx** [comment]
thanks @pmahnke @anasereijo  - I'll publish tomorrow morning :)
