### ISSUE TITLE
Server block text makes needs refinement

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/ubuntu.com#9829]
The text in the first paragraph of the server block is very awkward to read and needs to be refined.

"Using Ubuntu Server speeds up the ability to deploy physical infrastructure on bare metal as it is in the cloud."

Perhaps something like this:

"We work with the world's leading OEMs to ensure that installing Ubuntu Server to bare metal in your datacenter is fast and trouble free, helping you deploy your critical workloads quickly and efficiently."

Or similar.  

(I realize this is just lifted from the existing site, but it is awkward none the less and now is a good time to fix that).

**Comment by davegoddard42** [comment]
I'll review the copy for the latest designs

**Comment by davegoddard42** [comment]
New copy has been written for this section by the PdMs. It'll be changed as part of the refresh of this page next iteration.

**Comment by cristinadresch** [comment]
This is now done

**Comment by bladernr** [comment]
The changes are being pushed to the production site?
