### ISSUE TITLE
No link to partners.ubuntu.com from cert site

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/ubuntu.com#9831]
There should be some linking between the cert site for Server and at a minimum:
https://canonical.com/partners/ihv-and-oem

Or perhaps https://canonical.com/partners/find-a-partner?filters=ihv-oem

**Comment by carkod** [comment]
@davegoddard42 Some help pointing where we can link this? Maybe @pmahnke can help us understanding the link between the two

**Comment by cristinadresch** [comment]
This is now live
