### ISSUE TITLE
Currently selected item pointer arrow overflows the payment summary on /advantage/subscribe

### ISSUE THREAD

**Issue by elioqoshi** [canonical-web-and-design/ubuntu.com#9840]
![image](https://user-images.githubusercontent.com/5436686/120225180-0d80aa00-c245-11eb-9404-27242eabfc84.png)

The arrow pointing to the Ubuntu version is currently flowing over the payment summary section. It should be underneath.

**Comment by SirSamTumless** [comment]
Remove the arrow!
