### ISSUE TITLE
Top nav changes size when search is opened

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/ubuntu.com#9849]
## Summary

When clicking on Search in top nav the navigation bar gets a bit smaller making whole page move a bit to the top.

## Process

Visit ubuntu.com and click `Search` in top navigation bar.

## Current and expected result

Navigation should not change size, page should not move when search is opened.

## Screenshot

![ubuntu-nav-search](https://user-images.githubusercontent.com/83575/120439462-d4e6ea80-c382-11eb-888d-39aeeb4e9770.gif)

**Comment by anshul2807** [comment]
I'm going to work on this issue.

**Comment by anthonydillon** [comment]
> I'm going to work on this issue.

Good to hear. If you have any questions please ask us.

**Comment by sowasred2012** [comment]
@bartaz do you still see this? I've tested on Firefox and Chrome, it seems OK now.

**Comment by bartaz** [comment]
> @bartaz do you still see this? I've tested on Firefox and Chrome, it seems OK now.

No, seems fine now.
