### ISSUE TITLE
Searching usn's are case sensitive

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-web-and-design/ubuntu.com#9856]
The following searches return different results:

https://ubuntu.com/security/notices?order=newest&release=bionic&details=runC
https://ubuntu.com/security/notices?order=newest&release=bionic&details=runc

The search should recognize runc and runC as the same.

---
*Reported from: https://ubuntu.com/security/notices?order=newest

**Comment by SirSamTumless** [comment]
@albertkol Can you please estimate this?
