### ISSUE TITLE
/advantage changes

### ISSUE THREAD

**Issue by lechsandecki** [canonical-web-and-design/ubuntu.com#9874]
Hi @SirSamTumless & team,

I'd like to make the following edits on /advantage:

![ESM](https://user-images.githubusercontent.com/55583702/121190945-6d89d880-c863-11eb-9d03-b8bd9fcf3abc.jpg)

A: ESM section of the /advantage table (logged in)
1. harmonise names of our offers: UA Infra, UA Apps
2. point (1) change 14.04 and 16.04 from LTS to ESM
3. point (2) add: "ESM Infra is not needed for 18.04 LTS and 20.04 LTS as they are currently within the 5 years free LTS maintenance period for Ubuntu Main repository. [Learn more about the Ubuntu LTS release cycle](https://ubuntu.com/about/release-cycle)."
-> @wgx could you review if you like this language, please?

![livepatch](https://user-images.githubusercontent.com/55583702/121190947-6e226f00-c863-11eb-911c-0f8846178e14.jpg)

B: Livepatch section of the /advantage table (logged in)
1. Add (1) text from the ESM page, eg. "Livepatch is active by default on any newly-attached Ubuntu 14.04 ESM or 16.04 ESM system"
2. Call the 16.04 "ESM" instead of "LTS"

![Screenshot from 2021-06-08 13-43-05](https://user-images.githubusercontent.com/55583702/121190950-6e226f00-c863-11eb-8a97-990e7a8da36f.png)

C. free personal subscription - bottom of the page
1. Harmonize offer name: UA Inra instead of UA Infrastructure
2. drop "(limitations apply)"
3. add 16.04 and call both 14.04 and 16.04 ESM instead of LTS

![Screenshot from 2021-06-08 13-47-02](https://user-images.githubusercontent.com/55583702/121190951-6e226f00-c863-11eb-953a-83c60fbc0d6f.png)

D. Main /advantage page - not logged in /I think this one was already reported elsewhere/
1. drop the last sentence in the free for personal use table
2. move the last sentence below the "buy button"

![certs](https://user-images.githubusercontent.com/55583702/121196278-408bf480-c868-11eb-8fe9-1384237731a0.jpg)

E. And finally the certification page still needs some work. I feel that we should promote the use of the UA client commands, at least for FIPS and CIS use-cases.

**Comment by anthonydillon** [comment]
I have a few questions/comments:

- Is 16.04 ESM a new and official term?
- The names of the contracts come from the contract service. We can't update them via the front end.

**Comment by lechsandecki** [comment]
hi @anthonydillon 
1. we used this naming logic for 14.04 ESM before so my understanding is that at the time when an LTS release moves from free LTS maintenance into ESM we change the attribute from LTS to ESM as well. I think it's a nice way to show at what stage our product is. But I cannot point to any agreement on that - it looks like we've been doing that even before I joined.
2. ok, thanks for letting me know. In that case, I will involve the CS team.

**Comment by anthonydillon** [comment]
@lechsandecki Good point, that makes sense. Just not seen it before.

**Comment by nmav** [comment]
The recommendation to call `ua enable fips-updates` for fips LGTM.

**Comment by wgx** [comment]
@lechsandecki tiny copy tweak:

>"ESM Infra is not required for 18.04 LTS and 20.04 LTS as they are currently within the 5 years free LTS maintenance period. Learn more about the Ubuntu LTS release cycle."

**Comment by wgx** [comment]
@lechsandecki can we also change the 

>Ubuntu Advantage for Infrastructure

heading to just

>Ubuntu Advantage

**Comment by wgx** [comment]
@lechsandecki 

>E. And finally the certification page still needs some work. I feel that we should promote the use of the UA client commands, at least for FIPS and CIS use-cases.

Fine to include the UA client commands - but can we still keep the documentation links please, important users can get to the docs if they need to.

**Comment by lechsandecki** [comment]
yes, I think that's the right call. I would drop use-case E.

After talking to Nikos I think that perhaps we don't want to promote the
commands outright - in some cases like fips, there is no easy way back. So
- as a customer - you better read the full documentation before enabling it
to ensure that you're making a conscious decision.

**Comment by wgx** [comment]
LGTM 👍🏽
