### ISSUE TITLE
advantage livechat during login

### ISSUE THREAD

**Issue by nmav** [canonical-web-and-design/ubuntu.com#9893]
When being logged in ubuntu.com/advantage I get a popup with livechat asking me a generic message "let me help you choose your program". As I am already logged in I am someone going to that page to get explicitly their token and the livechat is a big distraction (I have to close the livechat in order to find where the token is).

I am suggesting the following
 1. Make the livechat client for logged-in users in ubuntu.com/advantage be discreet - minimized. That way I can get assistance if I need it, by clicking there. Otherwise I can get my token without distractions.
 2. Make the message in the livechat client for logged in users more relevant to them. Example "Do you need any assistance managing your subscription?"

I'm adding also @lechsandecki as the relevant PM.

---
*Reported from: https://ubuntu.com/advantage*

**Comment by pmahnke** [comment]
@nmav I don't think the livechat client is that smart to differentiate user states as the URL doesn't change.  I think this might be impossible to achieve.

**Comment by nottrobin** [comment]
Don't we have a number of options around livechat itself? Couldn't we only load the livechat JS when we want to? Or write some JS that blocks the livechat element from being created on that page? Or something.

**Comment by wgx** [comment]
From a UX standpoint: no, we shouldn't display our sales LiveChat to customers who've already bought UA - they will have better, more relevant controls on the UI to get help with their paid plan.

**Comment by anthonydillon** [comment]
I believe livechat is enabled on all pages so we would need to write a script to disable it and wrap that in a template conditional.

**Comment by wgx** [comment]
Update: I spoke with Alyson today and we shouldn't remove this chat. 

Rather than being a sales tool - it is currently used by 1 or 2 users per day to ask non-technical account managmeent questions.

However - Alyson mentioned that we can conditioanlly change the prompt text on Livechat based on the URL of the page, so perhaps that would be a good compromise. 

If user is on /advantage, we open with a less-salesy like like:

> Welcome to Ubuntu Advantage, please get in touch with any account issues you may have

Or similar? 

cc @nottrobin @pmahnke @anthonydillon

**Comment by nottrobin** [comment]
You're talking about the initial message that is sent to the visitor right? I assume this is auto-generated:

![image](https://user-images.githubusercontent.com/519935/122240050-5b3e1900-ceb9-11eb-83b8-633746df798d.png)

I can't see a way to modify this message through [the JavaScript API](https://developers.livechat.com/docs/extending-chat-widget/javascript-api/v1.0/), so it might only be possible through the livechat portal. Does anyone know who has access to that?

**Comment by wgx** [comment]
Yes that's the text - I assume Alyson R. or someone else on the customer success team may have access?

**Comment by campbieil** [comment]
Marco in the SDR team can help with this. He's re-written all the messages lately.

**Comment by nmav** [comment]
> Rather than being a sales tool - it is currently used by 1 or 2 users per day to ask non-technical account managmeent questions.

I am not sure that's a good argument against starting livechat minimized. 1 or 2 users out of how many? There are also users really annoyed by it https://twitter.com/Evil_Mog/status/1385712672591605765 as they are on this page for a particular task, and the window explicitly prevents them from completing it as it takes most of the screen.

**Comment by lechsandecki** [comment]
I think that @Nikos Mavrogiannopoulos
***@***.***> has a point

**Comment by wgx** [comment]
@lechsandecki You're the PM on this product - so I'm happy to go with your instinct for the product.

Are you saying we *should* conditionally remove the chat from /advantage pages?

**Comment by alysonrose88** [comment]
We get a lot of questions from customers via Livechat that Arianna and I can answer without involving the support team, so in the interest of sparing them from dealing with these small enquiries I'd prefer we keep some way for customers to contact us on this page. Additionally, Arianna and I are able to answer these non-urgent enquiries very quickly, whereas the Support Team would not prioritise them, so it makes for a better customer experience

As an alternative, could we possibly create a contact us form that we link from here and which gets routed to customersuccess@canonical.com? I don't think we need to keep Livechat as the medium, but having some way for these enquiries to come to Arianna and me would be good.

@wgx @nmav @campbieil @lechsandecki

**Comment by nmav** [comment]
My suggestion was to start livechat minimized, so it is not apparent to me why we are discussing removing it completely. Isn't it possible to start it but minimized so that the user can take explicit action if needed to open it up?

**Comment by alysonrose88** [comment]
I think it should be possible to have it minimised @nmav. The SDR managers would know (Marco Ciatti)

**Comment by albertkol** [comment]
It's a year old. If we still want this we can re-open.
