### ISSUE TITLE
Second+ purchases show in Paid Subscription table as sharing a start date with original licenses

### ISSUE THREAD

**Issue by alysonrose88** [canonical-web-and-design/ubuntu.com#9897]
Hi team,

A customer has just added 6 new subscriptions of the same product type to their existing account, and was confused by the fact that the 'Your Paid Subscription' table showed the new licenses as sharing a start date with the original license - they thought we charged them for the new licenses from the start date of their original licenses, i.e. that licenses they paid for today started back in Aprik. Could we work improve that part of the table (perhaps just showing an end date) to make it more clear?

---
*Reported from: https://ubuntu.com/advantage*

**Comment by wgx** [comment]
Hi @alysonrose88 - you're quite right, this is an issue. 

The start and end date of the contract is calculated from the minimum start date of the **earliest contract item** to the maximum **end date of the latest contract**. 

In our proposed re-design (which you'll see on our call tomorrow) - we expose the **contract items** to users, so this confusion will go away. :)
