### ISSUE TITLE
certification.ubuntu.com searches do not redirect to ubuntu.com/certified searches

### ISSUE THREAD

**Issue by codersquid** [canonical-web-and-design/ubuntu.com#9901]
All hits to certification.ubuntu.com should be forwarded to ubuntu.com/certified, but that is not happening. And, some searches on the new site are resulting in 500s.

For example, https://ubuntu.com/certified/iot/models?category=Ubuntu%20Core&vendors=Dell returns a 500 (it was forwarded from an old search on the new site).

The API is not returning 500s.

**Comment by bladernr** [comment]
https://ubuntu.com/#enterprise

There's a link there under "Data Centre" that also points to certification.ubuntu.com

**Comment by codersquid** [comment]
Hopefully the PR that fixes the linked bug catches all the places where certification.ubuntu.com is listed, but we might have whack a mole for a while.
