### ISSUE TITLE
Link to Service Description is being missed by lots of customers

### ISSUE THREAD

**Issue by alysonrose88** [canonical-web-and-design/ubuntu.com#9908]
Hi everyone,

I've just been speaking to Support and they have asked if we could move the link to the Service Description (currently at the bottom of the page) higher up (we were thinking just below the paid subscription table, opposite the 'Add a new subscription button'). This is because we are seeing several customers who have purchased UA but seem to have not understood what services are included.

Alternatively, I think I remember that in early iteration of /advantage, clicking on 'Add a subscription' opened up a table detailing the UA services, and you would then click again to be taken to the store. Bringing that back would also help, because I think it is the signed-in customer view which is missing the service description or info about what is included.

---
*Reported from: https://ubuntu.com/advantage*

**Comment by SirSamTumless** [comment]
Thanks for flagging this @alysonrose88!This is being covered by the new /advantage page.
