### ISSUE TITLE
[Design] Changes to add support portal link, remove sign in line, remove beta banner

### ISSUE THREAD

**Issue by wgx** [canonical-web-and-design/ubuntu.com#9910]
On /advantage (for authenticated users)

Following discussion with @lechsandecki we should:

1. Remove the "Ubuntu pro on prem" beta invitation banner
2. Remove the "You are signed in as {email} [Sign out]" line
3. Add a link to the support potal as seen below:

So the resulting view should look like:

![image](https://user-images.githubusercontent.com/930099/122230992-05b23e00-ceb2-11eb-8cfe-2735155eb4c2.png)

@elioqoshi @anasereijo please review for UX & Visual

**Comment by anasereijo** [comment]
Hi @wgx, I propose the following:

I don't think we need the `hr separator` anymore, this will actually help moving content up on the page.

<img width="1680" alt="Screenshot 2021-06-16 at 15 15 43" src="https://user-images.githubusercontent.com/36884067/122235655-c7b71900-ceb5-11eb-92b8-d49baddd3fdc.png">

Just a thought: I don't think we usually use a colon before a button? Also, aren't we supposed to put actions as button labels? Something like 'Open', 'Add', 'Get'?


notes to dev:

<img width="1680" alt="Screenshot 2021-06-16 at 15 16 27" src="https://user-images.githubusercontent.com/36884067/122236198-3a27f900-ceb6-11eb-871e-b23b9bc91e01.png">

**Comment by wgx** [comment]
@anasereijo looks good to me. Yeah we should put a verb in, good catch: 

>Visit support portal

**Comment by anasereijo** [comment]
@ClementChaumel this is ready for you! I'll move back to 'Icebox'. Please estimate it
