### ISSUE TITLE
/cube/study - Purchase Study Lab access button doesn't work

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#9913]
If I click on 'Purchase Study Lab access' nothing happens.

https://user-images.githubusercontent.com/36884067/122373156-2c777f80-cf59-11eb-9002-418b8229bf65.mov

---
*Reported from: https://ubuntu.com/cube/study*

**Comment by SirSamTumless** [comment]
@lex-joy Is that button supposed to be there yet as we haven't built any shop parts?

**Comment by lex-joy** [comment]
Hi all! Yes, please keep the button there for now. We need it to show what the final product is intended to look like. We are waiting on CS to finish the backend part.

**Comment by lex-joy** [comment]
This issue is related to this ticket. Please keep them in conversation. :)

https://github.com/canonical-web-and-design/ubuntu.com/issues/9867
