### ISSUE TITLE
expanding search: hide nav elements

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#9914]
when the search is expanded it should be the only item "visible" - everything else should have the `-overlay` class.

How it looks like: Global nav, Ubuntu logo and secondary nav are "visible" and it should be grayed out

<img width="1680" alt="Screenshot 2021-06-17 at 11 52 53" src="https://user-images.githubusercontent.com/36884067/122383544-d6a7d500-cf62-11eb-94c8-01ac49a8d92b.png">

<img width="1680" alt="Screenshot 2021-06-17 at 11 52 00" src="https://user-images.githubusercontent.com/36884067/122383825-0e168180-cf63-11eb-8beb-7ce517b611c6.png">

---
*Reported from: https://ubuntu.com/*

**Comment by anasereijo** [comment]
@anthonydillon do you think you will have time to do this soon?

**Comment by anthonydillon** [comment]
Sorry wasn't assigned so fell off the radar. Will take a look today.
