### ISSUE TITLE
certified component is only showing one status

### ISSUE THREAD

**Issue by codersquid** [canonical-web-and-design/ubuntu.com#9923]
## Summary

A component is only showing a status for 18.04 LTS when it should also be showing a status for 20.04 LTS.

## Process

Go to this page https://ubuntu.com/certified/202102-28728 and scroll down to the Components section.

## Current and expected result

The components row for the nVidia Quadro P400 should show a checkmark for 20.04 LTS.

The API is returning the information in _lts_releases_. And you can also see it listed on the component detail page:

https://certification.canonical.com/api/v1/componentsummaries/?format=json&canonical_id=202102-28728
https://ubuntu.com/certified/component/716

**Comment by codersquid** [comment]
I did some troubleshooting and this is really confusing. I edited the template to add debugging text. The template conditional for a status that doesn't show up seems to be hitting both conditions because it displayed the text in both conditions.

**Comment by carkod** [comment]
> I did some troubleshooting and this is really confusing. I edited the template to add debugging text. The template conditional for a status that doesn't show up seems to be hitting both conditions because it displayed the text in both conditions.

So what I see is that the data under nVidia Quadro P400 has two 20.04 LTS releases, one that contains `status: certified` and `third_party_driver:false` and another that contains `third_party_driver: false` so I think the code is overriding one on top of another. Is it normal to have 2 releases? If that's the case I think we need to change a bit the code, we can't use `elif`
```
{
   "20.04 LTS":[
      {
         "release":"20.04 LTS",
         "status":"certified",
         "third_party_driver":false
      }
   ]
}{
   "18.04 LTS":[
      {
         "release":"18.04 LTS",
         "status":"certified",
         "third_party_driver":true
      }
   ],
   "20.04 LTS":[
      {
         "release":"20.04 LTS",
         "status":"certified",
         "third_party_driver":true
      }
   ]
}{
```

**Comment by codersquid** [comment]
There should be only one dictionary key for 20.04 LTS.

Where are you getting that? I only see two statuses. https://certification.canonical.com/api/v1/componentsummaries/716/

```
"lts_releases": {
"18.04 LTS": [
    {
      "release": "18.04 LTS",
      "status": "certified",
      "third_party_driver": true
    }
   ],
"20.04 LTS": [
    {
      "release": "20.04 LTS",
      "status": "certified",
      "third_party_driver": true
    }
   ]
},
```

**Comment by carkod** [comment]
> There should be only one dictionary key for 20.04 LTS.
> 
> Where are you getting that? I only see two statuses. https://certification.canonical.com/api/v1/componentsummaries/716/
> 
> ```
> "lts_releases": {
> "18.04 LTS": [
>     {
>       "release": "18.04 LTS",
>       "status": "certified",
>       "third_party_driver": true
>     }
>    ],
> "20.04 LTS": [
>     {
>       "release": "20.04 LTS",
>       "status": "certified",
>       "third_party_driver": true
>     }
>    ]
> },
> ```

Sorry. Digging a bit deeper, it seems to be a CSS issue. The icon is showing but for some reason it's overflowing to the right... So I might need to have a chat with beth to figure this out, as this seems like table width issue.
