### ISSUE TITLE
Deep links for Study Labs content and changing the URL for the Study labs

### ISSUE THREAD

**Issue by KellenRenshaw** [canonical-web-and-design/ubuntu.com#9953]
We would like this change to go live on July 1. This change should only apply to the Study Lab("Prepare") buttons/links, the Exam("Take" button) URLs are *not* changing.

Please change the "Prepare" buttons next to each Microcertifcation to the links below which match the Exam to the topic the "Prepare" button leads the user to. Additionally, we would like the "Prepare" button at the top under "Refresh your knowledge" to be removed.

The general form of the links is "https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2F" + "exam_shortname" + "%2F%3Fchild%3Dfirst"

The specific links and the exam shortname they match are below.

admintasks    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fadmintasks%2F%3Fchild%3Dfirst
commands    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fcommands%2F%3Fchild%3Dfirst
devices    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fdevices%2F%3Fchild%3Dfirst
juju    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fjuju%2F%3Fchild%3Dfirst
kernel    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fkernel%2F%3Fchild%3Dfirst
maas    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fmaas%2F%3Fchild%3Dfirst
microk8s    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fmicrok8s%2F%3Fchild%3Dfirst
networking    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fnetworking%2F%3Fchild%3Dfirst
package    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fpackage%2F%3Fchild%3Dfirst
security    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fsecurity%2F%3Fchild%3Dfirst
shellscript    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fshellscript%2F%3Fchild%3Dfirst
storage    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fstorage%2F%3Fchild%3Dfirst
sysarch    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fsysarch%2F%3Fchild%3Dfirst
systemd    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fsystemd%2F%3Fchild%3Dfirst
virtualisation    https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourseware%2Fvirtualisation%2F%3Fchild%3Dfirst

The generic link to the Study Lab course should be:
https://cube.ubuntu.com/auth/login/tpa-saml/?auth_entry=login&idp=ubuntuone&next=%2Fcourses%2Fcourse-v1%3ACUBE%2Bstudy_labs%2B2020%2Fcourse%2F

I believe this is used on the /cube/study page.

---
*Reported from: https://ubuntu.com/cube/microcerts*

**Comment by SirSamTumless** [comment]
@jpmartinspt Does this need work from you or can it be done in the frontend?

**Comment by jpmartinspt** [comment]
@SirSamTumless this needs some backend work, should not be super complicated though.

**Comment by jpmartinspt** [comment]
@KellenRenshaw is the study labs course not `course-v1:CUBE+study_labs_2020+alpha` anymore?
Also the links to the courseware just seem to take me to ubuntu.com?

**Comment by KellenRenshaw** [comment]
@jpmartinspt Yes, the study labs course has changed to: `course-v1:CUBE+study_labs+2020`

The old `course-v1:CUBE+study_labs_2020+alpha` still exists, but we phasing it out, since it has Alpha in the name.

The links will redirect through to ubuntu.com/cube because you are not enrolled in the course. Clicking on the links sends you to the course page, which you don't have access to, so you get redirected to cube.ubuntu.com/dashboard, which redirects to ubuntu.com/cube.

I can enroll you after July 1, then the links should work.

**Comment by KellenRenshaw** [comment]
@jpmartinspt Apologies for the delay, you are enrolled in the course on Prod. The links *should* work for you.
