### ISSUE TITLE
Arrow on card is going over text on scroll up on subscribe page

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/ubuntu.com#9955]
## Summary

Arrow on card is going over text on scroll up

## Process

On subscribe page: https://ubuntu.com/advantage/subscribe
- Select:
  - servers
  - ubuntu 20.04 LTS
  - No thanks
  - 1 machine
- Scroll back up
- See the arrow going over the text 

## Screenshot

![arrow](https://user-images.githubusercontent.com/2707508/123603626-fc9a6880-d7f1-11eb-90e7-1cb239c077d9.gif)

## Browser details
Firefox

**Comment by SirSamTumless** [comment]
Thanks for flagging @tbille. We actually have this already #9956

**Comment by tbille** [comment]
@SirSamTumless this is a different issue:
- #9956 is about the footer that appears onload of the page
- #9955 is about the arrow that has a wrong behaviour of the page

**Comment by wgx** [comment]
Resolved, closing.
