### ISSUE TITLE
On load of /advantage/subscribe page the summary footer appears and leaves

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/ubuntu.com#9956]
## Summary

https://ubuntu.com/advantage/subscribe
On load of the page the summary footer hides

## Process

- Go on https://ubuntu.com/advantage/subscribe
- Reload page, notice the summary footer that is there and goes away

## Current and expected result

The footer should be hidden by default

## Screenshot
![bump](https://user-images.githubusercontent.com/2707508/123605542-dbd31280-d7f3-11eb-8efe-a1d8dcb59bc1.gif)

## Browser details

Firefox

**Comment by anthonydillon** [comment]
I can't seem to replicate this? @tbille do you still get it?

**Comment by tbille** [comment]
@anthonydillon yes I can on chrome and firefox

**Comment by wgx** [comment]
Should be resolved now, or your localStorage is in a mangled state, cannot repro.
