### ISSUE TITLE
Terms and conditions checkbox doesn't work on contact form

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/ubuntu.com#9958]
- Go to https://ubuntu.com/openstack/what-is-openstack#get-in-touch
- Fill out the form and progress to the end
- Try to click the "I agree to receive information about Canonical's products and services." checkbox
- It doesn't get checked

**Comment by anthonydillon** [comment]
This is due to the same field being available on the page underneath. The interactive form needs to keep the field name the same but this causes an issue for other forms on the page.
