### ISSUE TITLE
Links in product selector are not clickable

### ISSUE THREAD

**Issue by elioqoshi** [canonical-web-and-design/ubuntu.com#9961]
@wgx noticed that within the product selectors, it's not possible to click on links, as the whole cards are buttons: 
https://github.com/canonical-web-and-design/ubuntu.com/pull/9940#issuecomment-866954822

That's fine though and it works as intended. I'd suggest to make the link part of the section description, similar to this:

![image.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/5ccd6ce8-3cbe-49e8-bea0-a66e3a19afa4)

Copy might need some finetuning with @lechsandecki signing off on it.

@ClementChaumel would this be fine for implementing?

**Comment by anasereijo** [comment]
LGTM!

**Comment by lechsandecki** [comment]
I like that, Elio. 
I also noticed two typos:
1. "Essential **feaatures**"
2. Should be "Select Infra only", "Selec Apps only", and not "Infrastructure", "Applications". I also think that logically we would call the bundle "Infra + Apps", not "Apps + Infra"

**Comment by elioqoshi** [comment]
> "Essential feaatures"

Sorry that was my mistake @lechsandecki, my mechanical keyboard bugs sometimes.

> Should be "Select Infra only", "Selec Apps only", and not "Infrastructure", "Applications".

Also for the titles? So are the cards called `Apps`,`Infra` then?

> I also think that logically we would call the bundle "Infra + Apps", not "Apps + Infra"

If you go by order yes, but isn't Apps the creme de la creme of our offering? If that's not relevant we can reverse the order, sure.

**Comment by SirSamTumless** [comment]
> that, Elio.
> I also noticed two typos:
> 
> 1. "Essential **feaatures**"
> 2. Should be "Select Infra only", "Selec Apps only", and not "Infrastructure", "Applications". I also think that logically we would call the bundle "Infra + Apps", not "Apps + Infra"

Could you open a seperate issue for these please?

**Comment by wgx** [comment]
The typos are just on the Miro, rather than the UI. 

I would change the text of the link to:

> [See what is included with Applications coverage](#).

I'm happy with this, UX+1 👍🏽

**Comment by lechsandecki** [comment]
> > "Essential feaatures"
> 
> Sorry that was my mistake @lechsandecki, my mechanical keyboard bugs sometimes.
> 
> > Should be "Select Infra only", "Selec Apps only", and not "Infrastructure", "Applications".
> 
> Also for the titles? So are the cards called `Apps`,`Infra` then?

yes, pls
> 
> > I also think that logically we would call the bundle "Infra + Apps", not "Apps + Infra"
> 
> If you go by order yes, but isn't Apps the creme de la creme of our offering? If that's not relevant we can reverse the order, sure.

you're right, but I'd still go with Infra + Apps

**Comment by elioqoshi** [comment]
@lechsandecki for reference here is a preview mockup with these changes. If this is good to go we can close this.

![image](https://user-images.githubusercontent.com/5436686/124556647-d485b780-de38-11eb-8baf-ed450413c3bc.png)
