### ISSUE TITLE
Prepare to remove SSO requirement from ubuntu.com/cube

### ISSUE THREAD

**Issue by KellenRenshaw** [canonical-web-and-design/ubuntu.com#9970]
@SirSamTumless We would like to start the process of changing the SSO requirements on the various CUBE pages.

We are not currently ready to have the requested changes go live, but wanted to have a head start to avoid crunches.

We would like the following:
ubuntu.com/cube - No SSO, open to the public.
ubuntu.com/cube/microcerts - SSO, open to anyone with an Ubuntu ONE SSO account.
ubuntu.com/cube/study - SSO, open to anyone with an Ubuntu ONE SSO account.
ubuntu.com/cube/* - SSO, open to anyone with an Ubuntu ONE SSO account. Refers to potential future pages.

Additionally, any access control lists should be removed as part of this.

---
*Reported from: https://ubuntu.com/cube*

**Comment by SirSamTumless** [comment]
Hi @KellenRenshaw Would you mind sending this through as a brief so we can put it in our working backlog.

**Comment by KellenRenshaw** [comment]
@SirSamTumless Done! Let me know if more detail is needed either here or there.

**Comment by KellenRenshaw** [comment]
@SirSamTumless Updated the [brief](https://docs.google.com/document/d/1It19GL696j5Z-UXL03s5lQ7EpnqrFPcMIUBwoHOXxYU/edit#), we would like this made live as soon as it is ready.
