### ISSUE TITLE
visual fixes on 'thanks for your purchase' page

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/ubuntu.com#9972]
Can you wrap the getting started text? Looks weird having just the word address on its own.
The sign-in button, do we need to use ellipsis? it doesn't open an edit mode it just takes you to SSO -maybe this question is for @wgx ?

<img width="907" alt="Screenshot 2021-06-29 at 14 20 48" src="https://user-images.githubusercontent.com/36884067/123804800-6e9faa00-d8e5-11eb-8cb6-2bd4f5f49163.png">

**Comment by albertkol** [comment]
We can perhaps A/B test this to see if we wish to do it. Closing.

**Comment by albertkol** [comment]
We can perhaps A/B test this to see if we wish to do it. Closing.
