### ISSUE TITLE
We can drop step 2 from "How to enable the Canonical Livepatch Service"

### ISSUE THREAD

**Issue by blackboxsw** [canonical-web-and-design/ubuntu.com#9979]
Steps to enable livepatch should be:
1. sudo ua attach <TOKEN>
2. sudo ua enable livepatch

We should drop the "sudo snap install canonical-livepatch"
---
*Reported from: https://ubuntu.com/security/livepatch*

**Comment by blackboxsw** [comment]
It feels a bit that the whole section "How to enable the Canonical Livepatch Service" should be dropped as these details will get out of date anyway and the source of truth for this information is  https://ubuntu.com/advantage which is already pointed to by both the "Get Livepatch now" and "Get Ubuntu Advantage" buttons (which are duplicate links)

**Comment by blackboxsw** [comment]
might we also consolidate "Get Livepatch now" vs "Get Ubuntu Advantage" buttons too somehow?

**Comment by nmav** [comment]
Nice suggestion, this page is about to be completely updated. I think we can wait until https://docs.google.com/document/d/1g_Ip5MzlBRpbM2wULpSnsR5XaHJVWgLPLdq8_7fCHrs/edit#heading=h.rfxogwozaxta replaces it

**Comment by nmav** [comment]
This is already done.
